namespace Game.Editor
{
    internal static class CH02M01GridlockCopyCatalog
    {
        internal static readonly (string Key,string English,string Persian)[] Ui={
            ("ui.aria.press_select","Press Select","«انتخاب» رو بزن"),
            ("ui.aria.normal_selection.title","Select units","نیروها رو انتخاب کن"),
            ("ui.aria.press_select.body","Press Select on the command bar.","دکمهٔ «انتخاب» رو توی نوار فرمان بزن."),
            ("ui.aria.drag_select.body","Drag from one corner of the marked box to the opposite corner, enclosing the units, then release.","از گوشهٔ کادر مشخص‌شده بکش تا دور همهٔ نیروها کادر بیفته، بعد رها کن."),
            ("ui.aria.tap_select.body","Tap the marked unit in the world.","روی نیروی مشخص‌شده توی میدان بزن."),
            ("narrative.speaker.fadi.name","Fadi","فادی"),
            ("narrative.speaker.fadi.role","Road crew leader","سرگروه راه‌سازی"),
            ("narrative.speaker.fadi.accessibleLabel","Fadi, road crew leader","فادی، سرگروه راه‌سازی"),
            ("mission.gridlock.fadi.name","Fadi","فادی"),
            ("mission.gridlock.worker.name","Road worker","کارگر راه‌سازی"),
            ("mission.gridlock.crew.group","{0} CREW","{0} نفر از گروه راه‌سازی"),
            ("mission.gridlock.crew.role","Road crew","گروه راه‌سازی"),
            ("mission.gridlock.crew.description","Civilian road crew. Keep Fadi and a worker close to the work site to clear it.","گروه غیرنظامی راه‌سازی. فادی و یک کارگر باید نزدیک محل کار باشن تا مسیر رو باز کنن."),
            ("mission.gridlock.guide.title","GRIDLOCK · FIELD GUIDE","راه‌بندان · راهنمای عملیات"),
            ("chapter.first_response.mission.1","FIRST CONTACT","اولین برخورد"),
            ("chapter.first_response.mission.2","ESTABLISH THE BASE","ساخت پایگاه"),
            ("chapter.first_response.mission.3","RADAR WARNING","هشدار رادار"),
            ("chapter.first_response.mission.4","AIRLIFT RESCUE","نجات هوایی"),
            ("chapter.first_response.mission.5","BREACH ASSAULT","شکستن محاصره"),
            ("chapter.broken_grid.mission.1","GRIDLOCK","راه‌بندان"),
            ("chapter.broken_grid.mission.2","SUPPLY LINE","خط تدارکات"),
            ("chapter.broken_grid.mission.3","MARKET LIFELINE","شریان بازار"),
            ("chapter.broken_grid.mission.4","POWER RELAY","رلهٔ برق"),
            ("chapter.broken_grid.mission.5","ROUTE REOPENED","بازگشایی مسیر"),
            ("mission.gridlock.result.victory","HOSPITAL REACHED","امداد به بیمارستان رسید"),
            ("mission.gridlock.result.defeat","RELIEF INTERRUPTED","امدادرسانی متوقف شد"),
            ("mission.gridlock.result.success","The service lane is open and the hospital has its supplies. The sabotage points toward a dormant substation.","مسیر فرعی باز شده و محموله به بیمارستان رسیده. رد خرابکاری به یک پست برق خاموش می‌رسه."),
            ("chapter.first_response.name","Chapter 1 · First Response","فصل ۱ · اولین واکنش"),
            ("chapter.broken_grid.name","Chapter 2 · Broken Grid","فصل ۲ · شبکهٔ گسسته"),
            ("chapter.broken_grid.available","Gridlock available","راه‌بندان باز شده"),
            ("chapter.broken_grid.locked","Complete Breach Assault","عملیات شکستن محاصره رو تموم کن"),
            ("mission.gridlock.name","GRIDLOCK","راه‌بندان"),
            ("mission.gridlock.summary","Protect Fadi and his road crew. Clear the service lane and escort relief supplies to the hospital.","از فادی و گروه راه‌سازی محافظت کن. مسیر فرعی رو باز کن و محمولهٔ امداد رو به بیمارستان برسون."),
            ("mission.gridlock.location","Hospital relief corridor","مسیر امدادرسانی بیمارستان"),
            ("mission.gridlock.enemy_intel","Two armed sabotage teams. A warned counterattack may contest the reopened lane.","دو گروه مسلح خرابکار توی مسیرن. قبل از ضدحمله به مسیر بازشده، هشدار می‌گیری."),
            ("mission.gridlock.objective.site_a","Clear work site A","محل کار اول رو باز کن"),
            ("mission.gridlock.objective.site_b","Clear work site B","محل کار دوم رو باز کن"),
            ("mission.gridlock.objective.delivery","Deliver relief and secure the hospital","امداد رو برسون و بیمارستان رو امن نگه دار"),
            ("mission.gridlock.objective.site_a.body","Move Fadi and a worker into site A. Keep hostiles away for 25 seconds of work.","فادی و یکی از کارگرها رو به محل اول ببر. برای ۲۵ ثانیه کار، دشمن‌ها رو دور نگه دار."),
            ("mission.gridlock.objective.site_b.body","Protect the crew at site B. Interrupted work resumes where it stopped.","تو محل دوم از گروه محافظت کن. اگه کار متوقف بشه، بعداً از همون‌جا ادامه پیدا می‌کنه."),
            ("mission.gridlock.objective.delivery.body","Keep the route clear. The relief truck must arrive, then the hospital must stay clear for 20 seconds.","مسیر رو امن نگه دار. کامیون امداد باید برسه؛ بعد اطراف بیمارستان باید ۲۰ ثانیه امن بمونه."),
            ("mission.gridlock.star.1","Restore hospital access","مسیر بیمارستان رو باز کن"),
            ("mission.gridlock.star.2","Fadi and both workers survive","فادی و هر دو کارگر زنده بمونن"),
            ("mission.gridlock.star.3","Finish in under 7 minutes","زیر ۷ دقیقه تموم کن"),
            ("mission.gridlock.reward.card","800 XP · 4,000 Credits","۸۰۰ تجربه · ۴٬۰۰۰ اعتبار"),
            ("mission.gridlock.resources","Relief vehicle and its fuel are supplied.","کامیون امداد و بنزینش از قبل تأمین شده."),
            ("mission.gridlock.forces","8 rifles · Fadi · 2 workers · 1 relief truck","۸ تفنگدار · فادی · ۲ کارگر · ۱ کامیون امداد"),
            ("mission.gridlock.deadline","12 active minutes","۱۲ دقیقه زمان فعال"),
            ("mission.gridlock.time_limit","TIME LIMIT","مهلت"),
            ("mission.gridlock.work.working","Working","در حال کار"),
            ("mission.gridlock.work.crew_missing","Fadi and a worker must be here","فادی و یک کارگر باید اینجا باشن"),
            ("mission.gridlock.work.threat_nearby","Threat nearby — work paused","دشمن نزدیکه — کار متوقف شده"),
            ("mission.gridlock.work.clearing","Removing obstruction","در حال برداشتن مانع"),
            ("mission.gridlock.work.complete","Route section cleared","این بخش مسیر باز شد"),
            ("mission.gridlock.relief.waiting","Relief truck waiting for a clear route","کامیون امداد منتظر امن شدن مسیره"),
            ("mission.gridlock.relief.moving","Relief truck en route","کامیون امداد توی راهه"),
            ("mission.gridlock.warning","Saboteurs approaching the cleared section. Protect the crew and route!","خرابکارها دارن به بخش بازشده نزدیک می‌شن. از گروه و مسیر محافظت کن!"),
            ("mission.gridlock.failure.fadi","Fadi was lost. Retry the operation.","فادی رو از دست دادیم. عملیات رو دوباره شروع کن."),
            ("mission.gridlock.failure.workers","Both road workers were lost.","هر دو کارگر رو از دست دادیم."),
            ("mission.gridlock.failure.rifles","The escort squads were lost.","گروه‌های محافظ رو از دست دادیم."),
            ("mission.gridlock.failure.vehicle","The relief truck was destroyed.","کامیون امداد نابود شد."),
            ("mission.gridlock.failure.deadline","The hospital relief deadline expired.","مهلت رسوندن امداد به بیمارستان تموم شد."),
            ("mission.gridlock.failure.integrity","Mission state could not be verified. Return and retry; no rewards were settled.","وضعیت عملیات قابل تأیید نیست. برگرد و دوباره تلاش کن؛ پاداشی ثبت نشده."),
            ("mission.gridlock.hud.work","A: {0}/25 — {1}\nB: {2}/25 — {3}","اول: {0}/۲۵ — {1}\nدوم: {2}/۲۵ — {3}"),
            ("mission.gridlock.hud.hold","Hospital secure: {0}/20","امنیت بیمارستان: {0}/۲۰"),
            ("mission.gridlock.crew.select","Select the road crew","گروه راه‌سازی رو انتخاب کن"),
            ("mission.gridlock.clue","The sabotage steers traffic toward a dormant substation.","این خرابکاری ترافیک رو به سمت یک پست برق خاموش هدایت می‌کنه."),
            ("mission.gridlock.next","Supply Line — awaiting mission content","خط تدارکات — هنوز آماده نیست")
        };
    }
}
