using System;
using System.Collections.Generic;
using System.Linq;
using Game.Configs;
using Game.UI.Runtime;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class CH02M04PowerRelayPresentationBuilder
    {
        public const string GuidePath="Assets/Game/Configs/Missions/Chapter02/CH02M04_PowerRelay_FieldGuide.asset";
        [MenuItem("Game/Campaign/Power Relay/Build Presentation")]
        public static void Build()
        {
            CH02M04PowerRelayMediaImporter.ConfigureArt();SeedLocalization();BuildGuide();BindArt();AssetDatabase.SaveAssets();
            Debug.Log("[PowerRelayPresentation] result=Passed locales=en,fa-IR controls=existing-only visual=approved");
        }
        private static void SeedLocalization()
        {
            var copy=new (string key,string en,string fa)[]{
                ("name","Power Relay","رلهٔ برق"),("summary","Protect displaced families on Samira's longer service road, deliver Fuel and engineers, then restore and secure the substation.","خانواده‌های آواره رو در مسیر خدماتیِ طولانی‌ترِ سمیرا محافظت کن، سوخت و مهندس‌ها رو برسون، بعد پست برق رو بازیابی و امن کن."),("location","East district substation and school shelter","پست برق منطقهٔ شرقی و پناهگاه مدرسه"),("enemy_intel","Ash Line teams hold the repair yard and watch the exposed industrial lane.","گروه‌های خط خاکستر محوطهٔ تعمیر رو در اختیار دارن و مسیر صنعتی روباز رو زیر نظر گرفتن."),
                ("objective.shelter","Escort families by the protected route","خانواده‌ها رو از مسیر محافظت‌شده ببر"),("objective.restore","Supply engineers and restore power","مهندس‌ها رو تأمین کن و برق رو برگردون"),("objective.secure","Secure the relay yard","محوطهٔ رله رو امن کن"),
                ("objective.shelter.body","Move the family convoy through the marked service road, then into the school shelter. The shorter industrial lane does not satisfy this objective.","کاروان خانواده‌ها رو از جادهٔ خدماتیِ مشخص‌شده عبور بده و بعد وارد پناهگاه مدرسه کن. مسیر صنعتی کوتاه‌تر این هدف رو کامل نمی‌کنه."),("objective.restore.body","Move the Fuel service truck and both engineers into the repair zone. Keep them stationary and protected for 8 seconds.","کامیون سوخت و هر دو مهندس رو وارد محدودهٔ تعمیر کن. ۸ ثانیه بی‌حرکت و محافظت‌شده نگهشون دار."),("objective.secure.body","Defeat the armed teams, restore power and keep the relay yard secure for 10 seconds.","گروه‌های مسلح رو شکست بده، برق رو برگردون و محوطهٔ رله رو ۱۰ ثانیه امن نگه دار."),
                ("star.1","Complete the mission","مأموریت رو کامل کن"),("star.2","No civilian or engineer losses","هیچ غیرنظامی یا مهندسی رو از دست نده"),("star.3","Finish within 7 minutes","در کمتر از ۷ دقیقه تمام کن"),("resources","One Fuel service truck · one family convoy · two engineers","یک کامیون سوخت · یک کاروان خانواده · دو مهندس"),("forces","8 rifles · 2 engineers · protected civilians","۸ تفنگدار · ۲ مهندس · غیرنظامی‌های محافظت‌شده"),("deadline","10 active minutes","۱۰ دقیقه زمان فعال"),("reward.card","1,000 Commander XP · 5,000 Credits","۱۰۰۰ تجربهٔ فرمانده · ۵۰۰۰ اعتبار"),
                ("result.victory","Power relay restored","رلهٔ برق بازیابی شد"),("result.defeat","Power relay operation failed","عملیات رلهٔ برق شکست خورد"),("result.success","Power, clean water and protected shelter access returned. The substation emitted a dormant Civic Relay handshake.","برق، آب سالم و دسترسی امن به پناهگاه برگشت. پست برق یک دست‌دهی خاموش از شبکهٔ شهری فرستاد."),
                ("failure.squad","The protective squad was lost. Keep rifles between the service convoy and the repair yard threat.","گروه محافظ از دست رفت. تفنگدارها رو بین کاروان خدماتی و تهدید محوطهٔ تعمیر نگه دار."),("failure.engineer","An engineer was lost. Both engineers must survive and complete the repair together.","یکی از مهندس‌ها از دست رفت. هر دو مهندس باید زنده بمونن و تعمیر رو با هم انجام بدن."),("failure.families","The family convoy was lost. Use the protected service road and screen it with rifles.","کاروان خانواده‌ها از دست رفت. از جادهٔ خدماتیِ محافظت‌شده استفاده کن و با تفنگدارها پوششش بده."),("failure.fuel","The Fuel service truck was lost. It must reach the repair zone intact.","کامیون سوخت از دست رفت. باید سالم به محدودهٔ تعمیر برسه."),("failure.deadline","Power was not restored within ten minutes.","برق تا پایان ده دقیقه برنگشت."),("failure.integrity","Mission state could not be verified. Return and retry; no rewards were settled.","وضعیت عملیات قابل تأیید نیست. برگرد و دوباره تلاش کن؛ پاداشی ثبت نشد."),
                ("guide.title","Power Relay field guide","راهنمای رلهٔ برق"),("guide.1.title","Choose the protected route","مسیر محافظت‌شده رو انتخاب کن"),("guide.1.body","Select the family convoy and move it through Samira's marked service-road waypoint. Do not use ARIA's exposed shortcut.","کاروان خانواده‌ها رو انتخاب کن و از نقطهٔ مشخص‌شدهٔ جادهٔ خدماتیِ سمیرا عبور بده. از میان‌برِ روبازِ آریا استفاده نکن."),("guide.2.title","Reach the school shelter","به پناهگاه مدرسه برس"),("guide.2.body","After the service-road waypoint confirms, move the family convoy into the school shelter.","بعد از تأیید نقطهٔ جادهٔ خدماتی، کاروان خانواده‌ها رو وارد پناهگاه مدرسه کن."),("guide.3.title","Deliver Fuel and engineers","سوخت و مهندس‌ها رو برسون"),("guide.3.body","Move the Fuel service truck and both engineers into the marked relay repair zone.","کامیون سوخت و هر دو مهندس رو وارد محدودهٔ مشخص‌شدهٔ تعمیر رله کن."),("guide.4.title","Protect the repair","از تعمیر محافظت کن"),("guide.4.body","Keep both engineers stationary in the repair zone for 8 seconds. Move rifles ahead and attack confirmed hostiles.","هر دو مهندس رو ۸ ثانیه در محدودهٔ تعمیر بی‌حرکت نگه دار. تفنگدارها رو جلو ببر و به دشمن‌های تأییدشده حمله کن."),("guide.5.title","Secure restored power","برق بازیابی‌شده رو امن کن"),("guide.5.body","After power returns, defeat remaining hostiles and hold the relay yard clear for 10 seconds.","بعد از برگشت برق، دشمن‌های باقی‌مونده رو شکست بده و محوطهٔ رله رو ۱۰ ثانیه امن نگه دار."),("guide.example","Use only Select, Move, Attack and Hold. ARIA can demonstrate these same orders.","فقط از انتخاب، حرکت، حمله و توقف استفاده کن. آریا هم می‌تونه همین فرمان‌ها رو اجرا کنه."),("guide.mistake","The exposed shortcut is shorter, but its shelter is full. It cannot complete the family objective.","میان‌برِ روباز کوتاه‌تره، اما پناهگاهش پره. این مسیر هدف خانواده‌ها رو کامل نمی‌کنه."),("guide.diagram","FAMILIES → SERVICE ROAD → SCHOOL · FUEL + 2 ENGINEERS → RELAY · RIFLES → SECURE","خانواده‌ها ← جادهٔ خدماتی ← مدرسه · سوخت + ۲ مهندس ← رله · تفنگدارها ← تأمین امنیت"),
                ("guide.1.title","Choose the protected route","مسیر محافظت‌شده رو انتخاب کن"),("guide.2.title","Reach the school shelter","به پناهگاه مدرسه برس"),("guide.3.title","Deliver Fuel and engineers","سوخت و مهندس‌ها رو برسون"),("guide.4.title","Protect the repair","از تعمیر محافظت کن"),("guide.5.title","Secure restored power","برق بازیابی‌شده رو امن کن"),
                ("guide.1.body","Select the family convoy and move it through Samira's marked service-road waypoint.","کاروان خانواده‌ها رو انتخاب کن و از نقطهٔ مشخص‌شدهٔ جادهٔ خدماتیِ سمیرا عبور بده."),("guide.2.body","Move the family convoy from the protected waypoint into the open school shelter.","کاروان خانواده‌ها رو از نقطهٔ محافظت‌شده وارد پناهگاه باز مدرسه کن."),("guide.3.body","Move the Fuel service truck and both engineers into the relay repair zone.","کامیون سوخت و هر دو مهندس رو وارد محدودهٔ تعمیر رله کن."),("guide.4.body","Hold both engineers in the repair zone for 8 seconds while rifles remove nearby threats.","هر دو مهندس رو ۸ ثانیه در محدودهٔ تعمیر نگه دار و با تفنگدارها تهدیدهای نزدیک رو از بین ببر."),("guide.5.body","Keep the restored relay clear for 10 seconds after all armed teams are defeated.","بعد از شکست همهٔ گروه‌های مسلح، رلهٔ بازیابی‌شده رو ۱۰ ثانیه امن نگه دار."),
                ("chapter_name","POWER RELAY","رلهٔ برق")};
            GameLocalizationCatalog catalog=AssetDatabase.LoadAssetAtPath<GameLocalizationCatalog>(V3UiLocalizationCatalogBuilder.CatalogPath)??throw new InvalidOperationException("Localization catalog missing.");var tables=new List<GameLocaleTable>();
            foreach(GameLocaleTable locale in catalog.Locales){if(locale.LocaleCode!="en"&&locale.LocaleCode!="fa-IR"){tables.Add(locale);continue;}bool fa=locale.LocaleCode=="fa-IR";var entries=locale.Entries.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal);foreach(var line in copy)entries[line.key=="chapter_name"?"chapter.broken_grid.mission.4":"mission.power_relay."+line.key]=fa?line.fa:line.en;foreach(var line in CH02M04PowerRelayMediaImporter.Lines)entries[line.Key]=fa?line.Persian:line.English;tables.Add(new GameLocaleTable(locale.LocaleCode,locale.DisplayName,locale.ShortLabel,locale.RightToLeft,locale.FontAsset,entries.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>new GameLocalizedStringRecord(x.Key,x.Value))));}
            catalog.Configure(catalog.SourceLocaleCode,tables);EditorUtility.SetDirty(catalog);
        }
        private static void BuildGuide()
        {
            var guide=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(GuidePath);if(guide==null){guide=ScriptableObject.CreateInstance<MissionFieldGuideConfig>();AssetDatabase.CreateAsset(guide,GuidePath);}var basis=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(M03RadarWarningGuideBuilder.Path);var classes=basis.Classes.ToArray();for(int i=0;i<classes.Length;i++)if(classes[i].Availability!=MissionGuideAvailability.Unavailable)classes[i].Availability=MissionGuideAvailability.Reference;
            guide.Configure(Enumerable.Range(1,5).Select(i=>new MissionGuideTopic{TitleKey=$"mission.power_relay.guide.{i}.title",BodyKey=$"mission.power_relay.guide.{i}.body",ExampleKey="mission.power_relay.guide.example",MistakeKey="mission.power_relay.guide.mistake",DiagramKey="mission.power_relay.guide.diagram"}).ToArray(),classes);EditorUtility.SetDirty(guide);
            GameObject root=PrefabUtility.LoadPrefabContents(M03RadarWarningUiBuilder.GuidePath);try{var data=new SerializedObject(root.GetComponentInChildren<MissionFieldGuideView>(true));data.FindProperty("powerRelayGuide").objectReferenceValue=guide;data.ApplyModifiedPropertiesWithoutUndo();MissionUiSerializedBindingsAuthoring.Apply(root);PrefabUtility.SaveAsPrefabAsset(root,M03RadarWarningUiBuilder.GuidePath);}finally{PrefabUtility.UnloadPrefabContents(root);}
        }
        private static void BindArt()
        {
            Texture art=CH02M04PowerRelayMediaImporter.Preview()??throw new InvalidOperationException("Power Relay art missing.");
            foreach(string path in new[]{"Assets/Game/Prefabs/UI/Shell/Content/SCN05_CampaignOperationsContent.prefab","Assets/Game/Prefabs/UI/Shell/Content/SCN06_MissionBriefingContent.prefab"}){GameObject root=PrefabUtility.LoadPrefabContents(path);try{var campaign=root.GetComponentInChildren<CampaignOperationsScreenView>(true);UnityEngine.Object view=campaign!=null?(UnityEngine.Object)campaign:root.GetComponentInChildren<MissionBriefingScreenView>(true);var data=new SerializedObject(view);data.FindProperty(campaign!=null?"powerRelayMissionPreview":"powerRelayMissionArt").objectReferenceValue=art;data.ApplyModifiedPropertiesWithoutUndo();PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
        }
        [MenuItem("Game/Campaign/Power Relay/Build Player-Ready Checkpoint")]
        public static void BuildCheckpoint(){CH02M04PowerRelayRulesValidation.Run();CH02M04PowerRelayConfigBuilder.Build();Build();CH02M04PowerRelayNarrativeBuilder.BuildCaptionedArtAndInstall();Debug.Log("[PowerRelayCheckpoint] result=Passed scope=CaptionedConfiguration controls=existing-only");}
    }
}
