using System;
using System.Linq;
using System.Reflection;
using Game.Catalog.Contracts;
using Game.Composition;
using Game.Configs;
using Game.Narrative.Contracts;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings.GroupSchemas;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.SceneManagement;

namespace Game.Editor
{
    public static class CH02M04PowerRelayNarrativeBuilder
    {
        public const string Path="Assets/Game/Configs/Narrative/Chapter02/CH02M04_PowerRelay_Narrative.asset";
        [MenuItem("Game/Campaign/Power Relay/Build Captioned Narrative")]
        public static void BuildAndInstall()=>Build(true);
        public static void BuildCaptionedArtAndInstall()=>Build(true);
        private static void Build(bool voices)
        {
            CH02M04PowerRelayMediaImporter.ConfigureArt();if(voices)CH02M04PowerRelayMediaImporter.ConfigureVoices();System.IO.Directory.CreateDirectory("Assets/Game/Configs/Narrative/Chapter02");AssetDatabase.Refresh();
            PowerRelayNarrativeLine[][] lines={CH02M04PowerRelayCopy.Brief,CH02M04PowerRelayCopy.Comms,CH02M04PowerRelayCopy.Debrief};string[] stages={"brief","comms","debrief"};var basis=AssetDatabase.LoadAllAssetsAtPath(M02EstablishBaseNarrativeConfigBuilder.NarrativePath).OfType<NarrativeSequenceConfig>().ToArray();for(int i=0;i<stages.Length;i++)Configure(stages[i],lines[i],basis.Single(s=>s.SequenceId.EndsWith("."+stages[i],StringComparison.Ordinal)));
            InstallLina();AddPersian();AssetDatabase.SaveAssets();Scene scene=EditorSceneManager.OpenScene(M02EstablishBaseNarrativeConfigBuilder.MenuScenePath,OpenSceneMode.Single);MenuBootstrapView bootstrap=UnityEngine.Object.FindAnyObjectByType<MenuBootstrapView>(FindObjectsInactive.Include)??throw new InvalidOperationException("Menu bootstrap missing.");var merged=(bootstrap.CampaignMissionNarrativeConfigs??Array.Empty<NarrativeSequenceConfig>()).Where(s=>s!=null&&!s.SequenceId.StartsWith("seq.ch02.m04.",StringComparison.Ordinal)).Concat(AssetDatabase.LoadAllAssetsAtPath(Path).OfType<NarrativeSequenceConfig>()).OrderBy(s=>s.SequenceId,StringComparer.Ordinal).ToArray();var menu=new SerializedObject(bootstrap);var configs=menu.FindProperty("campaignMissionNarrativeConfigs");configs.arraySize=merged.Length;for(int i=0;i<merged.Length;i++)configs.GetArrayElementAtIndex(i).objectReferenceValue=merged[i];menu.ApplyModifiedPropertiesWithoutUndo();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);
            Debug.Log("[CH02M04PowerRelayNarrativeBuilder] result=Passed sequences=3 presentation=CaptionedCheckpoint locales=en,fa-IR voices="+voices);
        }
        private static void InstallLina()
        {
            var catalog=AssetDatabase.LoadAssetAtPath<NarrativeSpeakerCatalog>("Assets/Game/Configs/Narrative/FirstLaunch/FirstLaunchSpeakers.asset")??throw new InvalidOperationException("Narrative speaker catalog missing.");var data=new SerializedObject(catalog);var entries=data.FindProperty("speakers");SerializedProperty entry=null;for(int i=0;i<entries.arraySize;i++)if(entries.GetArrayElementAtIndex(i).FindPropertyRelative("speakerId").intValue==(int)NarrativeSpeakerId.Lina)entry=entries.GetArrayElementAtIndex(i);entry??=entries.GetArrayElementAtIndex(entries.arraySize++);entry.FindPropertyRelative("speakerId").intValue=(int)NarrativeSpeakerId.Lina;
            foreach(var pair in new[]{("name","Dr. Lina Mansour"),("role","East district shelter physician"),("accessibleLabel","Doctor Lina Mansour, east district shelter physician")}){entry.FindPropertyRelative(pair.Item1+"Key").stringValue="narrative.speaker.lina."+pair.Item1;entry.FindPropertyRelative(pair.Item1+"Fallback").stringValue=pair.Item2;}
            entry.FindPropertyRelative("treatment").intValue=(int)NarrativeSpeakerTreatment.HumanPortrait;const string portrait="Assets/Game/Art/UI/Portraits/Secondary/Portrait_Unit_Chr_Civilian_Female_02_Civilian_Card_512.png";var importer=AssetImporter.GetAtPath(portrait) as TextureImporter??throw new InvalidOperationException("Dr. Lina portrait missing.");importer.textureType=TextureImporterType.Sprite;importer.spriteImportMode=SpriteImportMode.Single;importer.mipmapEnabled=false;importer.SaveAndReimport();entry.FindPropertyRelative("identitySprite").objectReferenceValue=AssetDatabase.LoadAssetAtPath<Sprite>(portrait);entry.FindPropertyRelative("accentColor").colorValue=new Color(.38f,.76f,.72f);data.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(catalog);
        }
        private static void Configure(string stage,PowerRelayNarrativeLine[] lines,NarrativeSequenceConfig basis)
        {
            string sequenceId="seq.ch02.m04."+stage;bool debrief=stage=="debrief";var sequence=AssetDatabase.LoadAllAssetsAtPath(Path).OfType<NarrativeSequenceConfig>().FirstOrDefault(s=>s.SequenceId==sequenceId);if(sequence==null){sequence=ScriptableObject.CreateInstance<NarrativeSequenceConfig>();if(AssetDatabase.LoadMainAssetAtPath(Path)==null)AssetDatabase.CreateAsset(sequence,Path);else AssetDatabase.AddObjectToAsset(sequence,Path);}EditorUtility.CopySerialized(basis,sequence);sequence.name="CH02M04_PowerRelay_"+stage;var data=new SerializedObject(sequence);data.FindProperty("sequenceId").stringValue=sequenceId;data.FindProperty("entryStateId").stringValue="PowerRelay-"+stage+"-0";data.FindProperty("defaultSkipDestinationId").stringValue="PowerRelay-"+stage+"-complete";var states=data.FindProperty("states");states.arraySize=lines.Length+1;
            for(int i=0;i<states.arraySize;i++){bool complete=i==lines.Length;var state=states.GetArrayElementAtIndex(i);string completion="PowerRelay-"+stage+"-complete";S(state,"stateId",complete?completion:"PowerRelay-"+stage+"-"+i);state.FindPropertyRelative("kind").intValue=(int)(complete?(debrief?NarrativeStateKind.RouteArrival:NarrativeStateKind.RouteHandoff):NarrativeStateKind.PanelDialogue);S(state,"continueStateId",complete?string.Empty:i+1==lines.Length?completion:"PowerRelay-"+stage+"-"+(i+1));S(state,"skipStateId",complete?string.Empty:completion);S(state,"completionPayloadId",complete?"request.power_relay."+(stage=="brief"?"interactive_brief":stage)+".complete":string.Empty);state.FindPropertyRelative("routeRole").intValue=(int)(complete&&debrief?NarrativeRouteRole.DebriefArrival:NarrativeRouteRole.None);state.FindPropertyRelative("reducedMotionSupported").boolValue=true;state.FindPropertyRelative("motionPreset").intValue=(int)NarrativeMotionPreset.Static;state.FindPropertyRelative("musicCue").intValue=(int)NarrativeMusicCue.Briefing;state.FindPropertyRelative("ambienceCue").intValue=(int)NarrativeAmbienceCue.CityConflict;state.FindPropertyRelative("eventCue").intValue=(int)NarrativeEventCue.Radio;state.FindPropertyRelative("evidenceIds").arraySize=0;state.FindPropertyRelative("missionContextFlags").arraySize=0;state.FindPropertyRelative("panel16x9").objectReferenceValue=null;state.FindPropertyRelative("panel20x9").objectReferenceValue=null;state.FindPropertyRelative("durationSeconds").floatValue=complete?0:Duration(lines[i]);var authored=state.FindPropertyRelative("lines");authored.arraySize=complete?0:1;if(complete)continue;var line=authored.GetArrayElementAtIndex(0);var copy=lines[i];S(line,"lineId",copy.Id);S(line,"textKey",copy.Key);S(line,"englishFallback",copy.English);line.FindPropertyRelative("speaker").intValue=(int)copy.Speaker;line.FindPropertyRelative("voiceClip").objectReferenceValue=CH02M04PowerRelayMediaImporter.Voice(copy.Id,false);line.FindPropertyRelative("femaleVoiceClip").objectReferenceValue=null;line.FindPropertyRelative("neutralVoiceClip").objectReferenceValue=null;line.FindPropertyRelative("startSeconds").floatValue=0;line.FindPropertyRelative("deadlineSeconds").floatValue=Duration(copy);line.FindPropertyRelative("essentialCaption").boolValue=true;}
            data.ApplyModifiedPropertiesWithoutUndo();for(int i=0;i<sequence.States.Count;i++)SetPanelReference(sequence.States[i],"panel16x9Reference",i<lines.Length);for(int i=0;i<sequence.States.Count;i++)SetPanelReference(sequence.States[i],"panel20x9Reference",i<lines.Length);EditorUtility.SetDirty(sequence);
        }
        private static void SetPanelReference(NarrativeStateRecord state,string field,bool enabled)
        {
            AssetReferenceSprite reference=null;if(enabled){var settings=AddressableAssetSettingsDefaultObject.GetSettings(true)??throw new InvalidOperationException("Addressables settings missing.");var group=settings.FindGroup("Power Relay Narrative")??settings.CreateGroup("Power Relay Narrative",false,false,false,null,typeof(BundledAssetGroupSchema),typeof(ContentUpdateGroupSchema));string guid=AssetDatabase.AssetPathToGUID(CH02M04PowerRelayMediaImporter.ArtPath);settings.CreateOrMoveEntry(guid,group,false,false).SetAddress("narrative.power_relay.approved",false);reference=new AssetReferenceSprite(guid){SubObjectName=CH02M04PowerRelayMediaImporter.Panel().name};EditorUtility.SetDirty(group);EditorUtility.SetDirty(settings);}typeof(NarrativeStateRecord).GetField(field,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(state,reference);
        }
        private static void AddPersian()
        {
            var locale=AssetDatabase.LoadAssetAtPath<NarrativeLocaleConfig>(M02EstablishBaseNarrativeLocaleBuilder.PersianLocalePath);var data=new SerializedObject(locale);var entries=data.FindProperty("text");for(int i=entries.arraySize-1;i>=0;i--)if(entries.GetArrayElementAtIndex(i).FindPropertyRelative("key").stringValue.StartsWith("narrative.power_relay.",StringComparison.Ordinal))entries.DeleteArrayElementAtIndex(i);var voices=data.FindProperty("voices");for(int i=voices.arraySize-1;i>=0;i--)if(voices.GetArrayElementAtIndex(i).FindPropertyRelative("lineId").stringValue.StartsWith("power_relay-",StringComparison.Ordinal))voices.DeleteArrayElementAtIndex(i);foreach(var line in CH02M04PowerRelayMediaImporter.Lines){var entry=entries.GetArrayElementAtIndex(entries.arraySize++);S(entry,"key",line.Key);S(entry,"value",line.Persian);var voice=voices.GetArrayElementAtIndex(voices.arraySize++);S(voice,"lineId",line.Id);voice.FindPropertyRelative("voiceClip").objectReferenceValue=CH02M04PowerRelayMediaImporter.Voice(line.Id,true);voice.FindPropertyRelative("femaleVoiceClip").objectReferenceValue=null;voice.FindPropertyRelative("neutralVoiceClip").objectReferenceValue=null;}data.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(locale);
        }
        private static float Duration(in PowerRelayNarrativeLine line){var en=CH02M04PowerRelayMediaImporter.Voice(line.Id,false);var fa=CH02M04PowerRelayMediaImporter.Voice(line.Id,true);return Mathf.Max(8f,Mathf.Max(en?en.length:0,fa?fa.length:0)+.5f,Mathf.Max(line.English.Length,line.Persian.Length)/14f);}
        private static void S(SerializedProperty property,string field,string value)=>property.FindPropertyRelative(field).stringValue=value;
    }
}
