using System;
using System.Collections.Generic;
using System.Linq;
using Game.Configs;
using Game.UI.Runtime;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class CH02M05RouteReopenedPresentationBuilder
    {
        public const string GuidePath="Assets/Game/Configs/Missions/Chapter02/CH02M05_RouteReopened_FieldGuide.asset";
        [MenuItem("Game/Campaign/Route Reopened/Build Presentation")]
        public static void Build(){CH02M05RouteReopenedMediaImporter.ConfigureArt();SeedLocalization();BuildGuide();BindArt();AssetDatabase.SaveAssets();Debug.Log("[RouteReopenedPresentation] result=Passed locales=en,fa-IR controls=existing-only visual=approved");}
        private static void SeedLocalization()
        {
            var copy=new (string key,string en,string fa)[]{
                ("name","Route Reopened","مسیر باز شد"),("summary","Keep relief and Fuel moving, restore the disrupted lane, capture the logistics hub, and preserve its routing records.","امداد و سوخت رو در حرکت نگه دار، مسیر قطع‌شده رو برگردون، مرکز تدارکات رو تصرف کن و اسناد مسیرها رو سالم نگه دار."),("location","Eastern industrial logistics hub","مرکز تدارکات صنعتیِ شرق"),("enemy_intel","A fortified Ash Line garrison controls both stolen routes and the routing archive.","یک پادگان مستحکم اش‌لاین هر دو مسیر دزدیده‌شده و بایگانی مسیرها رو کنترل می‌کنه."),
                ("objective.lifelines","Keep both lifelines open","هر دو مسیر حیاتی رو باز نگه دار"),("objective.link","Reopen the disrupted lane","مسیر قطع‌شده رو باز کن"),("objective.hub","Capture the logistics hub","مرکز تدارکات رو تصرف کن"),("objective.records","Preserve the routing records","اسناد مسیرها رو سالم نگه دار"),
                ("objective.lifelines.body","Move the relief truck to the clinic lane and the Fuel truck to the water-service lane. Both vehicles must survive.","کامیون امداد رو به مسیر درمانگاه و کامیون سوخت رو به مسیر خدمات آب برسون. هر دو خودرو باید سالم بمونن."),("objective.link.body","Move both road engineers to the disrupted link and protect them there for 7 seconds.","هر دو مهندس راه‌سازی رو به اتصال قطع‌شده برسون و ۷ ثانیه ازشون محافظت کن."),("objective.hub.body","Move rifles through the marked hub gate and defeat the fortified garrison.","تفنگدارها رو از دروازهٔ مشخص‌شده وارد کن و پادگان مستحکم رو شکست بده."),("objective.records.body","After the garrison falls, hold rifles at the archive for 10 seconds without destroying the records.","بعد از سقوط پادگان، تفنگدارها رو ۱۰ ثانیه کنار بایگانی نگه دار و اسناد رو از بین نبر."),
                ("star.1","Complete the mission","مأموریت رو کامل کن"),("star.2","No lifeline lost","هیچ مسیر حیاتی از دست نره"),("star.3","Records intact","اسناد سالم بمونه"),("resources","Relief truck · Fuel truck · two road engineers","کامیون امداد · کامیون سوخت · دو مهندس راه‌سازی"),("forces","8 rifles · split defense and assault","۸ تفنگدار · تقسیم دفاع و تهاجم"),("deadline","10 active minutes","۱۰ دقیقه زمان فعال"),("reward.card","1,200 Commander XP · 6,000 Credits","۱۲۰۰ تجربهٔ فرمانده · ۶۰۰۰ اعتبار"),
                ("result.victory","Route reopened","مسیر باز شد"),("result.defeat","Logistics hub operation failed","عملیات مرکز تدارکات شکست خورد"),("result.success","Both lifelines remained active, the hub was captured, and Protocol Fragment Two was recovered from the intact routing archive.","هر دو مسیر حیاتی فعال موند، مرکز تصرف شد و قطعهٔ دوم پروتکل از بایگانی سالم مسیرها بازیابی شد."),
                ("failure.squad","The assault force was lost before the hub and archive were secured.","نیروی تهاجم پیش از تأمین مرکز و بایگانی از دست رفت."),("failure.engineer","A road engineer was lost. Both are required to restore the disrupted link.","یکی از مهندس‌های راه‌سازی از دست رفت. هر دو برای برگردوندن مسیر لازم هستن."),("failure.relief","The relief truck was lost and the clinic lifeline collapsed.","کامیون امداد از دست رفت و مسیر حیاتی درمانگاه قطع شد."),("failure.fuel","The Fuel truck was lost and the water-service lifeline collapsed.","کامیون سوخت از دست رفت و مسیر حیاتی خدمات آب قطع شد."),("failure.records","The routing archive was destroyed before ARIA could recover the evidence.","بایگانی مسیرها پیش از بازیابی مدارک توسط آریا نابود شد."),("failure.deadline","The hub and lifelines were not secured within ten minutes.","مرکز و مسیرهای حیاتی تا پایان ده دقیقه تأمین نشدن."),("failure.integrity","Mission state could not be verified. Return and retry; no rewards were settled.","وضعیت عملیات قابل تأیید نیست. برگرد و دوباره تلاش کن؛ پاداشی ثبت نشد."),
                ("guide.title","Route Reopened field guide","راهنمای مسیر باز شد"),("guide.1.title","Deliver clinic relief","امداد درمانگاه رو برسون"),("guide.1.body","Select the relief truck and move it to the marked clinic-lane destination.","کامیون امداد رو انتخاب کن و به مقصد مشخص‌شدهٔ مسیر درمانگاه ببر."),("guide.2.title","Deliver water-service Fuel","سوخت خدمات آب رو برسون"),("guide.2.body","Select the Fuel truck and move it to the marked water-service destination.","کامیون سوخت رو انتخاب کن و به مقصد مشخص‌شدهٔ خدمات آب ببر."),("guide.3.title","Restore the broken link","اتصال قطع‌شده رو برگردون"),("guide.3.body","Move both engineers to the disrupted lane and hold them there for 7 seconds.","هر دو مهندس رو به مسیر قطع‌شده ببر و ۷ ثانیه همون‌جا نگه دار."),("guide.4.title","Enter the logistics hub","وارد مرکز تدارکات شو"),("guide.4.body","Split off rifles, move through the marked gate, and keep convoy defenders behind.","بخشی از تفنگدارها رو جدا کن، از دروازهٔ مشخص‌شده وارد شو و محافظ‌های کاروان رو عقب نگه دار."),("guide.5.title","Defeat the garrison","پادگان رو شکست بده"),("guide.5.body","Attack confirmed Ash Line defenders without damaging the routing archive.","به مدافع‌های تأییدشدهٔ اش‌لاین حمله کن، بدون اینکه به بایگانی مسیرها آسیب بزنی."),("guide.6.title","Preserve the routing records","اسناد مسیرها رو حفظ کن"),("guide.6.body","Hold rifles at the archive for 10 seconds while ARIA assembles Protocol Fragment Two.","تفنگدارها رو ۱۰ ثانیه کنار بایگانی نگه دار تا آریا قطعهٔ دوم پروتکل رو کامل کنه."),
                ("guide.example","Use only Select, Move, Attack and Hold. ARIA demonstrates these same player orders.","فقط از انتخاب، حرکت، حمله و توقف استفاده کن. آریا هم همین فرمان‌های بازیکن رو نمایش می‌ده."),("guide.mistake","Do not abandon a lifeline or destroy the hub. Victory requires the city to keep operating and the records to survive.","هیچ مسیر حیاتی رو رها نکن و مرکز رو نابود نکن. پیروزی یعنی شهر فعال بمونه و اسناد سالم بمونن."),("guide.diagram","RELIEF + FUEL → ACTIVE LANES · 2 ENGINEERS → LINK · RIFLES → HUB → RECORDS","امداد + سوخت ← مسیرهای فعال · ۲ مهندس ← اتصال · تفنگدارها ← مرکز ← اسناد"),("chapter_name","ROUTE REOPENED","مسیر باز شد")};
            GameLocalizationCatalog catalog=AssetDatabase.LoadAssetAtPath<GameLocalizationCatalog>(V3UiLocalizationCatalogBuilder.CatalogPath)??throw new InvalidOperationException("Localization catalog missing.");var tables=new List<GameLocaleTable>();
            foreach(GameLocaleTable locale in catalog.Locales){if(locale.LocaleCode!="en"&&locale.LocaleCode!="fa-IR"){tables.Add(locale);continue;}bool fa=locale.LocaleCode=="fa-IR";var entries=locale.Entries.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal);foreach(var line in copy)entries[line.key=="chapter_name"?"chapter.broken_grid.mission.5":"mission.route_reopened."+line.key]=fa?line.fa:line.en;foreach(var line in CH02M05RouteReopenedMediaImporter.Lines)entries[line.Key]=fa?line.Persian:line.English;tables.Add(new GameLocaleTable(locale.LocaleCode,locale.DisplayName,locale.ShortLabel,locale.RightToLeft,locale.FontAsset,entries.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>new GameLocalizedStringRecord(x.Key,x.Value))));}catalog.Configure(catalog.SourceLocaleCode,tables);EditorUtility.SetDirty(catalog);
        }
        private static void BuildGuide()
        {
            var guide=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(GuidePath);if(guide==null){guide=ScriptableObject.CreateInstance<MissionFieldGuideConfig>();AssetDatabase.CreateAsset(guide,GuidePath);}var basis=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(M03RadarWarningGuideBuilder.Path);var classes=basis.Classes.ToArray();for(int i=0;i<classes.Length;i++)if(classes[i].Availability!=MissionGuideAvailability.Unavailable)classes[i].Availability=MissionGuideAvailability.Reference;
            guide.Configure(Enumerable.Range(1,6).Select(i=>new MissionGuideTopic{TitleKey=$"mission.route_reopened.guide.{i}.title",BodyKey=$"mission.route_reopened.guide.{i}.body",ExampleKey="mission.route_reopened.guide.example",MistakeKey="mission.route_reopened.guide.mistake",DiagramKey="mission.route_reopened.guide.diagram"}).ToArray(),classes);EditorUtility.SetDirty(guide);
            GameObject root=PrefabUtility.LoadPrefabContents(M03RadarWarningUiBuilder.GuidePath);try{var data=new SerializedObject(root.GetComponentInChildren<MissionFieldGuideView>(true));data.FindProperty("routeReopenedGuide").objectReferenceValue=guide;data.ApplyModifiedPropertiesWithoutUndo();MissionUiSerializedBindingsAuthoring.Apply(root);PrefabUtility.SaveAsPrefabAsset(root,M03RadarWarningUiBuilder.GuidePath);}finally{PrefabUtility.UnloadPrefabContents(root);}
        }
        private static void BindArt()
        {
            Texture art=CH02M05RouteReopenedMediaImporter.Preview()??throw new InvalidOperationException("Route Reopened art missing.");foreach(string path in new[]{"Assets/Game/Prefabs/UI/Shell/Content/SCN05_CampaignOperationsContent.prefab","Assets/Game/Prefabs/UI/Shell/Content/SCN06_MissionBriefingContent.prefab"}){GameObject root=PrefabUtility.LoadPrefabContents(path);try{var campaign=root.GetComponentInChildren<CampaignOperationsScreenView>(true);UnityEngine.Object view=campaign!=null?(UnityEngine.Object)campaign:root.GetComponentInChildren<MissionBriefingScreenView>(true);var data=new SerializedObject(view);data.FindProperty(campaign!=null?"routeReopenedMissionPreview":"routeReopenedMissionArt").objectReferenceValue=art;data.ApplyModifiedPropertiesWithoutUndo();PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
        }
        [MenuItem("Game/Campaign/Route Reopened/Build Player-Ready Checkpoint")]
        public static void BuildCheckpoint(){CH02M05RouteReopenedRulesValidation.Run();CH02M05RouteReopenedConfigBuilder.Build();Build();CH02M05RouteReopenedNarrativeBuilder.BuildCaptionedArtAndInstall();Debug.Log("[RouteReopenedCheckpoint] result=Passed scope=CaptionedConfiguration controls=existing-only");}
    }
}
