using System;
using System.Collections.Generic;
using System.Linq;
using Game.Configs;
using Game.UI.Runtime;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class CH03M01SignalTracePresentationBuilder
    {
        public const string GuidePath="Assets/Game/Configs/Missions/Chapter03/CH03M01_SignalTrace_FieldGuide.asset";
        [MenuItem("Game/Campaign/Signal Trace/Build Presentation")]
        public static void Build(){CH03M01SignalTraceMediaImporter.ConfigureArt();SeedLocalization();BuildGuide();BindArt();AssetDatabase.SaveAssets();Debug.Log("[SignalTracePresentation] result=Passed locales=en,fa-IR controls=existing-only visual=approved");}
        private static void SeedLocalization()
        {
            var copy=new (string key,string en,string fa)[]{
                ("name","Signal Trace","ردیابی سیگنال"),("summary","Compare two observation points, protect legitimate civilian radios, isolate the confirmed armed carrier and recover its Relay device intact.","دو نقطهٔ دیده‌بانی رو مقایسه کن، از بی‌سیم‌های عادی مردم محافظت کن، حامل مسلحِ تأییدشده رو جدا کن و دستگاه شبکه رو سالم تحویل بگیر."),("location","South district service corridors","راهروهای خدماتی منطقهٔ جنوبی"),("enemy_intel","Several legitimate radios share the signature. Only the transmitter moving with a confirmed armed escort is targetable.","چند بی‌سیم عادی همین امضا رو دارن. فقط فرستنده‌ای که همراه اسکورت مسلحِ تأییدشده حرکت می‌کنه قابل هدف‌گیریه."),
                ("objective.compare","Compare both observation points","هر دو نقطهٔ دیده‌بانی رو مقایسه کن"),("objective.intercept","Isolate the confirmed armed escort","اسکورت مسلحِ تأییدشده رو جدا کن"),("objective.recover","Recover the device; protect civilian radios","دستگاه رو تحویل بگیر؛ از بی‌سیم‌های مردم محافظت کن"),("objective.compare.body","Move a rifle squad to each marked observation point and hold for 6 seconds. ARIA cannot confirm a target from proximity alone.","یک گروه تفنگدار رو به هر نقطهٔ دیده‌بانی ببر و ۶ ثانیه نگه دار. آریا فقط با نزدیک بودن نمی‌تونه هدف رو تأیید کنه."),("objective.intercept.body","After both observations confirm the carrier, defeat only its armed escort and keep fire away from protected transmitters.","بعد از اینکه هر دو دیده‌بانی حامل رو تأیید کردن، فقط اسکورت مسلحش رو شکست بده و از فرستنده‌های حفاظت‌شده دور بمون."),("objective.recover.body","Escort the three protected civilian transmitters through the district, leave the suspect carrier isolated, and secure the recovered device for 10 seconds.","سه فرستندهٔ غیرنظامیِ حفاظت‌شده رو از منطقه عبور بده، حامل مشکوک رو جدا نگه دار و دستگاه بازیابی‌شده رو ۱۰ ثانیه امن کن."),
                ("star.1","Complete the mission","مأموریت رو کامل کن"),("star.2","No protected signal lost","هیچ سیگنال حفاظت‌شده‌ای از دست نره"),("star.3","Finish within 7 minutes","در کمتر از ۷ دقیقه تمام کن"),("resources","Two observation points · three protected signals · one suspect carrier","دو نقطهٔ دیده‌بانی · سه سیگنال حفاظت‌شده · یک حامل مشکوک"),("forces","8 rifles · observation and interception team","۸ تفنگدار · گروه دیده‌بانی و رهگیری"),("deadline","10 active minutes","۱۰ دقیقه زمان فعال"),("reward.card","1,000 Commander XP · 5,000 Credits","۱۰۰۰ تجربهٔ فرمانده · ۵۰۰۰ اعتبار"),
                ("result.victory","Signal traced","سیگنال ردیابی شد"),("result.defeat","Signal trace compromised","عملیات ردیابی مختل شد"),("result.success","The armed carrier was isolated, civilian radios remained protected and the intact Relay device revealed a verified safehouse.","حامل مسلح جدا شد، بی‌سیم‌های مردم امن موندن و دستگاه سالم شبکه یک مخفیگاه تأییدشده رو آشکار کرد."),("failure.squad","The observation team was lost before the carrier could be confirmed.","گروه دیده‌بانی پیش از تأیید حامل از دست رفت."),("failure.convoy","A protected civilian transmitter was lost. Legitimate local radio use must remain safe.","یک فرستندهٔ غیرنظامیِ حفاظت‌شده از دست رفت. استفادهٔ عادی مردم از بی‌سیم باید امن بمونه."),("failure.wrong_transfer","A protected signal was treated as hostile. Verify both observation points before isolating the armed carrier.","یک سیگنال حفاظت‌شده به‌عنوان دشمن هدف گرفته شد. قبل از جدا کردن حامل مسلح، هر دو نقطهٔ دیده‌بانی رو بررسی کن."),("failure.deadline","The carrier was not isolated within ten minutes.","حامل تا پایان ده دقیقه جدا نشد."),("failure.integrity","Mission state could not be verified. Return and retry; no rewards were settled.","وضعیت عملیات قابل تأیید نیست. برگرد و دوباره تلاش کن؛ پاداشی ثبت نشد."),
                ("guide.title","Signal Trace field guide","راهنمای ردیابی سیگنال"),("guide.1.title","Observe before acting","قبل از اقدام بررسی کن"),("guide.1.body","Move rifles to the first marked observation point and hold for 6 seconds.","تفنگدارها رو به نقطهٔ دیده‌بانی اول ببر و ۶ ثانیه نگه دار."),("guide.2.title","Corroborate the route","مسیر رو دوباره تأیید کن"),("guide.2.body","Repeat at the second observation point. Two observations separate coincidence from evidence.","همین کار رو در نقطهٔ دوم تکرار کن. دو مشاهده فرق تصادف و مدرک رو روشن می‌کنه."),("guide.3.title","Protect legitimate signals","از سیگنال‌های عادی محافظت کن"),("guide.3.body","Keep the clinic, delivery and neighborhood radios moving. They are protected, not targets.","بی‌سیم‌های درمانگاه، پخش و محله رو در حرکت نگه دار. اون‌ها حفاظت‌شده‌ان، نه هدف."),("guide.4.title","Isolate the armed escort","اسکورت مسلح رو جدا کن"),("guide.4.body","Attack only after ARIA confirms the carrier travelling with the armed patrol.","فقط وقتی حمله کن که آریا حرکت حامل همراه گشت مسلح رو تأیید کرده باشه."),("guide.5.title","Recover the device intact","دستگاه رو سالم تحویل بگیر"),("guide.5.body","Hold the secured area for 10 seconds while ARIA extracts the continuity-era route.","منطقهٔ امن‌شده رو ۱۰ ثانیه نگه دار تا آریا مسیر قدیمی شبکه رو استخراج کنه."),("guide.example","Use Select, Move, Attack and Hold. ARIA demonstrates the same player orders.","از انتخاب، حرکت، حمله و توقف استفاده کن. آریا همین فرمان‌های بازیکن رو نمایش می‌ده."),("guide.mistake","Shared signatures are not proof. Never attack a transmitter until the armed escort is confirmed.","امضای مشترک مدرک نیست. تا وقتی اسکورت مسلح تأیید نشده، به هیچ فرستنده‌ای حمله نکن."),("guide.diagram","2 OBSERVATIONS → CONFIRM · CIVILIAN SIGNALS → PROTECT · ARMED CARRIER → ISOLATE","۲ دیده‌بانی ← تأیید · سیگنال‌های مردم ← حفاظت · حامل مسلح ← جداسازی")};
            GameLocalizationCatalog catalog=AssetDatabase.LoadAssetAtPath<GameLocalizationCatalog>(V3UiLocalizationCatalogBuilder.CatalogPath)??throw new InvalidOperationException("Localization catalog missing.");var tables=new List<GameLocaleTable>();foreach(GameLocaleTable locale in catalog.Locales){if(locale.LocaleCode!="en"&&locale.LocaleCode!="fa-IR"){tables.Add(locale);continue;}bool fa=locale.LocaleCode=="fa-IR";var entries=locale.Entries.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal);entries["chapter.hidden_network.name"]=fa?"شبکهٔ پنهان":"HIDDEN NETWORK";string[] enNames={"Signal Trace","Safehouse Sweep","False Front","Evidence Chain","Network Break"};string[] faNames={"ردیابی سیگنال","پاکسازی مخفیگاه","پوشش جعلی","زنجیرهٔ شواهد","شکستن شبکه"};for(int i=0;i<5;i++)entries["chapter.hidden_network.mission."+(i+1)]=fa?faNames[i]:enNames[i];foreach(var line in copy)entries["mission.signal_trace."+line.key]=fa?line.fa:line.en;foreach(var line in CH03M01SignalTraceMediaImporter.Lines)entries[line.Key]=fa?line.Persian:line.English;tables.Add(new GameLocaleTable(locale.LocaleCode,locale.DisplayName,locale.ShortLabel,locale.RightToLeft,locale.FontAsset,entries.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>new GameLocalizedStringRecord(x.Key,x.Value))));}catalog.Configure(catalog.SourceLocaleCode,tables);EditorUtility.SetDirty(catalog);
        }
        private static void BuildGuide()
        {
            System.IO.Directory.CreateDirectory("Assets/Game/Configs/Missions/Chapter03");var guide=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(GuidePath);if(guide==null){guide=ScriptableObject.CreateInstance<MissionFieldGuideConfig>();AssetDatabase.CreateAsset(guide,GuidePath);}var basis=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(M03RadarWarningGuideBuilder.Path);var classes=basis.Classes.ToArray();for(int i=0;i<classes.Length;i++)if(classes[i].Availability!=MissionGuideAvailability.Unavailable)classes[i].Availability=MissionGuideAvailability.Reference;guide.Configure(Enumerable.Range(1,5).Select(i=>new MissionGuideTopic{TitleKey=$"mission.signal_trace.guide.{i}.title",BodyKey=$"mission.signal_trace.guide.{i}.body",ExampleKey="mission.signal_trace.guide.example",MistakeKey="mission.signal_trace.guide.mistake",DiagramKey="mission.signal_trace.guide.diagram"}).ToArray(),classes);EditorUtility.SetDirty(guide);
            GameObject root=PrefabUtility.LoadPrefabContents(M03RadarWarningUiBuilder.GuidePath);try{var data=new SerializedObject(root.GetComponentInChildren<MissionFieldGuideView>(true));data.FindProperty("signalTraceGuide").objectReferenceValue=guide;data.ApplyModifiedPropertiesWithoutUndo();MissionUiSerializedBindingsAuthoring.Apply(root);PrefabUtility.SaveAsPrefabAsset(root,M03RadarWarningUiBuilder.GuidePath);}finally{PrefabUtility.UnloadPrefabContents(root);}
        }
        private static void BindArt()
        {
            Texture art=CH03M01SignalTraceMediaImporter.Preview()??throw new InvalidOperationException("Signal Trace art missing.");foreach(string path in new[]{"Assets/Game/Prefabs/UI/Shell/Content/SCN05_CampaignOperationsContent.prefab","Assets/Game/Prefabs/UI/Shell/Content/SCN06_MissionBriefingContent.prefab"}){GameObject root=PrefabUtility.LoadPrefabContents(path);try{var campaign=root.GetComponentInChildren<CampaignOperationsScreenView>(true);UnityEngine.Object view=campaign!=null?(UnityEngine.Object)campaign:root.GetComponentInChildren<MissionBriefingScreenView>(true);var data=new SerializedObject(view);data.FindProperty(campaign!=null?"signalTraceMissionPreview":"signalTraceMissionArt").objectReferenceValue=art;data.ApplyModifiedPropertiesWithoutUndo();PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
        }
        [MenuItem("Game/Campaign/Signal Trace/Build Player-Ready Checkpoint")]
        public static void BuildCheckpoint(){CH03M01SignalTraceRulesValidation.Run();CH03M01SignalTraceConfigBuilder.Build();Build();CH03M01SignalTraceNarrativeBuilder.BuildCaptionedArtAndInstall();Debug.Log("[SignalTraceCheckpoint] result=Passed scope=CaptionedConfiguration controls=existing-only");}
        [MenuItem("Game/Campaign/Signal Trace/Build Local Checkpoint Without Voices")]
        public static void BuildLocalCheckpointWithoutVoices(){CH03M01SignalTraceRulesValidation.Run();CH03M01SignalTraceConfigBuilder.Build();Build();CH03M01SignalTraceNarrativeBuilder.BuildCaptionedArtWithoutVoices();Debug.Log("[SignalTraceLocalCheckpoint] result=Passed scope=CaptionedConfiguration voices=pending-external-transfer controls=existing-only");}
    }
}
