using System;
using System.Collections.Generic;
using System.Linq;
using Game.Configs;
using Game.UI.Runtime;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class CH03M02SafehouseSweepPresentationBuilder
    {
        public const string GuidePath="Assets/Game/Configs/Missions/Chapter03/CH03M02_SafehouseSweep_FieldGuide.asset";

        [MenuItem("Game/Campaign/Safehouse Sweep/Build Presentation")]
        public static void Build()
        {
            CH03M02SafehouseSweepMediaImporter.ConfigureArt();SeedLocalization();BuildGuide();BindArt();AssetDatabase.SaveAssets();
            Debug.Log("[SafehouseSweepPresentation] result=Passed locales=en,fa-IR preview=clean comicPanels=7 controls=existing-only visual=approved");
        }

        private static void SeedLocalization()
        {
            var copy=new (string key,string en,string fa)[]{
                ("name","Safehouse Sweep","پاکسازی مخفیگاه"),("summary","Confirm both exits, protect the occupied family homes, clear only the verified weapons safehouse and capture its courier with the evidence ledger intact.","هر دو راه خروج رو تأیید کن، از خانه‌های مسکونی محافظت کن، فقط مخفیگاه سلاحِ تأییدشده رو پاکسازی کن و پیک رو همراه دفتر شواهد سالم دستگیر کن."),("location","Residential service lanes · east district","راه‌های خدماتی محلهٔ مسکونی · منطقهٔ شرقی"),("enemy_intel","One reinforced weapons node is verified. The neighboring building is an occupied family home. A courier may flee through the rear service lane.","یک انبار سلاحِ تقویت‌شده تأیید شده. ساختمان کناری خانهٔ یک خانواده‌ست. ممکنه پیک از راه خدماتی پشت ساختمان فرار کنه."),
                ("objective.confirm","Seal and confirm both safehouse exits","هر دو راه خروج مخفیگاه رو ببند و تأیید کن"),("objective.protect","Keep three civilian assets protected","از سه دارایی غیرنظامی محافظت کن"),("objective.ledger","Capture the courier and preserve the ledger","پیک رو دستگیر کن و دفتر شواهد رو سالم نگه دار"),("objective.confirm.body","Move the assault squad to each marked exit and hold for 6 seconds. Do not breach until both sides of the verified building are sealed.","گروه تهاجمی رو به هر خروجی علامت‌گذاری‌شده ببر و ۶ ثانیه نگه دار. تا وقتی هر دو سمت ساختمان تأییدشده بسته نشده، وارد نشو."),("objective.protect.body","Keep the family home, east passage and resident route protected. Any attack on a protected asset fails the mission.","خانهٔ خانوادگی، گذر شرقی و مسیر ساکن‌ها رو امن نگه دار. هر حمله به دارایی حفاظت‌شده مأموریت رو شکست می‌ده."),("objective.ledger.body","Clear the armed safehouse, block the rear lane and hold the courier capture area for 10 seconds without destroying the evidence.","مخفیگاه مسلح رو پاکسازی کن، راه پشت رو ببند و بدون نابود کردن شواهد ۱۰ ثانیه منطقهٔ دستگیری پیک رو نگه دار."),
                ("star.1","Complete the mission","مأموریت رو کامل کن"),("star.2","No protected civilian asset lost","هیچ دارایی غیرنظامی از دست نره"),("star.3","Finish within 7 minutes","در کمتر از ۷ دقیقه تمام کن"),("resources","Two exits · three protected assets · one evidence courier","دو خروجی · سه دارایی حفاظت‌شده · یک پیک شواهد"),("forces","8 rifles · perimeter and capture team","۸ تفنگدار · گروه محاصره و دستگیری"),("deadline","10 active minutes","۱۰ دقیقه زمان فعال"),("reward.card","1,200 Commander XP · 6,000 Credits","۱۲۰۰ تجربهٔ فرمانده · ۶۰۰۰ اعتبار"),
                ("result.victory","Safehouse secured","مخفیگاه امن شد"),("result.defeat","Safehouse sweep failed","پاکسازی مخفیگاه شکست خورد"),("result.success","The verified weapons node was cleared, the neighboring family was unharmed and the intact ledger exposed the evidence courier network.","انبار سلاحِ تأییدشده پاکسازی شد، خانوادهٔ ساختمان کناری آسیب ندید و دفتر سالم شبکهٔ پیک شواهد رو آشکار کرد."),("failure.squad","The perimeter team was lost before the safehouse could be secured.","گروه محاصره پیش از امن شدن مخفیگاه از دست رفت."),("failure.convoy","A protected civilian asset was lost. Fire must stay inside the verified safehouse boundary.","یک دارایی غیرنظامی از دست رفت. آتش باید داخل محدودهٔ مخفیگاه تأییدشده بمونه."),("failure.wrong_transfer","The occupied family home was treated as hostile. Only the verified weapons node is a valid target.","خانهٔ مسکونی به‌عنوان دشمن هدف گرفته شد. فقط انبار سلاحِ تأییدشده هدف معتبره."),("failure.deadline","The courier escaped with the ledger.","پیک همراه دفتر شواهد فرار کرد."),("failure.integrity","Mission state could not be verified. Return and retry; no rewards were settled.","وضعیت عملیات قابل تأیید نیست. برگرد و دوباره تلاش کن؛ پاداشی ثبت نشد."),
                ("guide.title","Safehouse Sweep field guide","راهنمای پاکسازی مخفیگاه"),("guide.1.title","Seal the front exit","خروجی جلو رو ببند"),("guide.1.body","Move rifles to the first marked exit and hold for 6 seconds.","تفنگدارها رو به خروجی اول ببر و ۶ ثانیه نگه دار."),("guide.2.title","Seal the service lane","راه خدماتی رو ببند"),("guide.2.body","Hold the rear exit too. The courier route is not secure until both exits are covered.","خروجی پشت رو هم نگه دار. تا هر دو راه پوشش داده نشن، مسیر پیک امن نیست."),("guide.3.title","Protect the occupied side","از بخش مسکونی محافظت کن"),("guide.3.body","Keep all three protected civilian assets moving and outside the safehouse fire boundary.","هر سه دارایی غیرنظامی رو در حرکت و بیرون از محدودهٔ آتش مخفیگاه نگه دار."),("guide.4.title","Clear the verified node","مخفیگاه تأییدشده رو پاکسازی کن"),("guide.4.body","Attack only the armed safehouse after both exits are confirmed. Never fire into the neighboring home.","بعد از تأیید هر دو خروجی فقط به مخفیگاه مسلح حمله کن. به خانهٔ کناری شلیک نکن."),("guide.5.title","Capture the ledger intact","دفتر شواهد رو سالم بگیر"),("guide.5.body","Hold the capture area for 10 seconds while ARIA secures the courier's ledger.","منطقهٔ دستگیری رو ۱۰ ثانیه نگه دار تا آریا دفتر پیک رو امن کنه."),("guide.example","Use Select, Move, Attack and Hold. ARIA demonstrates the same player orders.","از انتخاب، حرکت، حمله و توقف استفاده کن. آریا همین فرمان‌های بازیکن رو نمایش می‌ده."),("guide.mistake","The second building is occupied, not hostile. Suspicion never authorizes a breach.","ساختمان دوم مسکونیه، نه دشمن. شک هیچ‌وقت مجوز ورود نیست."),("guide.diagram","2 EXITS → SEAL · CIVILIAN SIDE → PROTECT · COURIER → CAPTURE","۲ خروجی ← بستن · بخش مسکونی ← حفاظت · پیک ← دستگیری")};
            GameLocalizationCatalog catalog=AssetDatabase.LoadAssetAtPath<GameLocalizationCatalog>(V3UiLocalizationCatalogBuilder.CatalogPath)??throw new InvalidOperationException("Localization catalog missing.");var tables=new List<GameLocaleTable>();
            foreach(GameLocaleTable locale in catalog.Locales){if(locale.LocaleCode!="en"&&locale.LocaleCode!="fa-IR"){tables.Add(locale);continue;}bool fa=locale.LocaleCode=="fa-IR";var entries=locale.Entries.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal);foreach(var line in copy)entries["mission.safehouse_sweep."+line.key]=fa?line.fa:line.en;foreach(var line in CH03M02SafehouseSweepMediaImporter.Lines)entries[line.Key]=fa?line.Persian:line.English;tables.Add(new GameLocaleTable(locale.LocaleCode,locale.DisplayName,locale.ShortLabel,locale.RightToLeft,locale.FontAsset,entries.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>new GameLocalizedStringRecord(x.Key,x.Value))));}
            catalog.Configure(catalog.SourceLocaleCode,tables);EditorUtility.SetDirty(catalog);
        }

        private static void BuildGuide()
        {
            System.IO.Directory.CreateDirectory("Assets/Game/Configs/Missions/Chapter03");var guide=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(GuidePath);if(guide==null){guide=ScriptableObject.CreateInstance<MissionFieldGuideConfig>();AssetDatabase.CreateAsset(guide,GuidePath);}var basis=AssetDatabase.LoadAssetAtPath<MissionFieldGuideConfig>(M03RadarWarningGuideBuilder.Path);var classes=basis.Classes.ToArray();for(int i=0;i<classes.Length;i++)if(classes[i].Availability!=MissionGuideAvailability.Unavailable)classes[i].Availability=MissionGuideAvailability.Reference;guide.Configure(Enumerable.Range(1,5).Select(i=>new MissionGuideTopic{TitleKey=$"mission.safehouse_sweep.guide.{i}.title",BodyKey=$"mission.safehouse_sweep.guide.{i}.body",ExampleKey="mission.safehouse_sweep.guide.example",MistakeKey="mission.safehouse_sweep.guide.mistake",DiagramKey="mission.safehouse_sweep.guide.diagram"}).ToArray(),classes);EditorUtility.SetDirty(guide);
            GameObject root=PrefabUtility.LoadPrefabContents(M03RadarWarningUiBuilder.GuidePath);try{var data=new SerializedObject(root.GetComponentInChildren<MissionFieldGuideView>(true));data.FindProperty("safehouseSweepGuide").objectReferenceValue=guide;data.ApplyModifiedPropertiesWithoutUndo();MissionUiSerializedBindingsAuthoring.Apply(root);PrefabUtility.SaveAsPrefabAsset(root,M03RadarWarningUiBuilder.GuidePath);}finally{PrefabUtility.UnloadPrefabContents(root);}
        }

        private static void BindArt()
        {
            Texture art=CH03M02SafehouseSweepMediaImporter.Preview()??throw new InvalidOperationException("Safehouse Sweep art missing.");if(AssetDatabase.GetAssetPath(art)==CH03M02SafehouseSweepMediaImporter.SourceArt)throw new InvalidOperationException("Safehouse Sweep preview must not embed the full briefing UI mockup.");
            foreach(string path in new[]{"Assets/Game/Prefabs/UI/Shell/Content/SCN05_CampaignOperationsContent.prefab","Assets/Game/Prefabs/UI/Shell/Content/SCN06_MissionBriefingContent.prefab"}){GameObject root=PrefabUtility.LoadPrefabContents(path);try{var campaign=root.GetComponentInChildren<CampaignOperationsScreenView>(true);UnityEngine.Object view=campaign!=null?(UnityEngine.Object)campaign:root.GetComponentInChildren<MissionBriefingScreenView>(true);var data=new SerializedObject(view);var property=data.FindProperty(campaign!=null?"safehouseSweepMissionPreview":"safehouseSweepMissionArt");property.objectReferenceValue=art;data.ApplyModifiedPropertiesWithoutUndo();if(AssetDatabase.GetAssetPath(property.objectReferenceValue)!=CH03M02SafehouseSweepMediaImporter.PreviewPath)throw new InvalidOperationException("Safehouse Sweep clean preview binding failed: "+path);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
        }

        [MenuItem("Game/Campaign/Safehouse Sweep/Build Player-Ready Checkpoint")]
        public static void BuildCheckpoint(){CH03M02SafehouseSweepRulesValidation.Run();CH03M02SafehouseSweepConfigBuilder.Build();Build();CH03M02SafehouseSweepNarrativeBuilder.BuildCaptionedArtAndInstall();Debug.Log("[SafehouseSweepCheckpoint] result=Passed scope=CaptionedConfiguration voices=local controls=existing-only");}
        [MenuItem("Game/Campaign/Safehouse Sweep/Build Local Checkpoint Without Voices")]
        public static void BuildLocalCheckpointWithoutVoices(){CH03M02SafehouseSweepRulesValidation.Run();CH03M02SafehouseSweepConfigBuilder.Build();Build();CH03M02SafehouseSweepNarrativeBuilder.BuildCaptionedArtWithoutVoices();Debug.Log("[SafehouseSweepLocalCheckpoint] result=Passed scope=CaptionedConfiguration voices=pending-external-transfer controls=existing-only");}
    }
}
