// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static class AudioEventIds
    {
        public const string UIButtonPrimaryClick = "UI.Button.Primary.Click";
        public const uint UIButtonPrimaryClickHash = 3161187545u;

        public const string UIButtonSecondaryClick = "UI.Button.Secondary.Click";
        public const uint UIButtonSecondaryClickHash = 2478076573u;

        public const string UIButtonNegativeClick = "UI.Button.Negative.Click";
        public const uint UIButtonNegativeClickHash = 2301339126u;

        public const string UIButtonDisabledTap = "UI.Button.Disabled.Tap";
        public const uint UIButtonDisabledTapHash = 117293880u;

        public const string UITabSelect = "UI.Tab.Select";
        public const uint UITabSelectHash = 3352358512u;

        public const string UICardSelect = "UI.Card.Select";
        public const uint UICardSelectHash = 3014326253u;

        public const string UICardLocked = "UI.Card.Locked";
        public const uint UICardLockedHash = 3087335763u;

        public const string UIPopupOpen = "UI.Popup.Open";
        public const uint UIPopupOpenHash = 1791759535u;

        public const string UIPopupClose = "UI.Popup.Close";
        public const uint UIPopupCloseHash = 3024952377u;

        public const string UISliderTick = "UI.Slider.Tick";
        public const uint UISliderTickHash = 1305878613u;

        public const string UIToggleOn = "UI.Toggle.On";
        public const uint UIToggleOnHash = 1412658802u;

        public const string UIToggleOff = "UI.Toggle.Off";
        public const uint UIToggleOffHash = 2434261764u;

        public const string UIFeedbackToastError = "UI.Feedback.Toast.Error";
        public const uint UIFeedbackToastErrorHash = 2617262137u;

        public const string UIFeedbackToastPositive = "UI.Feedback.Toast.Positive";
        public const uint UIFeedbackToastPositiveHash = 3875576338u;

        public const string GameplayUnitSelectInfantry = "Gameplay.Unit.Select.Infantry";
        public const uint GameplayUnitSelectInfantryHash = 3141110590u;

        public const string GameplayUnitSelectVehicle = "Gameplay.Unit.Select.Vehicle";
        public const uint GameplayUnitSelectVehicleHash = 3174649265u;

        public const string GameplayUnitSelectAir = "Gameplay.Unit.Select.Air";
        public const uint GameplayUnitSelectAirHash = 2620032125u;

        public const string GameplayCommandMoveAccepted = "Gameplay.Command.Move.Accepted";
        public const uint GameplayCommandMoveAcceptedHash = 1382687044u;

        public const string GameplayCommandAttackAccepted = "Gameplay.Command.Attack.Accepted";
        public const uint GameplayCommandAttackAcceptedHash = 3185718759u;

        public const string GameplayCommandHoldAccepted = "Gameplay.Command.Hold.Accepted";
        public const uint GameplayCommandHoldAcceptedHash = 2504035620u;

        public const string GameplayCommandStopReturning = "Gameplay.Command.Stop.Returning";
        public const uint GameplayCommandStopReturningHash = 3510404204u;

        public const string GameplayCommandScanTargeting = "Gameplay.Command.Scan.Targeting";
        public const uint GameplayCommandScanTargetingHash = 1422340592u;

        public const string GameplayCommandScanAccepted = "Gameplay.Command.Scan.Accepted";
        public const uint GameplayCommandScanAcceptedHash = 1764603952u;

        public const string GameplayCommandRejected = "Gameplay.Command.Rejected";
        public const uint GameplayCommandRejectedHash = 4172340306u;

        public const string GameplayBuildPlaceValid = "Gameplay.Build.Place.Valid";
        public const uint GameplayBuildPlaceValidHash = 3769720894u;

        public const string GameplayBuildPlaceInvalid = "Gameplay.Build.Place.Invalid";
        public const uint GameplayBuildPlaceInvalidHash = 1788114895u;

        public const string GameplayProductionQueued = "Gameplay.Production.Queued";
        public const uint GameplayProductionQueuedHash = 2682016025u;

        public const string GameplayProductionComplete = "Gameplay.Production.Complete";
        public const uint GameplayProductionCompleteHash = 2701904751u;

        public const string AlertThreatMinor = "Alert.Threat.Minor";
        public const uint AlertThreatMinorHash = 3119639462u;

        public const string AlertThreatCritical = "Alert.Threat.Critical";
        public const uint AlertThreatCriticalHash = 2327085632u;

        public const string AlertUnitUnderAttack = "Alert.Unit.UnderAttack";
        public const uint AlertUnitUnderAttackHash = 4035338951u;

        public const string AlertBaseBreached = "Alert.Base.Breached";
        public const uint AlertBaseBreachedHash = 2770899834u;

        public const string GameplayObjectiveProgress = "Gameplay.Objective.Progress";
        public const uint GameplayObjectiveProgressHash = 3042211329u;

        public const string GameplayObjectiveComplete = "Gameplay.Objective.Complete";
        public const uint GameplayObjectiveCompleteHash = 1524265589u;

        public const string GameplayObjectiveFailed = "Gameplay.Objective.Failed";
        public const uint GameplayObjectiveFailedHash = 2020740559u;

        public const string MusicSplashIntro = "Music.Splash.Intro";
        public const uint MusicSplashIntroHash = 525010837u;

        public const string MusicMenuLoop = "Music.Menu.Loop";
        public const uint MusicMenuLoopHash = 3629030835u;

        public const string MusicBriefingLoop = "Music.Briefing.Loop";
        public const uint MusicBriefingLoopHash = 316398394u;

        public const string MusicMatchCalmLoop = "Music.Match.CalmLoop";
        public const uint MusicMatchCalmLoopHash = 4285376118u;

        public const string MusicMatchCombatLoop = "Music.Match.CombatLoop";
        public const uint MusicMatchCombatLoopHash = 1880341561u;

        public const string MusicResultVictory = "Music.Result.Victory";
        public const uint MusicResultVictoryHash = 1502319359u;

        public const string MusicResultDefeat = "Music.Result.Defeat";
        public const uint MusicResultDefeatHash = 552063808u;

        public const string AmbienceCityDayLoop = "Ambience.City.DayLoop";
        public const uint AmbienceCityDayLoopHash = 3552601528u;

        public const string AmbienceBaseDistantLoop = "Ambience.Base.DistantLoop";
        public const uint AmbienceBaseDistantLoopHash = 1729659713u;

        public static readonly string[] AllEventIds =
        {
            UIButtonPrimaryClick,
            UIButtonSecondaryClick,
            UIButtonNegativeClick,
            UIButtonDisabledTap,
            UITabSelect,
            UICardSelect,
            UICardLocked,
            UIPopupOpen,
            UIPopupClose,
            UISliderTick,
            UIToggleOn,
            UIToggleOff,
            UIFeedbackToastError,
            UIFeedbackToastPositive,
            GameplayUnitSelectInfantry,
            GameplayUnitSelectVehicle,
            GameplayUnitSelectAir,
            GameplayCommandMoveAccepted,
            GameplayCommandAttackAccepted,
            GameplayCommandHoldAccepted,
            GameplayCommandStopReturning,
            GameplayCommandScanTargeting,
            GameplayCommandScanAccepted,
            GameplayCommandRejected,
            GameplayBuildPlaceValid,
            GameplayBuildPlaceInvalid,
            GameplayProductionQueued,
            GameplayProductionComplete,
            AlertThreatMinor,
            AlertThreatCritical,
            AlertUnitUnderAttack,
            AlertBaseBreached,
            GameplayObjectiveProgress,
            GameplayObjectiveComplete,
            GameplayObjectiveFailed,
            MusicSplashIntro,
            MusicMenuLoop,
            MusicBriefingLoop,
            MusicMatchCalmLoop,
            MusicMatchCombatLoop,
            MusicResultVictory,
            MusicResultDefeat,
            AmbienceCityDayLoop,
            AmbienceBaseDistantLoop,
        };

        public static readonly uint[] AllEventHashes =
        {
            UIButtonPrimaryClickHash,
            UIButtonSecondaryClickHash,
            UIButtonNegativeClickHash,
            UIButtonDisabledTapHash,
            UITabSelectHash,
            UICardSelectHash,
            UICardLockedHash,
            UIPopupOpenHash,
            UIPopupCloseHash,
            UISliderTickHash,
            UIToggleOnHash,
            UIToggleOffHash,
            UIFeedbackToastErrorHash,
            UIFeedbackToastPositiveHash,
            GameplayUnitSelectInfantryHash,
            GameplayUnitSelectVehicleHash,
            GameplayUnitSelectAirHash,
            GameplayCommandMoveAcceptedHash,
            GameplayCommandAttackAcceptedHash,
            GameplayCommandHoldAcceptedHash,
            GameplayCommandStopReturningHash,
            GameplayCommandScanTargetingHash,
            GameplayCommandScanAcceptedHash,
            GameplayCommandRejectedHash,
            GameplayBuildPlaceValidHash,
            GameplayBuildPlaceInvalidHash,
            GameplayProductionQueuedHash,
            GameplayProductionCompleteHash,
            AlertThreatMinorHash,
            AlertThreatCriticalHash,
            AlertUnitUnderAttackHash,
            AlertBaseBreachedHash,
            GameplayObjectiveProgressHash,
            GameplayObjectiveCompleteHash,
            GameplayObjectiveFailedHash,
            MusicSplashIntroHash,
            MusicMenuLoopHash,
            MusicBriefingLoopHash,
            MusicMatchCalmLoopHash,
            MusicMatchCombatLoopHash,
            MusicResultVictoryHash,
            MusicResultDefeatHash,
            AmbienceCityDayLoopHash,
            AmbienceBaseDistantLoopHash,
        };

        public static uint StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261u;
                for (int i = 0; i < value.Length; i++)
                {
                    hash ^= value[i];
                    hash *= 16777619u;
                }

                return hash;
            }
        }
    }
}
