using Game.Catalog.Contracts;
namespace Game.Configs
{
    public readonly struct CommandNodeNarrativeLine
    {
        public readonly string Id, English, Persian;
        public readonly NarrativeSpeakerId Speaker;
        public string Key => "narrative.command_node." + Id.Substring("command_node-".Length);
        public CommandNodeNarrativeLine(string id, NarrativeSpeakerId speaker, string english, string persian)
        { Id="command_node-"+id; Speaker=speaker; English=english; Persian=persian; }
    }
    public static class CH05M05CommandNodeNarrativeCopy
    {
        public static readonly CommandNodeNarrativeLine[] Brief={
            new("brief-01",NarrativeSpeakerId.Dalia,"The Civic Relay joins power, communications, clinics and transport. Isolate its outer military controls before entering the core. The city must survive the assault.","رلهٔ شهری، برق، ارتباطات، درمانگاه‌ها و حمل‌ونقل رو به هم وصل می‌کنه. پیش از ورود به مرکز، کنترل‌های نظامی بیرونی رو جدا کنین. شهر باید از این حمله سالم عبور کنه."),
            new("brief-02",NarrativeSpeakerId.Samira,"My engineers will preserve the civic connections. Keep the protected service sites and their staff intact; losing them defeats the purpose of this operation.","مهندس‌های من اتصال‌های خدمات شهری رو حفظ می‌کنن. مرکزهای خدماتی محافظت‌شده و کارکنانشون رو سالم نگه دارین؛ از دست رفتن اون‌ها هدف این عملیات رو از بین می‌بره."),
            new("brief-03",NarrativeSpeakerId.Yusuf,"I will supervise the hazardous-control checks. Bring the original engineer to each marked isolation point after its guards are defeated, and let the full verification finish.","بررسی کنترل‌های خطرناک با منه. بعد از شکست نگهبان‌ها، مهندس اصلی رو به هر نقطهٔ مشخص‌شدهٔ جداسازی برسونین و اجازه بدین بررسی کامل بشه."),
            new("brief-04",NarrativeSpeakerId.Laila,"Karim and I will coordinate relief access beyond the complex. The approach here remains with your ground teams; do not sacrifice the services to shorten the fight.","کریم و من دسترسی امداد بیرون مجموعه رو هماهنگ می‌کنیم. نزدیک شدن در اینجا با تیم‌های زمینی شماست؛ برای کوتاه کردن نبرد، خدمات رو قربانی نکنین."),
            new("brief-05",NarrativeSpeakerId.Qassem,"You centralized force and made this city obey. The only difference is that you still pretend you will give the power back. I am beginning the override.","نیرو رو متمرکز کردی و شهر رو به اطاعت واداشتی. تنها فرق اینه که هنوز وانمود می‌کنی قدرت رو پس می‌دی. دارم فرمان تصاحب رو آغاز می‌کنم."),
            new("brief-06",NarrativeSpeakerId.Aria,"The two keys are my preserved archive and your live emergency credential. Together they can stop his override without granting permanent rule. I will wait for explicit authority.","دو کلید، آرشیو حفظ‌شدهٔ من و مجوز زندهٔ اضطراری شما هستن. با هم می‌تونن تصاحب او رو متوقف کنن، بدون اینکه اختیار دائمی بدن. منتظر اجازهٔ صریح می‌مونم."),
            new("brief-07",NarrativeSpeakerId.Samira,"Dalia controls the military breach; I coordinate civic continuity. Neither mandate replaces the other. Keep the specialists alive through the final release.","دالیا رخنهٔ نظامی رو فرماندهی می‌کنه و من تداوم خدمات شهری رو هماهنگ می‌کنم. هیچ‌کدوم جای اختیار دیگری رو نمی‌گیره. متخصص‌ها رو تا انتشار نهایی زنده نگه دارین."),
            new("brief-08",NarrativeSpeakerId.Commander,"Isolate the weapons, preserve the services, release the audit. Use emergency authority only to stop the override. We are not taking Qassem’s place.","سلاح‌ها رو جدا کنین، خدمات رو حفظ کنین، گزارش حسابرسی رو منتشر کنین. اختیار اضطراری فقط برای توقف تصاحب استفاده بشه. ما جای قاسم رو نمی‌گیریم."),
        };
        public static readonly CommandNodeNarrativeLine[] Comms={
            new("comms-01",NarrativeSpeakerId.Qassem,"Activate the Relay without limits. I can end the argument, the uncertainty and the disorder. One command is enough.","رله رو بدون محدودیت فعال کن. می‌تونم بحث، تردید و بی‌نظمی رو تموم کنم. یک فرمان کافیه."),
            new("comms-02",NarrativeSpeakerId.Aria,"The audit identifies his original shutdown, the attempted erasure and my self-partition. The bounded path preserves civic services and sends that record beyond any single office. It does not authorize later actions.","گزارش، خاموشی اولیهٔ او، تلاش برای پاک کردن مدرک و بخش‌بندی خودم رو مشخص می‌کنه. مسیر محدود، خدمات شهری رو حفظ می‌کنه و گزارش رو از اختیار هر ادارهٔ تنها بیرون می‌بره. این اجازه‌ای برای کارهای بعدی نیست."),
            new("comms-03",NarrativeSpeakerId.Aria,"I am awaiting authority. Bring the original engineer to the marked release point and complete the six-second hold to authorize this release. Your orders remain the decision; this message issues none.","منتظر اجازه‌ام. مهندس اصلی رو به نقطهٔ انتشار برسونین و شش ثانیه توقف رو کامل کنین تا همین انتشار مجاز بشه. تصمیم با فرمان‌های شماست؛ این پیام هیچ فرمانی صادر نمی‌کنه."),
        };
        public static readonly CommandNodeNarrativeLine[] Debrief={
            new("debrief-01",NarrativeSpeakerId.Dalia,"The override failed. Qassem’s force is defeated, and the Civic Relay is separated from his command. Our teams will secure the complex without shutting down its essential services.","تصاحب شکست خورد. نیروهای قاسم شکست خوردن و رلهٔ شهری از فرمان او جدا شده. تیم‌های ما مجموعه رو امن می‌کنن، بدون اینکه خدمات ضروری رو خاموش کنن."),
            new("debrief-02",NarrativeSpeakerId.Aria,"The complete audit has reached district councils, clinic networks, military commands and independent civic archives. No single office can bury the record again.","گزارش کامل به شوراهای محله، شبکهٔ درمانگاه‌ها، فرماندهی‌های نظامی و آرشیوهای مستقل شهری رسیده. هیچ اداره‌ای نمی‌تونه دوباره به‌تنهایی پنهانش کنه."),
            new("debrief-03",NarrativeSpeakerId.Samira,"Dalia and I secure military and civilian authority together. The two keys protected this emergency action; they do not appoint a permanent ruler.","دالیا و من اختیار نظامی و غیرنظامی رو با هم امن نگه می‌داریم. دو کلید از این اقدام اضطراری محافظت کردن؛ حاکم دائمی تعیین نمی‌کنن."),
            new("debrief-04",NarrativeSpeakerId.Aria,"Emergency command is ending. What follows must be visible, auditable and open to challenge. I can support that work, but I cannot choose its governors.","فرماندهی اضطراری داره پایان می‌گیره. چیزی که جاش میاد باید قابل دیدن، حسابرسی و اعتراض باشه. می‌تونم کمک کنم، ولی نمی‌تونم حاکمانش رو انتخاب کنم."),
        };
        public static readonly CommandNodeNarrativeLine[] Close={
            new("close-01",NarrativeSpeakerId.Aria,"Protocol Fragment Five is complete. Qassem’s original override, his attempted erasure and my self-partition now align in one surviving audit.","قطعهٔ پنجم پروتکل کامل شد. تصاحب اولیهٔ قاسم، تلاشش برای پاک کردن مدرک و بخش‌بندی من حالا در یک گزارش باقی‌مونده کنار هم قرار گرفتن."),
            new("close-02",NarrativeSpeakerId.Dalia,"Bombings, false reports, Fuel diversions, Relay activations and Vanguard hardware follow the same operation record. These attacks were built to manufacture necessity.","بمب‌گذاری‌ها، گزارش‌های دروغ، انحراف سوخت، فعال شدن رله و تجهیزات ونگارد در یک سابقهٔ عملیاتی جمع شدن. این حمله‌ها برای ساختن حس ضرورت طراحی شدن."),
            new("close-03",NarrativeSpeakerId.Samira,"Qassem caused the shutdown, built Ash Line and invited Vanguard into this crisis. The public record breaks his claim that terror made him necessary.","قاسم خاموشی رو ایجاد کرد، خط خاکستر رو ساخت و ونگارد رو وارد این بحران کرد. گزارش عمومی، ادعای او رو که وحشت وجودش رو ضروری کرده بود می‌شکنه."),
            new("close-04",NarrativeSpeakerId.Commander,"No permanent unilateral control. Return emergency authority to a shared structure that can explain its decisions and be stopped.","هیچ اختیار دائمی یک‌طرفه‌ای در کار نیست. اختیار اضطراری به ساختاری مشترک برگرده که تصمیم‌هاش رو توضیح بده و بشه متوقفش کرد."),
            new("close-05",NarrativeSpeakerId.Dalia,"The military mandate is bounded: protect the city, secure dangerous controls and stand down under accountable authority. It is not a claim to govern everyone.","اختیار نظامی محدوده؛ حفظ شهر، امن کردن کنترل‌های خطرناک و پایان دادن به آماده‌باش زیر نظر مسئولانه. این ادعای حکومت بر همه نیست."),
            new("close-06",NarrativeSpeakerId.Samira,"District representatives, workers, utilities and clinics share civilian oversight. Disagreement stays part of command instead of becoming its enemy.","نماینده‌های محله، کارگرها، خدمات و درمانگاه‌ها در نظارت غیرنظامی شریک می‌شن. اختلاف نظر بخشی از فرماندهی می‌مونه، نه دشمن اون."),
            new("close-07",NarrativeSpeakerId.Aria,"I remain active with visible permissions, explicit consent and an audit trail. My recommendations can be challenged; my actions can be overridden.","با اجازه‌های قابل دیدن، رضایت صریح و سابقهٔ حسابرسی فعال می‌مونم. می‌شه توصیه‌هام رو زیر سؤال برد و اقدام‌هام رو متوقف کرد."),
            new("close-08",NarrativeSpeakerId.Samira,"Sahrin’s map now coordinates recovery instead of hostile override. Fragment Five, the complete audit and the governance resolution belong in the public archive.","نقشهٔ سهرین حالا به جای تصاحب دشمن، بازسازی رو هماهنگ می‌کنه. قطعهٔ پنجم، گزارش کامل و تصمیم دربارهٔ ادارهٔ شهر در آرشیو عمومی ثبت می‌شن."),
        };
        public static readonly CommandNodeNarrativeLine[] Epilogue={
            new("epilogue-01",NarrativeSpeakerId.Dalia,"The Civic Relay is secured and disconnected from Qassem’s override. Essential services remain connected to the people they serve.","رلهٔ شهری امن شده و از تصاحب قاسم جداست. خدمات ضروری همچنان به مردمی که بهشون نیاز دارن وصله."),
            new("epilogue-02",NarrativeSpeakerId.Dalia,"Ash Line command has collapsed. The remaining Vanguard forces withdraw or surrender; protection continues while the weapons fall silent.","فرماندهی خط خاکستر فروپاشیده. نیروهای باقی‌موندهٔ ونگارد عقب می‌کشن یا تسلیم می‌شن؛ با خاموش شدن سلاح‌ها، حفاظت ادامه داره."),
            new("epilogue-03",NarrativeSpeakerId.Aria,"The complete audit is public. It is not retained as secret command evidence, and Qassem’s responsibility does not depend on a reward or a perfect operation.","گزارش کامل عمومیه. به‌عنوان مدرک محرمانهٔ فرماندهی نگه داشته نمی‌شه و مسئولیت قاسم به پاداش یا عملیاتی بی‌نقص بستگی نداره."),
            new("epilogue-04",NarrativeSpeakerId.Dalia,"I am supervising a disciplined stand-down. Enough protection remains for clinics, roads and recovery teams; emergency force is not becoming permanent authority.","پایان منظم آماده‌باش رو زیر نظر دارم. حفاظت کافی برای درمانگاه‌ها، راه‌ها و تیم‌های بازسازی باقی می‌مونه؛ نیروی اضطراری به اختیار دائمی تبدیل نمی‌شه."),
            new("epilogue-05",NarrativeSpeakerId.Samira,"Civil representatives and workers restore power, communications and transport together. Fadi’s crews reopen the hospital corridor, and Yasin organizes market deliveries.","نماینده‌های غیرنظامی و کارگرها با هم برق، ارتباطات و حمل‌ونقل رو برمی‌گردونن. تیم‌های فادی مسیر بیمارستان رو باز می‌کنن و یاسین تحویل‌های بازار رو سامان می‌ده."),
            new("epilogue-06",NarrativeSpeakerId.Laila,"The relief air corridor is reopening. Karim returns transport aircraft to relief duty, and Dr. Lina receives medicine while clinics and markets resume work.","مسیر هوایی امداد دوباره باز می‌شه. کریم هواپیماهای ترابری رو به کار امداد برمی‌گردونه و دکتر لینا دارو دریافت می‌کنه، در حالی که درمانگاه‌ها و بازار کارشون رو از سر می‌گیرن."),
            new("epilogue-07",NarrativeSpeakerId.Aria,"My permissions and audit trail are visible. I mark what I know, what I infer and what I cannot see. The Commander can override me, and the city can audit us both.","اجازه‌ها و سابقهٔ حسابرسی من قابل دیدنه. دانسته‌ها، برداشت‌ها و چیزهایی که نمی‌بینم رو مشخص می‌کنم. فرمانده می‌تونه من رو متوقف کنه و شهر می‌تونه هر دومون رو حسابرسی کنه."),
            new("epilogue-08",NarrativeSpeakerId.Commander,"Return the last emergency authority to the shared council. No one person receives the master control Qassem wanted. Emergency powers carry an end date.","آخرین اختیار اضطراری به شورای مشترک برگرده. هیچ‌کس کنترل اصلی‌ای رو که قاسم می‌خواست به‌تنهایی نمی‌گیره. قدرت اضطراری تاریخ پایان داره."),
            new("epilogue-09",NarrativeSpeakerId.Samira,"Sahrin is alive again: damaged roads, waiting families, busy clinics, workers and vendors. Survival begins the repair; it does not erase what the city endured.","سهرین دوباره زنده‌ست؛ راه‌های آسیب‌دیده، خانواده‌های منتظر، درمانگاه‌های شلوغ، کارگرها و فروشنده‌ها. زنده موندن آغاز تعمیره؛ رنج شهر رو پاک نمی‌کنه."),
        };
        public static readonly CommandNodeNarrativeLine[] TrustHigh={
            new("trust_high-01",NarrativeSpeakerId.Samira,"The recorded relief operations protected civilians and civic staff. Their participation has a safer starting point; oversight must still earn trust by listening and explaining.","عملیات‌های امدادی ثبت‌شده، مردم و کارکنان خدمات رو حفظ کردن. مشارکتشون شروع امن‌تری داره؛ نظارت هنوز باید با شنیدن و توضیح دادن، اعتماد به دست بیاره."),
        };
        public static readonly CommandNodeNarrativeLine[] TrustLow={
            new("trust_low-01",NarrativeSpeakerId.Samira,"People enter recovery with questions and justified skepticism. Shared civilian oversight remains, with a longer work of listening and repairing legitimacy.","مردم با سؤال و تردید موجه وارد بازسازی می‌شن. نظارت مشترک غیرنظامی باقی می‌مونه، با کار طولانی‌تر برای شنیدن و بازسازی اعتبار."),
        };
        public static readonly CommandNodeNarrativeLine[] EvidenceHigh={
            new("evidence_high-01",NarrativeSpeakerId.Aria,"The released critical-path audit proves Qassem’s role and preserves the verified links gathered in this operation. External financiers and Vanguard connections remain subject to investigation.","گزارش ضروری منتشرشده، نقش قاسم رو ثابت می‌کنه و ارتباط‌های تأییدشدهٔ این عملیات رو حفظ می‌کنه. سرمایه‌گذارهای بیرونی و ارتباط‌های ونگارد همچنان نیاز به بررسی دارن."),
        };
        public static readonly CommandNodeNarrativeLine[] EvidenceLow={
            new("evidence_low-01",NarrativeSpeakerId.Aria,"The complete critical-path audit proves Qassem’s guilt. Parts of the wider support network remain disputed or hidden; that uncertainty does not undo the ending.","گزارش کامل و ضروری، گناه قاسم رو ثابت می‌کنه. بخش‌هایی از شبکهٔ پشتیبانی بزرگ‌تر پنهان یا مورد اختلافه؛ این ابهام پایان رو از بین نمی‌بره."),
        };
        public static readonly CommandNodeNarrativeLine[] InfrastructureHigh={
            new("infrastructure_high-01",NarrativeSpeakerId.Samira,"The recorded operations preserved essential services without losing their teams. Roads, power, Fuel, clinics, shelters and trade can resume with a stronger base for repairs.","عملیات‌های ثبت‌شده خدمات ضروری و تیم‌هاشون رو حفظ کردن. راه‌ها، برق، سوخت، درمانگاه‌ها، پناهگاه‌ها و تجارت با پایهٔ سالم‌تری برای تعمیرها دوباره راه می‌افتن."),
        };
        public static readonly CommandNodeNarrativeLine[] InfrastructureLow={
            new("infrastructure_low-01",NarrativeSpeakerId.Samira,"Sahrin survived, but shortages, displacement and repairs extend the transition. Recovery begins under shared authority while the damaged systems are restored.","سهرین زنده موند، ولی کمبودها، آوارگی و تعمیرها دورهٔ گذار رو طولانی می‌کنن. بازسازی زیر اختیار مشترک آغاز می‌شه و سامانه‌های آسیب‌دیده ترمیم می‌شن."),
        };
        public static readonly CommandNodeNarrativeLine[] Postscript={
            new("postscript-01",NarrativeSpeakerId.Aria,"The Story Archive now holds all five reconstructed Protocol Fragments, the complete audit and the recovery emphasis. The Campaign is complete.","آرشیو داستان حالا هر پنج قطعهٔ بازسازی‌شدهٔ پروتکل، گزارش کامل و تأکید بازسازی رو نگه می‌داره. کارزار کامل شده."),
            new("postscript-02",NarrativeSpeakerId.Aria,"External Vanguard links remain under review. No immediate threat is confirmed. These are future investigations, not an unfinished ending.","ارتباط‌های بیرونی ونگارد همچنان در دست بررسیه. تهدید فوری تأیید نشده. این‌ها بررسی‌های آینده‌ان، نه پایانی ناتمام."),
            new("postscript-03",NarrativeSpeakerId.Commander,"Then we do not invent a threat. Open the restored operations map for replay. This city has work ahead, and room to live.","پس تهدیدی اختراع نمی‌کنیم. نقشهٔ عملیات بازیابی‌شده رو برای مرور دوباره باز کنین. این شهر کار پیش رو داره و جایی برای زندگی."),
        };
    }
}
