namespace Game.Configs
{
    public static class M03RadarWarningUiCopyCatalog
    {
        public static readonly (string Key, string English, string Persian)[] Entries =
        {
            ("ui.aria.select_defenders", "Select defenders", "انتخاب مدافعان"),
            ("ui.aria.select_group", "Select mission group", "انتخاب گروه مأموریت"),
            ("ui.aria.select_specialists", "Select all specialists", "انتخاب همهٔ متخصصان"),
            ("ui.aria.select_helicopter", "Select helicopter", "انتخاب بالگرد"),
            ("ui.aria.select_carrier", "Select rescue APC", "انتخاب نفربر نجات"),
            ("ui.aria.select_group.title", "Select your units", "نیروهای خود را انتخاب کنید"),
            ("ui.aria.select_group.body", "Tap {0} below. It selects the units needed for this lesson together. Then follow the next highlighted action.", "دکمهٔ «{0}» را در پایین بزنید. نیروهای موردنیاز این درس با هم انتخاب می‌شوند. سپس راهنمای زرد بعدی را دنبال کنید."),
            ("mission.m03.order.holding", "Holding position", "در حال حفظ موضع"),
            ("ui.aria.placement.title", "Confirm this position", "جای سازه را تأیید کنید"),
            ("ui.aria.production_wait.title", "Reinforcements are training", "نیروی کمکی در حال آموزش است"),
            ("ui.aria.production_wait.body", "Your rifle squad is queued. Wait for training to finish; no further click is needed. Keep your defenders on Hold. This lesson advances when the squad arrives.", "گروه تفنگدار شما در صف آموزش است. منتظر پایان آموزش بمانید؛ کلیک دیگری لازم نیست. مدافعان را در حالت حفظ نگه دارید. با آماده‌شدن گروه، درس بعد آغاز می‌شود."),
            ("ui.aria.placement.body", "Move the preview onto a green footprint; rotate if needed, then tap Place Building. Cancel returns to the lesson.", "پیش‌نمایش را به محل سبز ببرید؛ در صورت نیاز بچرخانید و قراردهی ساختمان را بزنید. لغو شما را به درس برمی‌گرداند."),
            ("mission.m03.clarity.brief", "Your mission: stop BOTH enemy convoys before they reach the post. Keep the post standing. First prepare your rifles; the convoy waits while you learn. Read the warning, then Continue.", "مأموریت شما: هر دو کاروان دشمن را پیش از رسیدن به پاسگاه متوقف کنید و پاسگاه را سالم نگه دارید. ابتدا تفنگداران را آماده کنید؛ هنگام آموزش، کاروان منتظر می‌ماند. هشدار را بخوانید و سپس ادامه را بزنید."),
            ("mission.m03.clarity.prepare", "First prepare a defensive line beside the marked road. Open Build to see your options. In the next lesson, choose ONE tower or road barrier, or skip building. You do not need all three buildings.", "ابتدا کنار جادهٔ مشخص‌شده موضع دفاعی بسازید. ساخت را بزنید تا گزینه‌ها را ببینید. در درس بعد فقط یک برج یا مانع جاده انتخاب کنید، یا از ساخت بگذرید. ساخت هر سه سازه لازم نیست."),
            ("mission.m03.clarity.radar", "Optional intelligence: Radar Ping reveals vehicles near your radar. It does not attack. Tap it once, or skip this lesson. You have two uses, 60 seconds apart; never wait for recharge to defend the road.", "اطلاعات اختیاری: پالس رادار خودروهای نزدیک رادار را آشکار می‌کند و حمله نمی‌کند. یک بار آن را بزنید یا از این درس بگذرید. دو نوبت با فاصلهٔ ۶۰ ثانیه دارید؛ برای دفاع منتظر بازیابی رادار نمانید."),
            ("mission.m03.clarity.vanguard", "Stop the first convoy", "کاروان اول را متوقف کنید"),
            ("mission.m03.clarity.main", "Stop the remaining convoy", "کاروان باقی‌مانده را متوقف کنید"),
            ("mission.m03.clarity.select", "Tap Select defenders in ARIA. Your goal is to stop both convoys before they reach the post. Radar recharge is optional; keep defending.", "دکمهٔ انتخاب مدافعان را در پنل آریا بزنید. هدف، توقف هر دو کاروان پیش از رسیدن به پاسگاه است. بازیابی رادار اختیاری است؛ دفاع را ادامه دهید."),
            ("mission.m03.clarity.move", "Press Move, then tap the marked position beside the road. Your rifles must cover the convoy route, not wait at the barracks.", "حرکت را بزنید و سپس محل مشخص‌شده کنار جاده را لمس کنید. تفنگداران باید مسیر کاروان را پوشش دهند و در پادگان منتظر نمانند."),
            ("mission.m03.clarity.moving", "Your rifles are moving to the defensive line. Wait for their arrival; then press Hold. The yellow ring marks the destination. Radar recharge does not stop the mission.", "تفنگداران به موضع دفاعی می‌روند. منتظر رسیدن آن‌ها بمانید؛ سپس حفظ را بزنید. حلقهٔ زرد مقصد را نشان می‌دهد. بازیابی رادار مأموریت را متوقف نمی‌کند."),
            ("mission.m03.clarity.hold", "Press Hold now. Your rifles will fire automatically at vehicles in range without chasing them. Protect the road to the post; Stop would disable their automatic fire.", "اکنون حفظ را بزنید. تفنگداران بدون تعقیب، به خودروهای داخل برد خودکار شلیک می‌کنند. مسیر پاسگاه را حفظ کنید؛ توقف، شلیک خودکار را قطع می‌کند."),
            ("mission.m03.clarity.wait", "Defense is ready. Keep your rifles here on Hold and wait for the convoy; no extra click is needed. The yellow ring marks the road to defend. The warning estimates enemy arrival; Radar Ping has a separate, optional recharge timer.", "دفاع آماده است. تفنگداران را اینجا در حالت حفظ نگه دارید و منتظر کاروان بمانید؛ کلیک دیگری لازم نیست. حلقهٔ زرد مسیر دفاع را نشان می‌دهد. زمان هشدار، رسیدن دشمن را تخمین می‌زند؛ زمان بازیابی پالس رادار جدا و اختیاری است."),
            ("mission.m03.clarity.engage", "Enemy vehicles are approaching. Keep rifles on Hold at the yellow ring: they fire automatically when enemies enter range. Stop every vehicle before the post. Another radar ping is not required.", "خودروهای دشمن نزدیک می‌شوند. تفنگداران را کنار حلقهٔ زرد در حالت حفظ نگه دارید تا با ورود دشمن به برد، خودکار شلیک کنند. همهٔ خودروها را پیش از پاسگاه متوقف کنید. پالس رادار دیگری لازم نیست."),
            ("mission.m03.ping.recharging_label", "Radar recharge", "بازیابی رادار"),
            ("mission.m03.ping.spent_label", "Radar used up", "رادار مصرف شد"),
            ("mission.m03.radar.description", "Ground radar vehicle that detects approaching enemy ground vehicles but cannot attack.", "خودروهای زمینی دشمن در نزدیکی را شناسایی می‌کند"),
            ("mission.m03.build.choose_one", "Choose ONE defense: a Road Barrier across the road, or a Guard Tower beside it.", "فقط یک سازهٔ دفاعی انتخاب کنید: مانع در عرض جاده، یا برج نگهبانی کنار جاده."),
            ("mission.m03.save.failed", "PROGRESS NOT SAVED", "پیشرفت ذخیره نشد"),
            ("mission.m03.save.body", "Defense complete. Progress and rewards could not be saved. Retry saving before leaving this mission.", "دفاع کامل شد، اما پیشرفت و پاداش‌ها ذخیره نشدند. پیش از خروج از مأموریت، ذخیره‌سازی را دوباره امتحان کنید."),
            ("mission.m03.save.pending", "Rewards pending save", "پاداش‌ها در انتظار ذخیره‌سازی"),
            ("mission.m03.save.retry", "RETRY SAVE", "ذخیرهٔ دوباره"),
            ("mission.m03.name", "Radar Warning", "هشدار رادار"),
            ("mission.reward.commander_xp", "COMMANDER XP", "تجربهٔ فرمانده"),
            ("mission.reward.credits", "CREDITS", "اعتبار"),
            ("mission.m03.result.victory", "VICTORY", "پیروزی"),
            ("mission.m03.result.defeat", "MISSION FAILED", "مأموریت ناموفق"),
            ("mission.m03.result.victory_body", "Both convoy elements stopped. The forward post is standing and the inner core held. Review the civilian and post-damage stars below.", "هر دو بخش کاروان متوقف شدند. پاسگاه پابرجاست و محدودهٔ مرکزی حفظ شد. ستاره‌های غیرنظامیان و آسیب پاسگاه را بررسی کنید."),
            ("mission.m03.result.post_lost", "The forward post was destroyed. Cover its approach and keep a reserve for the next attempt.", "پاسگاه نابود شد. در تلاش بعدی مسیر آن را پوشش دهید و نیروی ذخیره نگه دارید."),
            ("mission.m03.result.breach", "A living hostile reached the inner core. Intercept the carrier before the final turn; an unarmed vehicle can still breach.", "دشمن زنده به محدودهٔ مرکزی رسید. نفربر را پیش از آخرین پیچ متوقف کنید؛ خودروی بی‌سلاح هم می‌تواند وارد مرکز شود."),
            ("mission.m03.result.integrity", "A required mission actor became unavailable. Restart this attempt; no victory or rewards were granted.", "یکی از نیروهای ضروری مأموریت از دسترس خارج شد. این تلاش را از نو آغاز کنید؛ پیروزی یا پاداشی ثبت نشد."),
            ("mission.m03.result.no_reward", "NO REWARD", "بدون پاداش"),
            ("mission.m03.result.retry", "RETRY", "تلاش دوباره"),
            ("mission.m03.result.stars", "{0} / 3 STARS", "{0} / ۳ ستاره"),
            ("mission.m03.result.stopped", "STOPPED", "متوقف شد"),
            ("mission.m03.result.incomplete", "INCOMPLETE", "ناتمام"),
            ("mission.m03.result.destroyed", "DESTROYED", "نابود شد"),
            ("mission.m03.result.damaged", "DAMAGED", "آسیب‌دیده"),
            ("mission.m03.result.undamaged", "UNDAMAGED", "بی‌آسیب"),
            ("mission.m03.result.safe", "ALL SAFE", "همه سالم"),
            ("mission.m03.result.losses", "LOSSES", "تلفات"),
            ("mission.m03.result.objectives", "DEFENSE & BONUS STARS", "دفاع و ستاره‌های امتیازی"),
            ("mission.m03.result.performance", "PERFORMANCE", "عملکرد"),
            ("mission.m03.result.rewards", "REWARDS", "پاداش‌ها"),
            ("mission.m03.result.squad_losses", "RIFLES LOST", "تفنگداران ازدست‌رفته"),
            ("mission.m03.result.enemies", "HOSTILES STOPPED", "دشمنان متوقف‌شده"),
            ("mission.m03.result.civilians", "CIVILIANS LOST", "غیرنظامیان ازدست‌رفته"),
            ("mission.m03.result.post", "FORWARD POST CONDITION", "وضعیت پاسگاه"),
            ("mission.m03.result.civilian_goal", "CIVILIAN SAFETY", "سلامت غیرنظامیان"),
            ("mission.m03.summary", "Hold the forward post against two convoy elements. Position your squads, read the warnings, and choose how to reinforce the defense.", "پاسگاه را در برابر دو بخش کاروان حفظ کنید. گروه‌ها را مستقر کنید، هشدارها را بخوانید و شیوهٔ تقویت دفاع را انتخاب کنید."),
            ("mission.m03.location", "Western approach · JRC forward post", "مسیر غربی · پاسگاه نیروهای مشترک"),
            ("mission.m03.enemy_intel", "SCOUT REPORT · COMPOSITION UNCONFIRMED", "گزارش دیده‌بان · ترکیب نیروها تأیید نشده"),
            ("mission.m03.objective.stop_convoy", "Stop both convoy elements", "هر دو بخش کاروان را متوقف کنید"),
            ("mission.m03.objective.hold_post", "Keep the forward post standing", "پاسگاه را حفظ کنید"),
            ("mission.m03.objective.keep_core_clear", "Prevent a breach of the inner core", "از ورود دشمن به محدودهٔ مرکزی جلوگیری کنید"),
            ("mission.m03.goal.civilians", "Bonus star: protect all four civilians", "ستارهٔ امتیازی: هر چهار غیرنظامی را حفظ کنید"),
            ("mission.m03.resources", "50,000 Credits · 100 Materials", "۵۰٬۰۰۰ اعتبار · ۱۰۰ مصالح"),
            ("mission.m03.access", "Two rifle squads · Ground Radar Tank", "دو گروه تفنگدار · خودروی رادار زمینی"),
            ("mission.m03.options", "Tower, Barrier or rifle reinforcements", "برج نگهبانی، مانع یا تفنگداران کمکی"),
            ("mission.m03.label.forces", "STARTING FORCES", "نیروهای آغازین"),
            ("mission.m03.label.options", "DEFENSE CHOICES", "گزینه‌های دفاعی"),
            ("mission.m03.reward.unlocks", "TOWER + RADAR PING", "برج نگهبانی + پالس رادار"),
            ("mission.m03.warning.scout", "Scout report", "گزارش دیده‌بان"),
            ("mission.m03.warning.sensor", "Ground radar", "رادار زمینی"),
            ("mission.m03.warning.visual", "Visual contact", "مشاهدهٔ مستقیم"),
            ("mission.m03.warning.ping", "Radar Ping", "پالس رادار"),
            ("mission.m03.warning.vanguard", "Vanguard · western road", "پیش‌قراول · جادهٔ غربی"),
            ("mission.m03.warning.main", "Main convoy · western road", "کاروان اصلی · جادهٔ غربی"),
            ("mission.m03.warning.unknown", "Composition unconfirmed", "ترکیب نیروها تأیید نشده"),
            ("mission.m03.warning.vehicles", "{0} vehicle(s) observed", "{0} خودرو مشاهده شده"),
            ("mission.m03.warning.eta", "Contact estimate: {0}s", "برآورد زمان تماس: {0} ثانیه"),
            ("mission.m03.warning.window", "Contact window open", "بازهٔ تماس آغاز شده"),
            ("mission.m03.warning.stale", "Last known contact", "آخرین اطلاعات تماس"),
            ("mission.m03.warning.resolved", "Convoy element stopped", "این بخش کاروان متوقف شد"),
            ("mission.m03.objective.protect_post", "Keep the forward post standing", "پاسگاه را حفظ کنید"),
            ("mission.m03.objective.prevent_breach", "Prevent a breach of the inner core", "از ورود دشمن به محدودهٔ مرکزی جلوگیری کنید"),
            ("mission.m03.star.complete", "Stop the convoy and hold the post", "کاروان را متوقف و پاسگاه را حفظ کنید"),
            ("mission.m03.star.civilians_safe", "All four civilians survived", "هر چهار غیرنظامی زنده ماندند"),
            ("mission.m03.star.post_undamaged", "Forward post took no damage", "پاسگاه آسیب ندید"),
            ("mission.m03.reward.guard_tower", "Guard Tower access", "دسترسی به برج نگهبانی"),
            ("mission.m03.reward.radar_ping", "Radar Ping ownership", "مالکیت پالس رادار"),
            ("mission.m03.ping.paused", "Paused", "مکث"),
            ("mission.m03.ping.no_sensor", "Ground sensor unavailable", "حسگر زمینی در دسترس نیست"),
            ("mission.m03.ping.empty", "No uses remaining", "نوبتی باقی نمانده است"),
            ("mission.m03.ping.cooldown", "Ready in {0}s", "آماده تا {0} ثانیهٔ دیگر"),
            ("mission.m03.ping.ready", "Radar Ping · {0} uses", "پالس رادار · {0} نوبت"),
            ("mission.m03.ping.requested", "Radar sweep requested.", "درخواست بررسی محدودهٔ رادار ارسال شد."),
            ("mission.m03.action.continue", "CONTINUE", "ادامه"),
            ("mission.m03.action.do_it", "DO IT", "انجامش بده"),
            ("mission.m03.action.skip", "SKIP OPTIONAL STEP", "عبور از مرحلهٔ اختیاری"),
            ("mission.m03.guide", "FIELD GUIDE", "راهنمای میدان"),
            ("mission.m03.jump", "JUMP TO REPORT", "نمایش محل گزارش"),
            ("mission.m03.camera.return", "RETURN VIEW", "بازگشت دوربین"),
            ("ui.narrative.story", "STORY", "داستان"),
            ("ui.narrative.resume", "RESUME", "ادامه"),
            ("ui.narrative.pause", "PAUSE", "مکث"),
            ("ui.narrative.subtitles_on", "CAPTIONS ON", "زیرنویس روشن"),
            ("ui.narrative.subtitles_off", "CAPTIONS OFF", "زیرنویس خاموش")
        };
    }
}
