namespace Game.Configs
{
    public static class M03RadarWarningUiCopyCatalog
    {
        public static readonly (string Key, string English, string Persian)[] Entries =
        {
            ("mission.m03.defense.wave", "Convoy {0}/{1}", "کاروان {0} از {1}"),
            ("mission.m03.defense.countdown", "Arriving in <size=130%><b>{0}</b></size>", "تا رسیدن: <size=130%><b>{0}</b></size>"),
            ("mission.m03.defense.fighting", "Defend · {0} vehicles left", "دفاع کن · {0} خودرو مونده"),
            ("mission.m03.defense.complete", "Both convoys stopped\nDefense complete", "هر دو کاروان متوقف شدن\nدفاع تموم شد"),
            ("mission.m03.warning.compact.first", "First convoy · western road", "کاروان اول · جادهٔ غربی"),
            ("mission.m03.warning.compact.main", "Main convoy · western road", "کاروان اصلی · جادهٔ غربی"),
            ("mission.m03.warning.compact.eta", "Arrival: {0}s", "رسیدن: {0} ثانیه"),
            ("mission.m03.warning.compact.unknown", "Unconfirmed", "تأییدنشده"),
            ("mission.m03.warning.compact.count", "{0} vehicles", "{0} خودرو"),
            ("mission.m03.scan.empty_result", "Scan: no vehicles. Keep holding.", "اسکن: خودرویی نیست؛ دفاع رو ادامه بده."),
            ("mission.m03.scan.contact_result", "Scan: {0} vehicles. Keep holding.", "اسکن: {0} خودرو پیدا شد؛ دفاع رو ادامه بده."),
            ("tactical.command.cease_fire", "CEASE FIRE", "قطع آتش"),
            ("tactical.command.mode.stop", "CEASE FIRE", "قطع آتش"),
            ("tactical.command.instruction.stop", "Cancel orders and stop automatic fire. Use Hold to defend again.", "دستورها و شلیک خودکار رو قطع کن. برای دفاع دوباره، «حفظ» رو بزن."),
            ("tactical.feedback.stopped_selected_units", "Orders cancelled; automatic fire off. Use Hold to defend again.", "دستورها لغو شد؛ شلیک خودکار قطع شد. برای دفاع دوباره، «حفظ» رو بزن."),
            ("ui.aria.select_defenders", "Select defenders", "انتخاب مدافعان"),
            ("ui.aria.select_group", "Select mission group", "انتخاب گروه مأموریت"),
            ("ui.aria.select_specialists", "Select all specialists", "انتخاب همهٔ متخصصان"),
            ("ui.aria.select_helicopter", "Select helicopter", "انتخاب بالگرد"),
            ("ui.aria.select_carrier", "Select rescue APC", "انتخاب نفربر نجات"),
            ("ui.aria.select_group.title", "Select your units", "نیروهای خودت رو انتخاب کن"),
            ("ui.aria.select_group.body", "Tap {0} below. It selects the units needed for this lesson together. Then follow the next highlighted action.", "پایین صفحه، «{0}» رو بزن تا نیروهای مورد نیاز این درس با هم انتخاب بشن. بعد راهنمای زرد بعدی رو دنبال کن."),
            ("mission.m03.order.holding", "Holding position", "در حال حفظ موضع"),
            ("ui.aria.placement.title", "Confirm this position", "جای سازه رو تأیید کن"),
            ("ui.aria.production_wait.title", "Reinforcements are training", "نیروی کمکی در حال آموزش است"),
            ("ui.aria.production_wait.body", "Your rifle squad is queued. Wait for training to finish; no further click is needed. Keep your defenders on Hold. This lesson advances when the squad arrives.", "گروه تفنگدارت توی صف آموزشه. صبر کن آماده بشن؛ لازم نیست دکمهٔ دیگه‌ای بزنی. مدافع‌ها رو روی «حفظ» نگه دار. وقتی گروه آماده بشه، می‌ریم درس بعد."),
            ("ui.aria.placement.body", "Move the preview onto a green footprint; rotate if needed, then tap Place Building. Cancel returns to the lesson.", "پیش‌نمایش رو به محل سبز بکش. اگه لازم شد بچرخونش، بعد «قراردهی ساختمان» رو بزن. «لغو» برت می‌گردونه به درس."),
            ("mission.m03.clarity.brief", "Your mission: stop BOTH enemy convoys before they reach the post. Keep the post standing. First prepare your rifles; the convoy waits while you learn. Read the warning, then Continue.", "هدفت اینه که هر دو کاروان رو قبل از رسیدن به پاسگاه متوقف کنی و پاسگاه رو سالم نگه داری. اول تفنگدارها رو آماده کن؛ کاروان تا پایان آموزش منتظر می‌مونه. هشدار رو بخون، بعد «ادامه» رو بزن."),
            ("mission.m03.clarity.prepare", "First prepare a defensive line beside the marked road. Open Build to see your options. In the next lesson, choose ONE tower or road barrier, or skip building. You do not need all three buildings.", "اول کنار جادهٔ مشخص‌شده دفاعت رو آماده کن. «ساخت» رو بزن تا گزینه‌ها رو ببینی. فقط یه برج یا مانع جاده کافیه؛ می‌تونی از ساخت هم بگذری. لازم نیست هر سه سازه رو بسازی."),
            ("mission.m03.clarity.radar", "Optional: press the existing Scan button to check your radar vehicle’s coverage. It confirms nearby enemy vehicles; it does not attack. Two scans are available, 60 seconds apart. You can skip this lesson and keep defending without scanning.", "اختیاری: «اسکن» رو بزن تا محدودهٔ خودروی رادار بررسی بشه. اسکن دشمن نزدیک رو پیدا می‌کنه؛ حمله نمی‌کنه. دو نوبت داری، با فاصلهٔ ۶۰ ثانیه. می‌تونی این درس رو رد کنی و بدون اسکن دفاع کنی."),
            ("mission.m03.clarity.vanguard", "Stop the first convoy", "کاروان اول رو متوقف کن"),
            ("mission.m03.clarity.main", "Stop the remaining convoy", "کاروان باقی‌مانده رو متوقف کن"),
            ("mission.m03.clarity.select", "Tap Select defenders in ARIA. Your goal is to stop both convoys before they reach the post. Radar recharge is optional; keep defending.", "«انتخاب مدافعان» رو توی پنل آریا بزن. باید هر دو کاروان رو قبل از رسیدن به پاسگاه متوقف کنی. منتظر آماده‌شدن اسکن نمون؛ دفاع رو ادامه بده."),
            ("mission.m03.clarity.move", "Press Move, then tap the marked position beside the road. Your rifles must cover the convoy route, not wait at the barracks.", "«حرکت» رو بزن، بعد محل مشخص‌شده کنار جاده رو لمس کن. تفنگدارها باید مسیر کاروان رو پوشش بدن؛ توی سربازخانه منتظر نمونن."),
            ("mission.m03.clarity.moving", "Your rifles are moving to the defensive line. Wait for their arrival; then press Hold. The yellow ring marks the destination. Radar recharge does not stop the mission.", "تفنگدارها دارن به موضع دفاعی می‌رن. صبر کن برسن، بعد «حفظ» رو بزن. حلقهٔ زرد مقصد رو نشون می‌ده. لازم نیست منتظر آماده‌شدن اسکن بمونی."),
            ("mission.m03.clarity.hold", "Press Hold now. Your rifles will fire automatically at vehicles in range without chasing them. Protect the road to the post.", "حالا «حفظ» رو بزن. تفنگدارها به خودروهایی که توی بردشون بیان شلیک می‌کنن، ولی دنبالشون نمی‌رن. مسیر پاسگاه رو نگه دار."),
            ("mission.m03.clarity.wait", "Defense is ready. Keep your rifles here on Hold and wait for the convoy; no extra click is needed. The yellow ring marks the road to defend. The warning estimates enemy arrival.", "دفاع آماده‌ست. تفنگدارها رو همین‌جا روی «حفظ» نگه دار و منتظر کاروان باش؛ لازم نیست دکمهٔ دیگه‌ای بزنی. حلقهٔ زرد مسیر دفاع رو نشون می‌ده. زمان هشدار، تخمین رسیدن دشمنه."),
            ("mission.m03.clarity.engage", "Enemy vehicles are approaching. Keep rifles on Hold at the yellow ring: they fire automatically when enemies enter range. Stop every vehicle before the post. Another scan is not required.", "خودروهای دشمن دارن نزدیک می‌شن. تفنگدارها رو کنار حلقهٔ زرد روی «حفظ» نگه دار تا وقتی دشمن توی برد اومد، شلیک کنن. همهٔ خودروها رو قبل از پاسگاه متوقف کن. اسکن دوباره لازم نیست."),
            ("mission.m03.ping.recharging_label", "Radar recharge", "بازیابی رادار"),
            ("mission.m03.ping.spent_label", "Radar used up", "رادار مصرف شد"),
            ("mission.m03.radar.description", "Ground radar vehicle that detects approaching enemy ground vehicles but cannot attack.", "خودروهای زمینی دشمن در نزدیکی رو شناسایی می‌کنه"),
            ("mission.m03.build.choose_one", "Choose ONE defense: a Road Barrier across the road, or a Guard Tower beside it.", "فقط یک سازهٔ دفاعی انتخاب کن: مانع در عرض جاده، یا برج نگهبانی کنار جاده."),
            ("mission.m03.save.failed", "PROGRESS NOT SAVED", "پیشرفت ذخیره نشد"),
            ("mission.m03.save.body", "Defense complete. Progress and rewards could not be saved. Retry saving before leaving this mission.", "دفاع تموم شد، ولی پیشرفت و پاداش‌ها ذخیره نشدن. قبل از خروج، دوباره ذخیره‌سازی رو امتحان کن."),
            ("mission.m03.save.pending", "Rewards pending save", "پاداش‌ها در انتظار ذخیره‌سازی"),
            ("mission.m03.save.retry", "RETRY SAVE", "ذخیرهٔ دوباره"),
            ("mission.m03.name", "Radar Warning", "هشدار رادار"),
            ("mission.reward.commander_xp", "COMMANDER XP", "تجربهٔ فرمانده"),
            ("mission.reward.credits", "CREDITS", "اعتبار"),
            ("mission.m03.result.victory", "VICTORY", "پیروزی"),
            ("mission.m03.result.defeat", "MISSION FAILED", "مأموریت ناموفق"),
            ("mission.m03.result.victory_body", "Both convoy elements stopped. The forward post is standing and the inner core held. Review the civilian and post-damage stars below.", "هر دو بخش کاروان متوقف شدن. پاسگاه سر جاشه و محدودهٔ مرکزی امنه. ستاره‌های حفاظت از مردم و سلامت پاسگاه رو ببین."),
            ("mission.m03.result.post_lost", "The forward post was destroyed. Cover its approach and keep a reserve for the next attempt.", "پاسگاه نابود شد. در تلاش بعدی مسیر اون رو پوشش بده و نیروی ذخیره نگه دار."),
            ("mission.m03.result.breach", "A living hostile reached the inner core. Intercept the carrier before the final turn; an unarmed vehicle can still breach.", "دشمن زنده به محدودهٔ مرکزی رسید. نفربر رو قبل از آخرین پیچ متوقف کن؛ حتی اگه سلاح نداشته باشه، می‌تونه وارد مرکز بشه."),
            ("mission.m03.result.integrity", "A required mission actor became unavailable. Restart this attempt; no victory or rewards were granted.", "یکی از نیروهای ضروری مأموریت در دسترس نیست. باید این تلاش رو از اول شروع کنی؛ برد یا پاداشی ثبت نشده."),
            ("mission.m03.result.no_reward", "NO REWARD", "بدون پاداش"),
            ("mission.m03.result.retry", "RETRY", "تلاش دوباره"),
            ("mission.m03.result.stars", "{0} / 3 STARS", "{0} / ۳ ستاره"),
            ("mission.m03.result.stopped", "STOPPED", "متوقف شد"),
            ("mission.m03.result.incomplete", "INCOMPLETE", "ناتمام"),
            ("mission.m03.result.destroyed", "DESTROYED", "نابود شد"),
            ("mission.m03.result.damaged", "DAMAGED", "آسیب‌دیده"),
            ("mission.m03.result.undamaged", "UNDAMAGED", "بی‌آسیب"),
            ("mission.m03.result.safe", "ALL SAFE", "همه سالم"),
            ("mission.m03.result.losses", "LOSSES", "تلفات"),
            ("mission.m03.result.objectives", "DEFENSE & BONUS STARS", "دفاع و ستاره‌های امتیازی"),
            ("mission.m03.result.performance", "PERFORMANCE", "عملکرد"),
            ("mission.m03.result.rewards", "REWARDS", "پاداش‌ها"),
            ("mission.m03.result.squad_losses", "RIFLES LOST", "تفنگداران ازدست‌رفته"),
            ("mission.m03.result.enemies", "HOSTILES STOPPED", "دشمنان متوقف‌شده"),
            ("mission.m03.result.civilians", "CIVILIANS LOST", "غیرنظامیان ازدست‌رفته"),
            ("mission.m03.result.post", "FORWARD POST CONDITION", "وضعیت پاسگاه"),
            ("mission.m03.result.civilian_goal", "CIVILIAN SAFETY", "سلامت غیرنظامیان"),
            ("mission.m03.summary", "Hold the forward post against two convoy elements. Position your squads, read the warnings, and choose how to reinforce the defense.", "از پاسگاه در برابر دو بخش کاروان دفاع کن. نیروهات رو مستقر کن، هشدارها رو بخون و خودت تصمیم بگیر چطور دفاعت رو تقویت کنی."),
            ("mission.m03.location", "Western approach · JRC forward post", "مسیر غربی · پاسگاه نیروهای مشترک"),
            ("mission.m03.enemy_intel", "SCOUT REPORT · COMPOSITION UNCONFIRMED", "گزارش دیده‌بان · ترکیب نیروها تأیید نشده"),
            ("mission.m03.objective.stop_convoy", "Stop both convoy elements", "هر دو بخش کاروان رو متوقف کن"),
            ("mission.m03.objective.hold_post", "Keep the forward post standing", "پاسگاه رو حفظ کن"),
            ("mission.m03.objective.keep_core_clear", "Prevent a breach of the inner core", "از ورود دشمن به محدودهٔ مرکزی جلوگیری کن"),
            ("mission.m03.goal.civilians", "Bonus star: protect all four civilians", "ستارهٔ امتیازی: هر چهار غیرنظامی رو حفظ کن"),
            ("mission.m03.resources", "50,000 Credits · 100 Materials", "۵۰٬۰۰۰ اعتبار · ۱۰۰ مصالح"),
            ("mission.m03.access", "Two rifle squads · Ground Radar Tank", "دو گروه تفنگدار · خودروی رادار زمینی"),
            ("mission.m03.options", "Tower, Barrier or rifle reinforcements", "برج نگهبانی، مانع یا تفنگداران کمکی"),
            ("mission.m03.label.forces", "STARTING FORCES", "نیروهای آغازین"),
            ("mission.m03.label.options", "DEFENSE CHOICES", "گزینه‌های دفاعی"),
            ("mission.m03.reward.unlocks", "TOWER + RADAR-ASSISTED SCAN", "برج نگهبانی + اسکن با رادار"),
            ("mission.m03.warning.scout", "Scout report", "گزارش دیده‌بان"),
            ("mission.m03.warning.sensor", "Ground radar", "رادار زمینی"),
            ("mission.m03.warning.visual", "Visual contact", "مشاهدهٔ مستقیم"),
            ("mission.m03.warning.ping", "Scan", "اسکن"),
            ("mission.m03.warning.vanguard", "Vanguard · western road", "پیش‌قراول · جادهٔ غربی"),
            ("mission.m03.warning.main", "Main convoy · western road", "کاروان اصلی · جادهٔ غربی"),
            ("mission.m03.warning.unknown", "Composition unconfirmed", "ترکیب نیروها تأیید نشده"),
            ("mission.m03.warning.vehicles", "{0} vehicle(s) observed", "{0} خودرو مشاهده شده"),
            ("mission.m03.warning.eta", "Contact estimate: {0}s", "برآورد زمان تماس: {0} ثانیه"),
            ("mission.m03.warning.window", "Contact window open", "بازهٔ تماس آغاز شده"),
            ("mission.m03.warning.stale", "Last known contact", "آخرین اطلاعات تماس"),
            ("mission.m03.warning.resolved", "Convoy element stopped", "این بخش کاروان متوقف شد"),
            ("mission.m03.objective.protect_post", "Keep the forward post standing", "پاسگاه رو حفظ کن"),
            ("mission.m03.objective.prevent_breach", "Prevent a breach of the inner core", "از ورود دشمن به محدودهٔ مرکزی جلوگیری کن"),
            ("mission.m03.star.complete", "Stop the convoy and hold the post", "کاروان رو متوقف و پاسگاه رو حفظ کن"),
            ("mission.m03.star.civilians_safe", "All four civilians survived", "هر چهار غیرنظامی زنده ماندند"),
            ("mission.m03.star.post_undamaged", "Forward post took no damage", "پاسگاه آسیب ندید"),
            ("mission.m03.reward.guard_tower", "Guard Tower access", "دسترسی به برج نگهبانی"),
            ("mission.m03.reward.radar_ping", "Radar-assisted Scan access", "دسترسی به اسکن با رادار"),
            ("mission.m03.ping.paused", "Paused", "مکث"),
            ("mission.m03.ping.no_sensor", "Ground sensor unavailable", "حسگر زمینی در دسترس نیست"),
            ("mission.m03.ping.empty", "No uses remaining", "نوبتی باقی نمانده است"),
            ("mission.m03.ping.cooldown", "Ready in {0}s", "آماده تا {0} ثانیهٔ دیگر"),
            ("mission.m03.ping.ready", "Scan · {0} uses", "اسکن · {0} نوبت"),
            ("mission.m03.ping.requested", "Radar sweep requested.", "درخواست بررسی محدودهٔ رادار ارسال شد."),
            ("mission.m03.action.continue", "CONTINUE", "ادامه"),
            ("mission.m03.action.do_it", "DO IT", "انجامش بده"),
            ("mission.m03.action.skip", "SKIP OPTIONAL STEP", "عبور از مرحلهٔ اختیاری"),
            ("mission.m03.guide", "FIELD GUIDE", "راهنمای میدان"),
            ("mission.m03.jump", "JUMP TO REPORT", "نمایش محل گزارش"),
            ("mission.m03.camera.return", "RETURN VIEW", "بازگشت دوربین"),
            ("ui.narrative.story", "STORY", "داستان"),
            ("ui.narrative.resume", "RESUME", "ادامه"),
            ("ui.narrative.pause", "PAUSE", "مکث"),
            ("ui.narrative.subtitles_on", "CAPTIONS ON", "زیرنویس روشن"),
            ("ui.narrative.subtitles_off", "CAPTIONS OFF", "زیرنویس خاموش")
        };
    }
}
