namespace Game.Configs
{
    public static class M03RadarWarningGuideCopyCatalog
    {
        public static readonly (string Key, string English, string Persian)[] Entries =
        {
            ("mission.m03.tutorial.resume.title", "Restore your defense", "دفاع رو از سر بگیر"),
            ("mission.m03.tutorial.resume.body", "Cease Fire disabled automatic fire. Keep the squad selected and press Hold to defend again. This lesson finishes after Hold is active.", "«قطع آتش» شلیک خودکار رو قطع کرد. گروهت رو انتخاب‌شده نگه دار و «حفظ» رو بزن تا دوباره دفاع کنن. وقتی حفظ فعال بشه، این درس تموم می‌شه."),
            ("mission.m03.action.wait", "Defending…", "در حال دفاع…"),
            ("mission.m03.action.restore_hold", "Hold position", "حفظ موضع"),
            ("mission.m03.camera.victory", "POST SECURED\nBoth convoy elements stopped. Your defense held.", "پاسگاه امن شد\nهر دو بخش کاروان متوقف شدند. مدافعان پیروز شدند."),
            ("build.drawer.price.credits", "{0} credits", "{0} اعتبار"),
            ("catalog.building.guard_tower", "Guard Tower", "برج نگهبانی"),
            ("catalog.building.road_barrier", "Road Barrier", "مانع جاده"),
            ("mission.m03.camera.opening", "MISSION OVERVIEW\nYour defenders and the convoy approach. ARIA’s tutorial starts after this overview.", "مرور مأموریت\nدوربین مدافع‌ها و مسیر کاروان رو نشونت می‌ده. بعدش آموزش آریا شروع می‌شه."),
            ("mission.m03.camera.skip", "Return to command view", "بازگشت به نمای فرماندهی"),
            ("mission.m03.guide.radio", "RADIO ARCHIVE", "بایگانی پیام رادیویی"),
            ("mission.m03.guide.control.6", "SCAN", "اسکن"),
            ("mission.m03.guide.control.8", "HOLD POSITION", "حفظ موضع"),
            ("mission.m03.guide.control.10", "CEASE FIRE", "قطع آتش"),
            ("mission.m03.guide.scroll", "Scroll to read the example and common mistake", "برای خواندن نمونه و اشتباه رایج، صفحه رو بالا و پایین کن"),
            ("mission.m03.action.warning", "Read warning", "خواندن هشدار"),
            ("mission.m03.guide.loading", "Loading class…", "در حال بارگذاری کلاس…"),
            ("mission.m03.guide.load_failed", "Class details could not load. Reopen this card to try again.", "جزئیات کلاس بارگذاری نشد. برای تلاش دوباره این کارت رو باز کن."),
            ("mission.m03.class.Unit_Chr_Bombsuit_Male_01", "Bomb Suit Specialist", "متخصص خنثی‌سازی بمب"),
            ("mission.m03.class.Unit_Chr_Civilian_Female_01", "Civilian Female I", "زن غیرنظامی ۱"),
            ("mission.m03.class.Unit_Chr_Civilian_Female_02", "Civilian Female II", "زن غیرنظامی ۲"),
            ("mission.m03.class.Unit_Chr_Civilian_Male_01", "Civilian Male I", "مرد غیرنظامی ۱"),
            ("mission.m03.class.Unit_Chr_Civilian_Male_02", "Civilian Male II", "مرد غیرنظامی ۲"),
            ("mission.m03.class.Unit_Chr_Contractor_Female_01", "Security Contractor Female I", "نیروی قراردادی زن ۱"),
            ("mission.m03.class.Unit_Chr_Contractor_Male_01", "Security Contractor Male I", "نیروی قراردادی مرد ۱"),
            ("mission.m03.class.Unit_Chr_Contractor_Male_02", "Security Contractor Male II", "نیروی قراردادی مرد ۲"),
            ("mission.m03.class.Unit_Chr_Ghillie_Male_01", "Ghillie Rocketeer", "راکت‌انداز استتاری"),
            ("mission.m03.class.Unit_Chr_Insurgent_Female_01", "Insurgent Rifleman Female I", "تفنگدار شورشی زن ۱"),
            ("mission.m03.class.Unit_Chr_Insurgent_Female_02", "Insurgent Sidearm Fighter Female II", "شورشی تپانچه‌دار زن ۲"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_01", "Insurgent Rocketeer Male I", "راکت‌انداز شورشی مرد ۱"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_02", "Insurgent Gunner Male II", "تیربارچی شورشی مرد ۲"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_03", "Insurgent Raider Male III", "مهاجم شورشی مرد ۳"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_04", "Insurgent Sniper Male IV", "تک‌تیرانداز شورشی مرد ۴"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_05", "Insurgent Rifleman Male V", "تفنگدار شورشی مرد ۵"),
            ("mission.m03.class.Unit_Chr_Leader_Male_01", "Field Commander", "فرماندهٔ میدان"),
            ("mission.m03.class.Unit_Chr_Pilot_Female_01", "Pilot Female I", "خلبان زن ۱"),
            ("mission.m03.class.Unit_Chr_Pilot_Male_01", "Pilot Male I", "خلبان مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01", "Marksman Female I", "تیرانداز دقیق زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01_Alt_01", "Rifleman Female I", "تفنگدار زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01_Alt_02", "Marksman Female II", "تیرانداز دقیق زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02", "Rifleman Female II", "تفنگدار زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02_Alt_01", "Rifleman Female I", "تفنگدار زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02_Alt_02", "Assault Breacher Female II", "نیروی رخنه‌گر زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01", "Heavy Gunner Male I", "تیربارچی سنگین مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01_Alt_01", "Marksman Male I", "تیرانداز دقیق مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01_Alt_02", "Advanced Rifleman Male II", "تفنگدار پیشرفته مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02", "Rifleman Male II", "تفنگدار مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_01", "Sidearm Specialist Male I", "متخصص تپانچه مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_02", "Rifleman Male II", "تفنگدار مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_03", "Sidearm Specialist Male III", "متخصص تپانچه مرد ۳"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_04", "Rifleman Male IV", "تفنگدار مرد ۴"),
            ("mission.m03.class.Unit_Sea_Coastal_Cutter", "Coastal Cutter", "شناور گشتی ساحلی"),
            ("mission.m03.class.Unit_Sea_Drone_Boat", "Drone Survey Boat", "قایق شناسایی بدون سرنشین"),
            ("mission.m03.class.Unit_Sea_Interceptor_Boat", "Fast Interceptor Boat", "قایق رهگیر سریع"),
            ("mission.m03.class.Unit_Sea_Landing_Craft", "Landing Craft", "شناور پیاده‌سازی"),
            ("mission.m03.class.Unit_Sea_Missile_Craft", "Missile Patrol Craft", "شناور گشتی موشک‌انداز"),
            ("mission.m03.class.Unit_Sea_Patrol_Boat", "Harbor Patrol Boat", "قایق گشت بندر"),
            ("mission.m03.class.Unit_Veh_APC_Fast", "Fast APC", "نفربر سریع"),
            ("mission.m03.class.Unit_Veh_APC_Heavy", "Heavy APC", "نفربر سنگین"),
            ("mission.m03.class.Unit_Veh_APC_Slow", "Armored APC", "نفربر زرهی"),
            ("mission.m03.class.Unit_Veh_Drone", "Recon Drone", "پهپاد شناسایی"),
            ("mission.m03.class.Unit_Veh_Helicopter_Attack", "Attack Helicopter", "بالگرد تهاجمی"),
            ("mission.m03.class.Unit_Veh_Helicopter_Attack_Small", "Light Attack Helicopter", "بالگرد تهاجمی سبک"),
            ("mission.m03.class.Unit_Veh_Helicopter_Transport", "Transport Helicopter", "بالگرد ترابری"),
            ("mission.m03.class.Unit_Veh_Jet_01", "Strike Jet", "جت تهاجمی"),
            ("mission.m03.class.Unit_Veh_Jet_02", "Fighter Jet", "جت جنگنده"),
            ("mission.m03.class.Unit_Veh_Light_Armored_Car", "Light Armored Car", "خودروی زرهی سبک"),
            ("mission.m03.class.Unit_Veh_Missle_Launcher_Air", "Air Missile Launcher", "موشک‌انداز هوایی"),
            ("mission.m03.class.Unit_Veh_Missle_Launcher_Ground", "Ground Missile Launcher", "موشک‌انداز زمینی"),
            ("mission.m03.class.Unit_Veh_Plane_Transport", "Transport Plane", "هواپیمای ترابری"),
            ("mission.m03.class.Unit_Veh_Radar_Tank", "Radar Tank", "خودروی رادار زمینی"),
            ("mission.m03.class.Unit_Veh_Tank_USA", "Battle Tank", "تانک نبرد"),
            ("mission.m03.class.Unit_Veh_Truck_Canopy", "Canopy Truck", "کامیون مسقف"),
            ("mission.m03.class.Unit_Veh_Truck_Tanker", "Tanker Truck", "کامیون سوخت‌رسان"),
            ("mission.m03.class.Unit_Veh_Truck_Tray", "Cargo Truck", "کامیون باربری"),
            ("unit.description.soldier.0", "Regular soldier armed with a rifle. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تفنگ؛ برای گشت و دفاع."),
            ("unit.description.soldier.1", "Regular soldier armed with a sniper rifle. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تفنگ تک‌تیرانداز؛ برای گشت و دفاع."),
            ("unit.description.soldier.2", "Regular soldier armed with a SMG. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به مسلسل سبک؛ برای گشت و دفاع."),
            ("unit.description.soldier.3", "Regular soldier armed with a machine gun. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تیربار؛ برای گشت و دفاع."),
            ("unit.description.soldier.4", "Regular soldier armed with an advanced rifle. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تفنگ پیشرفته؛ برای گشت و دفاع."),
            ("unit.description.soldier.5", "Regular soldier armed with a pistol. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تپانچه؛ برای گشت و دفاع."),
            ("unit.description.soldier.6", "Regular soldier armed with a metal pistol. Reliable frontline infantry for patrols, defense, and direct engagements.", "پیاده‌نظام مجهز به تپانچه؛ برای گشت و دفاع."),
            ("mission.m03.prepare.short", "PREPARATION · Enemy advance is paused", "آماده‌سازی · پیشروی دشمن متوقف است"),
            ("mission.m03.prepare.progress", "Position your defenders, then press Hold", "مدافع‌ها رو مستقر کن، بعد «حفظ» رو بزن"),
            ("mission.m03.result.radar_used", "Post secured. Radar revealed the approach early. Stars reward civilian and post protection.", "پاسگاه امن شد. رادار زودتر اطلاعات تماس داد. سلامت مردم و پاسگاه ستارهٔ اضافی دارد."),
            ("mission.m03.result.radar_saved", "Post secured without radar. Tools are optional; stars reward protection.", "پاسگاه بدون رادار حفظ شد. ابزارها اختیاری‌اند؛ ستاره پاداش حفاظت است."),
            ("mission.m03.tactics.radar", "Radar confirmed the approach early. Your remaining charges can be saved for the next wave.", "رادار مسیر رو زودتر تأیید کرد. اسکن باقی‌مانده رو برای موج بعد نگه دار."),
            ("mission.m03.tactics.visual", "Visual contact confirms nearby threats for free. Radar trades a limited charge for earlier information.", "اگه دشمن نزدیک باشه، با دید مستقیم هم می‌تونی شناساییش کنی. رادار یه نوبت اسکن مصرف می‌کنه تا زودتر خبرت کنه."),
            ("mission.m03.tactics.build", "A tower adds fixed defensive fire; a barrier blocks a road. Spend materials to cover an approach, or save them for rifle reinforcements.", "برج از یه جای ثابت شلیک می‌کنه؛ مانع، جاده رو می‌بنده. مصالح رو برای پوشش مسیر خرج کن یا برای نیروی کمکی نگه دار."),
            ("mission.m03.prepare", "PREPARATION · Position your defenders, then press Hold to begin the defense.", "آماده‌سازی · مدافع‌ها رو مستقر کن، بعد «حفظ» رو بزن تا دفاع شروع بشه."),
            ("mission.m03.casualties", "SQUAD LOSSES: {0} · Reinforce from your Barracks", "تلفات گروه: {0} · از سربازخانه نیروی کمکی بساز"),
            ("mission.m03.guide.title", "FIELD GUIDE · RADAR WARNING", "راهنمای میدانی · هشدار رادار"),
            ("mission.m03.guide.open", "Field guide", "راهنمای میدانی"),
            ("mission.m03.guide.pause", "Battle paused · Close to resume", "نبرد متوقف است · برای ادامه ببند"),
            ("mission.m03.guide.topics", "12 lessons", "۱۲ درس"),
            ("mission.m03.guide.classes", "57 classes", "۵۷ کلاس"),
            ("mission.m03.guide.search", "Search classes…", "جست‌وجوی کلاس‌ها…"),
            ("mission.m03.guide.previous", "Previous", "قبلی"),
            ("mission.m03.guide.next", "Next", "بعدی"),
            ("mission.m03.guide.close", "Close guide", "بستن راهنما"),
            ("mission.m03.guide.example", "EXAMPLE", "نمونه"),
            ("mission.m03.guide.mistake", "COMMON MISTAKE", "اشتباه رایج"),
            ("mission.m03.guide.identity", "Class identity", "شناسهٔ کلاس"),
            ("mission.m03.guide.no_match", "No matching class", "کلاسی پیدا نشد"),
            ("mission.m03.guide.all", "All classes", "همهٔ کلاس‌ها"),
            ("mission.m03.guide.availability.0", "Friendly in M3", "خودی در مأموریت ۳"),
            ("mission.m03.guide.availability.1", "Hostile in M3", "دشمن در مأموریت ۳"),
            ("mission.m03.guide.availability.2", "Protected civilian in M3", "غیرنظامی محافظت‌شده در مأموریت ۳"),
            ("mission.m03.guide.availability.3", "Reference only · unavailable in M3", "فقط برای آشنایی · در مأموریت ۳ در دسترس نیست"),
            ("mission.m03.guide.availability.4", "Future reference · no playable prefab", "معرفی آینده · مدل قابل‌بازی آماده نیست"),
            ("mission.m03.guide.category.character", "Personnel", "نیروی انسانی"),
            ("mission.m03.guide.category.vehicle", "Vehicle", "وسیلهٔ نقلیه"),
            ("mission.m03.guide.category.seaVehicle", "Naval", "دریایی"),
            ("mission.m03.guide.stats", "Health {0} · Speed {1}\nAttack {2} · Range {3}\nGround sensor {4} · Air sensor {5}\nPassenger seats {6} · Vehicle capacity {7}", "سلامت {0} · سرعت {1}\nآسیب {2} · برد {3}\nرادار زمینی {4} · رادار هوایی {5}\nظرفیت نفر {6} · ظرفیت خودرو {7}"),
            ("mission.m03.guide.unarmed", "Unarmed", "بی‌سلاح"),
            ("mission.m03.guide.unavailable_stats", "Gameplay statistics will appear when this class has a playable configuration.", "وقتی اطلاعات کلاس آماده بشه، آمارش اینجا نشون داده می‌شه."),
            ("mission.m03.guide.reference_notice", "Reference values come from the class configuration. Availability, production price and squad size are shown by the current mission’s production panel.", "این آمار از تنظیمات واقعی کلاس میاد. برای هزینه، تعداد نیروها و امکان ساخت، پنل تولید مأموریت رو ببین."),
            ("mission.m03.guide.role.sensor", "ROLE · Ground reconnaissance. Keep the unarmed sensor safe; it provides warning information, not firepower.", "نقش: شناسایی زمینی. رادار سلاح نداره؛ ازش محافظت کن تا اطلاعات بده."),
            ("mission.m03.guide.role.protected", "ROLE · Protected civilian. Keep combat away from them to preserve the civilian bonus star.", "نقش: غیرنظامی. نبرد رو از مردم دور نگه دار تا ستارهٔ حفاظت از اون‌ها رو بگیری."),
            ("mission.m03.guide.role.transport", "ROLE · Transport. Passenger capacity does not guarantee an onboard weapon. In M3 the enemy carrier can breach the core even without firing.", "نقش · ترابری. داشتن ظرفیت مسافر به معنی داشتن سلاح نیست. در مأموریت ۳ نفربر دشمن بدون شلیک هم می‌تواند وارد مرکز شود."),
            ("mission.m03.guide.role.armed", "ROLE · Armed unit. Range and damage are configuration values; position and confirmed targets determine whether it can contribute.", "نقش: نیروی مسلح. برد و آسیبش توی آمار مشخصه؛ موضع خوب و هدف درست کمک می‌کنن مؤثر بجنگه."),
            ("mission.m03.guide.role.unarmed", "ROLE · Support. This configuration cannot attack. Do not count it as a defensive weapon.", "نقش: پشتیبانی. این واحد نمی‌تونه حمله کنه؛ برای دفاع به سلاحش حساب نکن."),
            ("mission.m03.optional.skip", "Skip optional lesson", "ردکردن درس اختیاری"),
            ("mission.m03.warning.title", "CONVOY WARNING", "هشدار کاروان"),
            ("mission.m03.warning.jump", "Inspect reported position", "بررسی موقعیت گزارش‌شده"),
            ("mission.m03.ping.label", "Scan", "اسکن"),
            ("mission.m03.guide.topic.1.title", "Your mission", "مأموریت تو"),
            ("mission.m03.guide.topic.1.body", "Stop every registered hostile while keeping the post standing and the inner core clear.", "هر دشمن ثبت‌شده رو متوقف کن و پاسگاه و محدودهٔ مرکزی رو حفظ کن."),
            ("mission.m03.guide.topic.1.example", "If the fast carrier survives the firefight, block or intercept it before it reaches the post core.", "اگه نفربر سریع از آتش نیروهات رد شد، قبل از رسیدن به مرکز پاسگاه جلوش رو بگیر."),
            ("mission.m03.guide.topic.1.mistake", "Treating civilian losses as an automatic mission defeat. They affect a bonus star.", "تلفات مردم، مأموریت رو شکست نمی‌ده؛ ولی ستارهٔ حفاظت از غیرنظامی‌ها رو از دست می‌دی."),
            ("mission.m03.guide.topic.1.diagram", "WEST ROAD → DEFENSE → FORWARD POST", "جادهٔ غربی ← دفاع ← پاسگاه"),
            ("mission.m03.guide.topic.2.title", "Read a warning", "خواندن هشدار"),
            ("mission.m03.guide.topic.2.body", "Read the source before acting on a reported position.", "قبل از اقدام، ببین گزارش موقعیت از کجا اومده."),
            ("mission.m03.guide.topic.2.example", "A scout warning gives an approach and an estimate. Read it, inspect the road, then check for sensor confirmation.", "دیده‌بان مسیر و زمان تقریبی رو گزارش می‌ده. هشدار رو بخون، جاده رو ببین و منتظر تأیید رادار باش."),
            ("mission.m03.guide.topic.2.mistake", "Assuming an estimated arrival time is a guaranteed countdown.", "قطعی دانستن زمان تقریبی رسیدن."),
            ("mission.m03.guide.topic.2.diagram", "SCOUT REPORT → SENSOR CONTACT → VISUAL CONFIRMATION", "گزارش دیده‌بان ← تماس رادار ← تأیید دیداری"),
            ("mission.m03.guide.topic.3.title", "Sources and confidence", "منبع و اطمینان"),
            ("mission.m03.guide.topic.3.body", "A Ground Radar Tank detects ground vehicles; the Air Radar Dish is for air contacts.", "خودروی رادار زمینی، خودروهای روی زمین رو پیدا می‌کنه. دیش رادار هوایی برای هدف‌های هواییه."),
            ("mission.m03.guide.topic.3.example", "A vehicle leaves radar coverage: its last reported position stays useful, but it is no longer a live location.", "اگه خودرو از پوشش رادار خارج بشه، آخرین جایی که دیدیمش هنوز به درد می‌خوره؛ ولی جای الانش نیست."),
            ("mission.m03.guide.topic.3.mistake", "Interpreting a lost or stale contact as a destroyed enemy.", "تعبیر تماس ازدست‌رفته یا قدیمی به‌عنوان دشمن نابودشده."),
            ("mission.m03.guide.topic.3.diagram", "REPORTED ≠ CONFIRMED · STALE ≠ DESTROYED", "گزارش ≠ تأیید · تماس قدیمی ≠ نابودی"),
            ("mission.m03.guide.topic.4.title", "Jump and Move", "پرش و حرکت"),
            ("mission.m03.guide.topic.4.body", "Inspect the road, return to your squad, then issue Move if repositioning is needed.", "جاده رو ببین، برگرد سراغ گروهت و اگه لازم شد دستور حرکت بده."),
            ("mission.m03.guide.topic.4.example", "Keep squad A selected, inspect the warning with Jump, then press Move and choose a reachable roadside position.", "گروه الف رو انتخاب‌شده نگه دار و با دکمهٔ هشدار، جاده رو ببین. بعد «حرکت» رو بزن و یه مقصد قابل‌دسترسی کنار جاده انتخاب کن."),
            ("mission.m03.guide.topic.4.mistake", "Expecting the camera’s Jump button to move a squad.", "انتظار جابه‌جایی گروه از دکمهٔ پرش دوربین."),
            ("mission.m03.guide.topic.4.diagram", "JUMP → CAMERA · MOVE → SELECTED UNITS", "پرش ← دوربین · حرکت ← واحدهای انتخاب‌شده"),
            ("mission.m03.guide.topic.5.title", "Tower and Barrier", "برج و مانع"),
            ("mission.m03.guide.topic.5.body", "A completed Tower adds firepower. A Barrier can change the route; keep a second approach covered.", "برج آماده، قدرت آتش بیشتری می‌ده. مانع ممکنه مسیر دشمن رو عوض کنه؛ مسیر جایگزین رو هم پوشش بده."),
            ("mission.m03.guide.topic.5.example", "Begin a Tower early and cover its construction with rifles. Place a Barrier only where you can cover the detour.", "ساخت برج رو زود شروع کن و با تفنگدارها ازش محافظت کن. مانع رو جایی بذار که مسیر جایگزینش هم زیر پوششت باشه."),
            ("mission.m03.guide.topic.5.mistake", "Spending on an unfinished defense while leaving the approach unguarded.", "هزینه‌کردن برای دفاع نیمه‌تمام و بی‌دفاع گذاشتن مسیر."),
            ("mission.m03.guide.topic.5.diagram", "CHECK COST → VALID FOOTPRINT → CONFIRM → COMPLETION", "هزینه ← محل مجاز ← تأیید ← تکمیل"),
            ("mission.m03.guide.topic.6.title", "Rifle reinforcements", "تفنگداران کمکی"),
            ("mission.m03.guide.topic.6.body", "Use the existing Barracks to order a four-person rifle squad when the displayed budget allows.", "اگه بودجهٔ نمایش‌داده‌شده کافیه، از سربازخانه یه گروه چهارنفری تفنگدار سفارش بده."),
            ("mission.m03.guide.topic.6.example", "Select the completed Barracks and order one rifle squad. Wait for all four to arrive before counting them in your defense.", "سربازخانهٔ آماده رو انتخاب کن و یه گروه تفنگدار سفارش بده. قبل از اینکه روشون حساب کنی، صبر کن هر چهار نفر آماده بشن."),
            ("mission.m03.guide.topic.6.mistake", "Reading a single class’s reference cost as the current mission’s squad transaction.", "اشتباه گرفتن هزینهٔ مرجع یک کلاس با هزینهٔ واقعی گروه در مأموریت."),
            ("mission.m03.guide.topic.6.diagram", "BARRACKS → PRODUCTION → FOUR RIFLES → POSITION", "پادگان ← تولید ← چهار تفنگدار ← استقرار"),
            ("mission.m03.guide.topic.7.title", "Hold and Cease Fire", "حفظ و قطع آتش"),
            ("mission.m03.guide.topic.7.body", "Hold keeps units defending in place. To cancel orders and stop automatic fire, select units, open Commands, and tap Cease Fire. Use Hold to defend again.", "«حفظ» نیروهات رو سر جاشون نگه می‌داره تا دفاع کنن. اگه می‌خوای دستورها و شلیک خودکار رو قطع کنی، نیروهات رو انتخاب کن، «فرمان‌ها» رو باز کن و «قطع آتش» رو بزن. برای دفاع دوباره، «حفظ» رو بزن."),
            ("mission.m03.guide.topic.7.example", "After reaching the roadside, use Hold. To change destination, issue a new Move order.", "وقتی نیروهات کنار جاده رسیدن، «حفظ» رو بزن. اگه می‌خوای جاشون رو عوض کنی، با «حرکت» مقصد تازه بده."),
            ("mission.m03.guide.topic.7.mistake", "Cease Fire does not pause the battle. Use Pause when you need time to read.", "«قطع آتش» نبرد رو متوقف نمی‌کنه. اگه برای خوندن وقت می‌خوای، بازی رو مکث کن."),
            ("mission.m03.guide.topic.7.diagram", "HOLD → DEFEND · COMMANDS → CEASE FIRE", "حفظ ← دفاع · فرمان‌ها ← قطع آتش"),
            ("mission.m03.guide.topic.8.title", "Scan", "اسکن"),
            ("mission.m03.guide.topic.8.body", "Scan checks the living radar’s coverage. An empty result means no ground vehicle was detected there. You can save Scan for the convoy warning.", "اسکن، محدودهٔ رادار سالم رو بررسی می‌کنه. اگه چیزی پیدا نکرد، یعنی خودرویی توی اون محدوده شناسایی نشده. می‌تونی اسکن رو برای هشدار کاروان نگه داری."),
            ("mission.m03.guide.topic.8.example", "A confirmed vehicle is nearby: use Scan once to refresh its position. Save the remaining use for the main element.", "یه خودروی تأییدشده نزدیکه؛ با یه اسکن می‌تونی جاش رو تازه کنی. نوبت بعدی رو برای بخش اصلی کاروان نگه دار."),
            ("mission.m03.guide.topic.8.mistake", "Expecting an empty scan to refund its charge or reveal the whole map.", "انتظار بازگشت نوبت اسکن بدون تماس یا آشکارشدن کل نقشه."),
            ("mission.m03.guide.topic.8.diagram", "2 USES · 60s COOLDOWN · GROUND SENSOR COVERAGE", "۲ نوبت · بازیابی ۶۰ ثانیه · پوشش رادار زمینی"),
            ("mission.m03.guide.topic.9.title", "Choose targets", "انتخاب هدف"),
            ("mission.m03.guide.topic.9.body", "Shoot a confirmed armed car; also intercept the unarmed carrier before it reaches the core.", "به خودروی مسلح تأییدشده شلیک کن؛ نفربر بی‌سلاح رو هم قبل از رسیدن به مرکز متوقف کن."),
            ("mission.m03.guide.topic.9.example", "Concentrate rifle fire on the armed car, but keep a reserve between the carrier and the post.", "آتش تفنگدارها رو روی خودروی مسلح متمرکز کن، ولی یه گروه ذخیره بین نفربر و پاسگاه نگه دار."),
            ("mission.m03.guide.topic.9.mistake", "Ignoring an unarmed enemy vehicle because it cannot shoot.", "نادیده گرفتن خودروی دشمن بی‌سلاح چون نمی‌تواند شلیک کند."),
            ("mission.m03.guide.topic.9.diagram", "ARMED CAR → DAMAGE · CARRIER → CORE BREACH", "خودروی مسلح ← آسیب · نفربر ← ورود به مرکز"),
            ("mission.m03.guide.topic.10.title", "Protect the core", "حفاظت از مرکز"),
            ("mission.m03.guide.topic.10.body", "Keep one squad covering the inner approach while another intercepts farther west.", "یه گروه مسیر داخلی رو پوشش بده و گروه دیگه جلوتر، توی غرب، جلوی دشمن رو بگیره."),
            ("mission.m03.guide.topic.10.example", "If a forward squad falls back, move your reserve into the approach before the carrier passes the last turn.", "اگه گروه جلویی عقب نشست، قبل از اینکه نفربر از آخرین پیچ رد بشه، نیروی ذخیره رو سر راهش ببر."),
            ("mission.m03.guide.topic.10.mistake", "Chasing a target until every defender leaves the post approach.", "همهٔ نیروهات رو دنبال یه هدف نفرست؛ مسیر پاسگاه بی‌دفاع می‌مونه."),
            ("mission.m03.guide.topic.10.diagram", "FORWARD INTERCEPTION + INNER COVERAGE", "مقابلهٔ جلو + پوشش مسیر داخلی"),
            ("mission.m03.guide.topic.11.title", "Stars and retry", "ستاره‌ها و تلاش دوباره"),
            ("mission.m03.guide.topic.11.body", "After victory, review the civilian and undamaged-post stars separately; retry for a better defense.", "بعد از برد، ستاره‌های حفاظت از مردم و پاسگاه رو جدا ببین. می‌تونی دوباره بازی کنی و دفاعت رو بهتر کنی."),
            ("mission.m03.guide.topic.11.example", "A damaged post can still win. Afterward, the result explains which bonus stars were missed and why.", "حتی اگه پاسگاه آسیب ببینه، باز هم می‌تونی ببری. صفحهٔ نتیجه می‌گه کدوم ستاره رو از دست دادی و چرا."),
            ("mission.m03.guide.topic.11.mistake", "Expecting first-clear unlocks to be granted again on replay.", "انتظار دریافت دوبارهٔ پاداش اولین پیروزی در تکرار مأموریت."),
            ("mission.m03.guide.topic.11.diagram", "VICTORY + CIVILIANS SAFE + POST UNDAMAGED", "پیروزی + سلامت غیرنظامیان + پاسگاه بی‌آسیب"),
            ("mission.m03.guide.topic.12.title", "Every class", "همهٔ کلاس‌ها"),
            ("mission.m03.guide.topic.12.body", "Search the 57 class identities and compare their actual configured capabilities.", "بین ۵۷ کلاس بگرد و قابلیت‌های واقعیشون رو مقایسه کن."),
            ("mission.m03.guide.topic.12.example", "Search Radar Tank, compare its ground-sensor range with the Air Radar Dish, then check each card’s availability label.", "خودروی رادار رو پیدا کن و برد حسگر زمینیش رو با دیش رادار هوایی مقایسه کن. روی هر کارت نوشته توی این مأموریت در دسترس هست یا نه."),
            ("mission.m03.guide.topic.12.mistake", "Assuming every reference class is available for production in M3.", "فرض اینکه همهٔ کلاس‌های مرجع در مأموریت ۳ قابل‌تولیدند."),
            ("mission.m03.guide.topic.12.diagram", "FRIENDLY · HOSTILE · PROTECTED · REFERENCE · FUTURE", "خودی · دشمن · محافظت‌شده · مرجع · آینده"),
        };
    }
}
