namespace Game.Configs
{
    public static class M03RadarWarningGuideCopyCatalog
    {
        public static readonly (string Key, string English, string Persian)[] Entries =
        {
            ("mission.m03.camera.opening", "MISSION OVERVIEW\nTouring the post and approach. ARIA’s tutorial starts when the camera returns.", "مرور مأموریت\nدوربین پاسگاه و مسیر ورودی را نشان می‌دهد. آموزش آریا پس از بازگشت دوربین آغاز می‌شود."),
            ("mission.m03.camera.skip", "Return to command view", "بازگشت به نمای فرماندهی"),
            ("mission.m03.guide.radio", "RADIO ARCHIVE", "بایگانی پیام رادیویی"),
            ("mission.m03.guide.control.6", "RADAR PING", "پالس رادار"),
            ("mission.m03.guide.control.8", "HOLD POSITION", "حفظ موضع"),
            ("mission.m03.guide.control.10", "CANCEL ORDER", "لغو دستور"),
            ("mission.m03.guide.scroll", "Scroll to read the example and common mistake", "برای خواندن نمونه و اشتباه رایج، صفحه را پیمایش کنید"),
            ("mission.m03.action.warning", "Read warning", "خواندن هشدار"),
            ("mission.m03.guide.loading", "Loading class…", "در حال بارگذاری کلاس…"),
            ("mission.m03.guide.load_failed", "Class details could not load. Reopen this card to try again.", "جزئیات کلاس بارگذاری نشد. برای تلاش دوباره این کارت را باز کنید."),
            ("mission.m03.class.Unit_Chr_Bombsuit_Male_01", "Bomb Suit Specialist", "متخصص خنثی‌سازی بمب"),
            ("mission.m03.class.Unit_Chr_Civilian_Female_01", "Civilian Female I", "زن غیرنظامی ۱"),
            ("mission.m03.class.Unit_Chr_Civilian_Female_02", "Civilian Female II", "زن غیرنظامی ۲"),
            ("mission.m03.class.Unit_Chr_Civilian_Male_01", "Civilian Male I", "مرد غیرنظامی ۱"),
            ("mission.m03.class.Unit_Chr_Civilian_Male_02", "Civilian Male II", "مرد غیرنظامی ۲"),
            ("mission.m03.class.Unit_Chr_Contractor_Female_01", "Security Contractor Female I", "نیروی قراردادی زن ۱"),
            ("mission.m03.class.Unit_Chr_Contractor_Male_01", "Security Contractor Male I", "نیروی قراردادی مرد ۱"),
            ("mission.m03.class.Unit_Chr_Contractor_Male_02", "Security Contractor Male II", "نیروی قراردادی مرد ۲"),
            ("mission.m03.class.Unit_Chr_Ghillie_Male_01", "Ghillie Rocketeer", "راکت‌انداز استتاری"),
            ("mission.m03.class.Unit_Chr_Insurgent_Female_01", "Insurgent Rifleman Female I", "تفنگدار شورشی زن ۱"),
            ("mission.m03.class.Unit_Chr_Insurgent_Female_02", "Insurgent Sidearm Fighter Female II", "شورشی تپانچه‌دار زن ۲"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_01", "Insurgent Rocketeer Male I", "راکت‌انداز شورشی مرد ۱"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_02", "Insurgent Gunner Male II", "تیربارچی شورشی مرد ۲"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_03", "Insurgent Raider Male III", "مهاجم شورشی مرد ۳"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_04", "Insurgent Sniper Male IV", "تک‌تیرانداز شورشی مرد ۴"),
            ("mission.m03.class.Unit_Chr_Insurgent_Male_05", "Insurgent Rifleman Male V", "تفنگدار شورشی مرد ۵"),
            ("mission.m03.class.Unit_Chr_Leader_Male_01", "Field Commander", "فرماندهٔ میدان"),
            ("mission.m03.class.Unit_Chr_Pilot_Female_01", "Pilot Female I", "خلبان زن ۱"),
            ("mission.m03.class.Unit_Chr_Pilot_Male_01", "Pilot Male I", "خلبان مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01", "Marksman Female I", "تیرانداز دقیق زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01_Alt_01", "Rifleman Female I", "تفنگدار زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_01_Alt_02", "Marksman Female II", "تیرانداز دقیق زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02", "Rifleman Female II", "تفنگدار زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02_Alt_01", "Rifleman Female I", "تفنگدار زن ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Female_02_Alt_02", "Assault Breacher Female II", "نیروی رخنه‌گر زن ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01", "Heavy Gunner Male I", "تیربارچی سنگین مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01_Alt_01", "Marksman Male I", "تیرانداز دقیق مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_01_Alt_02", "Advanced Rifleman Male II", "تفنگدار پیشرفته مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02", "Rifleman Male II", "تفنگدار مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_01", "Sidearm Specialist Male I", "متخصص تپانچه مرد ۱"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_02", "Rifleman Male II", "تفنگدار مرد ۲"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_03", "Sidearm Specialist Male III", "متخصص تپانچه مرد ۳"),
            ("mission.m03.class.Unit_Chr_Soldier_Male_02_Alt_04", "Rifleman Male IV", "تفنگدار مرد ۴"),
            ("mission.m03.class.Unit_Sea_Coastal_Cutter", "Coastal Cutter", "شناور گشتی ساحلی"),
            ("mission.m03.class.Unit_Sea_Drone_Boat", "Drone Survey Boat", "قایق شناسایی بدون سرنشین"),
            ("mission.m03.class.Unit_Sea_Interceptor_Boat", "Fast Interceptor Boat", "قایق رهگیر سریع"),
            ("mission.m03.class.Unit_Sea_Landing_Craft", "Landing Craft", "شناور پیاده‌سازی"),
            ("mission.m03.class.Unit_Sea_Missile_Craft", "Missile Patrol Craft", "شناور گشتی موشک‌انداز"),
            ("mission.m03.class.Unit_Sea_Patrol_Boat", "Harbor Patrol Boat", "قایق گشت بندر"),
            ("mission.m03.class.Unit_Veh_APC_Fast", "Fast APC", "نفربر سریع"),
            ("mission.m03.class.Unit_Veh_APC_Heavy", "Heavy APC", "نفربر سنگین"),
            ("mission.m03.class.Unit_Veh_APC_Slow", "Armored APC", "نفربر زرهی"),
            ("mission.m03.class.Unit_Veh_Drone", "Recon Drone", "پهپاد شناسایی"),
            ("mission.m03.class.Unit_Veh_Helicopter_Attack", "Attack Helicopter", "بالگرد تهاجمی"),
            ("mission.m03.class.Unit_Veh_Helicopter_Attack_Small", "Light Attack Helicopter", "بالگرد تهاجمی سبک"),
            ("mission.m03.class.Unit_Veh_Helicopter_Transport", "Transport Helicopter", "بالگرد ترابری"),
            ("mission.m03.class.Unit_Veh_Jet_01", "Strike Jet", "جت تهاجمی"),
            ("mission.m03.class.Unit_Veh_Jet_02", "Fighter Jet", "جت جنگنده"),
            ("mission.m03.class.Unit_Veh_Light_Armored_Car", "Light Armored Car", "خودروی زرهی سبک"),
            ("mission.m03.class.Unit_Veh_Missle_Launcher_Air", "Air Missile Launcher", "موشک‌انداز هوایی"),
            ("mission.m03.class.Unit_Veh_Missle_Launcher_Ground", "Ground Missile Launcher", "موشک‌انداز زمینی"),
            ("mission.m03.class.Unit_Veh_Plane_Transport", "Transport Plane", "هواپیمای ترابری"),
            ("mission.m03.class.Unit_Veh_Radar_Tank", "Radar Tank", "خودروی رادار زمینی"),
            ("mission.m03.class.Unit_Veh_Tank_USA", "Battle Tank", "تانک نبرد"),
            ("mission.m03.class.Unit_Veh_Truck_Canopy", "Canopy Truck", "کامیون مسقف"),
            ("mission.m03.class.Unit_Veh_Truck_Tanker", "Tanker Truck", "کامیون سوخت‌رسان"),
            ("mission.m03.class.Unit_Veh_Truck_Tray", "Cargo Truck", "کامیون باربری"),
            ("mission.m03.guide.title", "FIELD GUIDE · RADAR WARNING", "راهنمای میدانی · هشدار رادار"),
            ("mission.m03.guide.open", "Field guide", "راهنمای میدانی"),
            ("mission.m03.guide.pause", "Battle paused · Close to resume", "نبرد متوقف است · برای ادامه ببندید"),
            ("mission.m03.guide.topics", "12 lessons", "۱۲ درس"),
            ("mission.m03.guide.classes", "57 classes", "۵۷ کلاس"),
            ("mission.m03.guide.search", "Search classes…", "جست‌وجوی کلاس‌ها…"),
            ("mission.m03.guide.previous", "Previous", "قبلی"),
            ("mission.m03.guide.next", "Next", "بعدی"),
            ("mission.m03.guide.close", "Close guide", "بستن راهنما"),
            ("mission.m03.guide.example", "EXAMPLE", "نمونه"),
            ("mission.m03.guide.mistake", "COMMON MISTAKE", "اشتباه رایج"),
            ("mission.m03.guide.identity", "Class identity", "شناسهٔ کلاس"),
            ("mission.m03.guide.no_match", "No matching class", "کلاسی پیدا نشد"),
            ("mission.m03.guide.all", "All classes", "همهٔ کلاس‌ها"),
            ("mission.m03.guide.availability.0", "Friendly in M3", "خودی در مأموریت ۳"),
            ("mission.m03.guide.availability.1", "Hostile in M3", "دشمن در مأموریت ۳"),
            ("mission.m03.guide.availability.2", "Protected civilian in M3", "غیرنظامی محافظت‌شده در مأموریت ۳"),
            ("mission.m03.guide.availability.3", "Reference only · unavailable in M3", "فقط برای آشنایی · در مأموریت ۳ در دسترس نیست"),
            ("mission.m03.guide.availability.4", "Future reference · no playable prefab", "معرفی آینده · مدل قابل‌بازی آماده نیست"),
            ("mission.m03.guide.category.character", "Personnel", "نیروی انسانی"),
            ("mission.m03.guide.category.vehicle", "Vehicle", "وسیلهٔ نقلیه"),
            ("mission.m03.guide.category.seaVehicle", "Naval", "دریایی"),
            ("mission.m03.guide.stats", "Health {0} · Speed {1}\nAttack {2} · Range {3}\nGround sensor {4} · Air sensor {5}\nPassenger seats {6} · Vehicle capacity {7}", "سلامت {0} · سرعت {1}\nآسیب {2} · برد {3}\nرادار زمینی {4} · رادار هوایی {5}\nظرفیت نفر {6} · ظرفیت خودرو {7}"),
            ("mission.m03.guide.unarmed", "Unarmed", "بی‌سلاح"),
            ("mission.m03.guide.unavailable_stats", "Gameplay statistics will appear when this class has a playable configuration.", "آمار گیم‌پلی پس از آماده‌شدن پیکربندی قابل‌بازی نمایش داده می‌شود."),
            ("mission.m03.guide.reference_notice", "Reference values come from the class configuration. Availability, production price and squad size are shown by the current mission’s production panel.", "این اعداد از پیکربندی کلاس خوانده می‌شوند. دسترسی، هزینهٔ تولید و اندازهٔ گروه را در پنل تولید مأموریت ببینید."),
            ("mission.m03.guide.role.sensor", "ROLE · Ground reconnaissance. Keep the unarmed sensor safe; it provides warning information, not firepower.", "نقش · شناسایی زمینی. رادار بی‌سلاح را حفظ کنید؛ اطلاعات می‌دهد و قدرت آتش ندارد."),
            ("mission.m03.guide.role.protected", "ROLE · Protected civilian. Keep combat away from them to preserve the civilian bonus star.", "نقش · غیرنظامی محافظت‌شده. نبرد را از آن‌ها دور نگه دارید تا ستارهٔ غیرنظامیان حفظ شود."),
            ("mission.m03.guide.role.transport", "ROLE · Transport. Passenger capacity does not guarantee an onboard weapon. In M3 the enemy carrier can breach the core even without firing.", "نقش · ترابری. داشتن ظرفیت مسافر به معنی داشتن سلاح نیست. در مأموریت ۳ نفربر دشمن بدون شلیک هم می‌تواند وارد مرکز شود."),
            ("mission.m03.guide.role.armed", "ROLE · Armed unit. Range and damage are configuration values; position and confirmed targets determine whether it can contribute.", "نقش · واحد مسلح. برد و آسیب از پیکربندی می‌آیند؛ موضع و هدف تأییدشده تعیین می‌کنند که واحد در نبرد مؤثر باشد."),
            ("mission.m03.guide.role.unarmed", "ROLE · Support. This configuration cannot attack. Do not count it as a defensive weapon.", "نقش · پشتیبانی. این پیکربندی امکان حمله ندارد؛ آن را سلاح دفاعی حساب نکنید."),
            ("mission.m03.optional.skip", "Skip optional lesson", "ردکردن درس اختیاری"),
            ("mission.m03.warning.title", "CONVOY WARNING", "هشدار کاروان"),
            ("mission.m03.warning.jump", "Inspect reported position", "بررسی موقعیت گزارش‌شده"),
            ("mission.m03.ping.label", "Radar Ping", "پالس رادار"),
            ("mission.m03.guide.topic.1.title", "Your mission", "مأموریت شما"),
            ("mission.m03.guide.topic.1.body", "Stop every registered hostile while keeping the post standing and the inner core clear.", "هر دشمن ثبت‌شده را متوقف کنید و پاسگاه و محدودهٔ مرکزی را حفظ کنید."),
            ("mission.m03.guide.topic.1.example", "If the fast carrier survives the firefight, block or intercept it before it reaches the post core.", "اگر نفربر سریع از تیراندازی جان سالم برد، پیش از رسیدن به مرکز پاسگاه جلوی آن را بگیرید."),
            ("mission.m03.guide.topic.1.mistake", "Treating civilian losses as an automatic mission defeat. They affect a bonus star.", "اشتباه گرفتن تلفات غیرنظامی با شکست مأموریت؛ این تلفات ستارهٔ امتیازی را کم می‌کنند."),
            ("mission.m03.guide.topic.1.diagram", "WEST ROAD → DEFENSE → FORWARD POST", "جادهٔ غربی ← دفاع ← پاسگاه"),
            ("mission.m03.guide.topic.2.title", "Read a warning", "خواندن هشدار"),
            ("mission.m03.guide.topic.2.body", "Read the source before acting on a reported position.", "پیش از اقدام، منبع موقعیت گزارش‌شده را بخوانید."),
            ("mission.m03.guide.topic.2.example", "A scout warning gives an approach and an estimate. Read it, inspect the road, then check for sensor confirmation.", "هشدار دیده‌بان مسیر و زمان تقریبی را می‌دهد. آن را بخوانید، جاده را بررسی کنید و منتظر تأیید حسگر باشید."),
            ("mission.m03.guide.topic.2.mistake", "Assuming an estimated arrival time is a guaranteed countdown.", "قطعی دانستن زمان تقریبی رسیدن."),
            ("mission.m03.guide.topic.2.diagram", "SCOUT REPORT → SENSOR CONTACT → VISUAL CONFIRMATION", "گزارش دیده‌بان ← تماس رادار ← تأیید دیداری"),
            ("mission.m03.guide.topic.3.title", "Sources and confidence", "منبع و اطمینان"),
            ("mission.m03.guide.topic.3.body", "A Ground Radar Tank detects ground vehicles; the Air Radar Dish is for air contacts.", "خودروی رادار زمینی، خودروهای زمینی را شناسایی می‌کند؛ دیش رادار هوایی برای تماس هوایی است."),
            ("mission.m03.guide.topic.3.example", "A vehicle leaves radar coverage: its last reported position stays useful, but it is no longer a live location.", "خودرویی از پوشش رادار خارج می‌شود: آخرین موقعیت آن هنوز مفید است، اما موقعیت زنده نیست."),
            ("mission.m03.guide.topic.3.mistake", "Interpreting a lost or stale contact as a destroyed enemy.", "تعبیر تماس ازدست‌رفته یا قدیمی به‌عنوان دشمن نابودشده."),
            ("mission.m03.guide.topic.3.diagram", "REPORTED ≠ CONFIRMED · STALE ≠ DESTROYED", "گزارش ≠ تأیید · تماس قدیمی ≠ نابودی"),
            ("mission.m03.guide.topic.4.title", "Jump and Move", "پرش و حرکت"),
            ("mission.m03.guide.topic.4.body", "Inspect the road, return to your squad, then issue Move if repositioning is needed.", "جاده را بررسی کنید، به گروه برگردید و در صورت نیاز دستور حرکت بدهید."),
            ("mission.m03.guide.topic.4.example", "Keep squad A selected, inspect the warning with Jump, then press Move and choose a reachable roadside position.", "گروه الف را انتخاب نگه دارید، با پرش هشدار را بررسی کنید، سپس حرکت را بزنید و مقصدی قابل‌دسترسی کنار جاده انتخاب کنید."),
            ("mission.m03.guide.topic.4.mistake", "Expecting the camera’s Jump button to move a squad.", "انتظار جابه‌جایی گروه از دکمهٔ پرش دوربین."),
            ("mission.m03.guide.topic.4.diagram", "JUMP → CAMERA · MOVE → SELECTED UNITS", "پرش ← دوربین · حرکت ← واحدهای انتخاب‌شده"),
            ("mission.m03.guide.topic.5.title", "Tower and Barrier", "برج و مانع"),
            ("mission.m03.guide.topic.5.body", "A completed Tower adds firepower. A Barrier can change the route; keep a second approach covered.", "برج آماده قدرت آتش می‌دهد. مانع می‌تواند مسیر را تغییر دهد؛ مسیر جایگزین را پوشش دهید."),
            ("mission.m03.guide.topic.5.example", "Begin a Tower early and cover its construction with rifles. Place a Barrier only where you can cover the detour.", "ساخت برج را زود آغاز کنید و با تفنگداران از آن محافظت کنید. مانع را جایی بگذارید که مسیر جایگزین را هم پوشش دهید."),
            ("mission.m03.guide.topic.5.mistake", "Spending on an unfinished defense while leaving the approach unguarded.", "هزینه‌کردن برای دفاع نیمه‌تمام و بی‌دفاع گذاشتن مسیر."),
            ("mission.m03.guide.topic.5.diagram", "CHECK COST → VALID FOOTPRINT → CONFIRM → COMPLETION", "هزینه ← محل مجاز ← تأیید ← تکمیل"),
            ("mission.m03.guide.topic.6.title", "Rifle reinforcements", "تفنگداران کمکی"),
            ("mission.m03.guide.topic.6.body", "Use the existing Barracks to order a four-person rifle squad when the displayed budget allows.", "در صورت کافی بودن بودجهٔ نمایش‌داده‌شده، از پادگان موجود گروه چهارنفری تفنگدار سفارش دهید."),
            ("mission.m03.guide.topic.6.example", "Select the completed Barracks and order one rifle squad. Wait for all four to arrive before counting them in your defense.", "پادگان آماده را انتخاب و یک گروه تفنگدار سفارش دهید. پیش از حساب کردن روی آن‌ها، منتظر رسیدن هر چهار نفر بمانید."),
            ("mission.m03.guide.topic.6.mistake", "Reading a single class’s reference cost as the current mission’s squad transaction.", "اشتباه گرفتن هزینهٔ مرجع یک کلاس با هزینهٔ واقعی گروه در مأموریت."),
            ("mission.m03.guide.topic.6.diagram", "BARRACKS → PRODUCTION → FOUR RIFLES → POSITION", "پادگان ← تولید ← چهار تفنگدار ← استقرار"),
            ("mission.m03.guide.topic.7.title", "Hold and Stop", "حفظ و توقف"),
            ("mission.m03.guide.topic.7.body", "Hold protects a position. Stop cancels the current order; the battle continues.", "حفظ از موضع دفاع می‌کند. توقف دستور فعلی را لغو می‌کند و نبرد ادامه دارد."),
            ("mission.m03.guide.topic.7.example", "After reaching the roadside, use Hold. If you chose the wrong destination, use Stop, then issue a corrected Move.", "پس از رسیدن به کنار جاده، حفظ را بزنید. اگر مقصد اشتباه بود، توقف را بزنید و سپس مقصد حرکت را اصلاح کنید."),
            ("mission.m03.guide.topic.7.mistake", "Using Stop when you intended to pause and read the guide.", "استفاده از توقف برای مکث نبرد و خواندن راهنما."),
            ("mission.m03.guide.topic.7.diagram", "HOLD → DEFEND POSITION · STOP → CANCEL ORDER", "حفظ ← دفاع از موضع · توقف ← لغو دستور"),
            ("mission.m03.guide.topic.8.title", "Radar Ping", "پالس رادار"),
            ("mission.m03.guide.topic.8.body", "Wait until an enemy vehicle is inside the living sensor’s coverage before spending a Ping.", "پیش از مصرف پالس، منتظر ورود خودروی دشمن به پوشش رادار سالم بمانید."),
            ("mission.m03.guide.topic.8.example", "A confirmed vehicle is nearby: use one Ping to refresh its position. Save the remaining use for the main element.", "خودرویی تأییدشده نزدیک است: با یک پالس موقعیت آن را تازه کنید. نوبت باقی‌مانده را برای بخش اصلی کاروان نگه دارید."),
            ("mission.m03.guide.topic.8.mistake", "Expecting an empty scan to refund its charge or reveal the whole map.", "انتظار بازگشت نوبت اسکن بدون تماس یا آشکارشدن کل نقشه."),
            ("mission.m03.guide.topic.8.diagram", "2 USES · 60s COOLDOWN · GROUND SENSOR COVERAGE", "۲ نوبت · بازیابی ۶۰ ثانیه · پوشش رادار زمینی"),
            ("mission.m03.guide.topic.9.title", "Choose targets", "انتخاب هدف"),
            ("mission.m03.guide.topic.9.body", "Shoot a confirmed armed car; also intercept the unarmed carrier before it reaches the core.", "به خودروی مسلح تأییدشده شلیک کنید؛ نفربر بی‌سلاح را هم پیش از رسیدن به مرکز متوقف کنید."),
            ("mission.m03.guide.topic.9.example", "Concentrate rifle fire on the armed car, but keep a reserve between the carrier and the post.", "آتش تفنگداران را روی خودروی مسلح متمرکز کنید، اما نیروی ذخیره را بین نفربر و پاسگاه نگه دارید."),
            ("mission.m03.guide.topic.9.mistake", "Ignoring an unarmed enemy vehicle because it cannot shoot.", "نادیده گرفتن خودروی دشمن بی‌سلاح چون نمی‌تواند شلیک کند."),
            ("mission.m03.guide.topic.9.diagram", "ARMED CAR → DAMAGE · CARRIER → CORE BREACH", "خودروی مسلح ← آسیب · نفربر ← ورود به مرکز"),
            ("mission.m03.guide.topic.10.title", "Protect the core", "حفاظت از مرکز"),
            ("mission.m03.guide.topic.10.body", "Keep one squad covering the inner approach while another intercepts farther west.", "یک گروه مسیر داخلی را پوشش دهد و گروه دیگر جلوتر در غرب مقابله کند."),
            ("mission.m03.guide.topic.10.example", "If a forward squad falls back, move your reserve into the approach before the carrier passes the last turn.", "اگر گروه جلو عقب نشست، پیش از عبور نفربر از آخرین پیچ، نیروی ذخیره را در مسیر مستقر کنید."),
            ("mission.m03.guide.topic.10.mistake", "Chasing a target until every defender leaves the post approach.", "تعقیب هدف تا جایی که همهٔ مدافعان مسیر پاسگاه را ترک کنند."),
            ("mission.m03.guide.topic.10.diagram", "FORWARD INTERCEPTION + INNER COVERAGE", "مقابلهٔ جلو + پوشش مسیر داخلی"),
            ("mission.m03.guide.topic.11.title", "Stars and retry", "ستاره‌ها و تلاش دوباره"),
            ("mission.m03.guide.topic.11.body", "After victory, review the civilian and undamaged-post stars separately; retry for a better defense.", "پس از پیروزی، ستارهٔ غیرنظامیان و پاسگاه بی‌آسیب را جدا بررسی کنید؛ برای دفاع بهتر دوباره تلاش کنید."),
            ("mission.m03.guide.topic.11.example", "A damaged post can still win. Afterward, the result explains which bonus stars were missed and why.", "پاسگاه آسیب‌دیده هم می‌تواند پیروز شود. پس از نبرد، نتیجه توضیح می‌دهد کدام ستارهٔ امتیازی و چرا از دست رفته است."),
            ("mission.m03.guide.topic.11.mistake", "Expecting first-clear unlocks to be granted again on replay.", "انتظار دریافت دوبارهٔ پاداش اولین پیروزی در تکرار مأموریت."),
            ("mission.m03.guide.topic.11.diagram", "VICTORY + CIVILIANS SAFE + POST UNDAMAGED", "پیروزی + سلامت غیرنظامیان + پاسگاه بی‌آسیب"),
            ("mission.m03.guide.topic.12.title", "Every class", "همهٔ کلاس‌ها"),
            ("mission.m03.guide.topic.12.body", "Search the 57 class identities and compare their actual configured capabilities.", "۵۷ شناسهٔ کلاس را جست‌وجو و قابلیت‌های واقعی پیکربندی‌شده را مقایسه کنید."),
            ("mission.m03.guide.topic.12.example", "Search Radar Tank, compare its ground-sensor range with the Air Radar Dish, then check each card’s availability label.", "خودروی رادار را جست‌وجو کنید، برد حسگر زمینی آن را با دیش رادار هوایی مقایسه کنید و برچسب دسترسی هر کارت را بخوانید."),
            ("mission.m03.guide.topic.12.mistake", "Assuming every reference class is available for production in M3.", "فرض اینکه همهٔ کلاس‌های مرجع در مأموریت ۳ قابل‌تولیدند."),
            ("mission.m03.guide.topic.12.diagram", "FRIENDLY · HOSTILE · PROTECTED · REFERENCE · FUTURE", "خودی · دشمن · محافظت‌شده · مرجع · آینده"),
        };
    }
}
