using Game.Catalog.Contracts;
namespace Game.Configs
{
    public readonly struct M04NarrativeLine
    {
        public readonly string Id,Key,English,Persian;public readonly NarrativeSpeakerId Speaker;
        public M04NarrativeLine(string id,NarrativeSpeakerId speaker,string en,string fa){Id="m04-"+id;Key="narrative.m04."+id.Replace('-','.');Speaker=speaker;English=en;Persian=fa;}
    }
    public static class M04AirliftCopyCatalog
    {
        public static readonly M04NarrativeLine[] Brief={
            new("brief-01",NarrativeSpeakerId.Laila,"Captain Laila Nasser. My helicopter is ready at the eastern landing area. Bring the four specialists to me in the APC; I can keep this extraction window open for ten minutes.","سروان لیلا ناصر هستم. بالگردم در محل فرود شرقی آماده است. چهار متخصص را با نفربر به من برسانید؛ فرصت تخلیه را ده دقیقه باز نگه می‌دارم."),
            new("brief-02",NarrativeSpeakerId.Samira,"Two medics and two engineers are stranded by the western road. They are the people who can reopen the clinics and restore the network. Bring every one of them home.","دو امدادگر و دو مهندس کنار جادهٔ غربی گرفتار شده‌اند. آن‌ها می‌توانند درمانگاه‌ها را باز کنند و شبکه را بازگردانند. همه را سالم برگردانید."),
            new("brief-03",NarrativeSpeakerId.Dalia,"Rifles cover the road; the APC carries the team. Unload beside Laila, board the helicopter, hold the area clear for twenty seconds, then fly to the marked departure zone.","تفنگدارها جاده را پوشش می‌دهند؛ نفربر تیم را منتقل می‌کند. کنار لیلا پیاده شوید، سوار بالگرد شوید، بیست ثانیه محل را امن نگه دارید و سپس به محدودهٔ خروج پرواز کنید.")};
        public static readonly M04NarrativeLine[] Comms={new("comms-01",NarrativeSpeakerId.Laila,"All four are aboard. The landing area is clear and departure is authorized. Fly to the marked exit; I will take the team from there.","هر چهار نفر سوار شده‌اند. محل فرود امن است و اجازهٔ خروج داریم. به محل خروج مشخص‌شده پرواز کنید؛ از آنجا تیم را منتقل می‌کنم.")};
        public static readonly M04NarrativeLine[] Debrief={
            new("debrief-01",NarrativeSpeakerId.Laila,"Four passengers accounted for. Your escort gave us the time we needed. I am joining this operation; you will have an airlift pilot when the next team needs a way out.","هر چهار مسافر حاضرند. پوشش شما زمان لازم را فراهم کرد. به این عملیات می‌پیوندم؛ از این پس برای نجات تیم بعدی یک خلبان ترابری هوایی خواهید داشت."),
            new("debrief-02",NarrativeSpeakerId.Samira,"The engineers brought their repair records. Several outages lead back to the same fortified communications node. We finally have a place to investigate.","مهندسان سوابق تعمیر را آورده‌اند. چند قطعی به یک گرهٔ ارتباطی مستحکم برمی‌گردد. سرانجام محلی برای بررسی داریم."),
            new("debrief-03",NarrativeSpeakerId.Aria,"Extraction confirmed. Captain Nasser is on the roster. Next objective: assess that communications node. First, let the medical team get back to work.","تخلیه تأیید شد. سروان ناصر به گروه پیوست. هدف بعدی: بررسی آن گرهٔ ارتباطی. ابتدا بگذارید تیم پزشکی به کارش برگردد.")};
        public static readonly (string Title,string PersianTitle,string Body,string PersianBody,string Example,string PersianExample,string Mistake,string PersianMistake)[] Lessons={
            ("A rescue, in two stages","نجات در دو مرحله","Save all four specialists: APC first, helicopter second. You have ten minutes after the camera returns. Enemy kills are optional. Both vehicles carry their own mission supply.","هر چهار متخصص را نجات دهید: ابتدا نفربر، سپس بالگرد. پس از بازگشت دوربین ده دقیقه فرصت دارید. کشتن دشمن الزامی نیست. هر دو وسیله ذخیرهٔ مأموریت خود را دارند.","Read the route, then continue.","مسیر را بخوانید و ادامه دهید.","Do not leave a specialist behind.","هیچ متخصصی را جا نگذارید."),
            ("Select the APC","نفربر را انتخاب کنید","Tap the wheeled APC near your rifle squads. Its passenger list shows the real seats. Keep escort soldiers outside so all four specialists can board.","نفربر چرخ‌دار کنار تفنگدارها را انتخاب کنید. فهرست مسافران ظرفیت واقعی را نشان می‌دهد. نیروهای محافظ را بیرون نگه دارید تا هر چهار متخصص سوار شوند.","Select the APC before giving its movement order.","پیش از فرمان حرکت، نفربر را انتخاب کنید.","A selected rifle squad is not the transport.","گروه تفنگدار انتخاب‌شده نفربر نیست."),
            ("Reach the stranded team","به تیم گرفتار برسید","Select Move and send the APC west along the road to the four specialists. Keep the rifles between them and the approaching patrol. Show Me locates the team.","حرکت را انتخاب کنید و نفربر را از جاده به سمت غرب و چهار متخصص بفرستید. تفنگدارها را میان تیم و گشتی در حال نزدیک‌شدن نگه دارید. نمایش محل، تیم را پیدا می‌کند.","The road gives a clear approach for the APC.","جاده مسیر مناسبی برای نزدیک‌شدن نفربر است.","Do not drive through buildings or leave the APC in enemy fire.","از میان ساختمان‌ها عبور نکنید و نفربر را زیر آتش رها نکنید."),
            ("Select the specialists","متخصصان را انتخاب کنید","Select the four unarmed specialists beside the road. They belong to your rescue team and accept movement and boarding commands. Their survival is mandatory.","چهار متخصص بی‌سلاح کنار جاده را انتخاب کنید. آن‌ها عضو تیم نجات شما هستند و فرمان حرکت و سوارشدن می‌پذیرند. زنده‌ماندن همه الزامی است.","Use a selection box around the four people.","کادر انتخاب را دور هر چهار نفر بکشید.","Keep armed escorts out of this selection.","محافظان مسلح را وارد این انتخاب نکنید."),
            ("Board all four into the APC","هر چهار نفر را سوار نفربر کنید","With the specialists selected, press Board and choose the APC. Wait for all four to appear in its passenger list. A boarding order is not a completed rescue.","با انتخاب متخصصان، سوارشدن را بزنید و نفربر را انتخاب کنید. صبر کنید هر چهار نفر در فهرست مسافران آن ظاهر شوند. فرمان سوارشدن به معنی پایان نجات نیست.","Check the passenger count before moving.","پیش از حرکت تعداد مسافران را بررسی کنید.","Moving too soon can leave a passenger walking behind.","حرکت زودهنگام ممکن است یک مسافر را جا بگذارد."),
            ("Escort the APC to Laila","نفربر را تا لیلا همراهی کنید","Move the loaded APC east to the landing area. The rifles can cover the road or hold the approach. Oil is نفت; Fuel is بنزین. These loaned vehicles do not require a new fuel network here.","نفربر پر را به سمت شرق و محل فرود ببرید. تفنگدارها می‌توانند جاده یا مسیر نزدیک‌شدن دشمن را پوشش دهند. نفت با بنزین فرق دارد. این وسایل امانی در این مأموریت به شبکهٔ سوخت تازه نیاز ندارند.","Keep the passenger count at four during the trip.","در طول مسیر تعداد مسافران را روی چهار نگه دارید.","Do not confuse the global fuel header with a passenger counter.","نمایش بنزین در نوار بالا شمارندهٔ مسافر نیست."),
            ("Unload beside the helicopter","کنار بالگرد پیاده شوید","Select the APC at the landing area and use its passenger panel to unload. All four must leave the APC before they can board the helicopter. If no safe cell exists, move the APC into open ground and retry.","نفربر را در محل فرود انتخاب کنید و از بخش مسافران پیاده‌شدن را بزنید. هر چهار نفر باید پیش از سوارشدن به بالگرد از نفربر خارج شوند. اگر جای امن نیست، نفربر را به فضای باز ببرید و دوباره امتحان کنید.","Unload close to the helicopter while the rifles cover.","با پوشش تفنگدارها نزدیک بالگرد پیاده شوید.","A rejected unload leaves passengers safely aboard; it does not transfer them.","ردشدن فرمان پیاده‌شدن مسافران را در نفربر نگه می‌دارد؛ آن‌ها منتقل نمی‌شوند."),
            ("Inspect the transport helicopter","بالگرد ترابری را بررسی کنید","Select Laila's helicopter. Boarding requires it to be landed and close to the passengers. Its seats, health and movement are real transport state, not a cinematic shortcut.","بالگرد لیلا را انتخاب کنید. برای سوارشدن باید فرود آمده و نزدیک مسافران باشد. ظرفیت، سلامت و حرکت آن واقعی است و میان‌بر سینمایی نیست.","Keep it at the landing area until all four are aboard.","تا سوارشدن هر چهار نفر آن را در محل فرود نگه دارید.","An airborne helicopter cannot instantly collect a passenger.","بالگرد در حال پرواز نمی‌تواند مسافر را فوری سوار کند."),
            ("Transfer the specialists","متخصصان را منتقل کنید","Select the unloaded specialists, press Board, and choose the helicopter. Verify four passengers in its manifest. Every specialist must have completed the APC leg first.","متخصصان پیاده‌شده را انتخاب کنید، سوارشدن را بزنید و بالگرد را انتخاب کنید. وجود چهار مسافر را در فهرست بررسی کنید. هر متخصص باید قبلاً مسیر نفربر را طی کرده باشد.","Board the team, not the escort rifle squads.","تیم متخصصان را سوار کنید، نه تفنگدارهای محافظ را.","Flying straight to the team skips the required APC leg and will not complete the mission.","پرواز مستقیم به سمت تیم، مرحلهٔ نفربر را حذف می‌کند و مأموریت را کامل نمی‌کند."),
            ("Hold the landing area clear","محل فرود را امن نگه دارید","Keep the loaded helicopter at the landing area for twenty uninterrupted seconds. Any active hostile inside the marked radius resets the countdown. Hold the approach with your rifles.","بالگرد پر را بیست ثانیهٔ پیوسته در محل فرود نگه دارید. ورود هر دشمن فعال به محدودهٔ مشخص‌شده زمان‌سنج را از نو آغاز می‌کند. تفنگدارها مسیر نزدیک‌شدن را پوشش دهند.","Wait for Laila's departure clearance.","منتظر اجازهٔ خروج لیلا بمانید.","Taking off early does not award extraction progress.","بلندشدن زودهنگام پیشرفت تخلیه را ثبت نمی‌کند."),
            ("Fly to the departure zone","به محدودهٔ خروج پرواز کنید","Select the helicopter, choose Move, and fly to the marked departure zone northeast of the landing area. Keep every specialist aboard and alive. Show Me locates the exit.","بالگرد را انتخاب کنید، حرکت را بزنید و به محدودهٔ خروج در شمال‌شرق محل فرود پرواز کنید. همهٔ متخصصان باید سوار و زنده باشند. نمایش محل، خروج را پیدا می‌کند.","Cross the departure area with the helicopter airborne.","با بالگرد در حال پرواز وارد محدودهٔ خروج شوید.","The APC reaching the exit does not count as an airlift.","رسیدن نفربر به خروج، تخلیهٔ هوایی محسوب نمی‌شود."),
            ("Review your rescue","نجات را مرور کنید","Earn one star for extraction, one for keeping every escort alive, and one for finishing within seven minutes. First-clear rewards are paid once. Replays can improve your stars.","برای تخلیه یک ستاره، برای زنده‌ماندن همهٔ محافظان یک ستاره و برای پایان در هفت دقیقه یک ستاره می‌گیرید. پاداش نخستین پیروزی یک‌بار پرداخت می‌شود. تکرار می‌تواند ستاره‌ها را بهتر کند.","Laila joins the campaign after the first successful extraction.","لیلا پس از نخستین تخلیهٔ موفق به کارزار می‌پیوندد.","Failure never grants rescue rewards or shows a successful departure.","شکست پاداش نجات نمی‌دهد و خروج موفق نشان نمی‌دهد.")};
        public static readonly (string Key,string English,string Persian)[] Ui={
            ("mission.m04.name","AIRLIFT","تخلیهٔ هوایی"),("mission.m04.summary","Rescue four specialists by APC, then escort their helicopter out.","چهار متخصص را با نفربر نجات دهید و سپس بالگردشان را تا خروج همراهی کنید."),
            ("mission.m04.location","Eastern district · medical landing area","بخش شرقی · محل فرود امدادی"),("mission.m04.enemy_intel","A finite patrol approaches from the west after two minutes.","یک گشتی محدود پس از دو دقیقه از غرب نزدیک می‌شود."),
            ("mission.m04.resources","Mission-supplied APC and helicopter","نفربر و بالگرد با ذخیرهٔ مأموریت"),("mission.m04.access","8 rifles · APC · helicopter · 4 specialists","۸ تفنگدار · نفربر · بالگرد · ۴ متخصص"),
            ("mission.m04.options","Cover the approach, board safely, leave together","مسیر را پوشش دهید، امن سوار شوید، با هم خارج شوید"),
            ("mission.m04.objective.extract","Extract all four specialists","هر چهار متخصص را تخلیه کنید"),("mission.m04.objective.transport","Protect the APC and helicopter","نفربر و بالگرد را حفظ کنید"),("mission.m04.objective.landing","Hold the landing area clear for 20 seconds","محل فرود را ۲۰ ثانیه امن نگه دارید"),
            ("mission.m04.objective.extract.body","APC → helicopter → departure zone; every specialist must survive.","نفربر، سپس بالگرد، سپس خروج؛ همهٔ متخصصان باید زنده بمانند."),
            ("mission.m04.objective.transport.body","Keep the APC until transfer and the helicopter through departure.","نفربر را تا پایان انتقال و بالگرد را تا خروج حفظ کنید."),
            ("mission.m04.objective.landing.body","All four aboard; keep the helicopter inside the clear landing area.","هر چهار نفر سوار باشند؛ بالگرد را در محل فرود امن نگه دارید."),
            ("mission.m04.star.1","All four extracted","هر چهار نفر تخلیه شدند"),("mission.m04.star.2","No escort losses","بدون تلفات محافظان"),("mission.m04.star.3","Finish within 7 minutes","پایان در ۷ دقیقه"),
            ("mission.m04.reward.laila","Captain Laila Nasser joins","پیوستن سروان لیلا ناصر"),("mission.m04.reward.transport","Transport access","دسترسی به ترابری"),
            ("mission.m04.reward.card","500 XP | 2,500 CREDITS | LAILA | TRANSPORT","۵۰۰ تجربه | ۲۵۰۰ اعتبار | لیلا | ترابری"),
            ("mission.m04.hud.status","Aboard {0}/4 · APC leg {1}/4 · Clear {2}/20s · {3}s left","سوار: {0} از ۴ · مسیر نفربر: {1} از ۴ · امن: {2} از ۲۰ ثانیه · زمان: {3} ثانیه"),
            ("mission.m04.hud.contested","LANDING AREA CONTESTED","محل فرود زیر تهدید است"),("mission.m04.hud.cleared","CLEARED FOR DEPARTURE","اجازهٔ خروج صادر شد"),
            ("mission.m04.focus.team","TEAM","تیم"),("mission.m04.focus.landing","LANDING AREA","محل فرود"),("mission.m04.focus.departure","DEPARTURE","خروج"),
            ("mission.m04.result.victory","EXTRACTION COMPLETE","تخلیه کامل شد"),("mission.m04.result.defeat","EXTRACTION FAILED","تخلیه ناموفق بود"),
            ("mission.m04.result.subtitle","AIRLIFT · MEDICAL LANDING ZONE","تخلیه هوایی · محل فرود امدادی"),
            ("mission.m04.result.objectives","RESCUE OBJECTIVES","هدف‌های نجات"),
            ("unit.apc.fast.description","Fast armored personnel carrier for quickly transporting infantry across the battlefield.","نفربر زرهی سریع برای جابه‌جایی پیاده‌نظام در میدان نبرد."),
            ("unit.helicopter.transport.description","Transport helicopter that lands for boarding and deploys soldiers by rope while airborne.","بالگرد ترابری برای سوار کردن نیروها روی زمین و پیاده‌سازی با طناب هنگام پرواز."),
            ("mission.m04.result.extract","Specialists rescued","متخصصان نجات‌یافته"),
            ("mission.m04.result.transport","Transport protection","حفاظت از ترابری"),
            ("mission.m04.result.landing","20-second LZ clearance","۲۰ ثانیه امنیت محل فرود"),
            ("mission.m04.guide.title","FIELD GUIDE · AIRLIFT","راهنمای میدانی · تخلیهٔ هوایی"),
            ("mission.m04.guide.availability.0","Friendly in M4","خودی در مأموریت ۴"),
            ("mission.m04.guide.availability.1","Hostile in M4","دشمن در مأموریت ۴"),
            ("mission.m04.guide.availability.2","Protected specialist in M4","متخصص محافظت‌شده در مأموریت ۴"),
            ("mission.m04.guide.availability.3","Reference only · unavailable in M4","فقط برای آشنایی · در مأموریت ۴ در دسترس نیست"),
            ("mission.m04.guide.role.protected","ROLE · Protected specialist. All four must ride the APC, transfer to the helicopter and leave alive. Losing anyone fails the rescue.","نقش · متخصص محافظت‌شده. هر چهار نفر باید سوار نفربر شوند، به بالگرد منتقل شوند و زنده خارج شوند. از دست دادن حتی یک نفر باعث شکست نجات می‌شود."),
            ("mission.m04.guide.role.transport","ROLE · Transport. Passenger capacity does not imply an onboard weapon. Use the APC for the road leg, unload at the landing area and board all four specialists onto the helicopter.","نقش · ترابری. ظرفیت مسافر به معنی داشتن سلاح نیست. مسیر زمینی را با نفربر طی کنید، در محل فرود پیاده شوید و هر چهار متخصص را سوار بالگرد کنید."),
            ("mission.m04.guide.notice","These values come from the class configuration. M4 supplies its escort, APC and helicopter; production is disabled. Reference classes cannot be deployed here.","این اعداد از پیکربندی کلاس خوانده می‌شوند. محافظان، نفربر و بالگرد برای مأموریت ۴ فراهم شده‌اند و تولید غیرفعال است. کلاس‌های مرجع را نمی‌توان در این مأموریت مستقر کرد."),
            ("mission.m04.result.success","All four specialists reached safety by APC and helicopter. Captain Laila Nasser joins the campaign.","هر چهار متخصص با نفربر و بالگرد به محل امن رسیدند. سروان لیلا ناصر به کارزار می‌پیوندد."),
            ("mission.m04.result.passenger_lost","A specialist was lost. Keep all four protected during boarding and transfer.","یک متخصص از دست رفت. هنگام سوارشدن و انتقال از هر چهار نفر محافظت کنید."),
            ("mission.m04.result.aircraft_lost","The helicopter was destroyed. Protect it until all four reach the departure zone.","بالگرد نابود شد. تا رسیدن هر چهار نفر به محل خروج از آن محافظت کنید."),
            ("mission.m04.result.carrier_lost","The APC was lost before the team completed the transfer.","نفربر پیش از پایان انتقال تیم از دست رفت."),
            ("mission.m04.result.timeout","The ten-minute extraction window closed before departure.","فرصت ده‌دقیقه‌ای تخلیه پیش از خروج پایان یافت."),
            ("mission.m04.result.integrity","The rescue roster could not be verified. Retry the operation.","فهرست تیم نجات قابل تأیید نبود. مأموریت را دوباره آغاز کنید."),
            ("mission.m04.result.escort_lost","The escort was lost. Keep at least one rifle soldier alive until departure.","محافظان از دست رفتند. دست‌کم یک تفنگدار را تا خروج زنده نگه دارید."),
            ("mission.m04.result.failure","Extraction failed. Review the passenger and transport status, then retry.","تخلیه ناموفق بود. وضعیت مسافران و وسایل را بررسی کنید و دوباره تلاش کنید."),
            ("narrative.speaker.laila.name","Captain Laila Nasser","سروان لیلا ناصر"),("narrative.speaker.laila.role","Airlift pilot","خلبان ترابری هوایی")};
    }
}
