using Game.Catalog.Contracts;
namespace Game.Configs
{
    public readonly struct M04NarrativeLine
    {
        public readonly string Id,Key,English,Persian;public readonly NarrativeSpeakerId Speaker;
        public M04NarrativeLine(string id,NarrativeSpeakerId speaker,string en,string fa){Id="m04-"+id;Key="narrative.m04."+id.Replace('-','.');Speaker=speaker;English=en;Persian=fa;}
    }
    public static class M04AirliftCopyCatalog
    {
        public static readonly M04NarrativeLine[] Brief={
            new("brief-01",NarrativeSpeakerId.Laila,"Captain Laila Nasser. My helicopter is ready at the eastern landing area. Bring the four specialists to me in the APC; I can keep this extraction window open for ten minutes.","من سروان لیلا ناصرم. بالگردم توی محل فرود شرقی آماده‌ست. چهار متخصص رو با نفربر به من برسونید. ده دقیقه می‌تونم منتظر بمونم."),
            new("brief-02",NarrativeSpeakerId.Samira,"Two medics and two engineers are stranded by the western road. They are the people who can reopen the clinics and restore the network. Bring every one of them home.","دو امدادگر و دو مهندس کنار جادهٔ غربی گیر افتادن. برای راه‌انداختن درمانگاه‌ها و شبکه بهشون نیاز داریم. همه رو سالم برگردونید."),
            new("brief-03",NarrativeSpeakerId.Dalia,"Rifles cover the road; the APC carries the team. Unload beside Laila, board the helicopter, hold the area clear for twenty seconds, then fly to the marked departure zone.","تفنگدارها جاده رو پوشش بدن؛ نفربر تیم رو جابه‌جا کنه. کنار لیلا پیاده‌شون کنید و سوار بالگردش کنید. بیست ثانیه محل رو امن نگه دارید، بعد به محدودهٔ خروج پرواز کنید.")};
        public static readonly M04NarrativeLine[] Comms={new("comms-01",NarrativeSpeakerId.Laila,"All four are aboard. The landing area is clear and departure is authorized. Fly to the marked exit; I will take the team from there.","هر چهار نفر سوار شدن. محل فرود امنه و اجازهٔ خروج داریم. به محل خروج مشخص‌شده پرواز کنید؛ از اونجا تیم رو می‌برم.")};
        public static readonly M04NarrativeLine[] Debrief={
            new("debrief-01",NarrativeSpeakerId.Laila,"Four passengers accounted for. Your escort gave us the time we needed. I am joining this operation; you will have an airlift pilot when the next team needs a way out.","هر چهار نفر سالم رسیدن. پوششتون بهمون وقت داد. من هم به تیمتون ملحق می‌شم؛ برای نجات بعدی روی بالگردم حساب کنید."),
            new("debrief-02",NarrativeSpeakerId.Samira,"The engineers brought their repair records. Several outages lead back to the same fortified communications node. We finally have a place to investigate.","مهندس‌ها گزارش‌های تعمیر رو آوردن. چند تا از قطعی‌ها به یه مرکز ارتباطی حفاظت‌شده می‌رسه. بالاخره می‌دونیم کجا رو باید بررسی کنیم."),
            new("debrief-03",NarrativeSpeakerId.Aria,"Extraction confirmed. Captain Nasser is on the roster. Next objective: assess that communications node. First, let the medical team get back to work.","نجات تأیید شد. سروان ناصر هم به تیم پیوست. بعدش باید اون مرکز ارتباطی رو بررسی کنیم. فعلاً بذاریم تیم پزشکی به کارش برسه.")};
        public static readonly (string Title,string PersianTitle,string Body,string PersianBody,string Example,string PersianExample,string Mistake,string PersianMistake)[] Lessons={
            ("A rescue, in two stages","نجات در دو مرحله","Rescue all four specialists: APC first, helicopter second. You have ten minutes. Enemy kills are optional; keep the escort alive for a bonus star.","باید هر چهار متخصص رو نجات بدی: اول با نفربر، بعد با بالگرد. ده دقیقه وقت داری. لازم نیست همهٔ دشمن‌ها رو بکشی؛ اگه محافظ‌ها سالم بمونن، یه ستارهٔ اضافه می‌گیری.","Read the route, then continue.","مسیر رو بخون و ادامه بده.","Do not leave a specialist behind.","هیچ متخصصی رو جا نذار."),
            ("Select the APC","نفربر رو انتخاب کن","Select the wheeled APC beside your rifles. Keep its four seats free for the specialists. Show Me locates the APC.","نفربر چرخ‌دار کنار تفنگدارها رو انتخاب کن. چهار صندلیش رو برای متخصص‌ها خالی نگه دار. اگه پیداش نکردی، «نشان بده» رو بزن.","Select the APC before giving its movement order.","قبل از فرمان حرکت، نفربر رو انتخاب کن.","A selected rifle squad is not the transport.","گروه تفنگدار انتخاب‌شده نفربر نیست."),
            ("Reach the stranded team","به تیم گرفتار برسید","Press Move, then tap beside the four specialists on the western road. Show Me locates them. Send the rifles forward to cover the pickup.","«حرکت» رو بزن و نفربر رو کنار چهار متخصص توی جادهٔ غربی ببر. «نشان بده» جاشون رو نشونت می‌ده. تفنگدارها رو هم برای پوشش جلو بفرست.","The road gives a clear approach for the APC.","جاده مسیر مناسبی برای نزدیک‌شدن نفربر است.","Do not drive through buildings or leave the APC in enemy fire.","از میان ساختمان‌ها عبور نکن و نفربر رو زیر آتش رها نکن."),
            ("Select the specialists","متخصصان رو انتخاب کن","Select all four specialists beside the road. Keep armed escorts outside the selection. This step completes when all four are selected.","هر چهار متخصص کنار جاده رو با دکمهٔ انتخاب متخصصان انتخاب کن. محافظ‌های مسلح نباید توی این گروه باشن. وقتی هر چهار نفر انتخاب بشن، می‌ریم مرحلهٔ بعد.","Tap Select all specialists in ARIA.","دکمهٔ انتخاب همهٔ متخصصان رو در پنل آریا بزن.","Keep armed escorts out of this selection.","محافظان مسلح رو وارد این انتخاب نکن."),
            ("Board all four into the APC","هر چهار نفر رو سوار نفربر کن","Press Board, then tap the APC. Wait until its passenger list shows all four specialists before moving.","«سوارشدن» رو بزن، بعد نفربر رو انتخاب کن. قبل از حرکت، صبر کن تا هر چهار متخصص توی فهرست مسافرها باشن.","Check the passenger count before moving.","قبل از حرکت تعداد مسافران رو بررسی کن.","Moving too soon can leave a passenger walking behind.","زود راه نیفت؛ ممکنه یکی از مسافرها جا بمونه."),
            ("Escort the APC to Laila","نفربر رو تا لیلا همراهی کن","Move the loaded APC east to the marked landing area. Show Me locates Laila. Keep the rifles covering the approaching patrol.","نفربر پر رو به محل فرود مشخص‌شده توی شرق ببر. «نشان بده» جای لیلا رو نشونت می‌ده. تفنگدارها رو برای پوشش مسیر گشت دشمن نگه دار.","Keep the passenger count at four during the trip.","در طول مسیر تعداد مسافران رو روی چهار نگه دار.","Do not leave the escort behind the convoy.","محافظ‌ها رو پشت کاروان جا نذار."),
            ("Unload beside the helicopter","متخصص‌ها رو کنار بالگرد پیاده کن","Open the APC passenger panel, then tap Unload. Wait until all four specialists stand beside the helicopter. Move into open ground if unloading is blocked.","بخش مسافرهای نفربر رو باز کن و «پیاده‌شدن» رو بزن. صبر کن هر چهار متخصص کنار بالگرد پیاده بشن. اگه جا بسته‌ست، نفربر رو یه کم ببر توی فضای باز.","Unload close to the helicopter while the rifles cover.","زیر پوشش تفنگدارها، متخصص‌ها رو کنار بالگرد پیاده کن.","A rejected unload leaves passengers safely aboard; it does not transfer them.","اگه دستور پیاده‌شدن رد بشه، مسافرها توی نفربر می‌مونن و منتقل نمی‌شن."),
            ("Inspect the helicopter","بالگرد رو بررسی کن","Select Laila’s helicopter. Keep it landed beside the specialists until all four have boarded.","بالگرد لیلا رو انتخاب کن. کنار متخصص‌ها روی زمین نگهش دار تا هر چهار نفر بتونن سوار بشن.","Keep it at the landing area until all four are aboard.","تا سوارشدن هر چهار نفر اون رو در محل فرود نگه دار.","An airborne helicopter cannot instantly collect a passenger.","بالگرد باید روی زمین باشه تا مسافرها سوار بشن."),
            ("Transfer the specialists","متخصصان رو منتقل کن","Select all four specialists, press Board, then tap the landed helicopter. Check that its passenger list shows four people.","با دکمهٔ انتخاب متخصصان، هر چهار نفر رو انتخاب کن. «سوارشدن» رو بزن، بعد بالگرد روی زمین رو انتخاب کن. باید هر چهار نفر توی فهرست مسافرها باشن.","Board the team, not the escort rifle squads.","فقط تیم متخصص‌ها رو سوار کن؛ تفنگدارهای محافظ بیرون بمونن.","Flying straight to the team skips the required APC leg and will not complete the mission.","پرواز مستقیم به سمت تیم، مرحلهٔ نفربر رو حذف می‌کنه و مأموریت رو کامل نمی‌کنه."),
            ("Hold the landing area clear","محل فرود رو امن نگه دار","Keep the loaded helicopter inside the marked landing area for twenty clear seconds. Use the rifles to stop threats entering the ring. Leaving or enemy entry resets the count.","بالگرد پر رو بیست ثانیه توی حلقهٔ امن فرود نگه دار. با تفنگدارها نذار دشمن وارد حلقه بشه. اگه بالگرد بیرون بره یا دشمن وارد بشه، زمان از اول شروع می‌شه.","Wait for Laila's departure clearance.","منتظر اجازهٔ خروج لیلا بمون.","Taking off early does not award extraction progress.","اگه زود بلند شی، مرحلهٔ امن‌کردن محل فرود کامل نمی‌شه."),
            ("Fly to the departure zone","به محدودهٔ خروج پرواز کن","Select the helicopter, press Move, then tap the marked exit. Show Me locates the exit. Keep all four specialists aboard until extraction is confirmed.","بالگرد رو انتخاب کن، «حرکت» رو بزن و به محل خروج مشخص‌شده بفرستش. «نشان بده» خروج رو نشونت می‌ده. تا نجات تأیید نشده، هر چهار متخصص باید سوار بمونن.","Cross the departure area with the helicopter airborne.","با بالگرد در حال پرواز وارد محدودهٔ خروج شو.","The APC reaching the exit does not count as an airlift.","رسیدن نفربر به خروج کافی نیست؛ تیم باید با بالگرد خارج بشه."),
            ("Review your rescue","نجات رو مرور کن","Extraction is being confirmed. Keep the passengers aboard and protect the helicopter until the result appears.","دارم نجات رو تأیید می‌کنم. تا نتیجه بیاد، مسافرها رو سوار نگه دار و از بالگرد محافظت کن.","Laila joins the campaign after the first successful extraction.","بعد از اولین نجات موفق، لیلا به تیمت اضافه می‌شه.","Failure never grants rescue rewards or shows a successful departure.","شکست پاداش نجات نمی‌دهد و خروج موفق نشان نمی‌دهد.")};
        public static readonly (string Key,string English,string Persian)[] Ui={
            ("mission.m04.tutorial.hold.wait","All four specialists are aboard. Wait {0} more seconds; no click is needed. Keep the helicopter inside the yellow landing ring. The next lesson will guide you to the exit.","هر چهار متخصص سوارن. {0} ثانیهٔ دیگه صبر کن؛ لازم نیست دکمه‌ای بزنی. بالگرد رو توی حلقهٔ زرد فرود نگه دار. درس بعدی مسیر خروج رو نشونت می‌ده."),
            ("mission.m04.tutorial.hold.contested","Enemy inside the landing ring: the safety timer has reset. Keep the helicopter here. Select your armed escorts and attack the intruders; the countdown resumes when the ring is clear.","دشمن وارد حلقهٔ فرود شده؛ زمان ایمنی از اول شروع می‌شه. بالگرد رو همین‌جا نگه دار. محافظ‌ها رو انتخاب کن و به مهاجم‌ها حمله کن؛ وقتی حلقه پاک بشه، شمارش ادامه پیدا می‌کنه."),
            ("mission.m04.tutorial.hold.return","The helicopter is outside the landing zone. Select it, press Move, then tap inside the yellow landing ring. Keep it there until the safety countdown finishes.","بالگرد بیرون محل فروده. انتخابش کن، «حرکت» رو بزن و داخل حلقهٔ زرد مقصد بده. تا شمارش تموم بشه، همون‌جا نگهش دار."),
            ("mission.m04.tutorial.selection_progress","Specialists selected: {0}/4. Tap Select all specialists to select the rescue team together. Once all four are selected, follow the next highlighted action.","متخصص‌های انتخاب‌شده: {0} از ۴. «انتخاب همهٔ متخصصان» رو بزن تا تیم نجات با هم انتخاب بشن. وقتی هر چهار نفر انتخاب شدن، راهنمای زرد بعدی رو دنبال کن."),
            ("mission.m04.camera.opening","RESCUE ROUTE\nReviewing the pickup and landing areas. ARIA starts when the camera returns.","مسیر نجات\nدوربین جای تیم و محل فرود رو نشونت می‌ده. وقتی برگشت، آموزش آریا شروع می‌شه."),
            ("mission.m04.camera.victory","AIRLIFT COMPLETE\nAll four specialists are safe. Laila is departing.","نجات کامل شد\nهر چهار متخصص سالم‌اند. لیلا در حال خروج است."),
            ("mission.m04.specialist.group","{0} SPECIALISTS","{0} متخصص"),
            ("mission.m04.specialist.name","Specialist","متخصص"),
            ("mission.m04.specialist.role","Rescue passenger","مسافر نجات"),
            ("mission.m04.specialist.description","Rescue passenger. Keep all four specialists safe.","مسافر نجات؛ هر چهار متخصص رو سالم نگه دار."),
            ("mission.m04.result.star_objectives","STAR OBJECTIVES","اهداف ستاره‌ها"),
            ("mission.m04.patrol.warning","Enemy patrol moves in {0}s","حرکت گشت دشمن: {0} ثانیه دیگر"),
            ("mission.m04.patrol.active","Enemy patrol advancing · Protect the team","گشت دشمن در حال پیشروی است · از تیم محافظت کن"),
            ("mission.m04.action.passengers","Open passengers","باز کردن مسافران"),
            ("mission.m04.result.rescued_stat","SPECIALISTS RESCUED","متخصصان نجات‌یافته"),
            ("mission.m04.result.star.complete","Rescue all four","نجات هر چهار نفر"),
            ("mission.m04.result.star.escort","No escort losses","بدون تلفات محافظان"),
            ("mission.m04.result.star.time","Under 7 minutes","کمتر از ۷ دقیقه"),
            ("mission.m04.result.earned","EARNED","دریافت شد"),
            ("mission.m04.result.missed","NOT EARNED","دریافت نشد"),
            ("mission.m04.name","AIRLIFT","تخلیهٔ هوایی"),("mission.m04.summary","Rescue four specialists by APC, then escort their helicopter out.","چهار متخصص رو با نفربر نجات بده، بعد بالگردشون رو تا خروج همراهی کن."),
            ("mission.m04.location","Eastern district · medical landing area","بخش شرقی · محل فرود امدادی"),("mission.m04.enemy_intel","A western patrol moves 15 seconds after boarding, or after two minutes.","گشت غربی ۱۵ ثانیه بعد از سوار شدن تیم، یا بعد از دو دقیقه حرکت می‌کنه."),
            ("mission.m04.resources","Mission-supplied APC and helicopter","نفربر و بالگرد با ذخیرهٔ مأموریت"),("mission.m04.access","8 rifles · APC · helicopter · 4 specialists","۸ تفنگدار · نفربر · بالگرد · ۴ متخصص"),
            ("mission.m04.options","Cover the approach, board safely, leave together","مسیر رو پوشش بده، تیم رو امن سوار کن و با هم خارج شو"),
            ("mission.m04.objective.extract","Extract all four specialists","هر چهار متخصص رو تخلیه کن"),("mission.m04.objective.transport","Protect the APC and helicopter","نفربر و بالگرد رو حفظ کن"),("mission.m04.objective.landing","Hold the landing area clear for 20 seconds","محل فرود رو ۲۰ ثانیه امن نگه دار"),
            ("mission.m04.objective.extract.body","APC → helicopter → departure zone; every specialist must survive.","نفربر، بعد بالگرد، بعد خروج؛ هر چهار متخصص باید زنده بمونن."),
            ("mission.m04.objective.transport.body","Keep the APC until transfer and the helicopter through departure.","نفربر رو تا پایان انتقال و بالگرد رو تا خروج حفظ کن."),
            ("mission.m04.objective.landing.body","All four aboard; keep the helicopter inside the clear landing area.","هر چهار نفر باید سوار باشن؛ بالگرد رو توی محل فرود امن نگه دار."),
            ("mission.m04.star.1","All four extracted","هر چهار نفر تخلیه شدند"),("mission.m04.star.2","No escort losses","بدون تلفات محافظان"),("mission.m04.star.3","Finish within 7 minutes","پایان در ۷ دقیقه"),
            ("mission.m04.reward.laila","Captain Laila Nasser joins","پیوستن سروان لیلا ناصر"),("mission.m04.reward.transport","Transport access","دسترسی به ترابری"),
            ("mission.m04.reward.card","500 XP | 2,500 CREDITS | LAILA | TRANSPORT","۵۰۰ تجربه | ۲۵۰۰ اعتبار | لیلا | ترابری"),
            ("mission.m04.hud.aboard","SPECIALISTS ABOARD","متخصصان سوار"),
            ("mission.m04.hud.carrier","APC TRANSFER","انتقال با نفربر"),
            ("mission.m04.hud.secure","LANDING AREA CLEAR","امنیت محل فرود"),
            ("mission.m04.hud.remaining","TIME REMAINING","زمان باقی‌مانده"),
            ("mission.m04.hud.route","APC → LANDING AREA → DEPARTURE","نفربر ← محل فرود ← خروج"),
            ("mission.m04.hud.status","Aboard {0}/4 · APC leg {1}/4 · Clear {2}/20s · {3}s left","سوار: {0} از ۴ · مسیر نفربر: {1} از ۴ · امن: {2} از ۲۰ ثانیه · زمان: {3} ثانیه"),
            ("mission.m04.hud.contested","LANDING AREA CONTESTED","محل فرود زیر تهدید است"),("mission.m04.hud.cleared","CLEARED FOR DEPARTURE","اجازهٔ خروج صادر شد"),
            ("mission.m04.focus.team","TEAM","تیم"),("mission.m04.focus.landing","LANDING AREA","محل فرود"),("mission.m04.focus.departure","DEPARTURE","خروج"),
            ("mission.m04.result.victory","EXTRACTION COMPLETE","تخلیه کامل شد"),("mission.m04.result.defeat","EXTRACTION FAILED","تخلیه ناموفق بود"),
            ("mission.m04.result.subtitle","AIRLIFT · MEDICAL LANDING ZONE","تخلیه هوایی · محل فرود امدادی"),
            ("mission.m04.result.objectives","RESCUE OBJECTIVES","هدف‌های نجات"),
            ("unit.apc.fast.description","Fast armored personnel carrier for quickly transporting infantry across the battlefield.","نفربر زرهی سریع برای جابه‌جایی پیاده‌نظام در میدان نبرد."),
            ("unit.helicopter.transport.description","Transport helicopter that lands for boarding and deploys soldiers by rope while airborne.","بالگرد ترابری برای سوار کردن نیروها روی زمین و پیاده‌سازی با طناب هنگام پرواز."),
            ("mission.m04.result.extract","Specialists rescued","متخصصان نجات‌یافته"),
            ("mission.m04.result.transport","Transport protection","حفاظت از ترابری"),
            ("mission.m04.result.landing","20-second LZ clearance","۲۰ ثانیه امنیت محل فرود"),
            ("mission.m04.guide.title","FIELD GUIDE · AIRLIFT","راهنمای میدانی · تخلیهٔ هوایی"),
            ("mission.m04.guide.availability.0","Friendly in M4","خودی در مأموریت ۴"),
            ("mission.m04.guide.availability.1","Hostile in M4","دشمن در مأموریت ۴"),
            ("mission.m04.guide.availability.2","Protected specialist in M4","متخصص محافظت‌شده در مأموریت ۴"),
            ("mission.m04.guide.availability.3","Reference only · unavailable in M4","فقط برای آشنایی · در مأموریت ۴ در دسترس نیست"),
            ("mission.m04.guide.role.protected","ROLE · Protected specialist. All four must ride the APC, transfer to the helicopter and leave alive. Losing anyone fails the rescue.","نقش: متخصص. هر چهار نفر باید اول سوار نفربر بشن، بعد بالگرد، و زنده خارج بشن. اگه حتی یه نفر رو از دست بدی، مأموریت شکست می‌خوره."),
            ("mission.m04.guide.role.transport","ROLE · Transport. Passenger capacity does not imply an onboard weapon. Use the APC for the road leg, unload at the landing area and board all four specialists onto the helicopter.","نقش: ترابری. صندلی مسافر داشتن، به معنی مسلح‌بودن نیست. تیم رو با نفربر ببر، توی محل فرود پیاده کن، بعد هر چهار نفر رو سوار بالگرد کن."),
            ("mission.m04.guide.notice","Use the supplied escorts, APC and helicopter. Reinforcements are unavailable in this mission.","از محافظان، نفربر و بالگرد موجود استفاده کن. در این مأموریت نیروی کمکی در دسترس نیست."),
            ("mission.m04.result.success","All four specialists reached safety by APC and helicopter. Captain Laila Nasser joins the campaign.","هر چهار متخصص با نفربر و بالگرد به محل امن رسیدند. سروان لیلا ناصر به کارزار می‌پیوندد."),
            ("mission.m04.result.passenger_lost","A specialist was lost. Keep all four protected during boarding and transfer.","یک متخصص از دست رفت. هنگام سوارشدن و انتقال از هر چهار نفر محافظت کن."),
            ("mission.m04.result.aircraft_lost","The helicopter was destroyed. Protect it until all four reach the departure zone.","بالگرد نابود شد. تا رسیدن هر چهار نفر به محل خروج از آن محافظت کن."),
            ("mission.m04.result.carrier_lost","The APC was lost before the team completed the transfer.","نفربر قبل از پایان انتقال تیم از دست رفت."),
            ("mission.m04.result.timeout","The ten-minute extraction window closed before departure.","ده دقیقه تموم شد و تیم هنوز خارج نشده."),
            ("mission.m04.result.integrity","The rescue roster could not be verified. Retry the operation.","نتونستم فهرست تیم نجات رو تأیید کنم. مأموریت رو دوباره شروع کن."),
            ("mission.m04.result.escort_lost","The escort was lost. Keep at least one rifle soldier alive until departure.","محافظ‌ها رو از دست دادی. حداقل یه تفنگدار رو تا خروج زنده نگه دار."),
            ("mission.m04.result.failure","Extraction failed. Review the passenger and transport status, then retry.","تخلیه ناموفق بود. وضعیت مسافران و وسایل رو بررسی کن و دوباره تلاش کن."),
            ("narrative.speaker.laila.name","Captain Laila Nasser","سروان لیلا ناصر"),("narrative.speaker.laila.role","Airlift pilot","خلبان ترابری هوایی")};
    }
}
