namespace Game.Configs
{
    public static class SupportUiCopyCatalog
    {
        public static readonly (string Key, string English, string Persian)[] Entries =
        {
            ("mission.reward.smoke_screen","Smoke Screen unlocked","پردهٔ دود باز شد"),
            ("support.lesson.1", "Optional lesson: choose visible ground and confirm. Smoke reduces direct ranged damage to grounded units for 15 seconds. Close to skip.", "آموزش اختیاری: زمین قابل‌دید را انتخاب و تأیید کنید. دود ۱۵ ثانیه آسیب تیراندازی مستقیم به واحدهای زمینی را کاهش می‌دهد. برای رد آموزش ببندید."),
            ("support.lesson.2", "Optional lesson: select a confirmed hostile vehicle or military building. Review the target and cost before confirming. Close to skip.", "آموزش اختیاری: خودروی دشمن تأییدشده یا ساختمان نظامی را انتخاب کنید. پیش از تأیید، هدف و هزینهٔ ۴ سوخت را بررسی کنید. برای رد آموزش ببندید."),
            ("support.lesson.3", "Optional lesson: choose a clear visible landing zone. Four rifle soldiers join normal command after landing. Close to skip.", "آموزش اختیاری: محل فرود خالی و قابل‌دید را انتخاب کنید. با ۶ سوخت تأیید کنید؛ چهار سرباز پیاده پس از فرود فرمان‌پذیر می‌شوند. برای رد آموزش ببندید."),
            ("support.lesson.4", "Optional lesson: land the crate, select a friendly ground unit, choose Collect, then tap the crate. Full storage keeps remaining stock. Close to skip.", "آموزش اختیاری: پس از فرود، واحد زمینی خودی را انتخاب کنید، جمع‌آوری را بزنید و صندوق را لمس کنید. در انبار پر، باقی مصالح حفظ می‌شود. برای رد آموزش ببندید."),
            ("support.supply.unreachable", "Cannot reach this crate. Select another ground unit and try Collect again.", "این واحد به صندوق نمی‌رسد. واحد زمینی دیگری را انتخاب و دوباره جمع‌آوری را بزنید."),
            ("support.supply.collect","COLLECT SUPPLIES","جمع‌آوری تدارکات"),
            ("support.supply.stock","{0} Materials remain · {1}","{0} مصالح باقی مانده · {1}"),
            ("support.supply.full","Storage full — stock stays in the crate","انبار پر است؛ موجودی در صندوق می‌ماند"),
            ("support.supply.claimed","Collection in progress","جمع‌آوری در حال انجام است"),
            ("support.supply.select","Select a friendly ground unit, then collect","یک واحد زمینی خودی را انتخاب کنید، سپس جمع‌آوری کنید"),
            ("support.supply.target","Tap the landed supply crate to collect. A new order cancels collection.","برای جمع‌آوری، صندوق فرودآمده را لمس کنید. دستور جدید جمع‌آوری را لغو می‌کند."),
            ("support.title", "SUPPORT", "پشتیبانی"),
            ("support.name.1", "SMOKE SCREEN", "پردهٔ دود"),
            ("support.name.2", "PRECISION STRIKE", "حملهٔ دقیق"),
            ("support.name.3", "PARATROOPERS", "چتربازان"),
            ("support.name.4", "SUPPLY DROP", "تدارکات هوایی"),
            ("support.description.1", "Protect ground units inside a fixed 12 m area for 15 seconds. Incoming direct ranged damage is reduced by 35%. Smoke protects either side.", "از نیروهای زمینی در محدودهٔ ثابت ۱۲ متری برای ۱۵ ثانیه محافظت کن. آسیب شلیک مستقیم ۳۵٪ کمتر می‌شود. دود از هر دو طرف محافظت می‌کند."),
            ("support.description.2", "One strike against a visible, confirmed hostile ground vehicle or military building. Requires a safe air route.", "یک حمله به خودروی زمینی یا ساختمان نظامی دشمنِ دیده‌شده و تأییدشده. مسیر هوایی امن لازم است."),
            ("support.description.3", "Call one rifle squad to a visible, clear landing zone. Requires population space and a safe air route.", "یک گروه تفنگدار به محل فرودِ دیده‌شده و باز فراخوان. ظرفیت نیرو و مسیر هوایی امن لازم است."),
            ("support.description.4", "Deliver 40 Materials in one crate. Select a friendly ground unit to collect it. Uncollected Materials remain in the crate.", "۴۰ مصالح در یک صندوق تحویل بگیر. یک نیروی زمینی خودی را برای جمع‌آوری انتخاب کن. مصالح باقیمانده در صندوق می‌ماند."),
            ("support.card.status", "{0} charges left · Cost: 1 charge + {1} Fuel", "{0} بار باقی‌مانده · هزینه: ۱ بار + {1} سوخت"),
            ("support.detail.cost", "{0} charges left\nCost: 1 charge + {1} Fuel\n{2}", "{0} بار باقی‌مانده\nهزینه: ۱ بار + {1} سوخت\n{2}"),
            ("support.fuel.available", "Available Fuel: {0}", "سوخت در دسترس: {0}"),
            ("support.choose.area", "CHOOSE AREA", "انتخاب محدوده"),
            ("support.choose.zone", "CHOOSE LANDING ZONE", "انتخاب محل فرود"),
            ("support.optional", "Optional support · Keep your mission objective in view", "پشتیبانی اختیاری · هدف مأموریت را دنبال کن"),
            ("support.instruction", "Choose support, then select a target on the battlefield.", "پشتیبانی را انتخاب کن؛ سپس هدف را در میدان انتخاب کن."),
            ("support.aria.wait", "I will wait for your confirmation.", "منتظر تأیید تو می‌مانم."),
            ("support.target.instruction", "Tap a visible ground area. Drag to inspect; confirm to deploy.", "یک محدودهٔ زمینی دیده‌شده را لمس کن. برای بررسی بکش؛ برای اجرا تأیید کن."),
            ("support.consent", "ARIA proposes {0} for {1} Fuel and 1 charge. Approve this exact action?", "آریا {0} را با {1} سوخت و ۱ بار پیشنهاد می‌کند. همین اقدام را تأیید می‌کنی؟"),
            ("support.choose.target", "CHOOSE HOSTILE TARGET", "انتخاب هدف دشمن"),
            ("support.target.strike", "Tap a visible, confirmed hostile vehicle or military building. Confirm to strike.", "خودرو یا ساختمان نظامی دشمنِ دیده‌شده و تأییدشده را لمس کن. برای حمله تأیید کن."),
            ("support.target.landing", "Tap a visible, clear landing zone. Confirm to call the transport.", "محل فرودِ دیده‌شده و باز را لمس کن. برای فراخوان هواپیما تأیید کن."),
            ("support.flight.approaching", "{0} approaching · {1} Fuel reserved · release in {2}s", "{0} در راه است · {1} سوخت رزرو شد · رهاسازی تا {2} ثانیه"),
            ("support.flight.resolved", "{0} deployed", "{0} اجرا شد"),
            ("support.flight.deploying", "{0} releasing troops · select them after landing", "{0} در حال رهاسازی نیرو · پس از فرود انتخابشان کن"),
            ("support.flight.partial", "{0} partially deployed · {1}", "{0} بخشی از نیرو را تحویل داد · {1}"),
            ("support.flight.aborted", "{0} cancelled · {1}", "{0} لغو شد · {1}"),
            ("support.confirm", "DEPLOY", "اجرا"),
            ("support.confirm.smoke", "DEPLOY SMOKE", "اجرای پردهٔ دود"),
            ("support.preview.cost", "Cost: 1 charge + {0} Fuel · {1}", "هزینه: ۱ بار + {0} سوخت · {1}"),
            ("support.cancel", "CANCEL", "لغو"),
            ("support.propose", "ASK ARIA", "پیشنهاد آریا"),
            ("support.approve", "APPROVE", "تأیید"),
            ("support.decline", "DECLINE", "رد"),
            ("support.show", "SHOW TARGET", "نمایش هدف"),
            ("support.play", "PLAY", "شروع"),
            ("support.stop", "STOP", "توقف"),
            ("support.stop_aria", "Stop ARIA", "توقف آریا"),
            ("support.close", "CLOSE", "بستن"),
            ("support.reason.0", "Ready · Confirm to deploy", "آماده · برای اجرا تأیید کن"),
            ("support.reason.1", "This attempt has ended", "این تلاش تمام شده"),
            ("support.reason.2", "Unavailable during pause or results", "هنگام مکث یا نتیجه در دسترس نیست"),
            ("support.reason.3", "Earn this support in Campaign", "این پشتیبانی را در کارزار کسب کن"),
            ("support.reason.4", "Unavailable in this mission", "در این مأموریت در دسترس نیست"),
            ("support.reason.5", "Support is not available yet", "این پشتیبانی هنوز در دسترس نیست"),
            ("support.reason.6", "No charges remaining", "بار دیگری باقی نمانده"),
            ("support.reason.7", "Cooling down", "در حال آماده‌سازی دوباره"),
            ("support.reason.8", "Choose ground inside the battlefield", "زمین داخل میدان را انتخاب کن"),
            ("support.reason.9", "Choose a visible area", "محدودهٔ دیده‌شده را انتخاب کن"),
            ("support.reason.10", "Confirm this hostile contact first", "ابتدا این تماس دشمن را تأیید کن"),
            ("support.reason.11", "Protected area or target", "محدوده یا هدف محافظت‌شده"),
            ("support.reason.12", "Choose a valid target", "هدف مجاز را انتخاب کن"),
            ("support.reason.13", "Target is no longer available", "هدف دیگر در دسترس نیست"),
            ("support.reason.14", "No safe air route", "مسیر هوایی امن نیست"),
            ("support.reason.15", "Landing zone is blocked", "محل فرود مسدود است"),
            ("support.reason.16", "No room for more troops", "ظرفیت نیروی بیشتر نیست"),
            ("support.reason.17", "Not enough available Fuel", "سوخت در دسترس کافی نیست"),
            ("support.reason.18", "Select the target again", "هدف را دوباره انتخاب کن"),
            ("support.reason.19", "This action requires your approval", "این اقدام به تأیید تو نیاز دارد"),
            ("support.reason.20", "Proposal expired; select the target again", "پیشنهاد منقضی شد؛ هدف را دوباره انتخاب کن"),
            ("support.reason.21", "This action was already processed", "این اقدام قبلاً پردازش شده")
        };
    }
}
