#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
GAME_SCRIPTS_ROOT = ROOT / "Assets/Game/Scripts"
OUTPUT_PATH = ROOT / "Design/Architecture/game_scripts_namespace_inventory.md"

NAMESPACE_RE = re.compile(
    r"^[ \t]*namespace[ \t]+(?P<name>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)[ \t]*(?:[;{]|$)",
    re.MULTILINE,
)


@dataclass(frozen=True)
class AssemblyOwner:
    name: str
    root_namespace: str
    directory: Path


@dataclass(frozen=True)
class ScriptNamespaceEntry:
    path: Path
    assembly: AssemblyOwner
    current_namespace: str
    target_namespace: str

    @property
    def has_namespace(self) -> bool:
        return bool(self.current_namespace)

    @property
    def matches_target(self) -> bool:
        return self.current_namespace == self.target_namespace


def normalize(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def load_assembly_owner(path: Path) -> AssemblyOwner:
    data = json.loads(path.read_text(encoding="utf-8"))
    name = data["name"]
    root_namespace = data.get("rootNamespace") or name
    return AssemblyOwner(name=name, root_namespace=root_namespace, directory=path.parent)


def assembly_owners() -> list[AssemblyOwner]:
    owners = [load_assembly_owner(path) for path in sorted(GAME_SCRIPTS_ROOT.rglob("*.asmdef"))]
    return sorted(owners, key=lambda owner: len(owner.directory.parts), reverse=True)


def find_owner(path: Path, owners: list[AssemblyOwner]) -> AssemblyOwner:
    for owner in owners:
        if path.is_relative_to(owner.directory):
            return owner

    raise ValueError(f"No assembly owner found for {normalize(path)}")


def current_namespace(path: Path) -> str:
    text = path.read_text(encoding="utf-8-sig")
    match = NAMESPACE_RE.search(text)
    return match.group("name") if match else ""


def inventory_entries() -> list[ScriptNamespaceEntry]:
    owners = assembly_owners()
    entries: list[ScriptNamespaceEntry] = []
    for path in sorted(GAME_SCRIPTS_ROOT.rglob("*.cs")):
        owner = find_owner(path, owners)
        entries.append(
            ScriptNamespaceEntry(
                path=path,
                assembly=owner,
                current_namespace=current_namespace(path),
                target_namespace=owner.root_namespace,
            )
        )

    return entries


def format_entries_by_assembly(entries: list[ScriptNamespaceEntry]) -> str:
    lines: list[str] = []
    assembly_names = sorted({entry.assembly.name for entry in entries})
    for assembly_name in assembly_names:
        assembly_entries = [entry for entry in entries if entry.assembly.name == assembly_name]
        complete = sum(1 for entry in assembly_entries if entry.matches_target)
        namespaced = sum(1 for entry in assembly_entries if entry.has_namespace)
        total = len(assembly_entries)
        percent = (complete / total * 100.0) if total else 100.0
        lines.append(f"### {assembly_name}")
        lines.append("")
        lines.append(f"- Target namespace: `{assembly_entries[0].target_namespace}`")
        lines.append(f"- Complete: {complete} / {total} ({percent:.1f}%)")
        lines.append(f"- Has any namespace: {namespaced} / {total}")
        lines.append("")
        lines.append("| Status | File | Current namespace | Target namespace |")
        lines.append("| --- | --- | --- | --- |")
        for entry in assembly_entries:
            status = "Complete" if entry.matches_target else "Pending"
            current = f"`{entry.current_namespace}`" if entry.current_namespace else "(none)"
            lines.append(
                f"| {status} | `{normalize(entry.path)}` | {current} | `{entry.target_namespace}` |"
            )
        lines.append("")

    return "\n".join(lines).rstrip()


def write_inventory() -> None:
    entries = inventory_entries()
    total = len(entries)
    complete = sum(1 for entry in entries if entry.matches_target)
    namespaced = sum(1 for entry in entries if entry.has_namespace)
    percent = (complete / total * 100.0) if total else 100.0
    any_namespace_percent = (namespaced / total * 100.0) if total else 100.0
    empty_root_namespaces = [
        owner for owner in assembly_owners() if not owner.root_namespace or owner.root_namespace != owner.name
    ]

    content = "\n".join(
        [
            "# Game Scripts Namespace Inventory",
            "",
            "Generated by `Tools/Architecture/generate_game_scripts_namespace_inventory.py`.",
            "",
            "## Summary",
            "",
            "| Metric | Count |",
            "| --- | ---: |",
            f"| C# files under `Assets/Game/Scripts` | {total} |",
            f"| Files matching target namespace | {complete} |",
            f"| Target namespace percent complete | {percent:.1f}% |",
            f"| Files with any namespace | {namespaced} |",
            f"| Any-namespace percent complete | {any_namespace_percent:.1f}% |",
            f"| Assembly root namespace mismatches | {len(empty_root_namespaces)} |",
            "",
            "## By Assembly",
            "",
            format_entries_by_assembly(entries),
            "",
        ]
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    write_inventory()
