using System;
using System.Collections.Generic;

namespace Game.Missions.Contracts
{
    public enum ContentAccessState { Allowed, UnknownContent, InstalledContentMissing, Unavailable, ProgressionLocked, NotOwned }
    public interface IVerifiedContentEntitlements
    {
        // The adapter verifies platform receipts/account identity. Temporary offline
        // reconciliation must return the last verified ownership for that account.
        bool Owns(string productId);
    }
    public readonly struct MissionProductMembership
    {
        public MissionProductMembership(string id, string product, bool free) { Id=id; ProductId=product; Free=free; }
        public string Id { get; }
        public string ProductId { get; }
        public bool Free { get; }
    }
    public sealed class ContentAccessAuthority
    {
        public const string CampaignProduct = "warline.campaign.shattered_relay";
        public const string OperationsProduct = "warline.operations.sahrin";
        private readonly IVerifiedContentEntitlements entitlements;
        public ContentAccessAuthority(IVerifiedContentEntitlements entitlements) =>
            this.entitlements=entitlements ?? throw new ArgumentNullException(nameof(entitlements));
        public ContentAccessState Evaluate(string id, bool installed, bool ready, bool progression,
            bool enforceOwnership=true)
        {
            if (!TryMembership(id,out var membership)) return ContentAccessState.UnknownContent;
            if (!installed) return ContentAccessState.InstalledContentMissing;
            if (!ready) return ContentAccessState.Unavailable;
            if (!progression) return ContentAccessState.ProgressionLocked;
            if (enforceOwnership && !membership.Free && !entitlements.Owns(membership.ProductId)) return ContentAccessState.NotOwned;
            return ContentAccessState.Allowed;
        }
        public static bool TryMembership(string id, out MissionProductMembership membership) => Members.TryGetValue(id ?? string.Empty, out membership);
        public static IEnumerable<MissionProductMembership> Memberships => Members.Values;
        // Canonical membership generated from the adopted 205-row policy register.
        // Runtime indices and prototype names are deliberately absent.
        private static readonly Dictionary<string,MissionProductMembership> Members = new(StringComparer.Ordinal)
        {
            ["saga.ch01.m01.first_contact"] = new("saga.ch01.m01.first_contact", CampaignProduct, true),
            ["saga.ch01.m02.establish_base"] = new("saga.ch01.m02.establish_base", CampaignProduct, true),
            ["saga.ch01.m03.radar_warning"] = new("saga.ch01.m03.radar_warning", CampaignProduct, true),
            ["saga.ch01.m04.airlift"] = new("saga.ch01.m04.airlift", CampaignProduct, true),
            ["saga.ch01.m05.breach_assault"] = new("saga.ch01.m05.breach_assault", CampaignProduct, true),
            ["saga.ch02.m01.gridlock"] = new("saga.ch02.m01.gridlock", CampaignProduct, false),
            ["saga.ch02.m02.supply_line"] = new("saga.ch02.m02.supply_line", CampaignProduct, false),
            ["saga.ch02.m03.market_lifeline"] = new("saga.ch02.m03.market_lifeline", CampaignProduct, false),
            ["saga.ch02.m04.power_relay"] = new("saga.ch02.m04.power_relay", CampaignProduct, false),
            ["saga.ch02.m05.route_reopened"] = new("saga.ch02.m05.route_reopened", CampaignProduct, false),
            ["saga.ch03.m01.signal_trace"] = new("saga.ch03.m01.signal_trace", CampaignProduct, false),
            ["saga.ch03.m02.safehouse_sweep"] = new("saga.ch03.m02.safehouse_sweep", CampaignProduct, false),
            ["saga.ch03.m03.false_front"] = new("saga.ch03.m03.false_front", CampaignProduct, false),
            ["saga.ch03.m04.evidence_chain"] = new("saga.ch03.m04.evidence_chain", CampaignProduct, false),
            ["saga.ch03.m05.network_break"] = new("saga.ch03.m05.network_break", CampaignProduct, false),
            ["saga.ch04.m01.air_corridor"] = new("saga.ch04.m01.air_corridor", CampaignProduct, false),
            ["saga.ch04.m02.steel_push"] = new("saga.ch04.m02.steel_push", CampaignProduct, false),
            ["saga.ch04.m03.split_front"] = new("saga.ch04.m03.split_front", CampaignProduct, false),
            ["saga.ch04.m04.grounded_signal"] = new("saga.ch04.m04.grounded_signal", CampaignProduct, false),
            ["saga.ch04.m05.armor_break"] = new("saga.ch04.m05.armor_break", CampaignProduct, false),
            ["saga.ch05.m01.citywide_alert"] = new("saga.ch05.m01.citywide_alert", CampaignProduct, false),
            ["saga.ch05.m02.trust_under_fire"] = new("saga.ch05.m02.trust_under_fire", CampaignProduct, false),
            ["saga.ch05.m03.network_collapse"] = new("saga.ch05.m03.network_collapse", CampaignProduct, false),
            ["saga.ch05.m04.last_corridor"] = new("saga.ch05.m04.last_corridor", CampaignProduct, false),
            ["saga.ch05.m05.command_node"] = new("saga.ch05.m05.command_node", CampaignProduct, false),
            ["skirmish.s001"] = new("skirmish.s001", CampaignProduct, true),
            ["skirmish.s002"] = new("skirmish.s002", CampaignProduct, false),
            ["skirmish.s003"] = new("skirmish.s003", CampaignProduct, false),
            ["skirmish.s004"] = new("skirmish.s004", CampaignProduct, false),
            ["skirmish.s005"] = new("skirmish.s005", CampaignProduct, false),
            ["skirmish.s006"] = new("skirmish.s006", CampaignProduct, false),
            ["skirmish.s007"] = new("skirmish.s007", CampaignProduct, false),
            ["skirmish.s008"] = new("skirmish.s008", CampaignProduct, false),
            ["skirmish.s009"] = new("skirmish.s009", CampaignProduct, false),
            ["skirmish.s010"] = new("skirmish.s010", CampaignProduct, false),
            ["skirmish.s011"] = new("skirmish.s011", CampaignProduct, false),
            ["skirmish.s012"] = new("skirmish.s012", CampaignProduct, false),
            ["skirmish.s013"] = new("skirmish.s013", CampaignProduct, false),
            ["skirmish.s014"] = new("skirmish.s014", CampaignProduct, false),
            ["skirmish.s015"] = new("skirmish.s015", CampaignProduct, false),
            ["skirmish.s016"] = new("skirmish.s016", CampaignProduct, false),
            ["skirmish.s017"] = new("skirmish.s017", CampaignProduct, false),
            ["skirmish.s018"] = new("skirmish.s018", CampaignProduct, false),
            ["skirmish.s019"] = new("skirmish.s019", CampaignProduct, false),
            ["skirmish.s020"] = new("skirmish.s020", CampaignProduct, false),
            ["skirmish.s021"] = new("skirmish.s021", CampaignProduct, false),
            ["skirmish.s022"] = new("skirmish.s022", CampaignProduct, false),
            ["skirmish.s023"] = new("skirmish.s023", CampaignProduct, false),
            ["skirmish.s024"] = new("skirmish.s024", CampaignProduct, false),
            ["skirmish.s025"] = new("skirmish.s025", CampaignProduct, false),
            ["skirmish.s026"] = new("skirmish.s026", CampaignProduct, false),
            ["skirmish.s027"] = new("skirmish.s027", CampaignProduct, false),
            ["skirmish.s028"] = new("skirmish.s028", CampaignProduct, false),
            ["skirmish.s029"] = new("skirmish.s029", CampaignProduct, false),
            ["skirmish.s030"] = new("skirmish.s030", CampaignProduct, false),
            ["skirmish.s031"] = new("skirmish.s031", CampaignProduct, false),
            ["skirmish.s032"] = new("skirmish.s032", CampaignProduct, false),
            ["skirmish.s033"] = new("skirmish.s033", CampaignProduct, false),
            ["skirmish.s034"] = new("skirmish.s034", CampaignProduct, false),
            ["skirmish.s035"] = new("skirmish.s035", CampaignProduct, false),
            ["skirmish.s036"] = new("skirmish.s036", CampaignProduct, false),
            ["skirmish.s037"] = new("skirmish.s037", CampaignProduct, false),
            ["skirmish.s038"] = new("skirmish.s038", CampaignProduct, false),
            ["skirmish.s039"] = new("skirmish.s039", CampaignProduct, false),
            ["skirmish.s040"] = new("skirmish.s040", CampaignProduct, false),
            ["skirmish.s041"] = new("skirmish.s041", CampaignProduct, false),
            ["skirmish.s042"] = new("skirmish.s042", CampaignProduct, false),
            ["skirmish.s043"] = new("skirmish.s043", CampaignProduct, false),
            ["skirmish.s044"] = new("skirmish.s044", CampaignProduct, false),
            ["skirmish.s045"] = new("skirmish.s045", CampaignProduct, false),
            ["skirmish.s046"] = new("skirmish.s046", CampaignProduct, false),
            ["skirmish.s047"] = new("skirmish.s047", CampaignProduct, false),
            ["skirmish.s048"] = new("skirmish.s048", CampaignProduct, false),
            ["skirmish.s049"] = new("skirmish.s049", CampaignProduct, false),
            ["skirmish.s050"] = new("skirmish.s050", CampaignProduct, false),
            ["skirmish.s051"] = new("skirmish.s051", CampaignProduct, false),
            ["skirmish.s052"] = new("skirmish.s052", CampaignProduct, false),
            ["skirmish.s053"] = new("skirmish.s053", CampaignProduct, false),
            ["skirmish.s054"] = new("skirmish.s054", CampaignProduct, false),
            ["skirmish.s055"] = new("skirmish.s055", CampaignProduct, false),
            ["skirmish.s056"] = new("skirmish.s056", CampaignProduct, false),
            ["skirmish.s057"] = new("skirmish.s057", CampaignProduct, false),
            ["skirmish.s058"] = new("skirmish.s058", CampaignProduct, false),
            ["skirmish.s059"] = new("skirmish.s059", CampaignProduct, false),
            ["skirmish.s060"] = new("skirmish.s060", CampaignProduct, false),
            ["skirmish.s061"] = new("skirmish.s061", CampaignProduct, false),
            ["skirmish.s062"] = new("skirmish.s062", CampaignProduct, false),
            ["skirmish.s063"] = new("skirmish.s063", CampaignProduct, false),
            ["skirmish.s064"] = new("skirmish.s064", CampaignProduct, false),
            ["skirmish.s065"] = new("skirmish.s065", CampaignProduct, false),
            ["skirmish.s066"] = new("skirmish.s066", CampaignProduct, false),
            ["skirmish.s067"] = new("skirmish.s067", CampaignProduct, false),
            ["skirmish.s068"] = new("skirmish.s068", CampaignProduct, false),
            ["skirmish.s069"] = new("skirmish.s069", CampaignProduct, false),
            ["skirmish.s070"] = new("skirmish.s070", CampaignProduct, false),
            ["skirmish.s071"] = new("skirmish.s071", CampaignProduct, false),
            ["skirmish.s072"] = new("skirmish.s072", CampaignProduct, false),
            ["skirmish.s073"] = new("skirmish.s073", CampaignProduct, false),
            ["skirmish.s074"] = new("skirmish.s074", CampaignProduct, false),
            ["skirmish.s075"] = new("skirmish.s075", CampaignProduct, false),
            ["skirmish.s076"] = new("skirmish.s076", CampaignProduct, false),
            ["skirmish.s077"] = new("skirmish.s077", CampaignProduct, false),
            ["skirmish.s078"] = new("skirmish.s078", CampaignProduct, false),
            ["skirmish.s079"] = new("skirmish.s079", CampaignProduct, false),
            ["skirmish.s080"] = new("skirmish.s080", CampaignProduct, false),
            ["skirmish.s081"] = new("skirmish.s081", CampaignProduct, false),
            ["skirmish.s082"] = new("skirmish.s082", CampaignProduct, false),
            ["skirmish.s083"] = new("skirmish.s083", CampaignProduct, false),
            ["skirmish.s084"] = new("skirmish.s084", CampaignProduct, false),
            ["skirmish.s085"] = new("skirmish.s085", CampaignProduct, false),
            ["skirmish.s086"] = new("skirmish.s086", CampaignProduct, false),
            ["skirmish.s087"] = new("skirmish.s087", CampaignProduct, false),
            ["skirmish.s088"] = new("skirmish.s088", CampaignProduct, false),
            ["skirmish.s089"] = new("skirmish.s089", CampaignProduct, false),
            ["skirmish.s090"] = new("skirmish.s090", CampaignProduct, false),
            ["skirmish.s091"] = new("skirmish.s091", CampaignProduct, false),
            ["skirmish.s092"] = new("skirmish.s092", CampaignProduct, false),
            ["skirmish.s093"] = new("skirmish.s093", CampaignProduct, false),
            ["skirmish.s094"] = new("skirmish.s094", CampaignProduct, false),
            ["skirmish.s095"] = new("skirmish.s095", CampaignProduct, false),
            ["skirmish.s096"] = new("skirmish.s096", CampaignProduct, false),
            ["skirmish.s097"] = new("skirmish.s097", CampaignProduct, false),
            ["skirmish.s098"] = new("skirmish.s098", CampaignProduct, false),
            ["skirmish.s099"] = new("skirmish.s099", CampaignProduct, false),
            ["skirmish.s100"] = new("skirmish.s100", CampaignProduct, false),
            ["skirmish.s101"] = new("skirmish.s101", CampaignProduct, false),
            ["skirmish.s102"] = new("skirmish.s102", CampaignProduct, false),
            ["skirmish.s103"] = new("skirmish.s103", CampaignProduct, false),
            ["skirmish.s104"] = new("skirmish.s104", CampaignProduct, false),
            ["skirmish.s105"] = new("skirmish.s105", CampaignProduct, false),
            ["skirmish.s106"] = new("skirmish.s106", CampaignProduct, false),
            ["skirmish.s107"] = new("skirmish.s107", CampaignProduct, false),
            ["skirmish.s108"] = new("skirmish.s108", CampaignProduct, false),
            ["skirmish.s109"] = new("skirmish.s109", CampaignProduct, false),
            ["skirmish.s110"] = new("skirmish.s110", CampaignProduct, false),
            ["skirmish.s111"] = new("skirmish.s111", CampaignProduct, false),
            ["skirmish.s112"] = new("skirmish.s112", CampaignProduct, false),
            ["skirmish.s113"] = new("skirmish.s113", CampaignProduct, false),
            ["skirmish.s114"] = new("skirmish.s114", CampaignProduct, false),
            ["skirmish.s115"] = new("skirmish.s115", CampaignProduct, false),
            ["skirmish.s116"] = new("skirmish.s116", CampaignProduct, false),
            ["skirmish.s117"] = new("skirmish.s117", CampaignProduct, false),
            ["skirmish.s118"] = new("skirmish.s118", CampaignProduct, false),
            ["skirmish.s119"] = new("skirmish.s119", CampaignProduct, false),
            ["skirmish.s120"] = new("skirmish.s120", CampaignProduct, false),
            ["operation.o001"] = new("operation.o001", OperationsProduct, true),
            ["operation.o002"] = new("operation.o002", OperationsProduct, true),
            ["operation.o003"] = new("operation.o003", OperationsProduct, true),
            ["operation.o004"] = new("operation.o004", OperationsProduct, false),
            ["operation.o005"] = new("operation.o005", OperationsProduct, false),
            ["operation.o006"] = new("operation.o006", OperationsProduct, false),
            ["operation.o007"] = new("operation.o007", OperationsProduct, false),
            ["operation.o008"] = new("operation.o008", OperationsProduct, false),
            ["operation.o009"] = new("operation.o009", OperationsProduct, false),
            ["operation.o010"] = new("operation.o010", OperationsProduct, false),
            ["operation.o011"] = new("operation.o011", OperationsProduct, false),
            ["operation.o012"] = new("operation.o012", OperationsProduct, false),
            ["operation.o013"] = new("operation.o013", OperationsProduct, false),
            ["operation.o014"] = new("operation.o014", OperationsProduct, false),
            ["operation.o015"] = new("operation.o015", OperationsProduct, false),
            ["operation.o016"] = new("operation.o016", OperationsProduct, false),
            ["operation.o017"] = new("operation.o017", OperationsProduct, false),
            ["operation.o018"] = new("operation.o018", OperationsProduct, false),
            ["operation.o019"] = new("operation.o019", OperationsProduct, false),
            ["operation.o020"] = new("operation.o020", OperationsProduct, false),
            ["operation.o021"] = new("operation.o021", OperationsProduct, false),
            ["operation.o022"] = new("operation.o022", OperationsProduct, false),
            ["operation.o023"] = new("operation.o023", OperationsProduct, false),
            ["operation.o024"] = new("operation.o024", OperationsProduct, false),
            ["operation.o025"] = new("operation.o025", OperationsProduct, false),
            ["operation.o026"] = new("operation.o026", OperationsProduct, false),
            ["operation.o027"] = new("operation.o027", OperationsProduct, false),
            ["operation.o028"] = new("operation.o028", OperationsProduct, false),
            ["operation.o029"] = new("operation.o029", OperationsProduct, false),
            ["operation.o030"] = new("operation.o030", OperationsProduct, false),
            ["operation.o031"] = new("operation.o031", OperationsProduct, false),
            ["operation.o032"] = new("operation.o032", OperationsProduct, false),
            ["operation.o033"] = new("operation.o033", OperationsProduct, false),
            ["operation.o034"] = new("operation.o034", OperationsProduct, false),
            ["operation.o035"] = new("operation.o035", OperationsProduct, false),
            ["operation.o036"] = new("operation.o036", OperationsProduct, false),
            ["operation.o037"] = new("operation.o037", OperationsProduct, false),
            ["operation.o038"] = new("operation.o038", OperationsProduct, false),
            ["operation.o039"] = new("operation.o039", OperationsProduct, false),
            ["operation.o040"] = new("operation.o040", OperationsProduct, false),
            ["operation.o041"] = new("operation.o041", OperationsProduct, false),
            ["operation.o042"] = new("operation.o042", OperationsProduct, false),
            ["operation.o043"] = new("operation.o043", OperationsProduct, false),
            ["operation.o044"] = new("operation.o044", OperationsProduct, false),
            ["operation.o045"] = new("operation.o045", OperationsProduct, false),
            ["operation.o046"] = new("operation.o046", OperationsProduct, false),
            ["operation.o047"] = new("operation.o047", OperationsProduct, false),
            ["operation.o048"] = new("operation.o048", OperationsProduct, false),
            ["operation.o049"] = new("operation.o049", OperationsProduct, false),
            ["operation.o050"] = new("operation.o050", OperationsProduct, false),
            ["operation.o051"] = new("operation.o051", OperationsProduct, false),
            ["operation.o052"] = new("operation.o052", OperationsProduct, false),
            ["operation.o053"] = new("operation.o053", OperationsProduct, false),
            ["operation.o054"] = new("operation.o054", OperationsProduct, false),
            ["operation.o055"] = new("operation.o055", OperationsProduct, false),
            ["operation.o056"] = new("operation.o056", OperationsProduct, false),
            ["operation.o057"] = new("operation.o057", OperationsProduct, false),
            ["operation.o058"] = new("operation.o058", OperationsProduct, false),
            ["operation.o059"] = new("operation.o059", OperationsProduct, false),
            ["operation.o060"] = new("operation.o060", OperationsProduct, false),
        };
    }
}
