#!/usr/bin/env python3
"""Generate audio event id constants from the placeholder catalog JSON."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "Assets" / "Game" / "Audio" / "Config" / "audio_event_catalog_v0_1.json"
OUTPUT_PATH = ROOT / "Assets" / "Game" / "Scripts" / "Audio" / "Config" / "AudioEventIds.cs"


def to_identifier(event_id: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", event_id)
    identifier = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not identifier or identifier[0].isdigit():
        identifier = f"Event{identifier}"
    return identifier


def stable_hash(value: str) -> int:
    hash_value = 2166136261
    for byte in value.encode("utf-8"):
        hash_value ^= byte
        hash_value = (hash_value * 16777619) & 0xFFFFFFFF
    return hash_value


def load_event_ids() -> list[str]:
    catalog = json.loads(CATALOG_PATH.read_text())
    event_ids = [entry["eventId"] for entry in catalog["events"]]
    if len(event_ids) != len(set(event_ids)):
        raise RuntimeError("Audio catalog contains duplicate event ids.")
    identifiers = [to_identifier(event_id) for event_id in event_ids]
    if len(identifiers) != len(set(identifiers)):
        raise RuntimeError("Audio catalog contains event ids that produce duplicate C# identifiers.")
    hashes = [stable_hash(event_id) for event_id in event_ids]
    if len(hashes) != len(set(hashes)):
        raise RuntimeError("Audio catalog contains event ids that produce duplicate stable hashes.")
    return event_ids


def write_event_ids(event_ids: list[str]) -> None:
    lines: list[str] = [
        "// <auto-generated>",
        "// Generated by Tools/Audio/generate_audio_event_ids.py.",
        "// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.",
        "// </auto-generated>",
        "",
        "namespace Game.Configs",
        "{",
        "    public static class AudioEventIds",
        "    {",
    ]

    for event_id in event_ids:
        identifier = to_identifier(event_id)
        lines.append(f'        public const string {identifier} = "{event_id}";')
        lines.append(f"        public const uint {identifier}Hash = {stable_hash(event_id)}u;")
        lines.append("")

    lines.extend(
        [
            "        public static readonly string[] AllEventIds =",
            "        {",
        ]
    )
    for event_id in event_ids:
        lines.append(f"            {to_identifier(event_id)},")
    lines.extend(
        [
            "        };",
            "",
            "        public static readonly uint[] AllEventHashes =",
            "        {",
        ]
    )
    for event_id in event_ids:
        lines.append(f"            {to_identifier(event_id)}Hash,")
    lines.extend(
        [
            "        };",
            "",
            "        public static uint StableHash(string value)",
            "        {",
            "            unchecked",
            "            {",
            "                uint hash = 2166136261u;",
            "                for (int i = 0; i < value.Length; i++)",
            "                {",
            "                    hash ^= value[i];",
            "                    hash *= 16777619u;",
            "                }",
            "",
            "                return hash;",
            "            }",
            "        }",
            "    }",
            "}",
        ]
    )
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")


def write_meta() -> None:
    meta_path = Path(f"{OUTPUT_PATH}.meta")
    if meta_path.exists():
        return
    meta_path.write_text(
        """fileFormatVersion: 2
guid: 1e8201d116f540e68cb35430b74542f0
MonoImporter:
  externalObjects: {}
  serializedVersion: 2
  defaultReferences: []
  executionOrder: 0
  icon: {instanceID: 0}
  userData:
  assetBundleName:
  assetBundleVariant:
"""
    )


def main() -> None:
    event_ids = load_event_ids()
    write_event_ids(event_ids)
    write_meta()
    print(f"Generated {len(event_ids)} audio event ids at {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
