#!/usr/bin/env python3
"""Generate audio event id constants from the placeholder catalog JSON."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "Assets" / "Game" / "Audio" / "Config" / "audio_event_catalog_v0_1.json"
OUTPUT_PATH = ROOT / "Assets" / "Game" / "Scripts" / "Configs" / "Audio" / "AudioEventIds.cs"
CONSTANT_OUTPUTS = [
    (OUTPUT_PATH.with_name(f"AudioEventIds.Constants{index}.cs"), guid)
    for index, guid in enumerate(
        (
            "0663940144374bf2ba527ac4d444f481",
            "f6b2832fbaa04adb9f2f984b44f18b62",
            "452e1fbf53c149f785122887135d366a",
        )
    )
]
EVENT_IDS_OUTPUT = (
    OUTPUT_PATH.with_name("AudioEventIds.AllEventIds.cs"),
    "eb8913f544e240a2a558883e5b80f630",
)
EVENT_HASHES_OUTPUT = (
    OUTPUT_PATH.with_name("AudioEventIds.AllEventHashes.cs"),
    "91e2802e9cbe4c3a8a83502830bfe21f",
)
CONSTANTS_PER_FILE = 100


def to_identifier(event_id: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", event_id)
    identifier = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not identifier or identifier[0].isdigit():
        identifier = f"Event{identifier}"
    return identifier


def stable_hash(value: str) -> int:
    hash_value = 2166136261
    for byte in value.encode("utf-8"):
        hash_value ^= byte
        hash_value = (hash_value * 16777619) & 0xFFFFFFFF
    return hash_value


def load_event_ids() -> list[str]:
    catalog = json.loads(CATALOG_PATH.read_text())
    event_ids = [entry["eventId"] for entry in catalog["events"]]
    if len(event_ids) != len(set(event_ids)):
        raise RuntimeError("Audio catalog contains duplicate event ids.")
    identifiers = [to_identifier(event_id) for event_id in event_ids]
    if len(identifiers) != len(set(identifiers)):
        raise RuntimeError("Audio catalog contains event ids that produce duplicate C# identifiers.")
    hashes = [stable_hash(event_id) for event_id in event_ids]
    if len(hashes) != len(set(hashes)):
        raise RuntimeError("Audio catalog contains event ids that produce duplicate stable hashes.")
    return event_ids


def generated_lines(body: list[str]) -> list[str]:
    return [
        "// <auto-generated>",
        "// Generated by Tools/Audio/generate_audio_event_ids.py.",
        "// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.",
        "// </auto-generated>",
        "",
        "namespace Game.Configs",
        "{",
        "    public static partial class AudioEventIds",
        "    {",
        *body,
        "    }",
        "}",
    ]


def write_generated_source(path: Path, body: list[str]) -> None:
    path.write_text("\n".join(generated_lines(body)) + "\n")


def write_event_ids(event_ids: list[str]) -> None:
    if len(event_ids) > len(CONSTANT_OUTPUTS) * CONSTANTS_PER_FILE:
        raise RuntimeError("Audio catalog exceeds the bounded generated constant-file capacity.")

    root_body = [
        "        public static uint StableHash(string value)",
        "        {",
        "            unchecked",
        "            {",
        "                uint hash = 2166136261u;",
        "                for (int i = 0; i < value.Length; i++)",
        "                {",
        "                    hash ^= value[i];",
        "                    hash *= 16777619u;",
        "                }",
        "",
        "                return hash;",
        "            }",
        "        }",
    ]
    write_generated_source(OUTPUT_PATH, root_body)

    for chunk_index, (path, guid) in enumerate(CONSTANT_OUTPUTS):
        start = chunk_index * CONSTANTS_PER_FILE
        chunk = event_ids[start : start + CONSTANTS_PER_FILE]
        body: list[str] = []
        for event_id in chunk:
            identifier = to_identifier(event_id)
            body.append(f'        public const string {identifier} = "{event_id}";')
            body.append(f"        public const uint {identifier}Hash = {stable_hash(event_id)}u;")
            body.append("")
        write_generated_source(path, body)
        write_meta(path, guid)

    event_id_body = [
        "        public static readonly string[] AllEventIds =",
        "        {",
    ]
    for event_id in event_ids:
        event_id_body.append(f"            {to_identifier(event_id)},")
    event_id_body.extend(["        };", ""])
    write_generated_source(EVENT_IDS_OUTPUT[0], event_id_body)
    write_meta(*EVENT_IDS_OUTPUT)

    event_hash_body = [
        "        public static readonly uint[] AllEventHashes =",
        "        {",
    ]
    for event_id in event_ids:
        event_hash_body.append(f"            {to_identifier(event_id)}Hash,")
    event_hash_body.extend(["        };", ""])
    write_generated_source(EVENT_HASHES_OUTPUT[0], event_hash_body)
    write_meta(*EVENT_HASHES_OUTPUT)

def write_meta(path: Path, guid: str) -> None:
    meta_path = Path(f"{path}.meta")
    if meta_path.exists():
        return
    meta_path.write_text(
        f"""fileFormatVersion: 2
guid: {guid}
MonoImporter:
  externalObjects: {{}}
  serializedVersion: 2
  defaultReferences: []
  executionOrder: 0
  icon: {{instanceID: 0}}
  userData:
  assetBundleName:
  assetBundleVariant:
"""
    )


def main() -> None:
    event_ids = load_event_ids()
    write_event_ids(event_ids)
    write_meta(OUTPUT_PATH, "1e8201d116f540e68cb35430b74542f0")
    print(f"Generated {len(event_ids)} audio event ids at {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
