// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static class AudioEventIds
    {
        public const string UIButtonPrimaryClick = "UI.Button.Primary.Click";
        public const uint UIButtonPrimaryClickHash = 3161187545u;

        public const string UIButtonSecondaryClick = "UI.Button.Secondary.Click";
        public const uint UIButtonSecondaryClickHash = 2478076573u;

        public const string UIButtonNegativeClick = "UI.Button.Negative.Click";
        public const uint UIButtonNegativeClickHash = 2301339126u;

        public const string UIButtonDisabledTap = "UI.Button.Disabled.Tap";
        public const uint UIButtonDisabledTapHash = 117293880u;

        public const string UITabSelect = "UI.Tab.Select";
        public const uint UITabSelectHash = 3352358512u;

        public const string UICardSelect = "UI.Card.Select";
        public const uint UICardSelectHash = 3014326253u;

        public const string UICardLocked = "UI.Card.Locked";
        public const uint UICardLockedHash = 3087335763u;

        public const string UIPopupOpen = "UI.Popup.Open";
        public const uint UIPopupOpenHash = 1791759535u;

        public const string UIPopupClose = "UI.Popup.Close";
        public const uint UIPopupCloseHash = 3024952377u;

        public const string UIScreenForward = "UI.Screen.Forward";
        public const uint UIScreenForwardHash = 805571044u;

        public const string UIScreenBack = "UI.Screen.Back";
        public const uint UIScreenBackHash = 4116222400u;

        public const string UIDrawerOpen = "UI.Drawer.Open";
        public const uint UIDrawerOpenHash = 1202804760u;

        public const string UIDrawerClose = "UI.Drawer.Close";
        public const uint UIDrawerCloseHash = 63668116u;

        public const string UISliderTick = "UI.Slider.Tick";
        public const uint UISliderTickHash = 1305878613u;

        public const string UIToggleOn = "UI.Toggle.On";
        public const uint UIToggleOnHash = 1412658802u;

        public const string UIToggleOff = "UI.Toggle.Off";
        public const uint UIToggleOffHash = 2434261764u;

        public const string UIFeedbackToastError = "UI.Feedback.Toast.Error";
        public const uint UIFeedbackToastErrorHash = 2617262137u;

        public const string UIFeedbackToastPositive = "UI.Feedback.Toast.Positive";
        public const uint UIFeedbackToastPositiveHash = 3875576338u;

        public const string GameplayUnitSelectInfantry = "Gameplay.Unit.Select.Infantry";
        public const uint GameplayUnitSelectInfantryHash = 3141110590u;

        public const string GameplayUnitSelectVehicle = "Gameplay.Unit.Select.Vehicle";
        public const uint GameplayUnitSelectVehicleHash = 3174649265u;

        public const string GameplayUnitSelectAir = "Gameplay.Unit.Select.Air";
        public const uint GameplayUnitSelectAirHash = 2620032125u;

        public const string GameplayUnitEngineVehicleMove = "Gameplay.Unit.Engine.Vehicle.Move";
        public const uint GameplayUnitEngineVehicleMoveHash = 1168540290u;

        public const string GameplayUnitEngineAircraftTakeoff = "Gameplay.Unit.Engine.Aircraft.Takeoff";
        public const uint GameplayUnitEngineAircraftTakeoffHash = 3592499569u;

        public const string GameplayUnitEngineAircraftFlight = "Gameplay.Unit.Engine.Aircraft.Flight";
        public const uint GameplayUnitEngineAircraftFlightHash = 1332154053u;

        public const string GameplayUnitEngineHelicopterFlight = "Gameplay.Unit.Engine.Helicopter.Flight";
        public const uint GameplayUnitEngineHelicopterFlightHash = 696811920u;

        public const string GameplayWeaponFireSmallArms = "Gameplay.Weapon.Fire.SmallArms";
        public const uint GameplayWeaponFireSmallArmsHash = 3212856651u;

        public const string GameplayWeaponMissileImpact = "Gameplay.Weapon.Missile.Impact";
        public const uint GameplayWeaponMissileImpactHash = 990836209u;

        public const string GameplayCommandMoveAccepted = "Gameplay.Command.Move.Accepted";
        public const uint GameplayCommandMoveAcceptedHash = 1382687044u;

        public const string GameplayCommandAttackAccepted = "Gameplay.Command.Attack.Accepted";
        public const uint GameplayCommandAttackAcceptedHash = 3185718759u;

        public const string GameplayCommandHoldAccepted = "Gameplay.Command.Hold.Accepted";
        public const uint GameplayCommandHoldAcceptedHash = 2504035620u;

        public const string GameplayCommandStopReturning = "Gameplay.Command.Stop.Returning";
        public const uint GameplayCommandStopReturningHash = 3510404204u;

        public const string GameplayCommandScanTargeting = "Gameplay.Command.Scan.Targeting";
        public const uint GameplayCommandScanTargetingHash = 1422340592u;

        public const string GameplayCommandScanAccepted = "Gameplay.Command.Scan.Accepted";
        public const uint GameplayCommandScanAcceptedHash = 1764603952u;

        public const string GameplayCommandRejected = "Gameplay.Command.Rejected";
        public const uint GameplayCommandRejectedHash = 4172340306u;

        public const string GameplayBuildPlaceValid = "Gameplay.Build.Place.Valid";
        public const uint GameplayBuildPlaceValidHash = 3769720894u;

        public const string GameplayBuildPlaceInvalid = "Gameplay.Build.Place.Invalid";
        public const uint GameplayBuildPlaceInvalidHash = 1788114895u;

        public const string GameplayProductionQueued = "Gameplay.Production.Queued";
        public const uint GameplayProductionQueuedHash = 2682016025u;

        public const string GameplayProductionComplete = "Gameplay.Production.Complete";
        public const uint GameplayProductionCompleteHash = 2701904751u;

        public const string GameplayResourceExchangeAccepted = "Gameplay.ResourceExchange.Accepted";
        public const uint GameplayResourceExchangeAcceptedHash = 677266519u;

        public const string GameplayResourceExchangeRejected = "Gameplay.ResourceExchange.Rejected";
        public const uint GameplayResourceExchangeRejectedHash = 624368988u;

        public const string GameplayResourceExchangeQueueStarted = "Gameplay.ResourceExchange.QueueStarted";
        public const uint GameplayResourceExchangeQueueStartedHash = 3901359954u;

        public const string GameplayResourceExchangeRushed = "Gameplay.ResourceExchange.Rushed";
        public const uint GameplayResourceExchangeRushedHash = 3276875873u;

        public const string GameplayResourceExchangeCompleted = "Gameplay.ResourceExchange.Completed";
        public const uint GameplayResourceExchangeCompletedHash = 2973504283u;

        public const string GameplayResourceExchangeCancelled = "Gameplay.ResourceExchange.Cancelled";
        public const uint GameplayResourceExchangeCancelledHash = 2587331601u;

        public const string GameplayWeaponRifleFire = "Gameplay.Weapon.Rifle.Fire";
        public const uint GameplayWeaponRifleFireHash = 644878421u;

        public const string GameplayWeaponVehicleCannonFire = "Gameplay.Weapon.VehicleCannon.Fire";
        public const uint GameplayWeaponVehicleCannonFireHash = 4224941188u;

        public const string GameplayWeaponMissileLaunch = "Gameplay.Weapon.Missile.Launch";
        public const uint GameplayWeaponMissileLaunchHash = 3753501364u;

        public const string GameplayWeaponAirMissileLaunch = "Gameplay.Weapon.AirMissile.Launch";
        public const uint GameplayWeaponAirMissileLaunchHash = 510872954u;

        public const string GameplayWeaponMissileFlight = "Gameplay.Weapon.Missile.Flight";
        public const uint GameplayWeaponMissileFlightHash = 1400335713u;

        public const string GameplayUnitAircraftFlyby = "Gameplay.Unit.Aircraft.Flyby";
        public const uint GameplayUnitAircraftFlybyHash = 3269847167u;

        public const string GameplayUnitVehicleEngine = "Gameplay.Unit.Vehicle.Engine";
        public const uint GameplayUnitVehicleEngineHash = 4282126079u;

        public const string GameplayImpactBullet = "Gameplay.Impact.Bullet";
        public const uint GameplayImpactBulletHash = 2654624111u;

        public const string GameplayExplosionSmall = "Gameplay.Explosion.Small";
        public const uint GameplayExplosionSmallHash = 217574373u;

        public const string GameplayExplosionLarge = "Gameplay.Explosion.Large";
        public const uint GameplayExplosionLargeHash = 4072520545u;

        public const string GameplayUnitVehicleDestroyed = "Gameplay.Unit.Vehicle.Destroyed";
        public const uint GameplayUnitVehicleDestroyedHash = 4083608480u;

        public const string AlertThreatMinor = "Alert.Threat.Minor";
        public const uint AlertThreatMinorHash = 3119639462u;

        public const string AlertThreatCritical = "Alert.Threat.Critical";
        public const uint AlertThreatCriticalHash = 2327085632u;

        public const string AlertUnitUnderAttack = "Alert.Unit.UnderAttack";
        public const uint AlertUnitUnderAttackHash = 4035338951u;

        public const string AlertBaseBreached = "Alert.Base.Breached";
        public const uint AlertBaseBreachedHash = 2770899834u;

        public const string GameplayObjectiveProgress = "Gameplay.Objective.Progress";
        public const uint GameplayObjectiveProgressHash = 3042211329u;

        public const string GameplayObjectiveComplete = "Gameplay.Objective.Complete";
        public const uint GameplayObjectiveCompleteHash = 1524265589u;

        public const string GameplayObjectiveFailed = "Gameplay.Objective.Failed";
        public const uint GameplayObjectiveFailedHash = 2020740559u;

        public const string MusicSplashIntro = "Music.Splash.Intro";
        public const uint MusicSplashIntroHash = 525010837u;

        public const string MusicMenuLoop = "Music.Menu.Loop";
        public const uint MusicMenuLoopHash = 3629030835u;

        public const string MusicBriefingLoop = "Music.Briefing.Loop";
        public const uint MusicBriefingLoopHash = 316398394u;

        public const string MusicMatchCalmLoop = "Music.Match.CalmLoop";
        public const uint MusicMatchCalmLoopHash = 4285376118u;

        public const string MusicMatchCombatLoop = "Music.Match.CombatLoop";
        public const uint MusicMatchCombatLoopHash = 1880341561u;

        public const string MusicResultVictory = "Music.Result.Victory";
        public const uint MusicResultVictoryHash = 1502319359u;

        public const string MusicResultDefeat = "Music.Result.Defeat";
        public const uint MusicResultDefeatHash = 552063808u;

        public const string AmbienceCityDayLoop = "Ambience.City.DayLoop";
        public const uint AmbienceCityDayLoopHash = 3552601528u;

        public const string AmbienceBaseDistantLoop = "Ambience.Base.DistantLoop";
        public const uint AmbienceBaseDistantLoopHash = 1729659713u;

        public const string VOARIAMessageConfirmDestroy = "VO.ARIA.Message.ConfirmDestroy";
        public const uint VOARIAMessageConfirmDestroyHash = 2769957816u;

        public const string VOARIAMessageNotEnoughMoney = "VO.ARIA.Message.NotEnoughMoney";
        public const uint VOARIAMessageNotEnoughMoneyHash = 1497698393u;

        public const string VOARIAMessageCreateFirst = "VO.ARIA.Message.CreateFirst";
        public const uint VOARIAMessageCreateFirstHash = 1865937768u;

        public const string VOARIAMessageDragBuildingToFinalPosition = "VO.ARIA.Message.DragBuildingToFinalPosition";
        public const uint VOARIAMessageDragBuildingToFinalPositionHash = 1885782560u;

        public const string VOARIAMessageWarningGroundAttackType = "VO.ARIA.Message.WarningGroundAttackType";
        public const uint VOARIAMessageWarningGroundAttackTypeHash = 2571709797u;

        public const string VOARIAMessageWarningAirAttackType = "VO.ARIA.Message.WarningAirAttackType";
        public const uint VOARIAMessageWarningAirAttackTypeHash = 425358394u;

        public const string VOARIAMessageWarningAttackEtaSeconds = "VO.ARIA.Message.WarningAttackEtaSeconds";
        public const uint VOARIAMessageWarningAttackEtaSecondsHash = 3440772663u;

        public const string VOARIAMessageWarningAttackEtaSuffix = "VO.ARIA.Message.WarningAttackEtaSuffix";
        public const uint VOARIAMessageWarningAttackEtaSuffixHash = 582726599u;

        public const string VOARIAMessageWarningAttackCountSuffix = "VO.ARIA.Message.WarningAttackCountSuffix";
        public const uint VOARIAMessageWarningAttackCountSuffixHash = 273208812u;

        public const string VOARIAMessageTacticalCommandReasonNoSelection = "VO.ARIA.Message.TacticalCommandReasonNoSelection";
        public const uint VOARIAMessageTacticalCommandReasonNoSelectionHash = 4135895351u;

        public const string VOARIAMessageTacticalCommandReasonTargetOutOfBounds = "VO.ARIA.Message.TacticalCommandReasonTargetOutOfBounds";
        public const uint VOARIAMessageTacticalCommandReasonTargetOutOfBoundsHash = 2910927259u;

        public const string VOARIAMessageTacticalCommandReasonTargetBlocked = "VO.ARIA.Message.TacticalCommandReasonTargetBlocked";
        public const uint VOARIAMessageTacticalCommandReasonTargetBlockedHash = 2805549707u;

        public const string VOARIAMessageTacticalCommandReasonTargetUnreachable = "VO.ARIA.Message.TacticalCommandReasonTargetUnreachable";
        public const uint VOARIAMessageTacticalCommandReasonTargetUnreachableHash = 2210103721u;

        public const string VOARIAMessageTacticalCommandReasonTargetNotEnemy = "VO.ARIA.Message.TacticalCommandReasonTargetNotEnemy";
        public const uint VOARIAMessageTacticalCommandReasonTargetNotEnemyHash = 1935329694u;

        public const string VOARIAMessageTacticalCommandReasonTargetNotAttackable = "VO.ARIA.Message.TacticalCommandReasonTargetNotAttackable";
        public const uint VOARIAMessageTacticalCommandReasonTargetNotAttackableHash = 3558763922u;

        public const string VOARIAMessageTacticalCommandReasonCommandUnavailable = "VO.ARIA.Message.TacticalCommandReasonCommandUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonCommandUnavailableHash = 3405920913u;

        public const string VOARIAMessageTacticalCommandReasonBuildUnavailable = "VO.ARIA.Message.TacticalCommandReasonBuildUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonBuildUnavailableHash = 4070679814u;

        public const string VOARIAMessageTacticalCommandReasonCameraJumpUnavailable = "VO.ARIA.Message.TacticalCommandReasonCameraJumpUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonCameraJumpUnavailableHash = 452837419u;

        public const string VOARIAMessageTacticalCommandReasonScanUnavailable = "VO.ARIA.Message.TacticalCommandReasonScanUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonScanUnavailableHash = 4008598569u;

        public const string VOARIAMessageTacticalCommandReasonScanCooldown = "VO.ARIA.Message.TacticalCommandReasonScanCooldown";
        public const uint VOARIAMessageTacticalCommandReasonScanCooldownHash = 1372693640u;

        public const string VOARIAMessageTacticalCommandReasonInsufficientResources = "VO.ARIA.Message.TacticalCommandReasonInsufficientResources";
        public const uint VOARIAMessageTacticalCommandReasonInsufficientResourcesHash = 173798012u;

        public const string VOARIAMessageTacticalCommandReasonInsufficientFuel = "VO.ARIA.Message.TacticalCommandReasonInsufficientFuel";
        public const uint VOARIAMessageTacticalCommandReasonInsufficientFuelHash = 1777687631u;

        public const string VOARIAMessageTacticalCommandReasonInvalidTransport = "VO.ARIA.Message.TacticalCommandReasonInvalidTransport";
        public const uint VOARIAMessageTacticalCommandReasonInvalidTransportHash = 668828628u;

        public const string VOARIAMessageTacticalCommandReasonInvalidPassenger = "VO.ARIA.Message.TacticalCommandReasonInvalidPassenger";
        public const uint VOARIAMessageTacticalCommandReasonInvalidPassengerHash = 3306814445u;

        public const string VOARIAMessageTacticalCommandReasonTransportFull = "VO.ARIA.Message.TacticalCommandReasonTransportFull";
        public const uint VOARIAMessageTacticalCommandReasonTransportFullHash = 1103806920u;

        public const string VOARIAMessageTacticalCommandReasonNoEligiblePassengers = "VO.ARIA.Message.TacticalCommandReasonNoEligiblePassengers";
        public const uint VOARIAMessageTacticalCommandReasonNoEligiblePassengersHash = 749650471u;

        public const string VOARIAMessageTacticalCommandReasonNoDisembarkCell = "VO.ARIA.Message.TacticalCommandReasonNoDisembarkCell";
        public const uint VOARIAMessageTacticalCommandReasonNoDisembarkCellHash = 2874977329u;

        public const string VOARIAMessageTacticalCommandReasonTransportPassengerMissing = "VO.ARIA.Message.TacticalCommandReasonTransportPassengerMissing";
        public const uint VOARIAMessageTacticalCommandReasonTransportPassengerMissingHash = 2925040837u;

        public const string VOARIAMessageTacticalCommandInstructionSelect = "VO.ARIA.Message.TacticalCommandInstructionSelect";
        public const uint VOARIAMessageTacticalCommandInstructionSelectHash = 2748094352u;

        public const string VOARIAMessageTacticalCommandInstructionMove = "VO.ARIA.Message.TacticalCommandInstructionMove";
        public const uint VOARIAMessageTacticalCommandInstructionMoveHash = 3308873509u;

        public const string VOARIAMessageTacticalCommandInstructionAttack = "VO.ARIA.Message.TacticalCommandInstructionAttack";
        public const uint VOARIAMessageTacticalCommandInstructionAttackHash = 4289552068u;

        public const string VOARIAMessageTacticalCommandInstructionHold = "VO.ARIA.Message.TacticalCommandInstructionHold";
        public const uint VOARIAMessageTacticalCommandInstructionHoldHash = 3439454485u;

        public const string VOARIAMessageTacticalCommandInstructionStop = "VO.ARIA.Message.TacticalCommandInstructionStop";
        public const uint VOARIAMessageTacticalCommandInstructionStopHash = 1501401760u;

        public const string VOARIAMessageTacticalCommandInstructionScan = "VO.ARIA.Message.TacticalCommandInstructionScan";
        public const uint VOARIAMessageTacticalCommandInstructionScanHash = 22836897u;

        public const string VOARIAMessageTacticalCommandInstructionBoard = "VO.ARIA.Message.TacticalCommandInstructionBoard";
        public const uint VOARIAMessageTacticalCommandInstructionBoardHash = 4022543000u;

        public const string VOARIAMessageTacticalCommandInstructionBuild = "VO.ARIA.Message.TacticalCommandInstructionBuild";
        public const uint VOARIAMessageTacticalCommandInstructionBuildHash = 1583154856u;

        public const string VOARIAMessageTacticalCommandInstructionSpecial = "VO.ARIA.Message.TacticalCommandInstructionSpecial";
        public const uint VOARIAMessageTacticalCommandInstructionSpecialHash = 3531066851u;

        public const string VOARIAMessageTacticalCommandBoardPromptTransportToPassenger = "VO.ARIA.Message.TacticalCommandBoardPromptTransportToPassenger";
        public const uint VOARIAMessageTacticalCommandBoardPromptTransportToPassengerHash = 4164327806u;

        public const string VOARIAMessageTacticalCommandBoardPromptPassengerToTransport = "VO.ARIA.Message.TacticalCommandBoardPromptPassengerToTransport";
        public const uint VOARIAMessageTacticalCommandBoardPromptPassengerToTransportHash = 626416944u;

        public const string VOARIAMessageTacticalCommandBoardUnavailable = "VO.ARIA.Message.TacticalCommandBoardUnavailable";
        public const uint VOARIAMessageTacticalCommandBoardUnavailableHash = 1010495506u;

        public const string VOARIAMessageTacticalCommandBoardTapUnitsToBoard = "VO.ARIA.Message.TacticalCommandBoardTapUnitsToBoard";
        public const uint VOARIAMessageTacticalCommandBoardTapUnitsToBoardHash = 346118675u;

        public const string VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoard = "VO.ARIA.Message.TacticalCommandBoardSelectedUnitCannotBoard";
        public const uint VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoardHash = 2595310816u;

        public const string VOARIAMessageTacticalCommandBoardSelectUnitFirst = "VO.ARIA.Message.TacticalCommandBoardSelectUnitFirst";
        public const uint VOARIAMessageTacticalCommandBoardSelectUnitFirstHash = 1312855484u;

        public const string VOARIAMessageTacticalCommandUnavailableHoldNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableHoldNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableHoldNoSelectionHash = 3755007230u;

        public const string VOARIAMessageTacticalCommandUnavailableStopNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableStopNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableStopNoSelectionHash = 339702977u;

        public const string VOARIAMessageTacticalCommandUnavailableScanNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableScanNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableScanNoSelectionHash = 1133512018u;

        public const string VOARIAMessageTacticalFeedbackCameraFollowUnavailable = "VO.ARIA.Message.TacticalFeedbackCameraFollowUnavailable";
        public const uint VOARIAMessageTacticalFeedbackCameraFollowUnavailableHash = 3282664940u;

        public const string VOARIAMessageTacticalFeedbackCameraFollowActive = "VO.ARIA.Message.TacticalFeedbackCameraFollowActive";
        public const uint VOARIAMessageTacticalFeedbackCameraFollowActiveHash = 108632900u;

        public const string VOARIAMessageTacticalFeedbackRtsCameraRestored = "VO.ARIA.Message.TacticalFeedbackRtsCameraRestored";
        public const uint VOARIAMessageTacticalFeedbackRtsCameraRestoredHash = 23298754u;

        public const string VOARIAMessageTacticalFeedbackFollowTargetLost = "VO.ARIA.Message.TacticalFeedbackFollowTargetLost";
        public const uint VOARIAMessageTacticalFeedbackFollowTargetLostHash = 1127465702u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedBuilding = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedBuilding";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedBuildingHash = 308779550u;

        public const string VOARIAMessageTacticalFeedbackAirDefenseAutoEngage = "VO.ARIA.Message.TacticalFeedbackAirDefenseAutoEngage";
        public const uint VOARIAMessageTacticalFeedbackAirDefenseAutoEngageHash = 1274052508u;

        public const string VOARIAMessageTacticalFeedbackExitingUnit = "VO.ARIA.Message.TacticalFeedbackExitingUnit";
        public const uint VOARIAMessageTacticalFeedbackExitingUnitHash = 3438748822u;

        public const string VOARIAMessageTacticalFeedbackExitingPassengers = "VO.ARIA.Message.TacticalFeedbackExitingPassengers";
        public const uint VOARIAMessageTacticalFeedbackExitingPassengersHash = 2482898073u;

        public const string VOARIAMessageTacticalFeedbackLoadingTransport = "VO.ARIA.Message.TacticalFeedbackLoadingTransport";
        public const uint VOARIAMessageTacticalFeedbackLoadingTransportHash = 2581984329u;

        public const string VOARIAMessageTacticalFeedbackBoardingTransport = "VO.ARIA.Message.TacticalFeedbackBoardingTransport";
        public const uint VOARIAMessageTacticalFeedbackBoardingTransportHash = 17053981u;

        public const string VOARIAMessageTacticalFeedbackHoldingCurrentPosition = "VO.ARIA.Message.TacticalFeedbackHoldingCurrentPosition";
        public const uint VOARIAMessageTacticalFeedbackHoldingCurrentPositionHash = 1472517519u;

        public const string VOARIAMessageTacticalFeedbackStoppedSelectedUnits = "VO.ARIA.Message.TacticalFeedbackStoppedSelectedUnits";
        public const uint VOARIAMessageTacticalFeedbackStoppedSelectedUnitsHash = 417175199u;

        public const string VOARIAMessageTacticalFeedbackUnitReturningToBase = "VO.ARIA.Message.TacticalFeedbackUnitReturningToBase";
        public const uint VOARIAMessageTacticalFeedbackUnitReturningToBaseHash = 2386725092u;

        public const string VOARIAMessageTacticalFeedbackUnitsReturningToBase = "VO.ARIA.Message.TacticalFeedbackUnitsReturningToBase";
        public const uint VOARIAMessageTacticalFeedbackUnitsReturningToBaseHash = 3885411515u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedUnit = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedUnit";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedUnitHash = 3408293596u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedUnits = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedUnits";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedUnitsHash = 2088779133u;

        public const string VOARIAMessageTacticalFeedbackScanOrdered = "VO.ARIA.Message.TacticalFeedbackScanOrdered";
        public const uint VOARIAMessageTacticalFeedbackScanOrderedHash = 3370429146u;

        public const string VOARIAMessageTacticalFeedbackScanOneContact = "VO.ARIA.Message.TacticalFeedbackScanOneContact";
        public const uint VOARIAMessageTacticalFeedbackScanOneContactHash = 1330041397u;

        public const string VOARIAMessageTacticalFeedbackScanContacts = "VO.ARIA.Message.TacticalFeedbackScanContacts";
        public const uint VOARIAMessageTacticalFeedbackScanContactsHash = 1511448996u;

        public const string VOARIAMessageTacticalFeedbackScanComplete = "VO.ARIA.Message.TacticalFeedbackScanComplete";
        public const uint VOARIAMessageTacticalFeedbackScanCompleteHash = 274538966u;

        public const string VOARIAMessageTacticalFeedbackMissileLaunched = "VO.ARIA.Message.TacticalFeedbackMissileLaunched";
        public const uint VOARIAMessageTacticalFeedbackMissileLaunchedHash = 1883554858u;

        public const string VOARIAMessageTacticalAirdropEmergencyDropVisualMissing = "VO.ARIA.Message.TacticalAirdropEmergencyDropVisualMissing";
        public const uint VOARIAMessageTacticalAirdropEmergencyDropVisualMissingHash = 3899966708u;

        public const string VOARIAMessageTacticalAirdropParachuteVisualMissing = "VO.ARIA.Message.TacticalAirdropParachuteVisualMissing";
        public const uint VOARIAMessageTacticalAirdropParachuteVisualMissingHash = 2041790521u;

        public const string VOARIAMessageTacticalAirdropNoClearLandingZone = "VO.ARIA.Message.TacticalAirdropNoClearLandingZone";
        public const uint VOARIAMessageTacticalAirdropNoClearLandingZoneHash = 2165697149u;

        public const string VOARIAMessageTacticalAirdropCargoDropBlocked = "VO.ARIA.Message.TacticalAirdropCargoDropBlocked";
        public const uint VOARIAMessageTacticalAirdropCargoDropBlockedHash = 1470553003u;

        public const string VOARIAMessageTacticalBannerModeMoveTitle = "VO.ARIA.Message.TacticalBannerModeMoveTitle";
        public const uint VOARIAMessageTacticalBannerModeMoveTitleHash = 271952847u;

        public const string VOARIAMessageTacticalBannerModeMoveDescription = "VO.ARIA.Message.TacticalBannerModeMoveDescription";
        public const uint VOARIAMessageTacticalBannerModeMoveDescriptionHash = 1976093803u;

        public const string VOARIAMessageTacticalBannerModeAttackTitle = "VO.ARIA.Message.TacticalBannerModeAttackTitle";
        public const uint VOARIAMessageTacticalBannerModeAttackTitleHash = 2299946128u;

        public const string VOARIAMessageTacticalBannerModeAttackDescription = "VO.ARIA.Message.TacticalBannerModeAttackDescription";
        public const uint VOARIAMessageTacticalBannerModeAttackDescriptionHash = 833516792u;

        public const string VOARIAMessageTacticalBannerModeScanTitle = "VO.ARIA.Message.TacticalBannerModeScanTitle";
        public const uint VOARIAMessageTacticalBannerModeScanTitleHash = 3264010615u;

        public const string VOARIAMessageTacticalBannerModeScanDescription = "VO.ARIA.Message.TacticalBannerModeScanDescription";
        public const uint VOARIAMessageTacticalBannerModeScanDescriptionHash = 4072862067u;

        public const string VOARIAMessageTacticalBannerModeBoardTitle = "VO.ARIA.Message.TacticalBannerModeBoardTitle";
        public const uint VOARIAMessageTacticalBannerModeBoardTitleHash = 1464553436u;

        public const string VOARIAMessageTacticalBannerModeBoardDescription = "VO.ARIA.Message.TacticalBannerModeBoardDescription";
        public const uint VOARIAMessageTacticalBannerModeBoardDescriptionHash = 3232575468u;

        public const string VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassenger = "VO.ARIA.Message.TacticalBannerModeBoardDescriptionTransportToPassenger";
        public const uint VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassengerHash = 1384777824u;

        public const string VOARIAMessageTacticalBannerModeBuildTitle = "VO.ARIA.Message.TacticalBannerModeBuildTitle";
        public const uint VOARIAMessageTacticalBannerModeBuildTitleHash = 1831091860u;

        public const string VOARIAMessageTacticalBannerModeBuildDescription = "VO.ARIA.Message.TacticalBannerModeBuildDescription";
        public const uint VOARIAMessageTacticalBannerModeBuildDescriptionHash = 4073486884u;

        public const string VOARIAMessageTacticalBannerAcceptedMoveTitle = "VO.ARIA.Message.TacticalBannerAcceptedMoveTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedMoveTitleHash = 984869289u;

        public const string VOARIAMessageTacticalBannerAcceptedMoveDescription = "VO.ARIA.Message.TacticalBannerAcceptedMoveDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedMoveDescriptionHash = 570569225u;

        public const string VOARIAMessageTacticalBannerAcceptedAttackTitle = "VO.ARIA.Message.TacticalBannerAcceptedAttackTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedAttackTitleHash = 2720292082u;

        public const string VOARIAMessageTacticalBannerAcceptedAttackDescription = "VO.ARIA.Message.TacticalBannerAcceptedAttackDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedAttackDescriptionHash = 3264300366u;

        public const string VOARIAMessageTacticalBannerAcceptedHoldTitle = "VO.ARIA.Message.TacticalBannerAcceptedHoldTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedHoldTitleHash = 3583674425u;

        public const string VOARIAMessageTacticalBannerAcceptedHoldDescription = "VO.ARIA.Message.TacticalBannerAcceptedHoldDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedHoldDescriptionHash = 892142297u;

        public const string VOARIAMessageTacticalBannerAcceptedStopTitle = "VO.ARIA.Message.TacticalBannerAcceptedStopTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedStopTitleHash = 649840534u;

        public const string VOARIAMessageTacticalBannerAcceptedStopDescription = "VO.ARIA.Message.TacticalBannerAcceptedStopDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedStopDescriptionHash = 3062344138u;

        public const string VOARIAMessageTacticalBannerAcceptedScanTitle = "VO.ARIA.Message.TacticalBannerAcceptedScanTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedScanTitleHash = 3208314925u;

        public const string VOARIAMessageTacticalBannerAcceptedScanDescription = "VO.ARIA.Message.TacticalBannerAcceptedScanDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedScanDescriptionHash = 1434493125u;

        public const string VOARIAMessageTacticalBannerAcceptedBoardTitle = "VO.ARIA.Message.TacticalBannerAcceptedBoardTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedBoardTitleHash = 1488960574u;

        public const string VOARIAMessageTacticalBannerAcceptedBoardDescription = "VO.ARIA.Message.TacticalBannerAcceptedBoardDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedBoardDescriptionHash = 2460007954u;

        public const string VOARIAMessageTacticalBannerAcceptedBuildTitle = "VO.ARIA.Message.TacticalBannerAcceptedBuildTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedBuildTitleHash = 2171834286u;

        public const string VOARIAMessageTacticalBannerAcceptedBuildDescription = "VO.ARIA.Message.TacticalBannerAcceptedBuildDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedBuildDescriptionHash = 881007938u;

        public const string VOARIAMessageTacticalBannerAcceptedReturnTitle = "VO.ARIA.Message.TacticalBannerAcceptedReturnTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedReturnTitleHash = 1131718632u;

        public const string VOARIAMessageTacticalBannerAcceptedReturnDescription = "VO.ARIA.Message.TacticalBannerAcceptedReturnDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedReturnDescriptionHash = 867428304u;

        public const string VOARIAMessageTacticalBannerAcceptedDestroyTitle = "VO.ARIA.Message.TacticalBannerAcceptedDestroyTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedDestroyTitleHash = 2047513668u;

        public const string VOARIAMessageTacticalBannerAcceptedDestroyDescription = "VO.ARIA.Message.TacticalBannerAcceptedDestroyDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedDestroyDescriptionHash = 3571275540u;

        public const string VOARIAMessageBuildDrawerEmptyName = "VO.ARIA.Message.BuildDrawerEmptyName";
        public const uint VOARIAMessageBuildDrawerEmptyNameHash = 3266764183u;

        public const string VOARIAMessageBuildDrawerReadyBuildings = "VO.ARIA.Message.BuildDrawerReadyBuildings";
        public const uint VOARIAMessageBuildDrawerReadyBuildingsHash = 1462777963u;

        public const string VOARIAMessageBuildDrawerReadyVehicles = "VO.ARIA.Message.BuildDrawerReadyVehicles";
        public const uint VOARIAMessageBuildDrawerReadyVehiclesHash = 385761459u;

        public const string VOARIAMessageBuildDrawerReadyAircraft = "VO.ARIA.Message.BuildDrawerReadyAircraft";
        public const uint VOARIAMessageBuildDrawerReadyAircraftHash = 101178724u;

        public const string VOARIAMessageBuildDrawerReadySoldiers = "VO.ARIA.Message.BuildDrawerReadySoldiers";
        public const uint VOARIAMessageBuildDrawerReadySoldiersHash = 7975065u;

        public const string VOARIAMessageBuildDrawerReadyDefault = "VO.ARIA.Message.BuildDrawerReadyDefault";
        public const uint VOARIAMessageBuildDrawerReadyDefaultHash = 2147982739u;

        public const string VOARIAMessageBuildDrawerInstructionPlacePendingConfirm = "VO.ARIA.Message.BuildDrawerInstructionPlacePendingConfirm";
        public const uint VOARIAMessageBuildDrawerInstructionPlacePendingConfirmHash = 2891047625u;

        public const string VOARIAMessageBuildDrawerInstructionCannotPlaceHere = "VO.ARIA.Message.BuildDrawerInstructionCannotPlaceHere";
        public const uint VOARIAMessageBuildDrawerInstructionCannotPlaceHereHash = 626012179u;

        public const string VOARIAMessageBuildDrawerFailureConnecting = "VO.ARIA.Message.BuildDrawerFailureConnecting";
        public const uint VOARIAMessageBuildDrawerFailureConnectingHash = 3062397965u;

        public const string VOARIAMessageBuildDrawerFailureNotEnoughMoney = "VO.ARIA.Message.BuildDrawerFailureNotEnoughMoney";
        public const uint VOARIAMessageBuildDrawerFailureNotEnoughMoneyHash = 3026994208u;

        public const string VOARIAMessageBuildDrawerFailureMissingProducerNamed = "VO.ARIA.Message.BuildDrawerFailureMissingProducerNamed";
        public const uint VOARIAMessageBuildDrawerFailureMissingProducerNamedHash = 262295072u;

        public const string VOARIAMessageBuildDrawerFailureMissingProducer = "VO.ARIA.Message.BuildDrawerFailureMissingProducer";
        public const uint VOARIAMessageBuildDrawerFailureMissingProducerHash = 2289244967u;

        public const string VOARIAMessageBuildDrawerFailureQueueFullNamed = "VO.ARIA.Message.BuildDrawerFailureQueueFullNamed";
        public const uint VOARIAMessageBuildDrawerFailureQueueFullNamedHash = 1859404272u;

        public const string VOARIAMessageBuildDrawerFailureQueueFull = "VO.ARIA.Message.BuildDrawerFailureQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureQueueFullHash = 1539003479u;

        public const string VOARIAMessageBuildDrawerFailureGlobalQueueFull = "VO.ARIA.Message.BuildDrawerFailureGlobalQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureGlobalQueueFullHash = 113904958u;

        public const string VOARIAMessageBuildDrawerFailureInvalidSelection = "VO.ARIA.Message.BuildDrawerFailureInvalidSelection";
        public const uint VOARIAMessageBuildDrawerFailureInvalidSelectionHash = 1375188920u;

        public const string VOARIAMessageBuildDrawerFailureUnavailable = "VO.ARIA.Message.BuildDrawerFailureUnavailable";
        public const uint VOARIAMessageBuildDrawerFailureUnavailableHash = 50900467u;

        public const string VOARIAMessageBuildDrawerFailureShortNotEnoughMoney = "VO.ARIA.Message.BuildDrawerFailureShortNotEnoughMoney";
        public const uint VOARIAMessageBuildDrawerFailureShortNotEnoughMoneyHash = 1771510712u;

        public const string VOARIAMessageBuildDrawerFailureShortRequiresNamed = "VO.ARIA.Message.BuildDrawerFailureShortRequiresNamed";
        public const uint VOARIAMessageBuildDrawerFailureShortRequiresNamedHash = 1283132284u;

        public const string VOARIAMessageBuildDrawerFailureShortMissingProducer = "VO.ARIA.Message.BuildDrawerFailureShortMissingProducer";
        public const uint VOARIAMessageBuildDrawerFailureShortMissingProducerHash = 4083487215u;

        public const string VOARIAMessageBuildDrawerFailureShortQueueFullNamed = "VO.ARIA.Message.BuildDrawerFailureShortQueueFullNamed";
        public const uint VOARIAMessageBuildDrawerFailureShortQueueFullNamedHash = 2091502008u;

        public const string VOARIAMessageBuildDrawerFailureShortQueueFull = "VO.ARIA.Message.BuildDrawerFailureShortQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureShortQueueFullHash = 1386062895u;

        public const string VOARIAMessageBuildDrawerFailureShortGlobalQueueFull = "VO.ARIA.Message.BuildDrawerFailureShortGlobalQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureShortGlobalQueueFullHash = 4040988550u;

        public const string VOARIAMessageBuildDrawerFailureShortUnavailable = "VO.ARIA.Message.BuildDrawerFailureShortUnavailable";
        public const uint VOARIAMessageBuildDrawerFailureShortUnavailableHash = 2077498219u;

        public const string VOARIAMessageBuildDrawerEmptyBuildings = "VO.ARIA.Message.BuildDrawerEmptyBuildings";
        public const uint VOARIAMessageBuildDrawerEmptyBuildingsHash = 3037375901u;

        public const string VOARIAMessageBuildDrawerEmptyVehicles = "VO.ARIA.Message.BuildDrawerEmptyVehicles";
        public const uint VOARIAMessageBuildDrawerEmptyVehiclesHash = 1033832213u;

        public const string VOARIAMessageBuildDrawerEmptyAircraft = "VO.ARIA.Message.BuildDrawerEmptyAircraft";
        public const uint VOARIAMessageBuildDrawerEmptyAircraftHash = 4166792890u;

        public const string VOARIAMessageBuildDrawerEmptySoldiers = "VO.ARIA.Message.BuildDrawerEmptySoldiers";
        public const uint VOARIAMessageBuildDrawerEmptySoldiersHash = 686826671u;

        public const string VOARIAMessageBuildDrawerEmptyDefault = "VO.ARIA.Message.BuildDrawerEmptyDefault";
        public const uint VOARIAMessageBuildDrawerEmptyDefaultHash = 4059349457u;

        public const string VOARIAMessageBuildDrawerEmptySelectItem = "VO.ARIA.Message.BuildDrawerEmptySelectItem";
        public const uint VOARIAMessageBuildDrawerEmptySelectItemHash = 2485650491u;

        public const string VOARIAMessageBuildDrawerPlacementInvalid = "VO.ARIA.Message.BuildDrawerPlacementInvalid";
        public const uint VOARIAMessageBuildDrawerPlacementInvalidHash = 836185597u;

        public const string VOARIAMessageBuildDrawerActionPlaceChooseFootprint = "VO.ARIA.Message.BuildDrawerActionPlaceChooseFootprint";
        public const uint VOARIAMessageBuildDrawerActionPlaceChooseFootprintHash = 299330988u;

        public const string VOARIAMessageBuildFeedbackPlaceBuilding = "VO.ARIA.Message.BuildFeedbackPlaceBuilding";
        public const uint VOARIAMessageBuildFeedbackPlaceBuildingHash = 947653148u;

        public const string VOARIAMessageBuildFeedbackProductionRequested = "VO.ARIA.Message.BuildFeedbackProductionRequested";
        public const uint VOARIAMessageBuildFeedbackProductionRequestedHash = 1032952502u;

        public const string VOARIAMessageBuildDrawerSuccessRecruitmentQueued = "VO.ARIA.Message.BuildDrawerSuccessRecruitmentQueued";
        public const uint VOARIAMessageBuildDrawerSuccessRecruitmentQueuedHash = 2087371149u;

        public const string VOARIAMessageBuildDrawerSuccessProductionQueued = "VO.ARIA.Message.BuildDrawerSuccessProductionQueued";
        public const uint VOARIAMessageBuildDrawerSuccessProductionQueuedHash = 4228330360u;

        public const string VOARIAMessageBuildFeedbackProductionCancelUnavailable = "VO.ARIA.Message.BuildFeedbackProductionCancelUnavailable";
        public const uint VOARIAMessageBuildFeedbackProductionCancelUnavailableHash = 1676707042u;

        public const string VOARIAMessageBuildFeedbackProductionCancelledNamed = "VO.ARIA.Message.BuildFeedbackProductionCancelledNamed";
        public const uint VOARIAMessageBuildFeedbackProductionCancelledNamedHash = 1006425134u;

        public const string VOARIAMessageBuildFeedbackProductionCancelled = "VO.ARIA.Message.BuildFeedbackProductionCancelled";
        public const uint VOARIAMessageBuildFeedbackProductionCancelledHash = 3728128669u;

        public const string VOARIAMessageBuildFeedbackProductionQueueEmpty = "VO.ARIA.Message.BuildFeedbackProductionQueueEmpty";
        public const uint VOARIAMessageBuildFeedbackProductionQueueEmptyHash = 294008646u;

        public const string VOARIAMessageBuildFeedbackProductionQueueClearedSentence = "VO.ARIA.Message.BuildFeedbackProductionQueueClearedSentence";
        public const uint VOARIAMessageBuildFeedbackProductionQueueClearedSentenceHash = 1114836450u;

        public const string VOARIAMessageBuildFeedbackProductionClearUnavailable = "VO.ARIA.Message.BuildFeedbackProductionClearUnavailable";
        public const uint VOARIAMessageBuildFeedbackProductionClearUnavailableHash = 983282855u;

        public const string VOARIAMessageBuildFeedbackProductionQueueCleared = "VO.ARIA.Message.BuildFeedbackProductionQueueCleared";
        public const uint VOARIAMessageBuildFeedbackProductionQueueClearedHash = 1354436635u;

        public const string VOARIAMessageBuildFeedbackPlacementCancelled = "VO.ARIA.Message.BuildFeedbackPlacementCancelled";
        public const uint VOARIAMessageBuildFeedbackPlacementCancelledHash = 782457683u;

        public const string VOARIAMessageBuildFeedbackRotated90 = "VO.ARIA.Message.BuildFeedbackRotated90";
        public const uint VOARIAMessageBuildFeedbackRotated90Hash = 3407979195u;

        public const string VOARIAMessageBuildFeedbackNoActivePlacement = "VO.ARIA.Message.BuildFeedbackNoActivePlacement";
        public const uint VOARIAMessageBuildFeedbackNoActivePlacementHash = 610169931u;

        public const string VOARIAMessageBuildFeedbackBuildingPlaced = "VO.ARIA.Message.BuildFeedbackBuildingPlaced";
        public const uint VOARIAMessageBuildFeedbackBuildingPlacedHash = 3914499800u;

        public const string VOARIAMessageBuildFeedbackPlaceOnValidGround = "VO.ARIA.Message.BuildFeedbackPlaceOnValidGround";
        public const uint VOARIAMessageBuildFeedbackPlaceOnValidGroundHash = 3633500962u;

        public const string VOARIAMessageBuildFeedbackDrawerNotReady = "VO.ARIA.Message.BuildFeedbackDrawerNotReady";
        public const uint VOARIAMessageBuildFeedbackDrawerNotReadyHash = 278832520u;

        public const string VOARIAMessageBuildPlacementStatusDragToPosition = "VO.ARIA.Message.BuildPlacementStatusDragToPosition";
        public const uint VOARIAMessageBuildPlacementStatusDragToPositionHash = 222977931u;

        public const string VOARIAMessageBuildPlacementStatusValidGround = "VO.ARIA.Message.BuildPlacementStatusValidGround";
        public const uint VOARIAMessageBuildPlacementStatusValidGroundHash = 2317288360u;

        public const string VOARIAMessageBuildPlacementTitleDefault = "VO.ARIA.Message.BuildPlacementTitleDefault";
        public const uint VOARIAMessageBuildPlacementTitleDefaultHash = 3370741470u;

        public const string VOARIAMessageBuildPlacementTitleNamed = "VO.ARIA.Message.BuildPlacementTitleNamed";
        public const uint VOARIAMessageBuildPlacementTitleNamedHash = 3856821926u;

        public const string VOARIAMessageBuildPlacementInstructionConfirm = "VO.ARIA.Message.BuildPlacementInstructionConfirm";
        public const uint VOARIAMessageBuildPlacementInstructionConfirmHash = 856648861u;

        public const string VOARIAMessageBuildPlacementTitleFallbackSubject = "VO.ARIA.Message.BuildPlacementTitleFallbackSubject";
        public const uint VOARIAMessageBuildPlacementTitleFallbackSubjectHash = 2345630073u;

        public const string VOARIAMessageMatchFeedbackTacticalMapNotReady = "VO.ARIA.Message.MatchFeedbackTacticalMapNotReady";
        public const uint VOARIAMessageMatchFeedbackTacticalMapNotReadyHash = 2536600289u;

        public const string VOARIAMessageMatchFeedbackBlockedCivilianZone = "VO.ARIA.Message.MatchFeedbackBlockedCivilianZone";
        public const uint VOARIAMessageMatchFeedbackBlockedCivilianZoneHash = 3153755251u;

        public const string VOARIAMessageSelectionFeedbackUnitSingular = "VO.ARIA.Message.SelectionFeedbackUnitSingular";
        public const uint VOARIAMessageSelectionFeedbackUnitSingularHash = 3735698480u;

        public const string VOARIAMessageSelectionFeedbackUnitPlural = "VO.ARIA.Message.SelectionFeedbackUnitPlural";
        public const uint VOARIAMessageSelectionFeedbackUnitPluralHash = 1693056703u;

        public const string VOARIAMessageSelectionFeedbackVehicleSingular = "VO.ARIA.Message.SelectionFeedbackVehicleSingular";
        public const uint VOARIAMessageSelectionFeedbackVehicleSingularHash = 2754198088u;

        public const string VOARIAMessageSelectionFeedbackSoldierSingular = "VO.ARIA.Message.SelectionFeedbackSoldierSingular";
        public const uint VOARIAMessageSelectionFeedbackSoldierSingularHash = 17882658u;

        public const string VOARIAMessageSelectionFeedbackSquadCount = "VO.ARIA.Message.SelectionFeedbackSquadCount";
        public const uint VOARIAMessageSelectionFeedbackSquadCountHash = 2585327106u;

        public const string VOARIAMessageSelectionFeedbackSquadSelected = "VO.ARIA.Message.SelectionFeedbackSquadSelected";
        public const uint VOARIAMessageSelectionFeedbackSquadSelectedHash = 2821846162u;

        public const string VOARIATutorialM01FindSquadEn = "VO.ARIA.Tutorial.M01.FindSquad.En";
        public const uint VOARIATutorialM01FindSquadEnHash = 4073964257u;

        public const string VOARIATutorialM01MoveToCoverEn = "VO.ARIA.Tutorial.M01.MoveToCover.En";
        public const uint VOARIATutorialM01MoveToCoverEnHash = 2083846237u;

        public const string VOARIATutorialM01MoveDestinationEn = "VO.ARIA.Tutorial.M01.MoveDestination.En";
        public const uint VOARIATutorialM01MoveDestinationEnHash = 3570977129u;

        public const string VOARIATutorialM01ConfirmThreatEn = "VO.ARIA.Tutorial.M01.ConfirmThreat.En";
        public const uint VOARIATutorialM01ConfirmThreatEnHash = 383473216u;

        public const string VOARIATutorialM01EngageEn = "VO.ARIA.Tutorial.M01.Engage.En";
        public const uint VOARIATutorialM01EngageEnHash = 29346487u;

        public const string VOARIATutorialM01AttackTargetEn = "VO.ARIA.Tutorial.M01.AttackTarget.En";
        public const uint VOARIATutorialM01AttackTargetEnHash = 3897856629u;

        public const string VOARIATutorialM01SecureCorridorEn = "VO.ARIA.Tutorial.M01.SecureCorridor.En";
        public const uint VOARIATutorialM01SecureCorridorEnHash = 2058127915u;

        public const string VOARIATutorialM01FindSquadFa = "VO.ARIA.Tutorial.M01.FindSquad.Fa";
        public const uint VOARIATutorialM01FindSquadFaHash = 4224521543u;

        public const string VOARIATutorialM01MoveToCoverFa = "VO.ARIA.Tutorial.M01.MoveToCover.Fa";
        public const uint VOARIATutorialM01MoveToCoverFaHash = 2100079403u;

        public const string VOARIATutorialM01MoveDestinationFa = "VO.ARIA.Tutorial.M01.MoveDestination.Fa";
        public const uint VOARIATutorialM01MoveDestinationFaHash = 2916208703u;

        public const string VOARIATutorialM01ConfirmThreatFa = "VO.ARIA.Tutorial.M01.ConfirmThreat.Fa";
        public const uint VOARIATutorialM01ConfirmThreatFaHash = 1037653262u;

        public const string VOARIATutorialM01EngageFa = "VO.ARIA.Tutorial.M01.Engage.Fa";
        public const uint VOARIATutorialM01EngageFaHash = 516044533u;

        public const string VOARIATutorialM01AttackTargetFa = "VO.ARIA.Tutorial.M01.AttackTarget.Fa";
        public const uint VOARIATutorialM01AttackTargetFaHash = 3108867251u;

        public const string VOARIATutorialM01SecureCorridorFa = "VO.ARIA.Tutorial.M01.SecureCorridor.Fa";
        public const uint VOARIATutorialM01SecureCorridorFaHash = 2679046913u;

        public static readonly string[] AllEventIds =
        {
            UIButtonPrimaryClick,
            UIButtonSecondaryClick,
            UIButtonNegativeClick,
            UIButtonDisabledTap,
            UITabSelect,
            UICardSelect,
            UICardLocked,
            UIPopupOpen,
            UIPopupClose,
            UIScreenForward,
            UIScreenBack,
            UIDrawerOpen,
            UIDrawerClose,
            UISliderTick,
            UIToggleOn,
            UIToggleOff,
            UIFeedbackToastError,
            UIFeedbackToastPositive,
            GameplayUnitSelectInfantry,
            GameplayUnitSelectVehicle,
            GameplayUnitSelectAir,
            GameplayUnitEngineVehicleMove,
            GameplayUnitEngineAircraftTakeoff,
            GameplayUnitEngineAircraftFlight,
            GameplayUnitEngineHelicopterFlight,
            GameplayWeaponFireSmallArms,
            GameplayWeaponMissileImpact,
            GameplayCommandMoveAccepted,
            GameplayCommandAttackAccepted,
            GameplayCommandHoldAccepted,
            GameplayCommandStopReturning,
            GameplayCommandScanTargeting,
            GameplayCommandScanAccepted,
            GameplayCommandRejected,
            GameplayBuildPlaceValid,
            GameplayBuildPlaceInvalid,
            GameplayProductionQueued,
            GameplayProductionComplete,
            GameplayResourceExchangeAccepted,
            GameplayResourceExchangeRejected,
            GameplayResourceExchangeQueueStarted,
            GameplayResourceExchangeRushed,
            GameplayResourceExchangeCompleted,
            GameplayResourceExchangeCancelled,
            GameplayWeaponRifleFire,
            GameplayWeaponVehicleCannonFire,
            GameplayWeaponMissileLaunch,
            GameplayWeaponAirMissileLaunch,
            GameplayWeaponMissileFlight,
            GameplayUnitAircraftFlyby,
            GameplayUnitVehicleEngine,
            GameplayImpactBullet,
            GameplayExplosionSmall,
            GameplayExplosionLarge,
            GameplayUnitVehicleDestroyed,
            AlertThreatMinor,
            AlertThreatCritical,
            AlertUnitUnderAttack,
            AlertBaseBreached,
            GameplayObjectiveProgress,
            GameplayObjectiveComplete,
            GameplayObjectiveFailed,
            MusicSplashIntro,
            MusicMenuLoop,
            MusicBriefingLoop,
            MusicMatchCalmLoop,
            MusicMatchCombatLoop,
            MusicResultVictory,
            MusicResultDefeat,
            AmbienceCityDayLoop,
            AmbienceBaseDistantLoop,
            VOARIAMessageConfirmDestroy,
            VOARIAMessageNotEnoughMoney,
            VOARIAMessageCreateFirst,
            VOARIAMessageDragBuildingToFinalPosition,
            VOARIAMessageWarningGroundAttackType,
            VOARIAMessageWarningAirAttackType,
            VOARIAMessageWarningAttackEtaSeconds,
            VOARIAMessageWarningAttackEtaSuffix,
            VOARIAMessageWarningAttackCountSuffix,
            VOARIAMessageTacticalCommandReasonNoSelection,
            VOARIAMessageTacticalCommandReasonTargetOutOfBounds,
            VOARIAMessageTacticalCommandReasonTargetBlocked,
            VOARIAMessageTacticalCommandReasonTargetUnreachable,
            VOARIAMessageTacticalCommandReasonTargetNotEnemy,
            VOARIAMessageTacticalCommandReasonTargetNotAttackable,
            VOARIAMessageTacticalCommandReasonCommandUnavailable,
            VOARIAMessageTacticalCommandReasonBuildUnavailable,
            VOARIAMessageTacticalCommandReasonCameraJumpUnavailable,
            VOARIAMessageTacticalCommandReasonScanUnavailable,
            VOARIAMessageTacticalCommandReasonScanCooldown,
            VOARIAMessageTacticalCommandReasonInsufficientResources,
            VOARIAMessageTacticalCommandReasonInsufficientFuel,
            VOARIAMessageTacticalCommandReasonInvalidTransport,
            VOARIAMessageTacticalCommandReasonInvalidPassenger,
            VOARIAMessageTacticalCommandReasonTransportFull,
            VOARIAMessageTacticalCommandReasonNoEligiblePassengers,
            VOARIAMessageTacticalCommandReasonNoDisembarkCell,
            VOARIAMessageTacticalCommandReasonTransportPassengerMissing,
            VOARIAMessageTacticalCommandInstructionSelect,
            VOARIAMessageTacticalCommandInstructionMove,
            VOARIAMessageTacticalCommandInstructionAttack,
            VOARIAMessageTacticalCommandInstructionHold,
            VOARIAMessageTacticalCommandInstructionStop,
            VOARIAMessageTacticalCommandInstructionScan,
            VOARIAMessageTacticalCommandInstructionBoard,
            VOARIAMessageTacticalCommandInstructionBuild,
            VOARIAMessageTacticalCommandInstructionSpecial,
            VOARIAMessageTacticalCommandBoardPromptTransportToPassenger,
            VOARIAMessageTacticalCommandBoardPromptPassengerToTransport,
            VOARIAMessageTacticalCommandBoardUnavailable,
            VOARIAMessageTacticalCommandBoardTapUnitsToBoard,
            VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoard,
            VOARIAMessageTacticalCommandBoardSelectUnitFirst,
            VOARIAMessageTacticalCommandUnavailableHoldNoSelection,
            VOARIAMessageTacticalCommandUnavailableStopNoSelection,
            VOARIAMessageTacticalCommandUnavailableScanNoSelection,
            VOARIAMessageTacticalFeedbackCameraFollowUnavailable,
            VOARIAMessageTacticalFeedbackCameraFollowActive,
            VOARIAMessageTacticalFeedbackRtsCameraRestored,
            VOARIAMessageTacticalFeedbackFollowTargetLost,
            VOARIAMessageTacticalFeedbackDestroyedSelectedBuilding,
            VOARIAMessageTacticalFeedbackAirDefenseAutoEngage,
            VOARIAMessageTacticalFeedbackExitingUnit,
            VOARIAMessageTacticalFeedbackExitingPassengers,
            VOARIAMessageTacticalFeedbackLoadingTransport,
            VOARIAMessageTacticalFeedbackBoardingTransport,
            VOARIAMessageTacticalFeedbackHoldingCurrentPosition,
            VOARIAMessageTacticalFeedbackStoppedSelectedUnits,
            VOARIAMessageTacticalFeedbackUnitReturningToBase,
            VOARIAMessageTacticalFeedbackUnitsReturningToBase,
            VOARIAMessageTacticalFeedbackDestroyedSelectedUnit,
            VOARIAMessageTacticalFeedbackDestroyedSelectedUnits,
            VOARIAMessageTacticalFeedbackScanOrdered,
            VOARIAMessageTacticalFeedbackScanOneContact,
            VOARIAMessageTacticalFeedbackScanContacts,
            VOARIAMessageTacticalFeedbackScanComplete,
            VOARIAMessageTacticalFeedbackMissileLaunched,
            VOARIAMessageTacticalAirdropEmergencyDropVisualMissing,
            VOARIAMessageTacticalAirdropParachuteVisualMissing,
            VOARIAMessageTacticalAirdropNoClearLandingZone,
            VOARIAMessageTacticalAirdropCargoDropBlocked,
            VOARIAMessageTacticalBannerModeMoveTitle,
            VOARIAMessageTacticalBannerModeMoveDescription,
            VOARIAMessageTacticalBannerModeAttackTitle,
            VOARIAMessageTacticalBannerModeAttackDescription,
            VOARIAMessageTacticalBannerModeScanTitle,
            VOARIAMessageTacticalBannerModeScanDescription,
            VOARIAMessageTacticalBannerModeBoardTitle,
            VOARIAMessageTacticalBannerModeBoardDescription,
            VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassenger,
            VOARIAMessageTacticalBannerModeBuildTitle,
            VOARIAMessageTacticalBannerModeBuildDescription,
            VOARIAMessageTacticalBannerAcceptedMoveTitle,
            VOARIAMessageTacticalBannerAcceptedMoveDescription,
            VOARIAMessageTacticalBannerAcceptedAttackTitle,
            VOARIAMessageTacticalBannerAcceptedAttackDescription,
            VOARIAMessageTacticalBannerAcceptedHoldTitle,
            VOARIAMessageTacticalBannerAcceptedHoldDescription,
            VOARIAMessageTacticalBannerAcceptedStopTitle,
            VOARIAMessageTacticalBannerAcceptedStopDescription,
            VOARIAMessageTacticalBannerAcceptedScanTitle,
            VOARIAMessageTacticalBannerAcceptedScanDescription,
            VOARIAMessageTacticalBannerAcceptedBoardTitle,
            VOARIAMessageTacticalBannerAcceptedBoardDescription,
            VOARIAMessageTacticalBannerAcceptedBuildTitle,
            VOARIAMessageTacticalBannerAcceptedBuildDescription,
            VOARIAMessageTacticalBannerAcceptedReturnTitle,
            VOARIAMessageTacticalBannerAcceptedReturnDescription,
            VOARIAMessageTacticalBannerAcceptedDestroyTitle,
            VOARIAMessageTacticalBannerAcceptedDestroyDescription,
            VOARIAMessageBuildDrawerEmptyName,
            VOARIAMessageBuildDrawerReadyBuildings,
            VOARIAMessageBuildDrawerReadyVehicles,
            VOARIAMessageBuildDrawerReadyAircraft,
            VOARIAMessageBuildDrawerReadySoldiers,
            VOARIAMessageBuildDrawerReadyDefault,
            VOARIAMessageBuildDrawerInstructionPlacePendingConfirm,
            VOARIAMessageBuildDrawerInstructionCannotPlaceHere,
            VOARIAMessageBuildDrawerFailureConnecting,
            VOARIAMessageBuildDrawerFailureNotEnoughMoney,
            VOARIAMessageBuildDrawerFailureMissingProducerNamed,
            VOARIAMessageBuildDrawerFailureMissingProducer,
            VOARIAMessageBuildDrawerFailureQueueFullNamed,
            VOARIAMessageBuildDrawerFailureQueueFull,
            VOARIAMessageBuildDrawerFailureGlobalQueueFull,
            VOARIAMessageBuildDrawerFailureInvalidSelection,
            VOARIAMessageBuildDrawerFailureUnavailable,
            VOARIAMessageBuildDrawerFailureShortNotEnoughMoney,
            VOARIAMessageBuildDrawerFailureShortRequiresNamed,
            VOARIAMessageBuildDrawerFailureShortMissingProducer,
            VOARIAMessageBuildDrawerFailureShortQueueFullNamed,
            VOARIAMessageBuildDrawerFailureShortQueueFull,
            VOARIAMessageBuildDrawerFailureShortGlobalQueueFull,
            VOARIAMessageBuildDrawerFailureShortUnavailable,
            VOARIAMessageBuildDrawerEmptyBuildings,
            VOARIAMessageBuildDrawerEmptyVehicles,
            VOARIAMessageBuildDrawerEmptyAircraft,
            VOARIAMessageBuildDrawerEmptySoldiers,
            VOARIAMessageBuildDrawerEmptyDefault,
            VOARIAMessageBuildDrawerEmptySelectItem,
            VOARIAMessageBuildDrawerPlacementInvalid,
            VOARIAMessageBuildDrawerActionPlaceChooseFootprint,
            VOARIAMessageBuildFeedbackPlaceBuilding,
            VOARIAMessageBuildFeedbackProductionRequested,
            VOARIAMessageBuildDrawerSuccessRecruitmentQueued,
            VOARIAMessageBuildDrawerSuccessProductionQueued,
            VOARIAMessageBuildFeedbackProductionCancelUnavailable,
            VOARIAMessageBuildFeedbackProductionCancelledNamed,
            VOARIAMessageBuildFeedbackProductionCancelled,
            VOARIAMessageBuildFeedbackProductionQueueEmpty,
            VOARIAMessageBuildFeedbackProductionQueueClearedSentence,
            VOARIAMessageBuildFeedbackProductionClearUnavailable,
            VOARIAMessageBuildFeedbackProductionQueueCleared,
            VOARIAMessageBuildFeedbackPlacementCancelled,
            VOARIAMessageBuildFeedbackRotated90,
            VOARIAMessageBuildFeedbackNoActivePlacement,
            VOARIAMessageBuildFeedbackBuildingPlaced,
            VOARIAMessageBuildFeedbackPlaceOnValidGround,
            VOARIAMessageBuildFeedbackDrawerNotReady,
            VOARIAMessageBuildPlacementStatusDragToPosition,
            VOARIAMessageBuildPlacementStatusValidGround,
            VOARIAMessageBuildPlacementTitleDefault,
            VOARIAMessageBuildPlacementTitleNamed,
            VOARIAMessageBuildPlacementInstructionConfirm,
            VOARIAMessageBuildPlacementTitleFallbackSubject,
            VOARIAMessageMatchFeedbackTacticalMapNotReady,
            VOARIAMessageMatchFeedbackBlockedCivilianZone,
            VOARIAMessageSelectionFeedbackUnitSingular,
            VOARIAMessageSelectionFeedbackUnitPlural,
            VOARIAMessageSelectionFeedbackVehicleSingular,
            VOARIAMessageSelectionFeedbackSoldierSingular,
            VOARIAMessageSelectionFeedbackSquadCount,
            VOARIAMessageSelectionFeedbackSquadSelected,
            VOARIATutorialM01FindSquadEn,
            VOARIATutorialM01MoveToCoverEn,
            VOARIATutorialM01MoveDestinationEn,
            VOARIATutorialM01ConfirmThreatEn,
            VOARIATutorialM01EngageEn,
            VOARIATutorialM01AttackTargetEn,
            VOARIATutorialM01SecureCorridorEn,
            VOARIATutorialM01FindSquadFa,
            VOARIATutorialM01MoveToCoverFa,
            VOARIATutorialM01MoveDestinationFa,
            VOARIATutorialM01ConfirmThreatFa,
            VOARIATutorialM01EngageFa,
            VOARIATutorialM01AttackTargetFa,
            VOARIATutorialM01SecureCorridorFa,
        };

        public static readonly uint[] AllEventHashes =
        {
            UIButtonPrimaryClickHash,
            UIButtonSecondaryClickHash,
            UIButtonNegativeClickHash,
            UIButtonDisabledTapHash,
            UITabSelectHash,
            UICardSelectHash,
            UICardLockedHash,
            UIPopupOpenHash,
            UIPopupCloseHash,
            UIScreenForwardHash,
            UIScreenBackHash,
            UIDrawerOpenHash,
            UIDrawerCloseHash,
            UISliderTickHash,
            UIToggleOnHash,
            UIToggleOffHash,
            UIFeedbackToastErrorHash,
            UIFeedbackToastPositiveHash,
            GameplayUnitSelectInfantryHash,
            GameplayUnitSelectVehicleHash,
            GameplayUnitSelectAirHash,
            GameplayUnitEngineVehicleMoveHash,
            GameplayUnitEngineAircraftTakeoffHash,
            GameplayUnitEngineAircraftFlightHash,
            GameplayUnitEngineHelicopterFlightHash,
            GameplayWeaponFireSmallArmsHash,
            GameplayWeaponMissileImpactHash,
            GameplayCommandMoveAcceptedHash,
            GameplayCommandAttackAcceptedHash,
            GameplayCommandHoldAcceptedHash,
            GameplayCommandStopReturningHash,
            GameplayCommandScanTargetingHash,
            GameplayCommandScanAcceptedHash,
            GameplayCommandRejectedHash,
            GameplayBuildPlaceValidHash,
            GameplayBuildPlaceInvalidHash,
            GameplayProductionQueuedHash,
            GameplayProductionCompleteHash,
            GameplayResourceExchangeAcceptedHash,
            GameplayResourceExchangeRejectedHash,
            GameplayResourceExchangeQueueStartedHash,
            GameplayResourceExchangeRushedHash,
            GameplayResourceExchangeCompletedHash,
            GameplayResourceExchangeCancelledHash,
            GameplayWeaponRifleFireHash,
            GameplayWeaponVehicleCannonFireHash,
            GameplayWeaponMissileLaunchHash,
            GameplayWeaponAirMissileLaunchHash,
            GameplayWeaponMissileFlightHash,
            GameplayUnitAircraftFlybyHash,
            GameplayUnitVehicleEngineHash,
            GameplayImpactBulletHash,
            GameplayExplosionSmallHash,
            GameplayExplosionLargeHash,
            GameplayUnitVehicleDestroyedHash,
            AlertThreatMinorHash,
            AlertThreatCriticalHash,
            AlertUnitUnderAttackHash,
            AlertBaseBreachedHash,
            GameplayObjectiveProgressHash,
            GameplayObjectiveCompleteHash,
            GameplayObjectiveFailedHash,
            MusicSplashIntroHash,
            MusicMenuLoopHash,
            MusicBriefingLoopHash,
            MusicMatchCalmLoopHash,
            MusicMatchCombatLoopHash,
            MusicResultVictoryHash,
            MusicResultDefeatHash,
            AmbienceCityDayLoopHash,
            AmbienceBaseDistantLoopHash,
            VOARIAMessageConfirmDestroyHash,
            VOARIAMessageNotEnoughMoneyHash,
            VOARIAMessageCreateFirstHash,
            VOARIAMessageDragBuildingToFinalPositionHash,
            VOARIAMessageWarningGroundAttackTypeHash,
            VOARIAMessageWarningAirAttackTypeHash,
            VOARIAMessageWarningAttackEtaSecondsHash,
            VOARIAMessageWarningAttackEtaSuffixHash,
            VOARIAMessageWarningAttackCountSuffixHash,
            VOARIAMessageTacticalCommandReasonNoSelectionHash,
            VOARIAMessageTacticalCommandReasonTargetOutOfBoundsHash,
            VOARIAMessageTacticalCommandReasonTargetBlockedHash,
            VOARIAMessageTacticalCommandReasonTargetUnreachableHash,
            VOARIAMessageTacticalCommandReasonTargetNotEnemyHash,
            VOARIAMessageTacticalCommandReasonTargetNotAttackableHash,
            VOARIAMessageTacticalCommandReasonCommandUnavailableHash,
            VOARIAMessageTacticalCommandReasonBuildUnavailableHash,
            VOARIAMessageTacticalCommandReasonCameraJumpUnavailableHash,
            VOARIAMessageTacticalCommandReasonScanUnavailableHash,
            VOARIAMessageTacticalCommandReasonScanCooldownHash,
            VOARIAMessageTacticalCommandReasonInsufficientResourcesHash,
            VOARIAMessageTacticalCommandReasonInsufficientFuelHash,
            VOARIAMessageTacticalCommandReasonInvalidTransportHash,
            VOARIAMessageTacticalCommandReasonInvalidPassengerHash,
            VOARIAMessageTacticalCommandReasonTransportFullHash,
            VOARIAMessageTacticalCommandReasonNoEligiblePassengersHash,
            VOARIAMessageTacticalCommandReasonNoDisembarkCellHash,
            VOARIAMessageTacticalCommandReasonTransportPassengerMissingHash,
            VOARIAMessageTacticalCommandInstructionSelectHash,
            VOARIAMessageTacticalCommandInstructionMoveHash,
            VOARIAMessageTacticalCommandInstructionAttackHash,
            VOARIAMessageTacticalCommandInstructionHoldHash,
            VOARIAMessageTacticalCommandInstructionStopHash,
            VOARIAMessageTacticalCommandInstructionScanHash,
            VOARIAMessageTacticalCommandInstructionBoardHash,
            VOARIAMessageTacticalCommandInstructionBuildHash,
            VOARIAMessageTacticalCommandInstructionSpecialHash,
            VOARIAMessageTacticalCommandBoardPromptTransportToPassengerHash,
            VOARIAMessageTacticalCommandBoardPromptPassengerToTransportHash,
            VOARIAMessageTacticalCommandBoardUnavailableHash,
            VOARIAMessageTacticalCommandBoardTapUnitsToBoardHash,
            VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoardHash,
            VOARIAMessageTacticalCommandBoardSelectUnitFirstHash,
            VOARIAMessageTacticalCommandUnavailableHoldNoSelectionHash,
            VOARIAMessageTacticalCommandUnavailableStopNoSelectionHash,
            VOARIAMessageTacticalCommandUnavailableScanNoSelectionHash,
            VOARIAMessageTacticalFeedbackCameraFollowUnavailableHash,
            VOARIAMessageTacticalFeedbackCameraFollowActiveHash,
            VOARIAMessageTacticalFeedbackRtsCameraRestoredHash,
            VOARIAMessageTacticalFeedbackFollowTargetLostHash,
            VOARIAMessageTacticalFeedbackDestroyedSelectedBuildingHash,
            VOARIAMessageTacticalFeedbackAirDefenseAutoEngageHash,
            VOARIAMessageTacticalFeedbackExitingUnitHash,
            VOARIAMessageTacticalFeedbackExitingPassengersHash,
            VOARIAMessageTacticalFeedbackLoadingTransportHash,
            VOARIAMessageTacticalFeedbackBoardingTransportHash,
            VOARIAMessageTacticalFeedbackHoldingCurrentPositionHash,
            VOARIAMessageTacticalFeedbackStoppedSelectedUnitsHash,
            VOARIAMessageTacticalFeedbackUnitReturningToBaseHash,
            VOARIAMessageTacticalFeedbackUnitsReturningToBaseHash,
            VOARIAMessageTacticalFeedbackDestroyedSelectedUnitHash,
            VOARIAMessageTacticalFeedbackDestroyedSelectedUnitsHash,
            VOARIAMessageTacticalFeedbackScanOrderedHash,
            VOARIAMessageTacticalFeedbackScanOneContactHash,
            VOARIAMessageTacticalFeedbackScanContactsHash,
            VOARIAMessageTacticalFeedbackScanCompleteHash,
            VOARIAMessageTacticalFeedbackMissileLaunchedHash,
            VOARIAMessageTacticalAirdropEmergencyDropVisualMissingHash,
            VOARIAMessageTacticalAirdropParachuteVisualMissingHash,
            VOARIAMessageTacticalAirdropNoClearLandingZoneHash,
            VOARIAMessageTacticalAirdropCargoDropBlockedHash,
            VOARIAMessageTacticalBannerModeMoveTitleHash,
            VOARIAMessageTacticalBannerModeMoveDescriptionHash,
            VOARIAMessageTacticalBannerModeAttackTitleHash,
            VOARIAMessageTacticalBannerModeAttackDescriptionHash,
            VOARIAMessageTacticalBannerModeScanTitleHash,
            VOARIAMessageTacticalBannerModeScanDescriptionHash,
            VOARIAMessageTacticalBannerModeBoardTitleHash,
            VOARIAMessageTacticalBannerModeBoardDescriptionHash,
            VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassengerHash,
            VOARIAMessageTacticalBannerModeBuildTitleHash,
            VOARIAMessageTacticalBannerModeBuildDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedMoveTitleHash,
            VOARIAMessageTacticalBannerAcceptedMoveDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedAttackTitleHash,
            VOARIAMessageTacticalBannerAcceptedAttackDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedHoldTitleHash,
            VOARIAMessageTacticalBannerAcceptedHoldDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedStopTitleHash,
            VOARIAMessageTacticalBannerAcceptedStopDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedScanTitleHash,
            VOARIAMessageTacticalBannerAcceptedScanDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedBoardTitleHash,
            VOARIAMessageTacticalBannerAcceptedBoardDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedBuildTitleHash,
            VOARIAMessageTacticalBannerAcceptedBuildDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedReturnTitleHash,
            VOARIAMessageTacticalBannerAcceptedReturnDescriptionHash,
            VOARIAMessageTacticalBannerAcceptedDestroyTitleHash,
            VOARIAMessageTacticalBannerAcceptedDestroyDescriptionHash,
            VOARIAMessageBuildDrawerEmptyNameHash,
            VOARIAMessageBuildDrawerReadyBuildingsHash,
            VOARIAMessageBuildDrawerReadyVehiclesHash,
            VOARIAMessageBuildDrawerReadyAircraftHash,
            VOARIAMessageBuildDrawerReadySoldiersHash,
            VOARIAMessageBuildDrawerReadyDefaultHash,
            VOARIAMessageBuildDrawerInstructionPlacePendingConfirmHash,
            VOARIAMessageBuildDrawerInstructionCannotPlaceHereHash,
            VOARIAMessageBuildDrawerFailureConnectingHash,
            VOARIAMessageBuildDrawerFailureNotEnoughMoneyHash,
            VOARIAMessageBuildDrawerFailureMissingProducerNamedHash,
            VOARIAMessageBuildDrawerFailureMissingProducerHash,
            VOARIAMessageBuildDrawerFailureQueueFullNamedHash,
            VOARIAMessageBuildDrawerFailureQueueFullHash,
            VOARIAMessageBuildDrawerFailureGlobalQueueFullHash,
            VOARIAMessageBuildDrawerFailureInvalidSelectionHash,
            VOARIAMessageBuildDrawerFailureUnavailableHash,
            VOARIAMessageBuildDrawerFailureShortNotEnoughMoneyHash,
            VOARIAMessageBuildDrawerFailureShortRequiresNamedHash,
            VOARIAMessageBuildDrawerFailureShortMissingProducerHash,
            VOARIAMessageBuildDrawerFailureShortQueueFullNamedHash,
            VOARIAMessageBuildDrawerFailureShortQueueFullHash,
            VOARIAMessageBuildDrawerFailureShortGlobalQueueFullHash,
            VOARIAMessageBuildDrawerFailureShortUnavailableHash,
            VOARIAMessageBuildDrawerEmptyBuildingsHash,
            VOARIAMessageBuildDrawerEmptyVehiclesHash,
            VOARIAMessageBuildDrawerEmptyAircraftHash,
            VOARIAMessageBuildDrawerEmptySoldiersHash,
            VOARIAMessageBuildDrawerEmptyDefaultHash,
            VOARIAMessageBuildDrawerEmptySelectItemHash,
            VOARIAMessageBuildDrawerPlacementInvalidHash,
            VOARIAMessageBuildDrawerActionPlaceChooseFootprintHash,
            VOARIAMessageBuildFeedbackPlaceBuildingHash,
            VOARIAMessageBuildFeedbackProductionRequestedHash,
            VOARIAMessageBuildDrawerSuccessRecruitmentQueuedHash,
            VOARIAMessageBuildDrawerSuccessProductionQueuedHash,
            VOARIAMessageBuildFeedbackProductionCancelUnavailableHash,
            VOARIAMessageBuildFeedbackProductionCancelledNamedHash,
            VOARIAMessageBuildFeedbackProductionCancelledHash,
            VOARIAMessageBuildFeedbackProductionQueueEmptyHash,
            VOARIAMessageBuildFeedbackProductionQueueClearedSentenceHash,
            VOARIAMessageBuildFeedbackProductionClearUnavailableHash,
            VOARIAMessageBuildFeedbackProductionQueueClearedHash,
            VOARIAMessageBuildFeedbackPlacementCancelledHash,
            VOARIAMessageBuildFeedbackRotated90Hash,
            VOARIAMessageBuildFeedbackNoActivePlacementHash,
            VOARIAMessageBuildFeedbackBuildingPlacedHash,
            VOARIAMessageBuildFeedbackPlaceOnValidGroundHash,
            VOARIAMessageBuildFeedbackDrawerNotReadyHash,
            VOARIAMessageBuildPlacementStatusDragToPositionHash,
            VOARIAMessageBuildPlacementStatusValidGroundHash,
            VOARIAMessageBuildPlacementTitleDefaultHash,
            VOARIAMessageBuildPlacementTitleNamedHash,
            VOARIAMessageBuildPlacementInstructionConfirmHash,
            VOARIAMessageBuildPlacementTitleFallbackSubjectHash,
            VOARIAMessageMatchFeedbackTacticalMapNotReadyHash,
            VOARIAMessageMatchFeedbackBlockedCivilianZoneHash,
            VOARIAMessageSelectionFeedbackUnitSingularHash,
            VOARIAMessageSelectionFeedbackUnitPluralHash,
            VOARIAMessageSelectionFeedbackVehicleSingularHash,
            VOARIAMessageSelectionFeedbackSoldierSingularHash,
            VOARIAMessageSelectionFeedbackSquadCountHash,
            VOARIAMessageSelectionFeedbackSquadSelectedHash,
            VOARIATutorialM01FindSquadEnHash,
            VOARIATutorialM01MoveToCoverEnHash,
            VOARIATutorialM01MoveDestinationEnHash,
            VOARIATutorialM01ConfirmThreatEnHash,
            VOARIATutorialM01EngageEnHash,
            VOARIATutorialM01AttackTargetEnHash,
            VOARIATutorialM01SecureCorridorEnHash,
            VOARIATutorialM01FindSquadFaHash,
            VOARIATutorialM01MoveToCoverFaHash,
            VOARIATutorialM01MoveDestinationFaHash,
            VOARIATutorialM01ConfirmThreatFaHash,
            VOARIATutorialM01EngageFaHash,
            VOARIATutorialM01AttackTargetFaHash,
            VOARIATutorialM01SecureCorridorFaHash,
        };

        public static uint StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261u;
                for (int i = 0; i < value.Length; i++)
                {
                    hash ^= value[i];
                    hash *= 16777619u;
                }

                return hash;
            }
        }
    }
}
