// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static partial class AudioEventIds
    {
        public const string UIButtonPrimaryClick = "UI.Button.Primary.Click";
        public const uint UIButtonPrimaryClickHash = 3161187545u;

        public const string UIButtonSecondaryClick = "UI.Button.Secondary.Click";
        public const uint UIButtonSecondaryClickHash = 2478076573u;

        public const string UIButtonNegativeClick = "UI.Button.Negative.Click";
        public const uint UIButtonNegativeClickHash = 2301339126u;

        public const string UIButtonDisabledTap = "UI.Button.Disabled.Tap";
        public const uint UIButtonDisabledTapHash = 117293880u;

        public const string UITabSelect = "UI.Tab.Select";
        public const uint UITabSelectHash = 3352358512u;

        public const string UICardSelect = "UI.Card.Select";
        public const uint UICardSelectHash = 3014326253u;

        public const string UICardLocked = "UI.Card.Locked";
        public const uint UICardLockedHash = 3087335763u;

        public const string UIPopupOpen = "UI.Popup.Open";
        public const uint UIPopupOpenHash = 1791759535u;

        public const string UIPopupClose = "UI.Popup.Close";
        public const uint UIPopupCloseHash = 3024952377u;

        public const string UIScreenForward = "UI.Screen.Forward";
        public const uint UIScreenForwardHash = 805571044u;

        public const string UIScreenBack = "UI.Screen.Back";
        public const uint UIScreenBackHash = 4116222400u;

        public const string UIDrawerOpen = "UI.Drawer.Open";
        public const uint UIDrawerOpenHash = 1202804760u;

        public const string UIDrawerClose = "UI.Drawer.Close";
        public const uint UIDrawerCloseHash = 63668116u;

        public const string UISliderTick = "UI.Slider.Tick";
        public const uint UISliderTickHash = 1305878613u;

        public const string UIToggleOn = "UI.Toggle.On";
        public const uint UIToggleOnHash = 1412658802u;

        public const string UIToggleOff = "UI.Toggle.Off";
        public const uint UIToggleOffHash = 2434261764u;

        public const string UIFeedbackToastError = "UI.Feedback.Toast.Error";
        public const uint UIFeedbackToastErrorHash = 2617262137u;

        public const string UIFeedbackToastPositive = "UI.Feedback.Toast.Positive";
        public const uint UIFeedbackToastPositiveHash = 3875576338u;

        public const string GameplayUnitSelectInfantry = "Gameplay.Unit.Select.Infantry";
        public const uint GameplayUnitSelectInfantryHash = 3141110590u;

        public const string GameplayUnitSelectVehicle = "Gameplay.Unit.Select.Vehicle";
        public const uint GameplayUnitSelectVehicleHash = 3174649265u;

        public const string GameplayUnitSelectAir = "Gameplay.Unit.Select.Air";
        public const uint GameplayUnitSelectAirHash = 2620032125u;

        public const string GameplayUnitEngineVehicleMove = "Gameplay.Unit.Engine.Vehicle.Move";
        public const uint GameplayUnitEngineVehicleMoveHash = 1168540290u;

        public const string GameplayUnitEngineAircraftTakeoff = "Gameplay.Unit.Engine.Aircraft.Takeoff";
        public const uint GameplayUnitEngineAircraftTakeoffHash = 3592499569u;

        public const string GameplayUnitEngineAircraftFlight = "Gameplay.Unit.Engine.Aircraft.Flight";
        public const uint GameplayUnitEngineAircraftFlightHash = 1332154053u;

        public const string GameplayUnitEngineHelicopterFlight = "Gameplay.Unit.Engine.Helicopter.Flight";
        public const uint GameplayUnitEngineHelicopterFlightHash = 696811920u;

        public const string GameplayWeaponFireSmallArms = "Gameplay.Weapon.Fire.SmallArms";
        public const uint GameplayWeaponFireSmallArmsHash = 3212856651u;

        public const string GameplayWeaponMissileImpact = "Gameplay.Weapon.Missile.Impact";
        public const uint GameplayWeaponMissileImpactHash = 990836209u;

        public const string GameplayCommandMoveAccepted = "Gameplay.Command.Move.Accepted";
        public const uint GameplayCommandMoveAcceptedHash = 1382687044u;

        public const string GameplayCommandAttackAccepted = "Gameplay.Command.Attack.Accepted";
        public const uint GameplayCommandAttackAcceptedHash = 3185718759u;

        public const string GameplayCommandHoldAccepted = "Gameplay.Command.Hold.Accepted";
        public const uint GameplayCommandHoldAcceptedHash = 2504035620u;

        public const string GameplayCommandStopReturning = "Gameplay.Command.Stop.Returning";
        public const uint GameplayCommandStopReturningHash = 3510404204u;

        public const string GameplayCommandScanTargeting = "Gameplay.Command.Scan.Targeting";
        public const uint GameplayCommandScanTargetingHash = 1422340592u;

        public const string GameplayCommandScanAccepted = "Gameplay.Command.Scan.Accepted";
        public const uint GameplayCommandScanAcceptedHash = 1764603952u;

        public const string GameplayCommandRejected = "Gameplay.Command.Rejected";
        public const uint GameplayCommandRejectedHash = 4172340306u;

        public const string GameplayBuildPlaceValid = "Gameplay.Build.Place.Valid";
        public const uint GameplayBuildPlaceValidHash = 3769720894u;

        public const string GameplayBuildPlaceInvalid = "Gameplay.Build.Place.Invalid";
        public const uint GameplayBuildPlaceInvalidHash = 1788114895u;

        public const string GameplayProductionQueued = "Gameplay.Production.Queued";
        public const uint GameplayProductionQueuedHash = 2682016025u;

        public const string GameplayProductionComplete = "Gameplay.Production.Complete";
        public const uint GameplayProductionCompleteHash = 2701904751u;

        public const string GameplayResourceExchangeAccepted = "Gameplay.ResourceExchange.Accepted";
        public const uint GameplayResourceExchangeAcceptedHash = 677266519u;

        public const string GameplayResourceExchangeRejected = "Gameplay.ResourceExchange.Rejected";
        public const uint GameplayResourceExchangeRejectedHash = 624368988u;

        public const string GameplayResourceExchangeQueueStarted = "Gameplay.ResourceExchange.QueueStarted";
        public const uint GameplayResourceExchangeQueueStartedHash = 3901359954u;

        public const string GameplayResourceExchangeRushed = "Gameplay.ResourceExchange.Rushed";
        public const uint GameplayResourceExchangeRushedHash = 3276875873u;

        public const string GameplayResourceExchangeCompleted = "Gameplay.ResourceExchange.Completed";
        public const uint GameplayResourceExchangeCompletedHash = 2973504283u;

        public const string GameplayResourceExchangeCancelled = "Gameplay.ResourceExchange.Cancelled";
        public const uint GameplayResourceExchangeCancelledHash = 2587331601u;

        public const string GameplayWeaponRifleFire = "Gameplay.Weapon.Rifle.Fire";
        public const uint GameplayWeaponRifleFireHash = 644878421u;

        public const string GameplayWeaponVehicleCannonFire = "Gameplay.Weapon.VehicleCannon.Fire";
        public const uint GameplayWeaponVehicleCannonFireHash = 4224941188u;

        public const string GameplayWeaponMissileLaunch = "Gameplay.Weapon.Missile.Launch";
        public const uint GameplayWeaponMissileLaunchHash = 3753501364u;

        public const string GameplayWeaponAirMissileLaunch = "Gameplay.Weapon.AirMissile.Launch";
        public const uint GameplayWeaponAirMissileLaunchHash = 510872954u;

        public const string GameplayWeaponMissileFlight = "Gameplay.Weapon.Missile.Flight";
        public const uint GameplayWeaponMissileFlightHash = 1400335713u;

        public const string GameplayUnitAircraftFlyby = "Gameplay.Unit.Aircraft.Flyby";
        public const uint GameplayUnitAircraftFlybyHash = 3269847167u;

        public const string GameplayUnitVehicleEngine = "Gameplay.Unit.Vehicle.Engine";
        public const uint GameplayUnitVehicleEngineHash = 4282126079u;

        public const string GameplayImpactBullet = "Gameplay.Impact.Bullet";
        public const uint GameplayImpactBulletHash = 2654624111u;

        public const string GameplayExplosionSmall = "Gameplay.Explosion.Small";
        public const uint GameplayExplosionSmallHash = 217574373u;

        public const string GameplayExplosionLarge = "Gameplay.Explosion.Large";
        public const uint GameplayExplosionLargeHash = 4072520545u;

        public const string GameplayUnitVehicleDestroyed = "Gameplay.Unit.Vehicle.Destroyed";
        public const uint GameplayUnitVehicleDestroyedHash = 4083608480u;

        public const string AlertThreatMinor = "Alert.Threat.Minor";
        public const uint AlertThreatMinorHash = 3119639462u;

        public const string AlertThreatCritical = "Alert.Threat.Critical";
        public const uint AlertThreatCriticalHash = 2327085632u;

        public const string AlertUnitUnderAttack = "Alert.Unit.UnderAttack";
        public const uint AlertUnitUnderAttackHash = 4035338951u;

        public const string AlertBaseBreached = "Alert.Base.Breached";
        public const uint AlertBaseBreachedHash = 2770899834u;

        public const string GameplayObjectiveProgress = "Gameplay.Objective.Progress";
        public const uint GameplayObjectiveProgressHash = 3042211329u;

        public const string GameplayObjectiveComplete = "Gameplay.Objective.Complete";
        public const uint GameplayObjectiveCompleteHash = 1524265589u;

        public const string GameplayObjectiveFailed = "Gameplay.Objective.Failed";
        public const uint GameplayObjectiveFailedHash = 2020740559u;

        public const string MusicSplashIntro = "Music.Splash.Intro";
        public const uint MusicSplashIntroHash = 525010837u;

        public const string MusicMenuLoop = "Music.Menu.Loop";
        public const uint MusicMenuLoopHash = 3629030835u;

        public const string MusicBriefingLoop = "Music.Briefing.Loop";
        public const uint MusicBriefingLoopHash = 316398394u;

        public const string MusicMatchCalmLoop = "Music.Match.CalmLoop";
        public const uint MusicMatchCalmLoopHash = 4285376118u;

        public const string MusicMatchCombatLoop = "Music.Match.CombatLoop";
        public const uint MusicMatchCombatLoopHash = 1880341561u;

        public const string MusicResultVictory = "Music.Result.Victory";
        public const uint MusicResultVictoryHash = 1502319359u;

        public const string MusicResultDefeat = "Music.Result.Defeat";
        public const uint MusicResultDefeatHash = 552063808u;

        public const string AmbienceCityDayLoop = "Ambience.City.DayLoop";
        public const uint AmbienceCityDayLoopHash = 3552601528u;

        public const string AmbienceMissionCivilianPanic = "Ambience.Mission.CivilianPanic";
        public const uint AmbienceMissionCivilianPanicHash = 2548328607u;

        public const string AmbienceBaseDistantLoop = "Ambience.Base.DistantLoop";
        public const uint AmbienceBaseDistantLoopHash = 1729659713u;

        public const string VOARIAMessageConfirmDestroy = "VO.ARIA.Message.ConfirmDestroy";
        public const uint VOARIAMessageConfirmDestroyHash = 2769957816u;

        public const string VOARIAMessageNotEnoughMoney = "VO.ARIA.Message.NotEnoughMoney";
        public const uint VOARIAMessageNotEnoughMoneyHash = 1497698393u;

        public const string VOARIAMessageCreateFirst = "VO.ARIA.Message.CreateFirst";
        public const uint VOARIAMessageCreateFirstHash = 1865937768u;

        public const string VOARIAMessageDragBuildingToFinalPosition = "VO.ARIA.Message.DragBuildingToFinalPosition";
        public const uint VOARIAMessageDragBuildingToFinalPositionHash = 1885782560u;

        public const string VOARIAMessageWarningGroundAttackType = "VO.ARIA.Message.WarningGroundAttackType";
        public const uint VOARIAMessageWarningGroundAttackTypeHash = 2571709797u;

        public const string VOARIAMessageWarningAirAttackType = "VO.ARIA.Message.WarningAirAttackType";
        public const uint VOARIAMessageWarningAirAttackTypeHash = 425358394u;

        public const string VOARIAMessageWarningAttackEtaSeconds = "VO.ARIA.Message.WarningAttackEtaSeconds";
        public const uint VOARIAMessageWarningAttackEtaSecondsHash = 3440772663u;

        public const string VOARIAMessageWarningAttackEtaSuffix = "VO.ARIA.Message.WarningAttackEtaSuffix";
        public const uint VOARIAMessageWarningAttackEtaSuffixHash = 582726599u;

        public const string VOARIAMessageWarningAttackCountSuffix = "VO.ARIA.Message.WarningAttackCountSuffix";
        public const uint VOARIAMessageWarningAttackCountSuffixHash = 273208812u;

        public const string VOARIAMessageTacticalCommandReasonNoSelection = "VO.ARIA.Message.TacticalCommandReasonNoSelection";
        public const uint VOARIAMessageTacticalCommandReasonNoSelectionHash = 4135895351u;

        public const string VOARIAMessageTacticalCommandReasonTargetOutOfBounds = "VO.ARIA.Message.TacticalCommandReasonTargetOutOfBounds";
        public const uint VOARIAMessageTacticalCommandReasonTargetOutOfBoundsHash = 2910927259u;

        public const string VOARIAMessageTacticalCommandReasonTargetBlocked = "VO.ARIA.Message.TacticalCommandReasonTargetBlocked";
        public const uint VOARIAMessageTacticalCommandReasonTargetBlockedHash = 2805549707u;

        public const string VOARIAMessageTacticalCommandReasonTargetUnreachable = "VO.ARIA.Message.TacticalCommandReasonTargetUnreachable";
        public const uint VOARIAMessageTacticalCommandReasonTargetUnreachableHash = 2210103721u;

        public const string VOARIAMessageTacticalCommandReasonTargetNotEnemy = "VO.ARIA.Message.TacticalCommandReasonTargetNotEnemy";
        public const uint VOARIAMessageTacticalCommandReasonTargetNotEnemyHash = 1935329694u;

        public const string VOARIAMessageTacticalCommandReasonTargetNotAttackable = "VO.ARIA.Message.TacticalCommandReasonTargetNotAttackable";
        public const uint VOARIAMessageTacticalCommandReasonTargetNotAttackableHash = 3558763922u;

        public const string VOARIAMessageTacticalCommandReasonCommandUnavailable = "VO.ARIA.Message.TacticalCommandReasonCommandUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonCommandUnavailableHash = 3405920913u;

        public const string VOARIAMessageTacticalCommandReasonBuildUnavailable = "VO.ARIA.Message.TacticalCommandReasonBuildUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonBuildUnavailableHash = 4070679814u;

        public const string VOARIAMessageTacticalCommandReasonCameraJumpUnavailable = "VO.ARIA.Message.TacticalCommandReasonCameraJumpUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonCameraJumpUnavailableHash = 452837419u;

        public const string VOARIAMessageTacticalCommandReasonScanUnavailable = "VO.ARIA.Message.TacticalCommandReasonScanUnavailable";
        public const uint VOARIAMessageTacticalCommandReasonScanUnavailableHash = 4008598569u;

        public const string VOARIAMessageTacticalCommandReasonScanCooldown = "VO.ARIA.Message.TacticalCommandReasonScanCooldown";
        public const uint VOARIAMessageTacticalCommandReasonScanCooldownHash = 1372693640u;

        public const string VOARIAMessageTacticalCommandReasonInsufficientResources = "VO.ARIA.Message.TacticalCommandReasonInsufficientResources";
        public const uint VOARIAMessageTacticalCommandReasonInsufficientResourcesHash = 173798012u;

        public const string VOARIAMessageTacticalCommandReasonInsufficientFuel = "VO.ARIA.Message.TacticalCommandReasonInsufficientFuel";
        public const uint VOARIAMessageTacticalCommandReasonInsufficientFuelHash = 1777687631u;

        public const string VOARIAMessageTacticalCommandReasonInvalidTransport = "VO.ARIA.Message.TacticalCommandReasonInvalidTransport";
        public const uint VOARIAMessageTacticalCommandReasonInvalidTransportHash = 668828628u;

        public const string VOARIAMessageTacticalCommandReasonInvalidPassenger = "VO.ARIA.Message.TacticalCommandReasonInvalidPassenger";
        public const uint VOARIAMessageTacticalCommandReasonInvalidPassengerHash = 3306814445u;

        public const string VOARIAMessageTacticalCommandReasonTransportFull = "VO.ARIA.Message.TacticalCommandReasonTransportFull";
        public const uint VOARIAMessageTacticalCommandReasonTransportFullHash = 1103806920u;

        public const string VOARIAMessageTacticalCommandReasonNoEligiblePassengers = "VO.ARIA.Message.TacticalCommandReasonNoEligiblePassengers";
        public const uint VOARIAMessageTacticalCommandReasonNoEligiblePassengersHash = 749650471u;

        public const string VOARIAMessageTacticalCommandReasonNoDisembarkCell = "VO.ARIA.Message.TacticalCommandReasonNoDisembarkCell";
        public const uint VOARIAMessageTacticalCommandReasonNoDisembarkCellHash = 2874977329u;

        public const string VOARIAMessageTacticalCommandReasonTransportPassengerMissing = "VO.ARIA.Message.TacticalCommandReasonTransportPassengerMissing";
        public const uint VOARIAMessageTacticalCommandReasonTransportPassengerMissingHash = 2925040837u;

    }
}
