// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static partial class AudioEventIds
    {
        public const string VOARIAMessageTacticalCommandInstructionSelect = "VO.ARIA.Message.TacticalCommandInstructionSelect";
        public const uint VOARIAMessageTacticalCommandInstructionSelectHash = 2748094352u;

        public const string VOARIAMessageTacticalCommandInstructionMove = "VO.ARIA.Message.TacticalCommandInstructionMove";
        public const uint VOARIAMessageTacticalCommandInstructionMoveHash = 3308873509u;

        public const string VOARIAMessageTacticalCommandInstructionAttack = "VO.ARIA.Message.TacticalCommandInstructionAttack";
        public const uint VOARIAMessageTacticalCommandInstructionAttackHash = 4289552068u;

        public const string VOARIAMessageTacticalCommandInstructionHold = "VO.ARIA.Message.TacticalCommandInstructionHold";
        public const uint VOARIAMessageTacticalCommandInstructionHoldHash = 3439454485u;

        public const string VOARIAMessageTacticalCommandInstructionStop = "VO.ARIA.Message.TacticalCommandInstructionStop";
        public const uint VOARIAMessageTacticalCommandInstructionStopHash = 1501401760u;

        public const string VOARIAMessageTacticalCommandInstructionScan = "VO.ARIA.Message.TacticalCommandInstructionScan";
        public const uint VOARIAMessageTacticalCommandInstructionScanHash = 22836897u;

        public const string VOARIAMessageTacticalCommandInstructionBoard = "VO.ARIA.Message.TacticalCommandInstructionBoard";
        public const uint VOARIAMessageTacticalCommandInstructionBoardHash = 4022543000u;

        public const string VOARIAMessageTacticalCommandInstructionBuild = "VO.ARIA.Message.TacticalCommandInstructionBuild";
        public const uint VOARIAMessageTacticalCommandInstructionBuildHash = 1583154856u;

        public const string VOARIAMessageTacticalCommandInstructionSpecial = "VO.ARIA.Message.TacticalCommandInstructionSpecial";
        public const uint VOARIAMessageTacticalCommandInstructionSpecialHash = 3531066851u;

        public const string VOARIAMessageTacticalCommandBoardPromptTransportToPassenger = "VO.ARIA.Message.TacticalCommandBoardPromptTransportToPassenger";
        public const uint VOARIAMessageTacticalCommandBoardPromptTransportToPassengerHash = 4164327806u;

        public const string VOARIAMessageTacticalCommandBoardPromptPassengerToTransport = "VO.ARIA.Message.TacticalCommandBoardPromptPassengerToTransport";
        public const uint VOARIAMessageTacticalCommandBoardPromptPassengerToTransportHash = 626416944u;

        public const string VOARIAMessageTacticalCommandBoardUnavailable = "VO.ARIA.Message.TacticalCommandBoardUnavailable";
        public const uint VOARIAMessageTacticalCommandBoardUnavailableHash = 1010495506u;

        public const string VOARIAMessageTacticalCommandBoardTapUnitsToBoard = "VO.ARIA.Message.TacticalCommandBoardTapUnitsToBoard";
        public const uint VOARIAMessageTacticalCommandBoardTapUnitsToBoardHash = 346118675u;

        public const string VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoard = "VO.ARIA.Message.TacticalCommandBoardSelectedUnitCannotBoard";
        public const uint VOARIAMessageTacticalCommandBoardSelectedUnitCannotBoardHash = 2595310816u;

        public const string VOARIAMessageTacticalCommandBoardSelectUnitFirst = "VO.ARIA.Message.TacticalCommandBoardSelectUnitFirst";
        public const uint VOARIAMessageTacticalCommandBoardSelectUnitFirstHash = 1312855484u;

        public const string VOARIAMessageTacticalCommandUnavailableHoldNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableHoldNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableHoldNoSelectionHash = 3755007230u;

        public const string VOARIAMessageTacticalCommandUnavailableStopNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableStopNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableStopNoSelectionHash = 339702977u;

        public const string VOARIAMessageTacticalCommandUnavailableScanNoSelection = "VO.ARIA.Message.TacticalCommandUnavailableScanNoSelection";
        public const uint VOARIAMessageTacticalCommandUnavailableScanNoSelectionHash = 1133512018u;

        public const string VOARIAMessageTacticalFeedbackCameraFollowUnavailable = "VO.ARIA.Message.TacticalFeedbackCameraFollowUnavailable";
        public const uint VOARIAMessageTacticalFeedbackCameraFollowUnavailableHash = 3282664940u;

        public const string VOARIAMessageTacticalFeedbackCameraFollowActive = "VO.ARIA.Message.TacticalFeedbackCameraFollowActive";
        public const uint VOARIAMessageTacticalFeedbackCameraFollowActiveHash = 108632900u;

        public const string VOARIAMessageTacticalFeedbackRtsCameraRestored = "VO.ARIA.Message.TacticalFeedbackRtsCameraRestored";
        public const uint VOARIAMessageTacticalFeedbackRtsCameraRestoredHash = 23298754u;

        public const string VOARIAMessageTacticalFeedbackFollowTargetLost = "VO.ARIA.Message.TacticalFeedbackFollowTargetLost";
        public const uint VOARIAMessageTacticalFeedbackFollowTargetLostHash = 1127465702u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedBuilding = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedBuilding";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedBuildingHash = 308779550u;

        public const string VOARIAMessageTacticalFeedbackAirDefenseAutoEngage = "VO.ARIA.Message.TacticalFeedbackAirDefenseAutoEngage";
        public const uint VOARIAMessageTacticalFeedbackAirDefenseAutoEngageHash = 1274052508u;

        public const string VOARIAMessageTacticalFeedbackExitingUnit = "VO.ARIA.Message.TacticalFeedbackExitingUnit";
        public const uint VOARIAMessageTacticalFeedbackExitingUnitHash = 3438748822u;

        public const string VOARIAMessageTacticalFeedbackExitingPassengers = "VO.ARIA.Message.TacticalFeedbackExitingPassengers";
        public const uint VOARIAMessageTacticalFeedbackExitingPassengersHash = 2482898073u;

        public const string VOARIAMessageTacticalFeedbackLoadingTransport = "VO.ARIA.Message.TacticalFeedbackLoadingTransport";
        public const uint VOARIAMessageTacticalFeedbackLoadingTransportHash = 2581984329u;

        public const string VOARIAMessageTacticalFeedbackBoardingTransport = "VO.ARIA.Message.TacticalFeedbackBoardingTransport";
        public const uint VOARIAMessageTacticalFeedbackBoardingTransportHash = 17053981u;

        public const string VOARIAMessageTacticalFeedbackHoldingCurrentPosition = "VO.ARIA.Message.TacticalFeedbackHoldingCurrentPosition";
        public const uint VOARIAMessageTacticalFeedbackHoldingCurrentPositionHash = 1472517519u;

        public const string VOARIAMessageTacticalFeedbackStoppedSelectedUnits = "VO.ARIA.Message.TacticalFeedbackStoppedSelectedUnits";
        public const uint VOARIAMessageTacticalFeedbackStoppedSelectedUnitsHash = 417175199u;

        public const string VOARIAMessageTacticalFeedbackUnitReturningToBase = "VO.ARIA.Message.TacticalFeedbackUnitReturningToBase";
        public const uint VOARIAMessageTacticalFeedbackUnitReturningToBaseHash = 2386725092u;

        public const string VOARIAMessageTacticalFeedbackUnitsReturningToBase = "VO.ARIA.Message.TacticalFeedbackUnitsReturningToBase";
        public const uint VOARIAMessageTacticalFeedbackUnitsReturningToBaseHash = 3885411515u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedUnit = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedUnit";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedUnitHash = 3408293596u;

        public const string VOARIAMessageTacticalFeedbackDestroyedSelectedUnits = "VO.ARIA.Message.TacticalFeedbackDestroyedSelectedUnits";
        public const uint VOARIAMessageTacticalFeedbackDestroyedSelectedUnitsHash = 2088779133u;

        public const string VOARIAMessageTacticalFeedbackScanOrdered = "VO.ARIA.Message.TacticalFeedbackScanOrdered";
        public const uint VOARIAMessageTacticalFeedbackScanOrderedHash = 3370429146u;

        public const string VOARIAMessageTacticalFeedbackScanOneContact = "VO.ARIA.Message.TacticalFeedbackScanOneContact";
        public const uint VOARIAMessageTacticalFeedbackScanOneContactHash = 1330041397u;

        public const string VOARIAMessageTacticalFeedbackScanContacts = "VO.ARIA.Message.TacticalFeedbackScanContacts";
        public const uint VOARIAMessageTacticalFeedbackScanContactsHash = 1511448996u;

        public const string VOARIAMessageTacticalFeedbackScanComplete = "VO.ARIA.Message.TacticalFeedbackScanComplete";
        public const uint VOARIAMessageTacticalFeedbackScanCompleteHash = 274538966u;

        public const string VOARIAMessageTacticalFeedbackMissileLaunched = "VO.ARIA.Message.TacticalFeedbackMissileLaunched";
        public const uint VOARIAMessageTacticalFeedbackMissileLaunchedHash = 1883554858u;

        public const string VOARIAMessageTacticalAirdropEmergencyDropVisualMissing = "VO.ARIA.Message.TacticalAirdropEmergencyDropVisualMissing";
        public const uint VOARIAMessageTacticalAirdropEmergencyDropVisualMissingHash = 3899966708u;

        public const string VOARIAMessageTacticalAirdropParachuteVisualMissing = "VO.ARIA.Message.TacticalAirdropParachuteVisualMissing";
        public const uint VOARIAMessageTacticalAirdropParachuteVisualMissingHash = 2041790521u;

        public const string VOARIAMessageTacticalAirdropNoClearLandingZone = "VO.ARIA.Message.TacticalAirdropNoClearLandingZone";
        public const uint VOARIAMessageTacticalAirdropNoClearLandingZoneHash = 2165697149u;

        public const string VOARIAMessageTacticalAirdropCargoDropBlocked = "VO.ARIA.Message.TacticalAirdropCargoDropBlocked";
        public const uint VOARIAMessageTacticalAirdropCargoDropBlockedHash = 1470553003u;

        public const string VOARIAMessageTacticalBannerModeMoveTitle = "VO.ARIA.Message.TacticalBannerModeMoveTitle";
        public const uint VOARIAMessageTacticalBannerModeMoveTitleHash = 271952847u;

        public const string VOARIAMessageTacticalBannerModeMoveDescription = "VO.ARIA.Message.TacticalBannerModeMoveDescription";
        public const uint VOARIAMessageTacticalBannerModeMoveDescriptionHash = 1976093803u;

        public const string VOARIAMessageTacticalBannerModeAttackTitle = "VO.ARIA.Message.TacticalBannerModeAttackTitle";
        public const uint VOARIAMessageTacticalBannerModeAttackTitleHash = 2299946128u;

        public const string VOARIAMessageTacticalBannerModeAttackDescription = "VO.ARIA.Message.TacticalBannerModeAttackDescription";
        public const uint VOARIAMessageTacticalBannerModeAttackDescriptionHash = 833516792u;

        public const string VOARIAMessageTacticalBannerModeScanTitle = "VO.ARIA.Message.TacticalBannerModeScanTitle";
        public const uint VOARIAMessageTacticalBannerModeScanTitleHash = 3264010615u;

        public const string VOARIAMessageTacticalBannerModeScanDescription = "VO.ARIA.Message.TacticalBannerModeScanDescription";
        public const uint VOARIAMessageTacticalBannerModeScanDescriptionHash = 4072862067u;

        public const string VOARIAMessageTacticalBannerModeBoardTitle = "VO.ARIA.Message.TacticalBannerModeBoardTitle";
        public const uint VOARIAMessageTacticalBannerModeBoardTitleHash = 1464553436u;

        public const string VOARIAMessageTacticalBannerModeBoardDescription = "VO.ARIA.Message.TacticalBannerModeBoardDescription";
        public const uint VOARIAMessageTacticalBannerModeBoardDescriptionHash = 3232575468u;

        public const string VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassenger = "VO.ARIA.Message.TacticalBannerModeBoardDescriptionTransportToPassenger";
        public const uint VOARIAMessageTacticalBannerModeBoardDescriptionTransportToPassengerHash = 1384777824u;

        public const string VOARIAMessageTacticalBannerModeBuildTitle = "VO.ARIA.Message.TacticalBannerModeBuildTitle";
        public const uint VOARIAMessageTacticalBannerModeBuildTitleHash = 1831091860u;

        public const string VOARIAMessageTacticalBannerModeBuildDescription = "VO.ARIA.Message.TacticalBannerModeBuildDescription";
        public const uint VOARIAMessageTacticalBannerModeBuildDescriptionHash = 4073486884u;

        public const string VOARIAMessageTacticalBannerAcceptedMoveTitle = "VO.ARIA.Message.TacticalBannerAcceptedMoveTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedMoveTitleHash = 984869289u;

        public const string VOARIAMessageTacticalBannerAcceptedMoveDescription = "VO.ARIA.Message.TacticalBannerAcceptedMoveDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedMoveDescriptionHash = 570569225u;

        public const string VOARIAMessageTacticalBannerAcceptedAttackTitle = "VO.ARIA.Message.TacticalBannerAcceptedAttackTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedAttackTitleHash = 2720292082u;

        public const string VOARIAMessageTacticalBannerAcceptedAttackDescription = "VO.ARIA.Message.TacticalBannerAcceptedAttackDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedAttackDescriptionHash = 3264300366u;

        public const string VOARIAMessageTacticalBannerAcceptedHoldTitle = "VO.ARIA.Message.TacticalBannerAcceptedHoldTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedHoldTitleHash = 3583674425u;

        public const string VOARIAMessageTacticalBannerAcceptedHoldDescription = "VO.ARIA.Message.TacticalBannerAcceptedHoldDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedHoldDescriptionHash = 892142297u;

        public const string VOARIAMessageTacticalBannerAcceptedStopTitle = "VO.ARIA.Message.TacticalBannerAcceptedStopTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedStopTitleHash = 649840534u;

        public const string VOARIAMessageTacticalBannerAcceptedStopDescription = "VO.ARIA.Message.TacticalBannerAcceptedStopDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedStopDescriptionHash = 3062344138u;

        public const string VOARIAMessageTacticalBannerAcceptedScanTitle = "VO.ARIA.Message.TacticalBannerAcceptedScanTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedScanTitleHash = 3208314925u;

        public const string VOARIAMessageTacticalBannerAcceptedScanDescription = "VO.ARIA.Message.TacticalBannerAcceptedScanDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedScanDescriptionHash = 1434493125u;

        public const string VOARIAMessageTacticalBannerAcceptedBoardTitle = "VO.ARIA.Message.TacticalBannerAcceptedBoardTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedBoardTitleHash = 1488960574u;

        public const string VOARIAMessageTacticalBannerAcceptedBoardDescription = "VO.ARIA.Message.TacticalBannerAcceptedBoardDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedBoardDescriptionHash = 2460007954u;

        public const string VOARIAMessageTacticalBannerAcceptedBuildTitle = "VO.ARIA.Message.TacticalBannerAcceptedBuildTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedBuildTitleHash = 2171834286u;

        public const string VOARIAMessageTacticalBannerAcceptedBuildDescription = "VO.ARIA.Message.TacticalBannerAcceptedBuildDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedBuildDescriptionHash = 881007938u;

        public const string VOARIAMessageTacticalBannerAcceptedReturnTitle = "VO.ARIA.Message.TacticalBannerAcceptedReturnTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedReturnTitleHash = 1131718632u;

        public const string VOARIAMessageTacticalBannerAcceptedReturnDescription = "VO.ARIA.Message.TacticalBannerAcceptedReturnDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedReturnDescriptionHash = 867428304u;

        public const string VOARIAMessageTacticalBannerAcceptedDestroyTitle = "VO.ARIA.Message.TacticalBannerAcceptedDestroyTitle";
        public const uint VOARIAMessageTacticalBannerAcceptedDestroyTitleHash = 2047513668u;

        public const string VOARIAMessageTacticalBannerAcceptedDestroyDescription = "VO.ARIA.Message.TacticalBannerAcceptedDestroyDescription";
        public const uint VOARIAMessageTacticalBannerAcceptedDestroyDescriptionHash = 3571275540u;

        public const string VOARIAMessageBuildDrawerEmptyName = "VO.ARIA.Message.BuildDrawerEmptyName";
        public const uint VOARIAMessageBuildDrawerEmptyNameHash = 3266764183u;

        public const string VOARIAMessageBuildDrawerReadyBuildings = "VO.ARIA.Message.BuildDrawerReadyBuildings";
        public const uint VOARIAMessageBuildDrawerReadyBuildingsHash = 1462777963u;

        public const string VOARIAMessageBuildDrawerReadyVehicles = "VO.ARIA.Message.BuildDrawerReadyVehicles";
        public const uint VOARIAMessageBuildDrawerReadyVehiclesHash = 385761459u;

        public const string VOARIAMessageBuildDrawerReadyAircraft = "VO.ARIA.Message.BuildDrawerReadyAircraft";
        public const uint VOARIAMessageBuildDrawerReadyAircraftHash = 101178724u;

        public const string VOARIAMessageBuildDrawerReadySoldiers = "VO.ARIA.Message.BuildDrawerReadySoldiers";
        public const uint VOARIAMessageBuildDrawerReadySoldiersHash = 7975065u;

        public const string VOARIAMessageBuildDrawerReadyDefault = "VO.ARIA.Message.BuildDrawerReadyDefault";
        public const uint VOARIAMessageBuildDrawerReadyDefaultHash = 2147982739u;

        public const string VOARIAMessageBuildDrawerInstructionPlacePendingConfirm = "VO.ARIA.Message.BuildDrawerInstructionPlacePendingConfirm";
        public const uint VOARIAMessageBuildDrawerInstructionPlacePendingConfirmHash = 2891047625u;

        public const string VOARIAMessageBuildDrawerInstructionCannotPlaceHere = "VO.ARIA.Message.BuildDrawerInstructionCannotPlaceHere";
        public const uint VOARIAMessageBuildDrawerInstructionCannotPlaceHereHash = 626012179u;

        public const string VOARIAMessageBuildDrawerFailureConnecting = "VO.ARIA.Message.BuildDrawerFailureConnecting";
        public const uint VOARIAMessageBuildDrawerFailureConnectingHash = 3062397965u;

        public const string VOARIAMessageBuildDrawerFailureNotEnoughMoney = "VO.ARIA.Message.BuildDrawerFailureNotEnoughMoney";
        public const uint VOARIAMessageBuildDrawerFailureNotEnoughMoneyHash = 3026994208u;

        public const string VOARIAMessageBuildDrawerFailureMissingProducerNamed = "VO.ARIA.Message.BuildDrawerFailureMissingProducerNamed";
        public const uint VOARIAMessageBuildDrawerFailureMissingProducerNamedHash = 262295072u;

        public const string VOARIAMessageBuildDrawerFailureMissingProducer = "VO.ARIA.Message.BuildDrawerFailureMissingProducer";
        public const uint VOARIAMessageBuildDrawerFailureMissingProducerHash = 2289244967u;

        public const string VOARIAMessageBuildDrawerFailureQueueFullNamed = "VO.ARIA.Message.BuildDrawerFailureQueueFullNamed";
        public const uint VOARIAMessageBuildDrawerFailureQueueFullNamedHash = 1859404272u;

        public const string VOARIAMessageBuildDrawerFailureQueueFull = "VO.ARIA.Message.BuildDrawerFailureQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureQueueFullHash = 1539003479u;

        public const string VOARIAMessageBuildDrawerFailureGlobalQueueFull = "VO.ARIA.Message.BuildDrawerFailureGlobalQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureGlobalQueueFullHash = 113904958u;

        public const string VOARIAMessageBuildDrawerFailureInvalidSelection = "VO.ARIA.Message.BuildDrawerFailureInvalidSelection";
        public const uint VOARIAMessageBuildDrawerFailureInvalidSelectionHash = 1375188920u;

        public const string VOARIAMessageBuildDrawerFailureUnavailable = "VO.ARIA.Message.BuildDrawerFailureUnavailable";
        public const uint VOARIAMessageBuildDrawerFailureUnavailableHash = 50900467u;

        public const string VOARIAMessageBuildDrawerFailureShortNotEnoughMoney = "VO.ARIA.Message.BuildDrawerFailureShortNotEnoughMoney";
        public const uint VOARIAMessageBuildDrawerFailureShortNotEnoughMoneyHash = 1771510712u;

        public const string VOARIAMessageBuildDrawerFailureShortRequiresNamed = "VO.ARIA.Message.BuildDrawerFailureShortRequiresNamed";
        public const uint VOARIAMessageBuildDrawerFailureShortRequiresNamedHash = 1283132284u;

        public const string VOARIAMessageBuildDrawerFailureShortMissingProducer = "VO.ARIA.Message.BuildDrawerFailureShortMissingProducer";
        public const uint VOARIAMessageBuildDrawerFailureShortMissingProducerHash = 4083487215u;

        public const string VOARIAMessageBuildDrawerFailureShortQueueFullNamed = "VO.ARIA.Message.BuildDrawerFailureShortQueueFullNamed";
        public const uint VOARIAMessageBuildDrawerFailureShortQueueFullNamedHash = 2091502008u;

        public const string VOARIAMessageBuildDrawerFailureShortQueueFull = "VO.ARIA.Message.BuildDrawerFailureShortQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureShortQueueFullHash = 1386062895u;

        public const string VOARIAMessageBuildDrawerFailureShortGlobalQueueFull = "VO.ARIA.Message.BuildDrawerFailureShortGlobalQueueFull";
        public const uint VOARIAMessageBuildDrawerFailureShortGlobalQueueFullHash = 4040988550u;

        public const string VOARIAMessageBuildDrawerFailureShortUnavailable = "VO.ARIA.Message.BuildDrawerFailureShortUnavailable";
        public const uint VOARIAMessageBuildDrawerFailureShortUnavailableHash = 2077498219u;

        public const string VOARIAMessageBuildDrawerEmptyBuildings = "VO.ARIA.Message.BuildDrawerEmptyBuildings";
        public const uint VOARIAMessageBuildDrawerEmptyBuildingsHash = 3037375901u;

        public const string VOARIAMessageBuildDrawerEmptyVehicles = "VO.ARIA.Message.BuildDrawerEmptyVehicles";
        public const uint VOARIAMessageBuildDrawerEmptyVehiclesHash = 1033832213u;

        public const string VOARIAMessageBuildDrawerEmptyAircraft = "VO.ARIA.Message.BuildDrawerEmptyAircraft";
        public const uint VOARIAMessageBuildDrawerEmptyAircraftHash = 4166792890u;

        public const string VOARIAMessageBuildDrawerEmptySoldiers = "VO.ARIA.Message.BuildDrawerEmptySoldiers";
        public const uint VOARIAMessageBuildDrawerEmptySoldiersHash = 686826671u;

    }
}
