// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static partial class AudioEventIds
    {
        public static uint StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261u;
                for (int i = 0; i < value.Length; i++)
                {
                    hash ^= value[i];
                    hash *= 16777619u;
                }

                return hash;
            }
        }
    }
}
