// <auto-generated>
// Generated by Tools/Audio/generate_audio_event_ids.py.
// Do not edit manually; update Assets/Game/Audio/Config/audio_event_catalog_v0_1.json and regenerate.
// </auto-generated>

namespace Game.Configs
{
    public static partial class AudioEventIds
    {
        public const string VOARIAMessageBuildDrawerEmptyDefault = "VO.ARIA.Message.BuildDrawerEmptyDefault";
        public const uint VOARIAMessageBuildDrawerEmptyDefaultHash = 4059349457u;

        public const string VOARIAMessageBuildDrawerEmptySelectItem = "VO.ARIA.Message.BuildDrawerEmptySelectItem";
        public const uint VOARIAMessageBuildDrawerEmptySelectItemHash = 2485650491u;

        public const string VOARIAMessageBuildDrawerPlacementInvalid = "VO.ARIA.Message.BuildDrawerPlacementInvalid";
        public const uint VOARIAMessageBuildDrawerPlacementInvalidHash = 836185597u;

        public const string VOARIAMessageBuildDrawerActionPlaceChooseFootprint = "VO.ARIA.Message.BuildDrawerActionPlaceChooseFootprint";
        public const uint VOARIAMessageBuildDrawerActionPlaceChooseFootprintHash = 299330988u;

        public const string VOARIAMessageBuildFeedbackPlaceBuilding = "VO.ARIA.Message.BuildFeedbackPlaceBuilding";
        public const uint VOARIAMessageBuildFeedbackPlaceBuildingHash = 947653148u;

        public const string VOARIAMessageBuildFeedbackProductionRequested = "VO.ARIA.Message.BuildFeedbackProductionRequested";
        public const uint VOARIAMessageBuildFeedbackProductionRequestedHash = 1032952502u;

        public const string VOARIAMessageBuildDrawerSuccessRecruitmentQueued = "VO.ARIA.Message.BuildDrawerSuccessRecruitmentQueued";
        public const uint VOARIAMessageBuildDrawerSuccessRecruitmentQueuedHash = 2087371149u;

        public const string VOARIAMessageBuildDrawerSuccessProductionQueued = "VO.ARIA.Message.BuildDrawerSuccessProductionQueued";
        public const uint VOARIAMessageBuildDrawerSuccessProductionQueuedHash = 4228330360u;

        public const string VOARIAMessageBuildFeedbackProductionCancelUnavailable = "VO.ARIA.Message.BuildFeedbackProductionCancelUnavailable";
        public const uint VOARIAMessageBuildFeedbackProductionCancelUnavailableHash = 1676707042u;

        public const string VOARIAMessageBuildFeedbackProductionCancelledNamed = "VO.ARIA.Message.BuildFeedbackProductionCancelledNamed";
        public const uint VOARIAMessageBuildFeedbackProductionCancelledNamedHash = 1006425134u;

        public const string VOARIAMessageBuildFeedbackProductionCancelled = "VO.ARIA.Message.BuildFeedbackProductionCancelled";
        public const uint VOARIAMessageBuildFeedbackProductionCancelledHash = 3728128669u;

        public const string VOARIAMessageBuildFeedbackProductionQueueEmpty = "VO.ARIA.Message.BuildFeedbackProductionQueueEmpty";
        public const uint VOARIAMessageBuildFeedbackProductionQueueEmptyHash = 294008646u;

        public const string VOARIAMessageBuildFeedbackProductionQueueClearedSentence = "VO.ARIA.Message.BuildFeedbackProductionQueueClearedSentence";
        public const uint VOARIAMessageBuildFeedbackProductionQueueClearedSentenceHash = 1114836450u;

        public const string VOARIAMessageBuildFeedbackProductionClearUnavailable = "VO.ARIA.Message.BuildFeedbackProductionClearUnavailable";
        public const uint VOARIAMessageBuildFeedbackProductionClearUnavailableHash = 983282855u;

        public const string VOARIAMessageBuildFeedbackProductionQueueCleared = "VO.ARIA.Message.BuildFeedbackProductionQueueCleared";
        public const uint VOARIAMessageBuildFeedbackProductionQueueClearedHash = 1354436635u;

        public const string VOARIAMessageBuildFeedbackPlacementCancelled = "VO.ARIA.Message.BuildFeedbackPlacementCancelled";
        public const uint VOARIAMessageBuildFeedbackPlacementCancelledHash = 782457683u;

        public const string VOARIAMessageBuildFeedbackRotated90 = "VO.ARIA.Message.BuildFeedbackRotated90";
        public const uint VOARIAMessageBuildFeedbackRotated90Hash = 3407979195u;

        public const string VOARIAMessageBuildFeedbackNoActivePlacement = "VO.ARIA.Message.BuildFeedbackNoActivePlacement";
        public const uint VOARIAMessageBuildFeedbackNoActivePlacementHash = 610169931u;

        public const string VOARIAMessageBuildFeedbackBuildingPlaced = "VO.ARIA.Message.BuildFeedbackBuildingPlaced";
        public const uint VOARIAMessageBuildFeedbackBuildingPlacedHash = 3914499800u;

        public const string VOARIAMessageBuildFeedbackPlaceOnValidGround = "VO.ARIA.Message.BuildFeedbackPlaceOnValidGround";
        public const uint VOARIAMessageBuildFeedbackPlaceOnValidGroundHash = 3633500962u;

        public const string VOARIAMessageBuildFeedbackDrawerNotReady = "VO.ARIA.Message.BuildFeedbackDrawerNotReady";
        public const uint VOARIAMessageBuildFeedbackDrawerNotReadyHash = 278832520u;

        public const string VOARIAMessageBuildPlacementStatusDragToPosition = "VO.ARIA.Message.BuildPlacementStatusDragToPosition";
        public const uint VOARIAMessageBuildPlacementStatusDragToPositionHash = 222977931u;

        public const string VOARIAMessageBuildPlacementStatusValidGround = "VO.ARIA.Message.BuildPlacementStatusValidGround";
        public const uint VOARIAMessageBuildPlacementStatusValidGroundHash = 2317288360u;

        public const string VOARIAMessageBuildPlacementTitleDefault = "VO.ARIA.Message.BuildPlacementTitleDefault";
        public const uint VOARIAMessageBuildPlacementTitleDefaultHash = 3370741470u;

        public const string VOARIAMessageBuildPlacementTitleNamed = "VO.ARIA.Message.BuildPlacementTitleNamed";
        public const uint VOARIAMessageBuildPlacementTitleNamedHash = 3856821926u;

        public const string VOARIAMessageBuildPlacementInstructionConfirm = "VO.ARIA.Message.BuildPlacementInstructionConfirm";
        public const uint VOARIAMessageBuildPlacementInstructionConfirmHash = 856648861u;

        public const string VOARIAMessageBuildPlacementTitleFallbackSubject = "VO.ARIA.Message.BuildPlacementTitleFallbackSubject";
        public const uint VOARIAMessageBuildPlacementTitleFallbackSubjectHash = 2345630073u;

        public const string VOARIAMessageMatchFeedbackTacticalMapNotReady = "VO.ARIA.Message.MatchFeedbackTacticalMapNotReady";
        public const uint VOARIAMessageMatchFeedbackTacticalMapNotReadyHash = 2536600289u;

        public const string VOARIAMessageMatchFeedbackBlockedCivilianZone = "VO.ARIA.Message.MatchFeedbackBlockedCivilianZone";
        public const uint VOARIAMessageMatchFeedbackBlockedCivilianZoneHash = 3153755251u;

        public const string VOARIAMessageSelectionFeedbackUnitSingular = "VO.ARIA.Message.SelectionFeedbackUnitSingular";
        public const uint VOARIAMessageSelectionFeedbackUnitSingularHash = 3735698480u;

        public const string VOARIAMessageSelectionFeedbackUnitPlural = "VO.ARIA.Message.SelectionFeedbackUnitPlural";
        public const uint VOARIAMessageSelectionFeedbackUnitPluralHash = 1693056703u;

        public const string VOARIAMessageSelectionFeedbackVehicleSingular = "VO.ARIA.Message.SelectionFeedbackVehicleSingular";
        public const uint VOARIAMessageSelectionFeedbackVehicleSingularHash = 2754198088u;

        public const string VOARIAMessageSelectionFeedbackSoldierSingular = "VO.ARIA.Message.SelectionFeedbackSoldierSingular";
        public const uint VOARIAMessageSelectionFeedbackSoldierSingularHash = 17882658u;

        public const string VOARIAMessageSelectionFeedbackSquadCount = "VO.ARIA.Message.SelectionFeedbackSquadCount";
        public const uint VOARIAMessageSelectionFeedbackSquadCountHash = 2585327106u;

        public const string VOARIAMessageSelectionFeedbackSquadSelected = "VO.ARIA.Message.SelectionFeedbackSquadSelected";
        public const uint VOARIAMessageSelectionFeedbackSquadSelectedHash = 2821846162u;

        public const string VOARIATutorialM01FindSquadEn = "VO.ARIA.Tutorial.M01.FindSquad.En";
        public const uint VOARIATutorialM01FindSquadEnHash = 4073964257u;

        public const string VOARIATutorialM01MoveToCoverEn = "VO.ARIA.Tutorial.M01.MoveToCover.En";
        public const uint VOARIATutorialM01MoveToCoverEnHash = 2083846237u;

        public const string VOARIATutorialM01MoveDestinationEn = "VO.ARIA.Tutorial.M01.MoveDestination.En";
        public const uint VOARIATutorialM01MoveDestinationEnHash = 3570977129u;

        public const string VOARIATutorialM01ConfirmThreatEn = "VO.ARIA.Tutorial.M01.ConfirmThreat.En";
        public const uint VOARIATutorialM01ConfirmThreatEnHash = 383473216u;

        public const string VOARIATutorialM01EngageEn = "VO.ARIA.Tutorial.M01.Engage.En";
        public const uint VOARIATutorialM01EngageEnHash = 29346487u;

        public const string VOARIATutorialM01AttackTargetEn = "VO.ARIA.Tutorial.M01.AttackTarget.En";
        public const uint VOARIATutorialM01AttackTargetEnHash = 3897856629u;

        public const string VOARIATutorialM01SecureCorridorEn = "VO.ARIA.Tutorial.M01.SecureCorridor.En";
        public const uint VOARIATutorialM01SecureCorridorEnHash = 2058127915u;

        public const string VOARIATutorialM01FindSquadFa = "VO.ARIA.Tutorial.M01.FindSquad.Fa";
        public const uint VOARIATutorialM01FindSquadFaHash = 4224521543u;

        public const string VOARIATutorialM01MoveToCoverFa = "VO.ARIA.Tutorial.M01.MoveToCover.Fa";
        public const uint VOARIATutorialM01MoveToCoverFaHash = 2100079403u;

        public const string VOARIATutorialM01MoveDestinationFa = "VO.ARIA.Tutorial.M01.MoveDestination.Fa";
        public const uint VOARIATutorialM01MoveDestinationFaHash = 2916208703u;

        public const string VOARIATutorialM01ConfirmThreatFa = "VO.ARIA.Tutorial.M01.ConfirmThreat.Fa";
        public const uint VOARIATutorialM01ConfirmThreatFaHash = 1037653262u;

        public const string VOARIATutorialM01EngageFa = "VO.ARIA.Tutorial.M01.Engage.Fa";
        public const uint VOARIATutorialM01EngageFaHash = 516044533u;

        public const string VOARIATutorialM01AttackTargetFa = "VO.ARIA.Tutorial.M01.AttackTarget.Fa";
        public const uint VOARIATutorialM01AttackTargetFaHash = 3108867251u;

        public const string VOARIATutorialM01SecureCorridorFa = "VO.ARIA.Tutorial.M01.SecureCorridor.Fa";
        public const uint VOARIATutorialM01SecureCorridorFaHash = 2679046913u;

        public const string VOARIATutorialM02OpenBuildEn = "VO.ARIA.Tutorial.M02.OpenBuild.En";
        public const uint VOARIATutorialM02OpenBuildEnHash = 2146463555u;

        public const string VOARIATutorialM02OpenBuildFa = "VO.ARIA.Tutorial.M02.OpenBuild.Fa";
        public const uint VOARIATutorialM02OpenBuildFaHash = 1962160009u;

        public const string VOARIATutorialM02SelectBarracksEn = "VO.ARIA.Tutorial.M02.SelectBarracks.En";
        public const uint VOARIATutorialM02SelectBarracksEnHash = 710888218u;

        public const string VOARIATutorialM02SelectBarracksFa = "VO.ARIA.Tutorial.M02.SelectBarracks.Fa";
        public const uint VOARIATutorialM02SelectBarracksFaHash = 224881720u;

        public const string VOARIATutorialM02PlaceBarracksEn = "VO.ARIA.Tutorial.M02.PlaceBarracks.En";
        public const uint VOARIATutorialM02PlaceBarracksEnHash = 755193143u;

        public const string VOARIATutorialM02PlaceBarracksFa = "VO.ARIA.Tutorial.M02.PlaceBarracks.Fa";
        public const uint VOARIATutorialM02PlaceBarracksFaHash = 1241891189u;

        public const string VOARIATutorialM02CheckCostEn = "VO.ARIA.Tutorial.M02.CheckCost.En";
        public const uint VOARIATutorialM02CheckCostEnHash = 610849292u;

        public const string VOARIATutorialM02CheckCostFa = "VO.ARIA.Tutorial.M02.CheckCost.Fa";
        public const uint VOARIATutorialM02CheckCostFaHash = 1130808386u;

        public const string VOARIATutorialM02TrainRifleSquadEn = "VO.ARIA.Tutorial.M02.TrainRifleSquad.En";
        public const uint VOARIATutorialM02TrainRifleSquadEnHash = 718340173u;

        public const string VOARIATutorialM02TrainRifleSquadFa = "VO.ARIA.Tutorial.M02.TrainRifleSquad.Fa";
        public const uint VOARIATutorialM02TrainRifleSquadFaHash = 734676507u;

        public const string VOARIATutorialM02IncomingPatrolEn = "VO.ARIA.Tutorial.M02.IncomingPatrol.En";
        public const uint VOARIATutorialM02IncomingPatrolEnHash = 143983277u;

        public const string VOARIATutorialM02IncomingPatrolFa = "VO.ARIA.Tutorial.M02.IncomingPatrol.Fa";
        public const uint VOARIATutorialM02IncomingPatrolFaHash = 160319611u;

        public const string VOARIATutorialM02DefendPostEn = "VO.ARIA.Tutorial.M02.DefendPost.En";
        public const uint VOARIATutorialM02DefendPostEnHash = 426694301u;

        public const string VOARIATutorialM02DefendPostFa = "VO.ARIA.Tutorial.M02.DefendPost.Fa";
        public const uint VOARIATutorialM02DefendPostFaHash = 443030635u;

    }
}
