#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_JSON = ROOT / "Design/AgentReports/ArchitectureMaturity/selected_owner_responsibility_maps.json"

SECTION_TITLES = (
    ("declaredTypes", "Declared ECS Types"),
    ("inputs", "Inputs"),
    ("outputs", "Outputs And Structural Changes"),
    ("stateAuthority", "State Authority"),
    ("updateOrder", "Update Order"),
    ("sideEffects", "Side Effects And Presentation"),
    ("failureBehavior", "Failure And Edge Behavior"),
    ("tests", "Tests And Validation Commands"),
    ("allowedDependencies", "Allowed Dependencies"),
    ("forbiddenDependencies", "Forbidden Dependencies"),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def format_references(references: list[dict]) -> str:
    values = []
    for reference in references:
        start = reference["lineStart"]
        end = reference["lineEnd"]
        suffix = str(start) if start == end else f"{start}-{end}"
        values.append(f"`{reference['path']}:{suffix}`")
    return ", ".join(values)


def render(data: dict, json_sha256: str) -> str:
    baseline = data["sourceBaseline"]
    lines = [
        "# AM-010 Selected Owner Responsibility Maps",
        "",
        "> Generated by `python3 Tools/CI/architecture_owner_responsibility_maps.py`; do not edit manually.",
        "",
        f"Artifact: `{data['artifactId']}`",
        "",
        "## Evidence Binding",
        "",
        f"- Authoritative JSON SHA-256: `{json_sha256}`",
        f"- Source baseline: `{baseline['commit']}` / tree `{baseline['tree']}` on `{baseline['branch']}`",
        f"- AM-009 ranking: `{data['sourceAuthorities']['rankingPath']}` / SHA-256 `{data['sourceAuthorities']['rankingSha256']}`",
        f"- Freshness-bound evidence files: `{len(data['evidenceFiles'])}`",
        "- Initial modification scopes remain the exact disjoint AM-009 one-file allowlists.",
        "- Proposed extraction paths are planning only and require the recorded expanded allowlist before implementation.",
    ]

    for owner in data["owners"]:
        lines.extend([
            "",
            f"## `{owner['path']}`",
            "",
            f"- Modification scope: `{owner['modificationScope']}`",
            "- Initial allowed paths: " + ", ".join(f"`{path}`" for path in owner["initialAllowedPaths"]),
            f"- Source SHA-256: `{owner['sourceSha256']}`",
        ])
        for field, title in SECTION_TITLES:
            lines.extend(["", f"### {title}", ""])
            for item in owner[field]:
                lines.append(f"- {item['statement']} Evidence: {format_references(item['references'])}.")

        lines.extend(["", "### Bounded Extraction Candidates", ""])
        for candidate in owner["boundedExtractionCandidates"]:
            status = candidate.get("status", "proposed")
            output_label = "Output paths" if status == "completed" else "Proposed output paths"
            lines.extend([
                f"- {candidate['statement']} Evidence: {format_references(candidate['references'])}.",
                f"  - Status: `{status}`",
                f"  - {output_label}: " + ", ".join(f"`{path}`" for path in candidate["proposedOutputPaths"]),
                "  - Required expanded allowlist: " + ", ".join(f"`{path}`" for path in candidate["requiredExpandedAllowedPaths"]),
                f"  - Authority boundary: {candidate['authorityBoundary']}",
                f"  - Proposed update order: {candidate['proposedUpdateOrder']}",
                f"  - Cleanup authority: {candidate['cleanupAuthority']}",
            ])
            if status == "completed":
                lines.append(f"  - Completion evidence: `{candidate['evidencePath']}` (`{candidate['evidenceSha256']}`)")

    lines.extend([
        "",
        "## Extraction Gate Status",
        "",
        "AM-011 characterization is accepted. Each completed extraction must retain exact evidence identity, focused behavior coverage, full regression coverage, and a fresh zero-allocation performance capture before the next production slice begins.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the AM-010 responsibility-map review surface.")
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    json_path = args.json.resolve()
    data = json.loads(json_path.read_text(encoding="utf-8"))
    output_path = args.output.resolve() if args.output else ROOT / data["summaryPath"]
    expected = render(data, sha256(json_path))
    if args.check:
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale responsibility-map summary: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
