using System;
using Unity.Entities;
using UnityEngine;

public sealed class RtsSelectionPointerTargetCommandContextSystem
{
    public RtsSelectionPointerTargetCommandSystem.Context Create(
        RuntimeGameplayStateSystem runtimeGameplayStateSystem,
        RtsSelectionInputSystem inputSystem,
        SelectionStateSystem selectionStateSystem,
        FocusedUnitLifecycleSystem focusedUnitLifecycleSystem,
        FocusableUnitLookupSystem focusableUnitLookupSystem,
        TransportBoardingCommandSystem transportBoardingCommandSystem,
        UnitTransportCapacitySystem unitTransportCapacitySystem,
        UnitTransportBoardingQuerySystem unitTransportBoardingQuerySystem,
        UnitTransportBoardingRuleSystem unitTransportBoardingRuleSystem,
        UnitTransportApproachCellSystem unitTransportApproachCellSystem,
        UnitTransportAirPickupSystem unitTransportAirPickupSystem,
        BuildingTargetMoveOrderSystem buildingTargetMoveOrderSystem,
        BuildingPlacementInteractionSystem buildingPlacementInteractionSystem,
        BuildingPlacementInteractionSystem.Context buildingPlacementInteractionContext,
        Camera worldCamera,
        RtsSelectionPointerTargetCommandSystem.TryGetEntityManagerDelegate tryGetEntityManager,
        RtsSelectionPointerTargetCommandSystem.TryGetPointerPositionDelegate tryGetPointerPosition,
        Func<bool> getExplicitAttackTargetModeActive,
        Action<bool> setExplicitAttackTargetModeActive,
        SelectionHudFeedbackBoundary hudFeedbackSystem,
        SelectionHudFeedbackBoundary.Context hudFeedbackContext,
        Action<EntityManager, string> clearCurrentSelection,
        Action<Vector2> requestMoveOrderScreenMarker,
        Action<bool> setCameraDragging,
        Func<bool> processAttackCommandRequests,
        Func<bool> processScanCommandRequests,
        Func<bool> processTransportCommandRequests,
        Action processMoveCommandRequests,
        Action<string> logSelectionDiagnostic,
        FocusedUnitLifecycleSystem.DescribeEntityDelegate describeEntity)
    {
        return new RtsSelectionPointerTargetCommandSystem.Context(
            runtimeGameplayStateSystem,
            inputSystem,
            selectionStateSystem,
            focusedUnitLifecycleSystem,
            focusableUnitLookupSystem,
            transportBoardingCommandSystem,
            unitTransportCapacitySystem,
            unitTransportBoardingQuerySystem,
            unitTransportBoardingRuleSystem,
            unitTransportApproachCellSystem,
            unitTransportAirPickupSystem,
            buildingTargetMoveOrderSystem,
            buildingPlacementInteractionSystem,
            buildingPlacementInteractionContext,
            worldCamera,
            tryGetEntityManager,
            tryGetPointerPosition,
            getExplicitAttackTargetModeActive,
            setExplicitAttackTargetModeActive,
            mode => hudFeedbackSystem.ApplyCommandMode(hudFeedbackContext, mode),
            result => hudFeedbackSystem.ApplyCommandResult(hudFeedbackContext, result),
            () => hudFeedbackSystem.ClearSelection(hudFeedbackContext),
            () => hudFeedbackSystem.ClearCommandMode(hudFeedbackContext),
            (em, entity) => hudFeedbackSystem.ApplySelection(hudFeedbackContext, em, entity),
            clearCurrentSelection,
            requestMoveOrderScreenMarker,
            setCameraDragging,
            processAttackCommandRequests,
            processScanCommandRequests,
            processTransportCommandRequests,
            processMoveCommandRequests,
            logSelectionDiagnostic,
            describeEntity);
    }
}
