using System;
using Unity.Entities;
using UnityEngine;

public sealed class RtsSelectionCommandResultContextSystem
{
    public RtsSelectionCommandResultFlushSystem.Context Create(
        RtsSelectionInputSystem inputSystem,
        SelectionHudFeedbackBoundary hudFeedbackSystem,
        SelectionHudFeedbackBoundary.Context hudFeedbackContext,
        SelectionOrderMarkerSystem orderMarkerSystem,
        SelectedMoveOrderCommandSystem selectedMoveOrderCommandSystem,
        AttackOrderCommandSystem attackOrderCommandSystem,
        ScanIntelCommandSystem scanIntelCommandSystem,
        TransportBoardingCommandSystem transportBoardingCommandSystem,
        UnitMoveOrderSystem unitMoveOrderSystem,
        UnitTransportCapacitySystem unitTransportCapacitySystem,
        UnitTransportAirPickupSystem unitTransportAirPickupSystem,
        SelectionStateSystem selectionStateSystem,
        BuildingPlacementInteractionSystem buildingPlacementInteractionSystem,
        BuildingPlacementInteractionSystem.Context buildingPlacementInteractionContext,
        SelectionRuntimeQuerySystem querySystem,
        RtsSelectionCommandResultFlushSystem.TryGetEntityManagerAction tryGetDefaultEntityManager,
        Action<EntityManager> ensureRuntimeSelectionDependencies,
        RtsSelectionCommandResultFlushSystem.ClearCurrentSelectionAction clearCurrentSelection,
        Action<bool> setExplicitAttackTargetModeActive,
        Action processSelectionRectangleRequests,
        Action<Vector2> requestMoveOrderScreenMarker,
        Action<Vector2> requestAttackOrderScreenMarker,
        Action<bool> setCameraDragging,
        Action<SelectionStateSystem> clearFocusedUnit,
        SelectedMoveOrderCommandSystem.ClickedUnitResolver tryGetMoveClickedUnitEntity,
        SelectedMoveOrderCommandSystem.ClickedCellResolver tryGetMoveClickedCell,
        SelectedMoveOrderCommandSystem.ClickedCellResolver tryGetScanClickedCell,
        AttackOrderCommandSystem.TryGetClickedUnitEntityDelegate tryGetAttackClickedUnitEntity,
        AttackOrderCommandSystem.CollectSelectedAttackSourcesDelegate collectSelectedAttackSources,
        TransportBoardingCommandSystem.TryGetClickedUnitEntityDelegate tryGetTransportClickedUnitEntity,
        TransportBoardingCommandSystem.TryGetClickedCellDelegate tryGetTransportClickedCell)
    {
        return new RtsSelectionCommandResultFlushSystem.Context(
            inputSystem,
            hudFeedbackSystem,
            orderMarkerSystem,
            selectedMoveOrderCommandSystem,
            attackOrderCommandSystem,
            scanIntelCommandSystem,
            transportBoardingCommandSystem,
            unitMoveOrderSystem,
            unitTransportCapacitySystem,
            unitTransportAirPickupSystem,
            selectionStateSystem,
            buildingPlacementInteractionSystem,
            buildingPlacementInteractionContext,
            querySystem.SelectedMoveQuery,
            querySystem.GridConfigQuery,
            querySystem.MapSurfaceQuery,
            tryGetDefaultEntityManager,
            ensureRuntimeSelectionDependencies,
            clearCurrentSelection,
            mode => hudFeedbackSystem.ApplyCommandMode(hudFeedbackContext, mode),
            result => hudFeedbackSystem.ApplyCommandResult(hudFeedbackContext, result),
            () => hudFeedbackSystem.ClearSelection(hudFeedbackContext),
            () => hudFeedbackSystem.ClearCommandMode(hudFeedbackContext),
            setExplicitAttackTargetModeActive,
            visible => hudFeedbackSystem.SetWorldMarkersVisible(hudFeedbackContext, visible),
            processSelectionRectangleRequests,
            requestMoveOrderScreenMarker,
            requestAttackOrderScreenMarker,
            setCameraDragging,
            clearFocusedUnit,
            tryGetMoveClickedUnitEntity,
            tryGetMoveClickedCell,
            tryGetScanClickedCell,
            tryGetAttackClickedUnitEntity,
            collectSelectedAttackSources,
            tryGetTransportClickedUnitEntity,
            tryGetTransportClickedCell);
    }
}
