using System;
using Unity.Entities;
using UnityEngine;

public sealed class RtsSelectionCommandResultContextSystem
{
    public RtsSelectionCommandResultFlushSystem.Context Create(
        RtsSelectionInputSystem inputSystem,
        SelectionHudFeedbackBoundary hudFeedbackSystem,
        SelectionHudFeedbackBoundary.Context hudFeedbackContext,
        SelectionOrderMarkerSystem orderMarkerSystem,
        SelectedMoveOrderCommandSystem selectedMoveOrderCommandSystem,
        AttackOrderCommandSystem attackOrderCommandSystem,
        ScanIntelCommandSystem scanIntelCommandSystem,
        TransportBoardingCommandSystem transportBoardingCommandSystem,
        UnitMoveOrderSystem unitMoveOrderSystem,
        UnitTransportCapacitySystem unitTransportCapacitySystem,
        UnitTransportAirPickupSystem unitTransportAirPickupSystem,
        SelectionStateSystem selectionStateSystem,
        BuildingPlacementInteractionSystem buildingPlacementInteractionSystem,
        BuildingPlacementInteractionSystem.Context buildingPlacementInteractionContext,
        SelectionRuntimeQuerySystem querySystem,
        RtsSelectionCommandResultFlushSystem.TryGetEntityManagerAction tryGetDefaultEntityManager,
        Action<EntityManager> ensureRuntimeSelectionDependencies,
        RtsSelectionCommandResultFlushSystem.ClearCurrentSelectionAction clearCurrentSelection,
        Action<bool> setExplicitAttackTargetModeActive,
        Action processSelectionRectangleRequests,
        Action<string> logSelectionClickDiagnostic,
        Action<Vector2> requestMoveOrderScreenMarker,
        Action<Vector2> requestAttackOrderScreenMarker,
        Action<bool> setCameraDragging,
        Action<SelectionStateSystem> clearFocusedUnit,
        RtsSelectionCommandResultFlushSystem.RefreshFocusedUnitAction refreshFocusedUnit,
        RtsSelectionCommandResultFlushSystem.SetFocusedUnitAction setFocusedUnit,
        SelectedMoveOrderCommandSystem.ClickedUnitResolver tryGetMoveClickedUnitEntity,
        SelectedMoveOrderCommandSystem.ClickedCellResolver tryGetMoveClickedCell,
        SelectedMoveOrderCommandSystem.ClickedCellResolver tryGetScanClickedCell,
        AttackOrderCommandSystem.TryGetClickedUnitEntityDelegate tryGetAttackClickedUnitEntity,
        TransportBoardingCommandSystem.TryGetClickedUnitEntityDelegate tryGetTransportClickedUnitEntity,
        TransportBoardingCommandSystem.TryGetClickedCellDelegate tryGetTransportClickedCell)
    {
        return new RtsSelectionCommandResultFlushSystem.Context(
            inputSystem,
            hudFeedbackSystem,
            orderMarkerSystem,
            selectedMoveOrderCommandSystem,
            attackOrderCommandSystem,
            scanIntelCommandSystem,
            transportBoardingCommandSystem,
            unitMoveOrderSystem,
            unitTransportCapacitySystem,
            unitTransportAirPickupSystem,
            selectionStateSystem,
            buildingPlacementInteractionSystem,
            buildingPlacementInteractionContext,
            querySystem.SelectedMoveQuery,
            querySystem.SelectedTagQuery,
            querySystem.GridConfigQuery,
            querySystem.MapSurfaceQuery,
            tryGetDefaultEntityManager,
            ensureRuntimeSelectionDependencies,
            clearCurrentSelection,
            mode => hudFeedbackSystem.ApplyCommandMode(hudFeedbackContext, mode),
            (direction, boardAllInteractable) =>
                hudFeedbackSystem.ApplyBoardCommandMode(hudFeedbackContext, direction, boardAllInteractable),
            result => hudFeedbackSystem.ApplyCommandResult(hudFeedbackContext, result),
            () => hudFeedbackSystem.ClearSelection(hudFeedbackContext),
            (em, entity) => hudFeedbackSystem.ApplySelection(hudFeedbackContext, em, entity),
            () => hudFeedbackSystem.ClearCommandMode(hudFeedbackContext),
            setExplicitAttackTargetModeActive,
            visible => hudFeedbackSystem.SetWorldMarkersVisible(hudFeedbackContext, visible),
            processSelectionRectangleRequests,
            logSelectionClickDiagnostic,
            requestMoveOrderScreenMarker,
            requestAttackOrderScreenMarker,
            setCameraDragging,
            clearFocusedUnit,
            refreshFocusedUnit,
            setFocusedUnit,
            tryGetMoveClickedUnitEntity,
            tryGetMoveClickedCell,
            tryGetScanClickedCell,
            tryGetAttackClickedUnitEntity,
            tryGetTransportClickedUnitEntity,
            tryGetTransportClickedCell);
    }
}
