public enum WarlineCaptureRoute
{
    Splash,
    MainMenu,
    Settings,
    QuickCustomSetup,
    Match,
    Armory,
    CommandExchange,
    Inbox,
    Events,
    Ranking,
    CommandFeed,
    SagaMap,
    MissionBriefing,
    LoadoutSquadPrep,
    CommanderProfile,
    OperationDashboard,
    DistrictDetail
}
